; generated by sdcc-z80-bin
    LD SP,#0x7700
    CALL _main
__sdcc_z80_bin_halt:
    JR __sdcc_z80_bin_halt

;--------------------------------------------------------
; File Created by SDCC : free open source ANSI-C Compiler
; Version 4.1.0 #12072 (Linux)
;--------------------------------------------------------
	.module test_main
	.optsdcc -mz80
	
;--------------------------------------------------------
; Public variables in this module
;--------------------------------------------------------
	.globl _main
;--------------------------------------------------------
; special function registers
;--------------------------------------------------------
;--------------------------------------------------------
; ram data
;--------------------------------------------------------
	.area _DATA
;--------------------------------------------------------
; ram data
;--------------------------------------------------------
	.area _INITIALIZED
;--------------------------------------------------------
; absolute external ram data
;--------------------------------------------------------
	.area _DABS (ABS)
;--------------------------------------------------------
; global & static initialisations
;--------------------------------------------------------
	.area _HOME
	.area _GSINIT
	.area _GSFINAL
	.area _GSINIT
;--------------------------------------------------------
; Home
;--------------------------------------------------------
	.area _HOME
	.area _HOME
;--------------------------------------------------------
; code
;--------------------------------------------------------
	.area _CODE
;c_programs/common/glic80.h:15: static void glic_clear_text(void) {
;	---------------------------------
; Function glic_clear_text
; ---------------------------------
_glic_clear_text:
;c_programs/common/glic80.h:18: for (i = 0; i < GLIC_CVRAM_BYTES; ++i) {
	ld	bc, #0x0000
00102$:
;c_programs/common/glic80.h:19: GLIC_CVRAM[i] = 0x00u;
	ld	hl, #0x7700
	add	hl, bc
	ld	(hl), #0x00
;c_programs/common/glic80.h:18: for (i = 0; i < GLIC_CVRAM_BYTES; ++i) {
	inc	bc
	ld	a, b
	sub	a, #0x01
	jr	C, 00102$
;c_programs/common/glic80.h:21: }
	ret
;c_programs/common/glic80.h:23: static void glic_fill_graphics(unsigned char value) {
;	---------------------------------
; Function glic_fill_graphics
; ---------------------------------
_glic_fill_graphics:
;c_programs/common/glic80.h:26: for (i = 0; i < GLIC_GVRAM_BYTES; ++i) {
	ld	bc, #0x0000
00102$:
;c_programs/common/glic80.h:27: GLIC_GVRAM[i] = value;
	ld	hl, #0x7800
	add	hl, bc
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	ld	(hl), a
;c_programs/common/glic80.h:26: for (i = 0; i < GLIC_GVRAM_BYTES; ++i) {
	inc	bc
	ld	a, b
	sub	a, #0x08
	jr	C, 00102$
;c_programs/common/glic80.h:29: }
	ret
;c_programs/common/glic80.h:31: static void glic_prepare_screen(unsigned char value) {
;	---------------------------------
; Function glic_prepare_screen
; ---------------------------------
_glic_prepare_screen:
;c_programs/common/glic80.h:32: glic_clear_text();
	call	_glic_clear_text
;c_programs/common/glic80.h:33: glic_fill_graphics(value);
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_glic_fill_graphics
	inc	sp
;c_programs/common/glic80.h:34: }
	ret
;c_programs/common/glic80.h:36: static void glic_fill_page_run(unsigned char page,
;	---------------------------------
; Function glic_fill_page_run
; ---------------------------------
_glic_fill_page_run:
;c_programs/common/glic80.h:42: p = GLIC_GVRAM + (((unsigned int)page) << 7) + x;
	ld	iy, #2
	add	iy, sp
	ld	c, 0 (iy)
	ld	b, #0x00
	xor	a, a
	rr	b
	ld	b, c
	rr	b
	rra
	ld	c, a
	ld	a, b
	add	a, #0x78
	ld	b, a
	ld	a, c
	ld	hl, #3
	add	hl, sp
	add	a, (hl)
	ld	c, a
	jr	NC, 00117$
	inc	b
00117$:
;c_programs/common/glic80.h:43: while (width != 0u) {
	ld	e, 2 (iy)
00101$:
	ld	a, e
	or	a, a
	ret	Z
;c_programs/common/glic80.h:44: *p++ = value;
	ld	iy, #5
	add	iy, sp
	ld	a, 0 (iy)
	ld	(bc), a
	inc	bc
;c_programs/common/glic80.h:45: --width;
	dec	e
;c_programs/common/glic80.h:47: }
	jr	00101$
;c_programs/common/glic80.h:49: static void glic_fill_pages(unsigned char first_page,
;	---------------------------------
; Function glic_fill_pages
; ---------------------------------
_glic_fill_pages:
;c_programs/common/glic80.h:52: while (page_count != 0u) {
	ld	iy, #2
	add	iy, sp
	ld	b, 0 (iy)
	ld	c, 1 (iy)
00101$:
	ld	a, c
	or	a, a
	ret	Z
;c_programs/common/glic80.h:53: glic_fill_page_run(first_page, 0u, GLIC_SCREEN_WIDTH, value);
	push	bc
	ld	hl, #6
	add	hl, sp
	ld	d, (hl)
	ld	e,#0x80
	push	de
	xor	a, a
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_fill_page_run
	pop	af
	pop	af
	pop	bc
;c_programs/common/glic80.h:54: ++first_page;
	inc	b
;c_programs/common/glic80.h:55: --page_count;
	dec	c
;c_programs/common/glic80.h:57: }
	jr	00101$
;c_programs/common/glic80.h:59: static void glic_fill_columns(unsigned char x,
;	---------------------------------
; Function glic_fill_columns
; ---------------------------------
_glic_fill_columns:
;c_programs/common/glic80.h:64: for (page = 0u; page < GLIC_SCREEN_PAGES; ++page) {
	ld	b, #0x00
00102$:
;c_programs/common/glic80.h:65: glic_fill_page_run(page, x, width, value);
	push	bc
	ld	iy, #6
	add	iy, sp
	ld	a, 0 (iy)
	push	af
	inc	sp
	ld	a, -1 (iy)
	dec	iy
	push	af
	inc	sp
	ld	a, -1 (iy)
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_fill_page_run
	pop	af
	pop	af
	pop	bc
;c_programs/common/glic80.h:64: for (page = 0u; page < GLIC_SCREEN_PAGES; ++page) {
	inc	b
	ld	a, b
	sub	a, #0x10
	jr	C, 00102$
;c_programs/common/glic80.h:67: }
	ret
;c_programs/test_main.c:3: void main(void) {
;	---------------------------------
; Function main
; ---------------------------------
_main::
;c_programs/test_main.c:6: glic_clear_text();
	call	_glic_clear_text
;c_programs/test_main.c:8: for (i = 0; i < GLIC_GVRAM_BYTES; ++i) {
	ld	bc, #0x0000
00102$:
;c_programs/test_main.c:9: GLIC_GVRAM[i] = (i & 1u) ? GLIC_BLACK : GLIC_WHITE;
	ld	hl, #0x7800
	add	hl, bc
	ex	de, hl
	bit	0, c
	jr	Z, 00106$
	ld	hl, #0x0000
	jr	00107$
00106$:
	ld	hl, #0x00ff
00107$:
	ld	a, l
	ld	(de), a
;c_programs/test_main.c:8: for (i = 0; i < GLIC_GVRAM_BYTES; ++i) {
	inc	bc
	ld	a, b
	sub	a, #0x08
	jr	C, 00102$
;c_programs/test_main.c:11: }
	ret
	.area _CODE
	.area _INITIALIZER
	.area _CABS (ABS)
