; generated by sdcc-z80-bin
    JR __sdcc_z80_bin_start
    DB "dvd_screensaver",0
__sdcc_z80_bin_start:
    LD SP,#0x7700
    CALL _main
__sdcc_z80_bin_halt:
    JR __sdcc_z80_bin_halt

;--------------------------------------------------------
; File Created by SDCC : free open source ANSI-C Compiler
; Version 4.1.0 #12072 (Linux)
;--------------------------------------------------------
	.module dvd_screensaver
	.optsdcc -mz80
	
;--------------------------------------------------------
; Public variables in this module
;--------------------------------------------------------
	.globl _main
;--------------------------------------------------------
; special function registers
;--------------------------------------------------------
;--------------------------------------------------------
; ram data
;--------------------------------------------------------
	.area _DATA
;--------------------------------------------------------
; ram data
;--------------------------------------------------------
	.area _INITIALIZED
;--------------------------------------------------------
; absolute external ram data
;--------------------------------------------------------
	.area _DABS (ABS)
;--------------------------------------------------------
; global & static initialisations
;--------------------------------------------------------
	.area _HOME
	.area _GSINIT
	.area _GSFINAL
	.area _GSINIT
;--------------------------------------------------------
; Home
;--------------------------------------------------------
	.area _HOME
	.area _HOME
;--------------------------------------------------------
; code
;--------------------------------------------------------
	.area _CODE
;apps/../common/glic80.h:29: static unsigned char glic_read_buttons(void) __naked {
;	---------------------------------
; Function glic_read_buttons
; ---------------------------------
_glic_read_buttons:
;apps/../common/glic80.h:34: __endasm;
	in	a,(0)
	ld	l,a
	ret
;apps/../common/glic80.h:35: }
;apps/../common/glic80.h:37: static unsigned char glic_button_pressed(unsigned char buttons,
;	---------------------------------
; Function glic_button_pressed
; ---------------------------------
_glic_button_pressed:
;apps/../common/glic80.h:39: return (buttons & mask) == 0u;
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	inc	iy
	and	a, 0 (iy)
	or	a, a
	ld	a, #0x01
	jr	Z, 00104$
	xor	a, a
00104$:
	ld	l, a
;apps/../common/glic80.h:40: }
	ret
_glic_bit_masks:
	.db #0x01	; 1
	.db #0x02	; 2
	.db #0x04	; 4
	.db #0x08	; 8
	.db #0x10	; 16
	.db #0x20	; 32
	.db #0x40	; 64
	.db #0x80	; 128
;apps/../common/glic80.h:42: static void glic_delay(unsigned int count) {
;	---------------------------------
; Function glic_delay
; ---------------------------------
_glic_delay:
;apps/../common/glic80.h:43: while (count != 0u) {
	pop	de
	pop	bc
	push	bc
	push	de
00101$:
	ld	a, b
	or	a, c
	ret	Z
;apps/../common/glic80.h:44: --count;
	dec	bc
;apps/../common/glic80.h:47: __endasm;
	nop
;apps/../common/glic80.h:49: }
	jr	00101$
;apps/../common/glic80.h:51: static void glic_clear_text(void) {
;	---------------------------------
; Function glic_clear_text
; ---------------------------------
_glic_clear_text:
;apps/../common/glic80.h:54: for (i = 0; i < GLIC_CVRAM_BYTES; ++i) {
	ld	bc, #0x0000
00102$:
;apps/../common/glic80.h:55: GLIC_CVRAM[i] = 0x00u;
	ld	hl, #0x7700
	add	hl, bc
	ld	(hl), #0x00
;apps/../common/glic80.h:54: for (i = 0; i < GLIC_CVRAM_BYTES; ++i) {
	inc	bc
	ld	a, b
	sub	a, #0x01
	jr	C, 00102$
;apps/../common/glic80.h:57: }
	ret
;apps/../common/glic80.h:59: static void glic_fill_graphics(unsigned char value) {
;	---------------------------------
; Function glic_fill_graphics
; ---------------------------------
_glic_fill_graphics:
;apps/../common/glic80.h:62: for (i = 0; i < GLIC_GVRAM_BYTES; ++i) {
	ld	bc, #0x0000
00102$:
;apps/../common/glic80.h:63: GLIC_GVRAM[i] = value;
	ld	hl, #0x7800
	add	hl, bc
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	ld	(hl), a
;apps/../common/glic80.h:62: for (i = 0; i < GLIC_GVRAM_BYTES; ++i) {
	inc	bc
	ld	a, b
	sub	a, #0x08
	jr	C, 00102$
;apps/../common/glic80.h:65: }
	ret
;apps/../common/glic80.h:67: static void glic_plot(unsigned char x, unsigned char y, unsigned char value) {
;	---------------------------------
; Function glic_plot
; ---------------------------------
_glic_plot:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/../common/glic80.h:71: if ((x >= GLIC_SCREEN_WIDTH) || (y >= 128u)) {
	ld	a, 4 (ix)
	sub	a, #0x80
	jr	NC, 00107$
	ld	a, 5 (ix)
	sub	a, #0x80
;apps/../common/glic80.h:72: return;
	jr	NC, 00107$
;apps/../common/glic80.h:75: offset = (((unsigned int)(y >> 3)) << 7) + x;
	ld	a, 5 (ix)
	rrca
	rrca
	rrca
	and	a, #0x1f
	ld	l, a
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	ld	c, 4 (ix)
	ld	b, #0x00
	add	hl, bc
	ex	de, hl
;apps/../common/glic80.h:76: mask = glic_bit_masks[y & 7u];
	ld	bc, #_glic_bit_masks+0
	ld	a, 5 (ix)
	and	a, #0x07
	ld	l, a
	ld	h, #0x00
	add	hl, bc
	ld	b, (hl)
;apps/../common/glic80.h:78: GLIC_GVRAM[offset] |= mask;
	ld	hl, #0x7800
	add	hl, de
	ld	c, (hl)
;apps/../common/glic80.h:77: if (value != 0u) {
	ld	a, 6 (ix)
	or	a, a
	jr	Z, 00105$
;apps/../common/glic80.h:78: GLIC_GVRAM[offset] |= mask;
	ld	a, c
	or	a, b
	ld	(hl), a
	jr	00107$
00105$:
;apps/../common/glic80.h:80: GLIC_GVRAM[offset] &= (unsigned char)~mask;
	ld	a, b
	cpl
	and	a, c
	ld	(hl), a
00107$:
;apps/../common/glic80.h:82: }
	pop	ix
	ret
;apps/../common/glic80.h:84: static void glic_draw_bitmap8(unsigned char x,
;	---------------------------------
; Function glic_draw_bitmap8
; ---------------------------------
_glic_draw_bitmap8:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/../common/glic80.h:92: for (row = 0u; row < 8u; ++row) {
	ld	c, #0x00
00107$:
;apps/../common/glic80.h:93: bits = rows[row];
	ld	l, 6 (ix)
	ld	h, 7 (ix)
	ld	b, #0x00
	add	hl, bc
	ld	l, (hl)
;apps/../common/glic80.h:94: mask = 0x80u;
	ld	e, #0x80
;apps/../common/glic80.h:95: for (col = 0u; col < 8u; ++col) {
	ld	a, 5 (ix)
	add	a, c
	ld	b, a
	ld	d, #0x00
00105$:
;apps/../common/glic80.h:96: if ((bits & mask) != 0u) {
	ld	a, l
	and	a,e
	jr	Z, 00102$
;apps/../common/glic80.h:97: glic_plot((unsigned char)(x + col), (unsigned char)(y + row), 1u);
	ld	a, 4 (ix)
	add	a, d
	push	hl
	push	bc
	push	de
	ld	h, #0x01
	ld	l, b
	push	hl
	push	af
	inc	sp
	call	_glic_plot
	pop	af
	inc	sp
	pop	de
	pop	bc
	pop	hl
00102$:
;apps/../common/glic80.h:99: mask >>= 1;
	srl	e
;apps/../common/glic80.h:95: for (col = 0u; col < 8u; ++col) {
	inc	d
	ld	a, d
	sub	a, #0x08
	jr	C, 00105$
;apps/../common/glic80.h:92: for (row = 0u; row < 8u; ++row) {
	inc	c
	ld	a, c
	sub	a, #0x08
	jr	C, 00107$
;apps/../common/glic80.h:102: }
	pop	ix
	ret
;apps/../common/glic80.h:104: static void glic_draw_tile8(unsigned char cell_x,
;	---------------------------------
; Function glic_draw_tile8
; ---------------------------------
_glic_draw_tile8:
	push	ix
	ld	ix,#0
	add	ix,sp
	push	af
;apps/../common/glic80.h:110: offset = (((unsigned int)cell_y) << 7) + (((unsigned int)cell_x) << 3);
	ld	c, 5 (ix)
	xor	a, a
	rr	a
	ld	b, c
	rr	b
	rra
	ld	c, a
	ld	l, 4 (ix)
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, bc
	ex	de, hl
;apps/../common/glic80.h:111: for (col = 0u; col < 8u; ++col) {
	ld	c, #0x00
00102$:
;apps/../common/glic80.h:112: GLIC_GVRAM[offset + col] = columns[col];
	ld	l, c
	ld	h, #0x00
	add	hl, de
	ld	-2 (ix), l
	ld	a, h
	add	a, #0x78
	ld	-1 (ix), a
	ld	l, 6 (ix)
	ld	h, 7 (ix)
	ld	b, #0x00
	add	hl, bc
	ld	a, (hl)
	pop	hl
	push	hl
	ld	(hl), a
;apps/../common/glic80.h:111: for (col = 0u; col < 8u; ++col) {
	inc	c
	ld	a, c
	sub	a, #0x08
	jr	C, 00102$
;apps/../common/glic80.h:114: }
	ld	sp, ix
	pop	ix
	ret
;apps/../common/glic80.h:116: static void glic_prepare_screen(unsigned char value) {
;	---------------------------------
; Function glic_prepare_screen
; ---------------------------------
_glic_prepare_screen:
;apps/../common/glic80.h:117: glic_clear_text();
	call	_glic_clear_text
;apps/../common/glic80.h:118: glic_fill_graphics(value);
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_glic_fill_graphics
	inc	sp
;apps/../common/glic80.h:119: }
	ret
;apps/../common/glic80.h:121: static void glic_fill_page_run(unsigned char page,
;	---------------------------------
; Function glic_fill_page_run
; ---------------------------------
_glic_fill_page_run:
;apps/../common/glic80.h:127: p = GLIC_GVRAM + (((unsigned int)page) << 7) + x;
	ld	iy, #2
	add	iy, sp
	ld	c, 0 (iy)
	ld	b, #0x00
	xor	a, a
	rr	b
	ld	b, c
	rr	b
	rra
	ld	c, a
	ld	a, b
	add	a, #0x78
	ld	b, a
	ld	a, c
	ld	hl, #3
	add	hl, sp
	add	a, (hl)
	ld	c, a
	jr	NC, 00117$
	inc	b
00117$:
;apps/../common/glic80.h:128: while (width != 0u) {
	ld	e, 2 (iy)
00101$:
	ld	a, e
	or	a, a
	ret	Z
;apps/../common/glic80.h:129: *p++ = value;
	ld	iy, #5
	add	iy, sp
	ld	a, 0 (iy)
	ld	(bc), a
	inc	bc
;apps/../common/glic80.h:130: --width;
	dec	e
;apps/../common/glic80.h:132: }
	jr	00101$
;apps/../common/glic80.h:134: static void glic_fill_pages(unsigned char first_page,
;	---------------------------------
; Function glic_fill_pages
; ---------------------------------
_glic_fill_pages:
;apps/../common/glic80.h:137: while (page_count != 0u) {
	ld	iy, #2
	add	iy, sp
	ld	b, 0 (iy)
	ld	c, 1 (iy)
00101$:
	ld	a, c
	or	a, a
	ret	Z
;apps/../common/glic80.h:138: glic_fill_page_run(first_page, 0u, GLIC_SCREEN_WIDTH, value);
	push	bc
	ld	hl, #6
	add	hl, sp
	ld	d, (hl)
	ld	e,#0x80
	push	de
	xor	a, a
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_fill_page_run
	pop	af
	pop	af
	pop	bc
;apps/../common/glic80.h:139: ++first_page;
	inc	b
;apps/../common/glic80.h:140: --page_count;
	dec	c
;apps/../common/glic80.h:142: }
	jr	00101$
;apps/../common/glic80.h:144: static void glic_fill_columns(unsigned char x,
;	---------------------------------
; Function glic_fill_columns
; ---------------------------------
_glic_fill_columns:
;apps/../common/glic80.h:149: for (page = 0u; page < GLIC_SCREEN_PAGES; ++page) {
	ld	b, #0x00
00102$:
;apps/../common/glic80.h:150: glic_fill_page_run(page, x, width, value);
	push	bc
	ld	iy, #6
	add	iy, sp
	ld	a, 0 (iy)
	push	af
	inc	sp
	ld	a, -1 (iy)
	dec	iy
	push	af
	inc	sp
	ld	a, -1 (iy)
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_fill_page_run
	pop	af
	pop	af
	pop	bc
;apps/../common/glic80.h:149: for (page = 0u; page < GLIC_SCREEN_PAGES; ++page) {
	inc	b
	ld	a, b
	sub	a, #0x10
	jr	C, 00102$
;apps/../common/glic80.h:152: }
	ret
;apps/dvd_screensaver.c:37: static void clear_logo_area(unsigned char x, unsigned char y) {
;	---------------------------------
; Function clear_logo_area
; ---------------------------------
_clear_logo_area:
	push	ix
	ld	ix,#0
	add	ix,sp
	push	af
;apps/dvd_screensaver.c:44: first_page = (unsigned char)(y >> 3);
	ld	c, 5 (ix)
	srl	c
	srl	c
	srl	c
;apps/dvd_screensaver.c:45: last_page = (unsigned char)((y + LOGO_HEIGHT - 1u) >> 3);
	ld	e, 5 (ix)
	ld	d, #0x00
	ld	hl, #0x0017
	add	hl, de
	ex	de, hl
	srl	d
	rr	e
	srl	d
	rr	e
	srl	d
	rr	e
;apps/dvd_screensaver.c:47: for (page = first_page; page <= last_page; ++page) {
00106$:
	ld	a, e
	sub	a, c
	jr	C, 00108$
;apps/dvd_screensaver.c:48: offset = (((unsigned int)page) << 7) + x;
	ld	a, c
	ld	b, #0x00
	rr	b
	ld	d, a
	rr	d
	ld	a, #0x00
	rra
	ld	l, 4 (ix)
	ld	h, #0x00
	add	a, l
	ld	b, a
	ld	a, d
	adc	a, h
	ld	d, a
	ld	-2 (ix), b
	ld	-1 (ix), d
;apps/dvd_screensaver.c:49: for (col = 0u; col < LOGO_WIDTH; ++col) {
	ld	b, #0x00
00103$:
;apps/dvd_screensaver.c:50: GLIC_GVRAM[offset + col] = GLIC_BLACK;
	ld	a, b
	ld	d, #0x00
	add	a, -2 (ix)
	ld	l, a
	ld	a, d
	adc	a, -1 (ix)
	add	a, #0x78
	ld	h, a
	ld	(hl), #0x00
;apps/dvd_screensaver.c:49: for (col = 0u; col < LOGO_WIDTH; ++col) {
	inc	b
	ld	a, b
	sub	a, #0x2c
	jr	C, 00103$
;apps/dvd_screensaver.c:47: for (page = first_page; page <= last_page; ++page) {
	inc	c
	jr	00106$
00108$:
;apps/dvd_screensaver.c:53: }
	ld	sp, ix
	pop	ix
	ret
_logo_shape:
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0xfc	; 252
	.db #0xfc	; 252
	.db #0x0c	; 12
	.db #0x0c	; 12
	.db #0x0c	; 12
	.db #0x0c	; 12
	.db #0x0c	; 12
	.db #0x0c	; 12
	.db #0xf0	; 240
	.db #0xf0	; 240
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0xfc	; 252
	.db #0xfc	; 252
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0xfc	; 252
	.db #0xfc	; 252
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0xfc	; 252
	.db #0xfc	; 252
	.db #0x0c	; 12
	.db #0x0c	; 12
	.db #0x0c	; 12
	.db #0x0c	; 12
	.db #0x0c	; 12
	.db #0x0c	; 12
	.db #0xf0	; 240
	.db #0xf0	; 240
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0xff	; 255
	.db #0xff	; 255
	.db #0xc0	; 192
	.db #0xc0	; 192
	.db #0xc0	; 192
	.db #0xc0	; 192
	.db #0xc0	; 192
	.db #0xc0	; 192
	.db #0x3f	; 63
	.db #0x3f	; 63
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x0f	; 15
	.db #0x0f	; 15
	.db #0xf0	; 240
	.db #0xf0	; 240
	.db #0x0f	; 15
	.db #0x0f	; 15
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0xff	; 255
	.db #0xff	; 255
	.db #0xc0	; 192
	.db #0xc0	; 192
	.db #0xc0	; 192
	.db #0xc0	; 192
	.db #0xc0	; 192
	.db #0xc0	; 192
	.db #0x3f	; 63
	.db #0x3f	; 63
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x08	; 8
	.db #0x1c	; 28
	.db #0x1c	; 28
	.db #0x1c	; 28
	.db #0x1c	; 28
	.db #0x3e	; 62
	.db #0x3e	; 62
	.db #0x3e	; 62
	.db #0x3e	; 62
	.db #0x3e	; 62
	.db #0x3e	; 62
	.db #0x7f	; 127
	.db #0x7f	; 127
	.db #0x7f	; 127
	.db #0x7f	; 127
	.db #0x7f	; 127
	.db #0x7f	; 127
	.db #0x7f	; 127
	.db #0x7f	; 127
	.db #0x7f	; 127
	.db #0x7f	; 127
	.db #0x7f	; 127
	.db #0x7f	; 127
	.db #0x7f	; 127
	.db #0x7f	; 127
	.db #0x7f	; 127
	.db #0x7f	; 127
	.db #0x7f	; 127
	.db #0x7f	; 127
	.db #0x7f	; 127
	.db #0x7f	; 127
	.db #0x7f	; 127
	.db #0x7f	; 127
	.db #0x3e	; 62
	.db #0x3e	; 62
	.db #0x3e	; 62
	.db #0x3e	; 62
	.db #0x3e	; 62
	.db #0x3e	; 62
	.db #0x1c	; 28
	.db #0x1c	; 28
	.db #0x1c	; 28
	.db #0x1c	; 28
	.db #0x08	; 8
;apps/dvd_screensaver.c:55: static void draw_logo_aligned(unsigned char x, unsigned char page) {
;	---------------------------------
; Function draw_logo_aligned
; ---------------------------------
_draw_logo_aligned:
	push	ix
	ld	ix,#0
	add	ix,sp
	push	af
	dec	sp
;apps/dvd_screensaver.c:61: for (logo_page = 0u; logo_page < LOGO_PAGES; ++logo_page) {
	ld	c, #0x00
00105$:
;apps/dvd_screensaver.c:62: offset = (((unsigned int)(page + logo_page)) << 7) + x;
	ld	e, 5 (ix)
	ld	d, #0x00
	ld	l, c
	ld	h, #0x00
	add	hl, de
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	ld	e, 4 (ix)
	ld	d, #0x00
	add	hl, de
	ex	(sp), hl
;apps/dvd_screensaver.c:63: for (col = 0u; col < LOGO_WIDTH; ++col) {
	ld	b, #0x00
	ld	l, c
	ld	h, b
	add	hl, hl
	add	hl, hl
	add	hl, bc
	add	hl, hl
	add	hl, bc
	add	hl, hl
	add	hl, hl
	ex	de, hl
	ld	hl, #_logo_shape
	add	hl, de
	ex	de, hl
	ld	b, #0x00
00103$:
;apps/dvd_screensaver.c:64: bits = logo_shape[logo_page][col];
	ld	l, b
	ld	h, #0x00
	add	hl, de
	ld	a, (hl)
	ld	-1 (ix), a
;apps/dvd_screensaver.c:65: GLIC_GVRAM[offset + col] |= bits;
	ld	a, b
	ld	h, #0x00
	add	a, -3 (ix)
	ld	l, a
	ld	a, h
	adc	a, -2 (ix)
	add	a, #0x78
	ld	h, a
	ld	a, (hl)
	or	a, -1 (ix)
	ld	(hl), a
;apps/dvd_screensaver.c:63: for (col = 0u; col < LOGO_WIDTH; ++col) {
	inc	b
	ld	a, b
	sub	a, #0x2c
	jr	C, 00103$
;apps/dvd_screensaver.c:61: for (logo_page = 0u; logo_page < LOGO_PAGES; ++logo_page) {
	inc	c
	ld	a, c
	sub	a, #0x03
	jr	C, 00105$
;apps/dvd_screensaver.c:68: }
	ld	sp, ix
	pop	ix
	ret
;apps/dvd_screensaver.c:70: static void draw_logo_shifted(unsigned char x,
;	---------------------------------
; Function draw_logo_shifted
; ---------------------------------
_draw_logo_shifted:
	push	ix
	ld	ix,#0
	add	ix,sp
	ld	hl, #-9
	add	hl, sp
	ld	sp, hl
;apps/dvd_screensaver.c:79: spill_shift = (unsigned char)(8u - shift);
	ld	a, #0x08
	sub	a, 6 (ix)
	ld	-9 (ix), a
;apps/dvd_screensaver.c:81: for (logo_page = 0u; logo_page < LOGO_PAGES; ++logo_page) {
	ld	c, #0x00
00107$:
;apps/dvd_screensaver.c:82: offset = (((unsigned int)(page + logo_page)) << 7) + x;
	ld	e, 5 (ix)
	ld	d, #0x00
	ld	l, c
	ld	h, #0x00
	add	hl, de
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	ld	e, 4 (ix)
	ld	d, #0x00
	add	hl, de
	ex	de, hl
;apps/dvd_screensaver.c:83: for (col = 0u; col < LOGO_WIDTH; ++col) {
	ld	hl, #0x0080
	add	hl, de
	ld	-8 (ix), l
	ld	-7 (ix), h
	ld	b, #0x00
	ld	l, c
	ld	h, b
	add	hl, hl
	add	hl, hl
	add	hl, bc
	add	hl, hl
	add	hl, bc
	add	hl, hl
	add	hl, hl
	ld	a, #<(_logo_shape)
	add	a, l
	ld	-6 (ix), a
	ld	a, #>(_logo_shape)
	adc	a, h
	ld	-5 (ix), a
	ld	-1 (ix), #0
00105$:
;apps/dvd_screensaver.c:84: bits = logo_shape[logo_page][col];
	ld	a, -6 (ix)
	add	a, -1 (ix)
	ld	l, a
	ld	a, -5 (ix)
	adc	a, #0x00
	ld	h, a
	ld	b, (hl)
;apps/dvd_screensaver.c:85: if (bits != 0u) {
	ld	a, b
	or	a, a
	jr	Z, 00106$
;apps/dvd_screensaver.c:86: GLIC_GVRAM[offset + col] |= (unsigned char)(bits << shift);
	ld	a, -1 (ix)
	ld	l, #0x00
	ld	-4 (ix), a
	ld	-3 (ix), l
	ld	l, -4 (ix)
	ld	h, -3 (ix)
	add	hl, de
	ld	a, h
	add	a, #0x78
	ld	h, a
	ld	a, (hl)
	push	af
	ld	a, 6 (ix)
	ld	-2 (ix), b
	inc	a
	jr	00134$
00133$:
	sla	-2 (ix)
00134$:
	dec	a
	jr	NZ,00133$
	pop	af
	or	a, -2 (ix)
	ld	(hl), a
;apps/dvd_screensaver.c:87: GLIC_GVRAM[offset + 128u + col] |=
	ld	a, -4 (ix)
	add	a, -8 (ix)
	ld	l, a
	ld	a, -3 (ix)
	adc	a, -7 (ix)
	add	a, #0x78
	ld	h, a
	ld	a, (hl)
	ld	-2 (ix), a
;apps/dvd_screensaver.c:88: (unsigned char)(bits >> spill_shift);
	ld	a, -9 (ix)
	inc	a
	jr	00136$
00135$:
	srl	b
00136$:
	dec	a
	jr	NZ, 00135$
	ld	a, -2 (ix)
	or	a, b
	ld	(hl), a
00106$:
;apps/dvd_screensaver.c:83: for (col = 0u; col < LOGO_WIDTH; ++col) {
	inc	-1 (ix)
	ld	a, -1 (ix)
	sub	a, #0x2c
	jr	C, 00105$
;apps/dvd_screensaver.c:81: for (logo_page = 0u; logo_page < LOGO_PAGES; ++logo_page) {
	inc	c
	ld	a, c
	sub	a, #0x03
	jp	C, 00107$
;apps/dvd_screensaver.c:92: }
	ld	sp, ix
	pop	ix
	ret
;apps/dvd_screensaver.c:94: static void draw_logo(unsigned char x, unsigned char y) {
;	---------------------------------
; Function draw_logo
; ---------------------------------
_draw_logo:
;apps/dvd_screensaver.c:98: page = (unsigned char)(y >> 3);
	ld	iy, #3
	add	iy, sp
	ld	b, 0 (iy)
	srl	b
	srl	b
	srl	b
;apps/dvd_screensaver.c:99: shift = (unsigned char)(y & 7u);
	ld	a, 0 (iy)
	and	a, #0x07
	ld	d, a
;apps/dvd_screensaver.c:101: if (shift == 0u) {
	or	a, a
	jr	NZ, 00102$
;apps/dvd_screensaver.c:102: draw_logo_aligned(x, page);
	push	bc
	inc	sp
	ld	a, -1 (iy)
	push	af
	inc	sp
	call	_draw_logo_aligned
	pop	af
	ret
00102$:
;apps/dvd_screensaver.c:104: draw_logo_shifted(x, page, shift);
	ld	e, b
	push	de
	ld	hl, #4
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_draw_logo_shifted
	pop	af
	inc	sp
;apps/dvd_screensaver.c:106: }
	ret
;apps/dvd_screensaver.c:108: void main(void) {
;	---------------------------------
; Function main
; ---------------------------------
_main::
	push	ix
	ld	ix,#0
	add	ix,sp
	push	af
	dec	sp
;apps/dvd_screensaver.c:114: glic_prepare_screen(GLIC_BLACK);
	xor	a, a
	push	af
	inc	sp
	call	_glic_prepare_screen
	inc	sp
;apps/dvd_screensaver.c:116: x = 9u;
	ld	c, #0x09
;apps/dvd_screensaver.c:117: y = 16u;
	ld	e, #0x10
;apps/dvd_screensaver.c:118: move_right = 1u;
	ld	-3 (ix), #0x01
;apps/dvd_screensaver.c:119: move_down = 1u;
	ld	-2 (ix), #0x01
;apps/dvd_screensaver.c:121: draw_logo(x, y);
	push	bc
	push	de
	ld	de, #0x1009
	push	de
	call	_draw_logo
	pop	af
	pop	de
	pop	bc
;apps/dvd_screensaver.c:123: while (1) {
00120$:
;apps/dvd_screensaver.c:124: glic_delay(FRAME_DELAY);
	push	bc
	push	de
	ld	hl, #0x0708
	push	hl
	call	_glic_delay
	pop	af
	pop	de
	pop	bc
;apps/dvd_screensaver.c:125: clear_logo_area(x, y);
	push	bc
	push	de
	ld	b, e
	push	bc
	call	_clear_logo_area
	pop	af
	pop	de
	pop	bc
;apps/dvd_screensaver.c:129: ++x;
	ld	a, c
	inc	a
	ld	-1 (ix), a
;apps/dvd_screensaver.c:132: --x;
	ld	b, c
	dec	b
;apps/dvd_screensaver.c:127: if (move_right != 0u) {
	ld	a, -3 (ix)
	or	a, a
	jr	Z, 00108$
;apps/dvd_screensaver.c:128: if (x < LOGO_MAX_X) {
	ld	a, c
	sub	a, #0x54
	jr	NC, 00102$
;apps/dvd_screensaver.c:129: ++x;
	ld	c, -1 (ix)
	jr	00109$
00102$:
;apps/dvd_screensaver.c:131: move_right = 0u;
	ld	-3 (ix), #0
;apps/dvd_screensaver.c:132: --x;
	ld	c, b
	jr	00109$
00108$:
;apps/dvd_screensaver.c:134: } else if (x != 0u) {
	ld	a, c
	or	a, a
	jr	Z, 00105$
;apps/dvd_screensaver.c:135: --x;
	ld	c, b
	jr	00109$
00105$:
;apps/dvd_screensaver.c:137: move_right = 1u;
	ld	-3 (ix), #0x01
;apps/dvd_screensaver.c:138: ++x;
	ld	c, -1 (ix)
00109$:
;apps/dvd_screensaver.c:143: ++y;
	ld	b, e
	inc	b
;apps/dvd_screensaver.c:146: --y;
	ld	d, e
	dec	d
;apps/dvd_screensaver.c:141: if (move_down != 0u) {
	ld	a, -2 (ix)
	or	a, a
	jr	Z, 00117$
;apps/dvd_screensaver.c:142: if (y < LOGO_MAX_Y) {
	ld	a, e
	sub	a, #0x68
	jr	NC, 00111$
;apps/dvd_screensaver.c:143: ++y;
	ld	e, b
	jr	00118$
00111$:
;apps/dvd_screensaver.c:145: move_down = 0u;
	ld	-2 (ix), #0
;apps/dvd_screensaver.c:146: --y;
	ld	e, d
	jr	00118$
00117$:
;apps/dvd_screensaver.c:148: } else if (y != 0u) {
	ld	a, e
	or	a, a
	jr	Z, 00114$
;apps/dvd_screensaver.c:149: --y;
	ld	e, d
	jr	00118$
00114$:
;apps/dvd_screensaver.c:151: move_down = 1u;
	ld	-2 (ix), #0x01
;apps/dvd_screensaver.c:152: ++y;
	ld	e, b
00118$:
;apps/dvd_screensaver.c:155: draw_logo(x, y);
	push	bc
	push	de
	ld	b, e
	push	bc
	call	_draw_logo
	pop	af
	pop	de
	pop	bc
;apps/dvd_screensaver.c:157: }
	jr	00120$
	.area _CODE
	.area _INITIALIZER
	.area _CABS (ABS)
