; generated by sdcc-z80-bin
    JR __sdcc_z80_bin_start
    DB "mini_os",0
__sdcc_z80_bin_start:
    LD SP,#0x7700
    CALL _main
__sdcc_z80_bin_halt:
    JR __sdcc_z80_bin_halt

;--------------------------------------------------------
; File Created by SDCC : free open source ANSI-C Compiler
; Version 4.1.0 #12072 (Linux)
;--------------------------------------------------------
	.module mini_os
	.optsdcc -mz80
	
;--------------------------------------------------------
; Public variables in this module
;--------------------------------------------------------
	.globl _main
;--------------------------------------------------------
; special function registers
;--------------------------------------------------------
;--------------------------------------------------------
; ram data
;--------------------------------------------------------
	.area _DATA
;--------------------------------------------------------
; ram data
;--------------------------------------------------------
	.area _INITIALIZED
;--------------------------------------------------------
; absolute external ram data
;--------------------------------------------------------
	.area _DABS (ABS)
;--------------------------------------------------------
; global & static initialisations
;--------------------------------------------------------
	.area _HOME
	.area _GSINIT
	.area _GSFINAL
	.area _GSINIT
;--------------------------------------------------------
; Home
;--------------------------------------------------------
	.area _HOME
	.area _HOME
;--------------------------------------------------------
; code
;--------------------------------------------------------
	.area _CODE
;apps/../common/glic80.h:29: static unsigned char glic_read_buttons(void) __naked {
;	---------------------------------
; Function glic_read_buttons
; ---------------------------------
_glic_read_buttons:
;apps/../common/glic80.h:34: __endasm;
	in	a,(0)
	ld	l,a
	ret
;apps/../common/glic80.h:35: }
;apps/../common/glic80.h:37: static unsigned char glic_button_pressed(unsigned char buttons,
;	---------------------------------
; Function glic_button_pressed
; ---------------------------------
_glic_button_pressed:
;apps/../common/glic80.h:39: return (buttons & mask) == 0u;
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	inc	iy
	and	a, 0 (iy)
	or	a, a
	ld	a, #0x01
	jr	Z, 00104$
	xor	a, a
00104$:
	ld	l, a
;apps/../common/glic80.h:40: }
	ret
_glic_bit_masks:
	.db #0x01	; 1
	.db #0x02	; 2
	.db #0x04	; 4
	.db #0x08	; 8
	.db #0x10	; 16
	.db #0x20	; 32
	.db #0x40	; 64
	.db #0x80	; 128
;apps/../common/glic80.h:42: static void glic_delay(unsigned int count) {
;	---------------------------------
; Function glic_delay
; ---------------------------------
_glic_delay:
;apps/../common/glic80.h:43: while (count != 0u) {
	pop	de
	pop	bc
	push	bc
	push	de
00101$:
	ld	a, b
	or	a, c
	ret	Z
;apps/../common/glic80.h:44: --count;
	dec	bc
;apps/../common/glic80.h:47: __endasm;
	nop
;apps/../common/glic80.h:49: }
	jr	00101$
;apps/../common/glic80.h:51: static void glic_clear_text(void) {
;	---------------------------------
; Function glic_clear_text
; ---------------------------------
_glic_clear_text:
;apps/../common/glic80.h:54: for (i = 0; i < GLIC_CVRAM_BYTES; ++i) {
	ld	bc, #0x0000
00102$:
;apps/../common/glic80.h:55: GLIC_CVRAM[i] = 0x00u;
	ld	hl, #0x7700
	add	hl, bc
	ld	(hl), #0x00
;apps/../common/glic80.h:54: for (i = 0; i < GLIC_CVRAM_BYTES; ++i) {
	inc	bc
	ld	a, b
	sub	a, #0x01
	jr	C, 00102$
;apps/../common/glic80.h:57: }
	ret
;apps/../common/glic80.h:59: static void glic_fill_graphics(unsigned char value) {
;	---------------------------------
; Function glic_fill_graphics
; ---------------------------------
_glic_fill_graphics:
;apps/../common/glic80.h:62: for (i = 0; i < GLIC_GVRAM_BYTES; ++i) {
	ld	bc, #0x0000
00102$:
;apps/../common/glic80.h:63: GLIC_GVRAM[i] = value;
	ld	hl, #0x7800
	add	hl, bc
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	ld	(hl), a
;apps/../common/glic80.h:62: for (i = 0; i < GLIC_GVRAM_BYTES; ++i) {
	inc	bc
	ld	a, b
	sub	a, #0x08
	jr	C, 00102$
;apps/../common/glic80.h:65: }
	ret
;apps/../common/glic80.h:67: static void glic_plot(unsigned char x, unsigned char y, unsigned char value) {
;	---------------------------------
; Function glic_plot
; ---------------------------------
_glic_plot:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/../common/glic80.h:71: if ((x >= GLIC_SCREEN_WIDTH) || (y >= 128u)) {
	ld	a, 4 (ix)
	sub	a, #0x80
	jr	NC, 00107$
	ld	a, 5 (ix)
	sub	a, #0x80
;apps/../common/glic80.h:72: return;
	jr	NC, 00107$
;apps/../common/glic80.h:75: offset = (((unsigned int)(y >> 3)) << 7) + x;
	ld	a, 5 (ix)
	rrca
	rrca
	rrca
	and	a, #0x1f
	ld	l, a
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	ld	c, 4 (ix)
	ld	b, #0x00
	add	hl, bc
	ex	de, hl
;apps/../common/glic80.h:76: mask = glic_bit_masks[y & 7u];
	ld	bc, #_glic_bit_masks+0
	ld	a, 5 (ix)
	and	a, #0x07
	ld	l, a
	ld	h, #0x00
	add	hl, bc
	ld	b, (hl)
;apps/../common/glic80.h:78: GLIC_GVRAM[offset] |= mask;
	ld	hl, #0x7800
	add	hl, de
	ld	c, (hl)
;apps/../common/glic80.h:77: if (value != 0u) {
	ld	a, 6 (ix)
	or	a, a
	jr	Z, 00105$
;apps/../common/glic80.h:78: GLIC_GVRAM[offset] |= mask;
	ld	a, c
	or	a, b
	ld	(hl), a
	jr	00107$
00105$:
;apps/../common/glic80.h:80: GLIC_GVRAM[offset] &= (unsigned char)~mask;
	ld	a, b
	cpl
	and	a, c
	ld	(hl), a
00107$:
;apps/../common/glic80.h:82: }
	pop	ix
	ret
;apps/../common/glic80.h:84: static void glic_draw_bitmap8(unsigned char x,
;	---------------------------------
; Function glic_draw_bitmap8
; ---------------------------------
_glic_draw_bitmap8:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/../common/glic80.h:92: for (row = 0u; row < 8u; ++row) {
	ld	c, #0x00
00107$:
;apps/../common/glic80.h:93: bits = rows[row];
	ld	l, 6 (ix)
	ld	h, 7 (ix)
	ld	b, #0x00
	add	hl, bc
	ld	l, (hl)
;apps/../common/glic80.h:94: mask = 0x80u;
	ld	e, #0x80
;apps/../common/glic80.h:95: for (col = 0u; col < 8u; ++col) {
	ld	a, 5 (ix)
	add	a, c
	ld	b, a
	ld	d, #0x00
00105$:
;apps/../common/glic80.h:96: if ((bits & mask) != 0u) {
	ld	a, l
	and	a,e
	jr	Z, 00102$
;apps/../common/glic80.h:97: glic_plot((unsigned char)(x + col), (unsigned char)(y + row), 1u);
	ld	a, 4 (ix)
	add	a, d
	push	hl
	push	bc
	push	de
	ld	h, #0x01
	ld	l, b
	push	hl
	push	af
	inc	sp
	call	_glic_plot
	pop	af
	inc	sp
	pop	de
	pop	bc
	pop	hl
00102$:
;apps/../common/glic80.h:99: mask >>= 1;
	srl	e
;apps/../common/glic80.h:95: for (col = 0u; col < 8u; ++col) {
	inc	d
	ld	a, d
	sub	a, #0x08
	jr	C, 00105$
;apps/../common/glic80.h:92: for (row = 0u; row < 8u; ++row) {
	inc	c
	ld	a, c
	sub	a, #0x08
	jr	C, 00107$
;apps/../common/glic80.h:102: }
	pop	ix
	ret
;apps/../common/glic80.h:104: static void glic_draw_tile8(unsigned char cell_x,
;	---------------------------------
; Function glic_draw_tile8
; ---------------------------------
_glic_draw_tile8:
	push	ix
	ld	ix,#0
	add	ix,sp
	push	af
;apps/../common/glic80.h:110: offset = (((unsigned int)cell_y) << 7) + (((unsigned int)cell_x) << 3);
	ld	c, 5 (ix)
	xor	a, a
	rr	a
	ld	b, c
	rr	b
	rra
	ld	c, a
	ld	l, 4 (ix)
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, bc
	ex	de, hl
;apps/../common/glic80.h:111: for (col = 0u; col < 8u; ++col) {
	ld	c, #0x00
00102$:
;apps/../common/glic80.h:112: GLIC_GVRAM[offset + col] = columns[col];
	ld	l, c
	ld	h, #0x00
	add	hl, de
	ld	-2 (ix), l
	ld	a, h
	add	a, #0x78
	ld	-1 (ix), a
	ld	l, 6 (ix)
	ld	h, 7 (ix)
	ld	b, #0x00
	add	hl, bc
	ld	a, (hl)
	pop	hl
	push	hl
	ld	(hl), a
;apps/../common/glic80.h:111: for (col = 0u; col < 8u; ++col) {
	inc	c
	ld	a, c
	sub	a, #0x08
	jr	C, 00102$
;apps/../common/glic80.h:114: }
	ld	sp, ix
	pop	ix
	ret
;apps/../common/glic80.h:116: static void glic_prepare_screen(unsigned char value) {
;	---------------------------------
; Function glic_prepare_screen
; ---------------------------------
_glic_prepare_screen:
;apps/../common/glic80.h:117: glic_clear_text();
	call	_glic_clear_text
;apps/../common/glic80.h:118: glic_fill_graphics(value);
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_glic_fill_graphics
	inc	sp
;apps/../common/glic80.h:119: }
	ret
;apps/../common/glic80.h:121: static void glic_fill_page_run(unsigned char page,
;	---------------------------------
; Function glic_fill_page_run
; ---------------------------------
_glic_fill_page_run:
;apps/../common/glic80.h:127: p = GLIC_GVRAM + (((unsigned int)page) << 7) + x;
	ld	iy, #2
	add	iy, sp
	ld	c, 0 (iy)
	ld	b, #0x00
	xor	a, a
	rr	b
	ld	b, c
	rr	b
	rra
	ld	c, a
	ld	a, b
	add	a, #0x78
	ld	b, a
	ld	a, c
	ld	hl, #3
	add	hl, sp
	add	a, (hl)
	ld	c, a
	jr	NC, 00117$
	inc	b
00117$:
;apps/../common/glic80.h:128: while (width != 0u) {
	ld	e, 2 (iy)
00101$:
	ld	a, e
	or	a, a
	ret	Z
;apps/../common/glic80.h:129: *p++ = value;
	ld	iy, #5
	add	iy, sp
	ld	a, 0 (iy)
	ld	(bc), a
	inc	bc
;apps/../common/glic80.h:130: --width;
	dec	e
;apps/../common/glic80.h:132: }
	jr	00101$
;apps/../common/glic80.h:134: static void glic_fill_pages(unsigned char first_page,
;	---------------------------------
; Function glic_fill_pages
; ---------------------------------
_glic_fill_pages:
;apps/../common/glic80.h:137: while (page_count != 0u) {
	ld	iy, #2
	add	iy, sp
	ld	b, 0 (iy)
	ld	c, 1 (iy)
00101$:
	ld	a, c
	or	a, a
	ret	Z
;apps/../common/glic80.h:138: glic_fill_page_run(first_page, 0u, GLIC_SCREEN_WIDTH, value);
	push	bc
	ld	hl, #6
	add	hl, sp
	ld	d, (hl)
	ld	e,#0x80
	push	de
	xor	a, a
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_fill_page_run
	pop	af
	pop	af
	pop	bc
;apps/../common/glic80.h:139: ++first_page;
	inc	b
;apps/../common/glic80.h:140: --page_count;
	dec	c
;apps/../common/glic80.h:142: }
	jr	00101$
;apps/../common/glic80.h:144: static void glic_fill_columns(unsigned char x,
;	---------------------------------
; Function glic_fill_columns
; ---------------------------------
_glic_fill_columns:
;apps/../common/glic80.h:149: for (page = 0u; page < GLIC_SCREEN_PAGES; ++page) {
	ld	b, #0x00
00102$:
;apps/../common/glic80.h:150: glic_fill_page_run(page, x, width, value);
	push	bc
	ld	iy, #6
	add	iy, sp
	ld	a, 0 (iy)
	push	af
	inc	sp
	ld	a, -1 (iy)
	dec	iy
	push	af
	inc	sp
	ld	a, -1 (iy)
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_fill_page_run
	pop	af
	pop	af
	pop	bc
;apps/../common/glic80.h:149: for (page = 0u; page < GLIC_SCREEN_PAGES; ++page) {
	inc	b
	ld	a, b
	sub	a, #0x10
	jr	C, 00102$
;apps/../common/glic80.h:152: }
	ret
;apps/mini_os.c:43: static volatile unsigned char *text_cell(unsigned char row,
;	---------------------------------
; Function text_cell
; ---------------------------------
_text_cell:
;apps/mini_os.c:48: while (row != 0u) {
	ld	bc, #0x7700
	ld	iy, #2
	add	iy, sp
	ld	l, 0 (iy)
00101$:
	ld	a, l
	or	a, a
	jr	Z, 00103$
;apps/mini_os.c:49: p += 16u;
	ld	a, c
	add	a, #0x10
	ld	c, a
	jr	NC, 00117$
	inc	b
00117$:
;apps/mini_os.c:50: --row;
	dec	l
	jr	00101$
00103$:
;apps/mini_os.c:52: p += col;
	ld	a, c
	ld	hl, #3
	add	hl, sp
	add	a, (hl)
	ld	l, a
	jr	NC, 00118$
	inc	b
00118$:
	ld	h, b
;apps/mini_os.c:53: return p;
;apps/mini_os.c:54: }
	ret
_math_left:
	.db #0x03	;  3
	.db #0x07	;  7
	.db #0x0c	;  12
	.db #0x09	;  9
	.db #0x08	;  8
	.db #0x0f	;  15
_math_right:
	.db #0x04	;  4
	.db #0x05	;  5
	.db #0x03	;  3
	.db #0x06	;  6
	.db #0x07	;  7
	.db #0x02	;  2
_math_op:
	.db #0x2b	; 43
	.db #0x2b	; 43
	.db #0x2d	; 45
	.db #0x2b	; 43
	.db #0x2d	; 45
	.db #0x2b	; 43
;apps/mini_os.c:56: static void text_put(unsigned char row, unsigned char col, unsigned char ch) {
;	---------------------------------
; Function text_put
; ---------------------------------
_text_put:
;apps/mini_os.c:57: if ((row >= 16u) || (col >= 16u)) {
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	sub	a, #0x10
	ret	NC
	ld	a, 1 (iy)
	sub	a, #0x10
;apps/mini_os.c:58: return;
	ret	NC
;apps/mini_os.c:60: *text_cell(row, col) = ch;
	ld	iy, #3
	add	iy, sp
	ld	h, 0 (iy)
	ld	l, -1 (iy)
	push	hl
	call	_text_cell
	pop	af
	ld	iy, #4
	add	iy, sp
	ld	a, 0 (iy)
	ld	(hl), a
;apps/mini_os.c:61: }
	ret
;apps/mini_os.c:63: static void text_clear_row(unsigned char row) {
;	---------------------------------
; Function text_clear_row
; ---------------------------------
_text_clear_row:
;apps/mini_os.c:66: for (col = 0u; col < 16u; ++col) {
	ld	b, #0x00
00102$:
;apps/mini_os.c:67: text_put(row, col, 0u);
	push	bc
	xor	a, a
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	hl, #6
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
	pop	bc
;apps/mini_os.c:66: for (col = 0u; col < 16u; ++col) {
	inc	b
	ld	a, b
	sub	a, #0x10
	jr	C, 00102$
;apps/mini_os.c:69: }
	ret
;apps/mini_os.c:71: static void text_write(unsigned char row, unsigned char col, const char *text) {
;	---------------------------------
; Function text_write
; ---------------------------------
_text_write:
;apps/mini_os.c:72: while ((*text != 0) && (col < 16u)) {
	ld	iy, #4
	add	iy, sp
	ld	l, 0 (iy)
	ld	h, 1 (iy)
	ld	b, -1 (iy)
00102$:
	ld	d, (hl)
	ld	a, d
	or	a, a
	ret	Z
	ld	a, b
	sub	a, #0x10
	ret	NC
;apps/mini_os.c:73: text_put(row, col, (unsigned char)*text);
	push	hl
	push	bc
	ld	e, b
	push	de
	ld	hl, #8
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
	pop	bc
	pop	hl
;apps/mini_os.c:74: ++text;
	inc	hl
;apps/mini_os.c:75: ++col;
	inc	b
;apps/mini_os.c:77: }
	jr	00102$
;apps/mini_os.c:79: static void text_write_u16(unsigned char row,
;	---------------------------------
; Function text_write_u16
; ---------------------------------
_text_write_u16:
	push	ix
	ld	ix,#0
	add	ix,sp
	dec	sp
;apps/mini_os.c:86: place = 10000u;
	ld	bc, #0x2710
;apps/mini_os.c:87: started = 0u;
	ld	e, #0x00
;apps/mini_os.c:88: while ((place != 0u) && (col < 16u)) {
	ld	d, 5 (ix)
00121$:
	ld	a, b
	or	a, c
	jp	Z, 00124$
	ld	a, d
	sub	a, #0x10
	jp	NC, 00124$
;apps/mini_os.c:90: while (value >= place) {
	ld	l, #0x00
00101$:
	ld	a, 6 (ix)
	sub	a, c
	ld	a, 7 (ix)
	sbc	a, b
	jr	C, 00137$
;apps/mini_os.c:91: value = (unsigned int)(value - place);
	ld	a, 6 (ix)
	sub	a, c
	ld	6 (ix), a
	ld	a, 7 (ix)
	sbc	a, b
	ld	7 (ix), a
;apps/mini_os.c:92: ++digit;
	inc	l
	jr	00101$
00137$:
	ld	-1 (ix), l
;apps/mini_os.c:94: if ((started != 0u) || (digit != 0u) || (place == 1u)) {
	ld	a, e
	or	a,a
	jr	NZ, 00104$
	or	a,l
	jr	NZ, 00104$
	ld	a, c
	dec	a
	or	a, b
	jr	NZ, 00105$
00104$:
;apps/mini_os.c:95: text_put(row, col, (unsigned char)('0' + digit));
	ld	a, -1 (ix)
	add	a, #0x30
	push	bc
	push	de
	push	af
	inc	sp
	push	de
	inc	sp
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
	pop	de
	pop	bc
;apps/mini_os.c:96: ++col;
	inc	d
;apps/mini_os.c:97: started = 1u;
	ld	e, #0x01
00105$:
;apps/mini_os.c:100: if (place == 10000u) {
	ld	a, c
	sub	a, #0x10
	jr	NZ, 00118$
	ld	a, b
	sub	a, #0x27
	jr	NZ, 00118$
;apps/mini_os.c:101: place = 1000u;
	ld	bc, #0x03e8
	jr	00121$
00118$:
;apps/mini_os.c:102: } else if (place == 1000u) {
	ld	a, c
	sub	a, #0xe8
	jr	NZ, 00115$
	ld	a, b
	sub	a, #0x03
	jr	NZ, 00115$
;apps/mini_os.c:103: place = 100u;
	ld	bc, #0x0064
	jr	00121$
00115$:
;apps/mini_os.c:104: } else if (place == 100u) {
	ld	a, c
	sub	a, #0x64
	or	a, b
	jr	NZ, 00112$
;apps/mini_os.c:105: place = 10u;
	ld	bc, #0x000a
	jr	00121$
00112$:
;apps/mini_os.c:106: } else if (place == 10u) {
	ld	a, c
	sub	a, #0x0a
	or	a, b
	jr	NZ, 00109$
;apps/mini_os.c:107: place = 1u;
	ld	bc, #0x0001
	jp	00121$
00109$:
;apps/mini_os.c:109: place = 0u;
	ld	bc, #0x0000
	jp	00121$
00124$:
;apps/mini_os.c:112: }
	inc	sp
	pop	ix
	ret
;apps/mini_os.c:114: static void text_write_i16(unsigned char row, unsigned char col, int value) {
;	---------------------------------
; Function text_write_i16
; ---------------------------------
_text_write_i16:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/mini_os.c:115: if (value < 0) {
	bit	7, 7 (ix)
	jr	Z, 00102$
;apps/mini_os.c:116: text_put(row, col, '-');
	ld	h, #0x2d
	ld	l, 5 (ix)
	push	hl
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
;apps/mini_os.c:117: ++col;
	inc	5 (ix)
;apps/mini_os.c:118: value = -value;
	xor	a, a
	sub	a, 6 (ix)
	ld	6 (ix), a
	ld	a, #0x00
	sbc	a, 7 (ix)
	ld	7 (ix), a
00102$:
;apps/mini_os.c:120: text_write_u16(row, col, (unsigned int)value);
	ld	c, 6 (ix)
	ld	b, 7 (ix)
	push	bc
	ld	h, 5 (ix)
	ld	l, 4 (ix)
	push	hl
	call	_text_write_u16
	pop	af
	pop	af
;apps/mini_os.c:121: }
	pop	ix
	ret
;apps/mini_os.c:123: static unsigned char button_edge(unsigned char buttons,
;	---------------------------------
; Function button_edge
; ---------------------------------
_button_edge:
;apps/mini_os.c:126: return (((last_buttons & mask) != 0u) && ((buttons & mask) == 0u));
	ld	iy, #3
	add	iy, sp
	ld	a, 0 (iy)
	inc	iy
	and	a, 0 (iy)
	or	a, a
	jr	Z, 00103$
	ld	a, -2 (iy)
	and	a, 0 (iy)
	or	a, a
	jr	Z, 00104$
00103$:
	ld	l, #0x00
	ret
00104$:
	ld	l, #0x01
;apps/mini_os.c:127: }
	ret
;apps/mini_os.c:129: static void wait_for_release(void) {
;	---------------------------------
; Function wait_for_release
; ---------------------------------
_wait_for_release:
;apps/mini_os.c:130: while (glic_read_buttons() != GLIC_BUTTONS_NONE) {
00101$:
	call	_glic_read_buttons
	inc	l
	ret	Z
;apps/mini_os.c:131: glic_delay(500u);
	ld	hl, #0x01f4
	push	hl
	call	_glic_delay
	pop	af
;apps/mini_os.c:133: }
	jr	00101$
;apps/mini_os.c:135: static unsigned char store_read(unsigned char offset) {
;	---------------------------------
; Function store_read
; ---------------------------------
_store_read:
;apps/mini_os.c:136: return OS_STORE[offset];
	ld	iy, #2
	add	iy, sp
	ld	l, 0 (iy)
	ld	a, #0x00
	add	a, #0x60
	ld	h, a
	ld	l, (hl)
;apps/mini_os.c:137: }
	ret
;apps/mini_os.c:139: static void store_write(unsigned char offset, unsigned char value) {
;	---------------------------------
; Function store_write
; ---------------------------------
_store_write:
;apps/mini_os.c:140: OS_STORE[offset] = value;
	ld	iy, #2
	add	iy, sp
	ld	c, 0 (iy)
	ld	a, #0x00
	add	a, #0x60
	ld	b, a
	ld	a, 1 (iy)
	ld	(bc), a
;apps/mini_os.c:141: }
	ret
;apps/mini_os.c:143: static unsigned int store_read_u16(unsigned char offset) {
;	---------------------------------
; Function store_read_u16
; ---------------------------------
_store_read_u16:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/mini_os.c:146: value = store_read(offset);
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_store_read
	inc	sp
	ld	h, #0x00
;apps/mini_os.c:147: value |= ((unsigned int)store_read((unsigned char)(offset + 1u))) << 8;
	ld	a, 4 (ix)
	inc	a
	push	hl
	push	af
	inc	sp
	call	_store_read
	ld	a, l
	inc	sp
	pop	hl
	ld	c, a
	ld	a, #0x00
	or	a, l
	ld	l, a
	ld	a, c
	or	a, h
	ld	h, a
;apps/mini_os.c:148: return value;
;apps/mini_os.c:149: }
	pop	ix
	ret
;apps/mini_os.c:151: static void store_write_u16(unsigned char offset, unsigned int value) {
;	---------------------------------
; Function store_write_u16
; ---------------------------------
_store_write_u16:
;apps/mini_os.c:152: store_write(offset, (unsigned char)(value & 0xffu));
	ld	iy, #3
	add	iy, sp
	ld	h, 0 (iy)
	ld	l, -1 (iy)
	push	hl
	call	_store_write
	pop	af
;apps/mini_os.c:153: store_write((unsigned char)(offset + 1u), (unsigned char)(value >> 8));
	ld	iy, #3
	add	iy, sp
	ld	b, 1 (iy)
	ld	c, #0x00
	ld	a, -1 (iy)
	inc	a
	push	bc
	inc	sp
	push	af
	inc	sp
	call	_store_write
	pop	af
;apps/mini_os.c:154: }
	ret
;apps/mini_os.c:156: static int store_read_i16(unsigned char offset) {
;	---------------------------------
; Function store_read_i16
; ---------------------------------
_store_read_i16:
;apps/mini_os.c:157: return (int)store_read_u16(offset);
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_store_read_u16
	inc	sp
;apps/mini_os.c:158: }
	ret
;apps/mini_os.c:160: static void store_write_i16(unsigned char offset, int value) {
;	---------------------------------
; Function store_write_i16
; ---------------------------------
_store_write_i16:
;apps/mini_os.c:161: store_write_u16(offset, (unsigned int)value);
	ld	iy, #3
	add	iy, sp
	ld	c, 0 (iy)
	ld	b, 1 (iy)
	push	bc
	ld	a, -1 (iy)
	push	af
	inc	sp
	call	_store_write_u16
	pop	af
	inc	sp
;apps/mini_os.c:162: }
	ret
;apps/mini_os.c:164: static void set_magic(void) {
;	---------------------------------
; Function set_magic
; ---------------------------------
_set_magic:
;apps/mini_os.c:165: store_write(0u, OS_MAGIC0);
	ld	a, #0x4d
	push	af
	inc	sp
	xor	a, a
	push	af
	inc	sp
	call	_store_write
	pop	af
;apps/mini_os.c:166: store_write(1u, OS_MAGIC1);
	ld	de, #0x4f01
	push	de
	call	_store_write
	pop	af
;apps/mini_os.c:167: store_write(2u, OS_MAGIC2);
	ld	de, #0x5302
	push	de
	call	_store_write
	pop	af
;apps/mini_os.c:168: store_write(3u, OS_MAGIC3);
	ld	de, #0x3103
	push	de
	call	_store_write
	pop	af
;apps/mini_os.c:169: }
	ret
;apps/mini_os.c:171: static void reset_counter_state(void) {
;	---------------------------------
; Function reset_counter_state
; ---------------------------------
_reset_counter_state:
;apps/mini_os.c:172: store_write_i16(STORE_COUNTER_VALUE, 0);
	ld	hl, #0x0000
	push	hl
	ld	a, #0x08
	push	af
	inc	sp
	call	_store_write_i16
;apps/mini_os.c:173: store_write_u16(STORE_COUNTER_RUNS, 0u);
	inc	sp
	ld	hl,#0x0000
	ex	(sp),hl
	ld	a, #0x0a
	push	af
	inc	sp
	call	_store_write_u16
	pop	af
	inc	sp
;apps/mini_os.c:174: }
	ret
;apps/mini_os.c:176: static void reset_math_state(void) {
;	---------------------------------
; Function reset_math_state
; ---------------------------------
_reset_math_state:
;apps/mini_os.c:177: store_write(STORE_MATH_INDEX, 0u);
	xor	a, a
	ld	d,a
	ld	e,#0x10
	push	de
	call	_store_write
	pop	af
;apps/mini_os.c:178: store_write(STORE_MATH_CORRECT, 0u);
	xor	a, a
	ld	d,a
	ld	e,#0x11
	push	de
	call	_store_write
;apps/mini_os.c:179: store_write_i16(STORE_MATH_ANSWER, 0);
	ld	hl, #0x0000
	ex	(sp),hl
	ld	a, #0x12
	push	af
	inc	sp
	call	_store_write_i16
	pop	af
	inc	sp
;apps/mini_os.c:180: store_write(STORE_MATH_ATTEMPTS, 0u);
	xor	a, a
	ld	d,a
	ld	e,#0x14
	push	de
	call	_store_write
	pop	af
;apps/mini_os.c:181: store_write(STORE_MATH_LAST, 0u);
	xor	a, a
	ld	d,a
	ld	e,#0x15
	push	de
	call	_store_write
	pop	af
;apps/mini_os.c:182: }
	ret
;apps/mini_os.c:184: static void reset_pad_state(void) {
;	---------------------------------
; Function reset_pad_state
; ---------------------------------
_reset_pad_state:
;apps/mini_os.c:187: store_write(STORE_PAD_X, 0u);
	xor	a, a
	ld	d,a
	ld	e,#0x20
	push	de
	call	_store_write
	pop	af
;apps/mini_os.c:188: store_write(STORE_PAD_Y, 0u);
	xor	a, a
	ld	d,a
	ld	e,#0x21
	push	de
	call	_store_write
	pop	af
;apps/mini_os.c:189: for (row = 0u; row < PAD_HEIGHT; ++row) {
	ld	c, #0x00
00102$:
;apps/mini_os.c:190: store_write_u16((unsigned char)(STORE_PAD_ROWS + (row << 1)), 0u);
	ld	a, c
	add	a, a
	add	a, #0x28
	push	bc
	ld	hl, #0x0000
	push	hl
	push	af
	inc	sp
	call	_store_write_u16
	pop	af
	inc	sp
	pop	bc
;apps/mini_os.c:189: for (row = 0u; row < PAD_HEIGHT; ++row) {
	inc	c
	ld	a, c
	sub	a, #0x08
	jr	C, 00102$
;apps/mini_os.c:192: }
	ret
;apps/mini_os.c:194: static void reset_program_state(unsigned char program) {
;	---------------------------------
; Function reset_program_state
; ---------------------------------
_reset_program_state:
;apps/mini_os.c:195: if (program == PROGRAM_COUNTER) {
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	or	a, a
;apps/mini_os.c:196: reset_counter_state();
	jp	Z,_reset_counter_state
;apps/mini_os.c:197: } else if (program == PROGRAM_MATH) {
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	dec	a
	jp	Z,_reset_math_state
;apps/mini_os.c:198: reset_math_state();
;apps/mini_os.c:200: reset_pad_state();
;apps/mini_os.c:202: }
	jp	_reset_pad_state
;apps/mini_os.c:204: static void storage_init(void) {
;	---------------------------------
; Function storage_init
; ---------------------------------
_storage_init:
;apps/mini_os.c:207: if ((store_read(0u) != OS_MAGIC0) ||
	xor	a, a
	push	af
	inc	sp
	call	_store_read
	ld	a, l
	inc	sp
	sub	a, #0x4d
	jr	NZ, 00101$
;apps/mini_os.c:208: (store_read(1u) != OS_MAGIC1) ||
	ld	a, #0x01
	push	af
	inc	sp
	call	_store_read
	ld	a, l
	inc	sp
	sub	a, #0x4f
	jr	NZ, 00101$
;apps/mini_os.c:209: (store_read(2u) != OS_MAGIC2) ||
	ld	a, #0x02
	push	af
	inc	sp
	call	_store_read
	ld	a, l
	inc	sp
	sub	a, #0x53
	jr	NZ, 00101$
;apps/mini_os.c:210: (store_read(3u) != OS_MAGIC3)) {
	ld	a, #0x03
	push	af
	inc	sp
	call	_store_read
	ld	a, l
	inc	sp
	sub	a, #0x31
	jr	Z, 00102$
00101$:
;apps/mini_os.c:211: set_magic();
	call	_set_magic
;apps/mini_os.c:212: store_write(STORE_SELECTED, 0u);
	xor	a, a
	ld	d,a
	ld	e,#0x04
	push	de
	call	_store_write
	pop	af
;apps/mini_os.c:213: reset_counter_state();
	call	_reset_counter_state
;apps/mini_os.c:214: reset_math_state();
	call	_reset_math_state
;apps/mini_os.c:215: reset_pad_state();
;apps/mini_os.c:216: return;
	jp	_reset_pad_state
00102$:
;apps/mini_os.c:219: selected = store_read(STORE_SELECTED);
	ld	a, #0x04
	push	af
	inc	sp
	call	_store_read
	ld	a, l
	inc	sp
;apps/mini_os.c:220: if (selected >= PROGRAM_COUNT) {
	sub	a, #0x03
	jr	C, 00107$
;apps/mini_os.c:221: store_write(STORE_SELECTED, 0u);
	xor	a, a
	ld	d,a
	ld	e,#0x04
	push	de
	call	_store_write
	pop	af
00107$:
;apps/mini_os.c:223: if (store_read(STORE_MATH_INDEX) >= MATH_COUNT) {
	ld	a, #0x10
	push	af
	inc	sp
	call	_store_read
	ld	a, l
	inc	sp
	sub	a, #0x06
	jr	C, 00109$
;apps/mini_os.c:224: store_write(STORE_MATH_INDEX, 0u);
	xor	a, a
	ld	d,a
	ld	e,#0x10
	push	de
	call	_store_write
	pop	af
00109$:
;apps/mini_os.c:226: if (store_read(STORE_PAD_X) >= PAD_WIDTH) {
	ld	a, #0x20
	push	af
	inc	sp
	call	_store_read
	ld	a, l
	inc	sp
	sub	a, #0x10
	jr	C, 00111$
;apps/mini_os.c:227: store_write(STORE_PAD_X, 0u);
	xor	a, a
	ld	d,a
	ld	e,#0x20
	push	de
	call	_store_write
	pop	af
00111$:
;apps/mini_os.c:229: if (store_read(STORE_PAD_Y) >= PAD_HEIGHT) {
	ld	a, #0x21
	push	af
	inc	sp
	call	_store_read
	inc	sp
	ld	a, l
	sub	a, #0x08
	ret	C
;apps/mini_os.c:230: store_write(STORE_PAD_Y, 0u);
	xor	a, a
	ld	d,a
	ld	e,#0x21
	push	de
	call	_store_write
	pop	af
;apps/mini_os.c:232: }
	ret
;apps/mini_os.c:234: static const char *program_name(unsigned char program) {
;	---------------------------------
; Function program_name
; ---------------------------------
_program_name:
;apps/mini_os.c:235: if (program == PROGRAM_COUNTER) {
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	or	a, a
	jr	NZ, 00102$
;apps/mini_os.c:236: return "COUNTER";
	ld	hl, #___str_0
	ret
00102$:
;apps/mini_os.c:238: if (program == PROGRAM_MATH) {
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	dec	a
	jr	NZ, 00104$
;apps/mini_os.c:239: return "MATH DRILL";
	ld	hl, #___str_1
	ret
00104$:
;apps/mini_os.c:241: return "PIXEL PAD";
	ld	hl, #___str_2
;apps/mini_os.c:242: }
	ret
___str_0:
	.ascii "COUNTER"
	.db 0x00
___str_1:
	.ascii "MATH DRILL"
	.db 0x00
___str_2:
	.ascii "PIXEL PAD"
	.db 0x00
;apps/mini_os.c:244: static void clear_screen(void) {
;	---------------------------------
; Function clear_screen
; ---------------------------------
_clear_screen:
;apps/mini_os.c:245: glic_prepare_screen(GLIC_BLACK);
	xor	a, a
	push	af
	inc	sp
	call	_glic_prepare_screen
	inc	sp
;apps/mini_os.c:246: }
	ret
;apps/mini_os.c:248: static void draw_title(const char *title) {
;	---------------------------------
; Function draw_title
; ---------------------------------
_draw_title:
;apps/mini_os.c:249: text_clear_row(0u);
	xor	a, a
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;apps/mini_os.c:250: text_write(0u, 0u, "MINIOS ");
	ld	hl, #___str_3
	push	hl
	xor	a, a
	push	af
	inc	sp
	xor	a, a
	push	af
	inc	sp
	call	_text_write
	pop	af
	pop	af
;apps/mini_os.c:251: text_write(0u, 7u, title);
	pop	bc
	pop	hl
	push	hl
	push	bc
	push	hl
	ld	a, #0x07
	push	af
	inc	sp
	xor	a, a
	push	af
	inc	sp
	call	_text_write
	pop	af
	pop	af
;apps/mini_os.c:252: }
	ret
___str_3:
	.ascii "MINIOS "
	.db 0x00
;apps/mini_os.c:254: static int math_answer_for(unsigned char index) {
;	---------------------------------
; Function math_answer_for
; ---------------------------------
_math_answer_for:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/mini_os.c:255: if (math_op[index] == '-') {
	ld	bc, #_math_op+0
	ld	l, 4 (ix)
	ld	h, #0x00
	add	hl, bc
	ld	a, (hl)
	sub	a, #0x2d
	jr	NZ, 00102$
;apps/mini_os.c:256: return (int)(math_left[index] - math_right[index]);
	ld	bc, #_math_left+0
	ld	l, 4 (ix)
	ld	h, #0x00
	add	hl, bc
	ld	a, (hl)
	ld	l, a
	rla
	sbc	a, a
	ld	h, a
	ld	bc, #_math_right+0
	ld	a, c
	add	a, 4 (ix)
	ld	c, a
	jr	NC, 00112$
	inc	b
00112$:
	ld	a, (bc)
	ld	c, a
	rla
	sbc	a, a
	ld	b, a
	cp	a, a
	sbc	hl, bc
	jr	00103$
00102$:
;apps/mini_os.c:258: return (int)(math_left[index] + math_right[index]);
	ld	bc, #_math_left+0
	ld	l, 4 (ix)
	ld	h, #0x00
	add	hl, bc
	ld	a, (hl)
	ld	c, a
	rla
	sbc	a, a
	ld	b, a
	ld	de, #_math_right+0
	ld	l, 4 (ix)
	ld	h, #0x00
	add	hl, de
	ld	a, (hl)
	ld	l, a
	rla
	sbc	a, a
	ld	h, a
	add	hl, bc
00103$:
;apps/mini_os.c:259: }
	pop	ix
	ret
;apps/mini_os.c:261: static unsigned char pad_row_offset(unsigned char y) {
;	---------------------------------
; Function pad_row_offset
; ---------------------------------
_pad_row_offset:
;apps/mini_os.c:262: return (unsigned char)(STORE_PAD_ROWS + (y << 1));
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	add	a, a
	add	a, #0x28
	ld	l, a
;apps/mini_os.c:263: }
	ret
;apps/mini_os.c:265: static unsigned int pad_row(unsigned char y) {
;	---------------------------------
; Function pad_row
; ---------------------------------
_pad_row:
;apps/mini_os.c:266: return store_read_u16(pad_row_offset(y));
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_pad_row_offset
	ld	a, l
	inc	sp
	push	af
	inc	sp
	call	_store_read_u16
	inc	sp
;apps/mini_os.c:267: }
	ret
;apps/mini_os.c:269: static void pad_write_row(unsigned char y, unsigned int value) {
;	---------------------------------
; Function pad_write_row
; ---------------------------------
_pad_write_row:
;apps/mini_os.c:270: store_write_u16(pad_row_offset(y), value);
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_pad_row_offset
	ld	a, l
	inc	sp
	ld	iy, #3
	add	iy, sp
	ld	l, 0 (iy)
	ld	h, 1 (iy)
	push	hl
	push	af
	inc	sp
	call	_store_write_u16
	pop	af
	inc	sp
;apps/mini_os.c:271: }
	ret
;apps/mini_os.c:273: static unsigned char pad_get(unsigned char x, unsigned char y) {
;	---------------------------------
; Function pad_get
; ---------------------------------
_pad_get:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/mini_os.c:276: mask = (unsigned int)(1u << x);
	ld	b, 4 (ix)
	ld	hl, #0x0001
	inc	b
	jr	00104$
00103$:
	add	hl, hl
00104$:
	djnz	00103$
;apps/mini_os.c:277: return (pad_row(y) & mask) != 0u;
	push	hl
	ld	a, 5 (ix)
	push	af
	inc	sp
	call	_pad_row
	inc	sp
	ex	de, hl
	pop	hl
	ld	a, l
	and	a, e
	ld	c, a
	ld	a, h
	and	a, d
	or	a, c
	sub	a,#0x01
	ld	a, #0x00
	rla
	xor	a, #0x01
	ld	l, a
;apps/mini_os.c:278: }
	pop	ix
	ret
;apps/mini_os.c:280: static void pad_set(unsigned char x, unsigned char y, unsigned char on) {
;	---------------------------------
; Function pad_set
; ---------------------------------
_pad_set:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/mini_os.c:284: row = pad_row(y);
	ld	a, 5 (ix)
	push	af
	inc	sp
	call	_pad_row
	inc	sp
	ex	de, hl
;apps/mini_os.c:285: mask = (unsigned int)(1u << x);
	ld	b, 4 (ix)
	ld	hl, #0x0001
	inc	b
	jr	00112$
00111$:
	add	hl, hl
00112$:
	djnz	00111$
;apps/mini_os.c:286: if (on != 0u) {
	ld	a, 6 (ix)
	or	a, a
	jr	Z, 00102$
;apps/mini_os.c:287: row |= mask;
	ld	a, e
	or	a, l
	ld	c, a
	ld	a, d
	or	a, h
	ld	b, a
	jr	00103$
00102$:
;apps/mini_os.c:289: row &= (unsigned int)~mask;
	ld	a, l
	cpl
	push	af
	ld	a, h
	cpl
	ld	b, a
	pop	af
	and	a, e
	ld	c, a
	ld	a, b
	and	a, d
	ld	b, a
00103$:
;apps/mini_os.c:291: pad_write_row(y, row);
	push	bc
	ld	a, 5 (ix)
	push	af
	inc	sp
	call	_pad_write_row
	pop	af
	inc	sp
;apps/mini_os.c:292: }
	pop	ix
	ret
;apps/mini_os.c:294: static unsigned char pad_count_pixels(void) {
;	---------------------------------
; Function pad_count_pixels
; ---------------------------------
_pad_count_pixels:
;apps/mini_os.c:299: total = 0u;
;apps/mini_os.c:300: for (row = 0u; row < PAD_HEIGHT; ++row) {
	ld	bc, #0x0000
;apps/mini_os.c:301: for (col = 0u; col < PAD_WIDTH; ++col) {
00112$:
	ld	l, c
	ld	h, #0x00
00105$:
;apps/mini_os.c:302: if (pad_get(col, row) != 0u) {
	push	hl
	push	bc
	ld	c, h
	push	bc
	call	_pad_get
	pop	af
	ld	a, l
	pop	bc
	pop	hl
	or	a, a
	jr	Z, 00106$
;apps/mini_os.c:303: ++total;
	inc	l
00106$:
;apps/mini_os.c:301: for (col = 0u; col < PAD_WIDTH; ++col) {
	inc	h
	ld	a, h
	sub	a, #0x10
	jr	C, 00105$
;apps/mini_os.c:300: for (row = 0u; row < PAD_HEIGHT; ++row) {
	ld	c, l
	inc	b
	ld	a, b
	sub	a, #0x08
	jr	C, 00112$
;apps/mini_os.c:307: return total;
;apps/mini_os.c:308: }
	ret
;apps/mini_os.c:310: static void draw_state_summary(unsigned char selected) {
;	---------------------------------
; Function draw_state_summary
; ---------------------------------
_draw_state_summary:
;apps/mini_os.c:311: text_clear_row(12u);
	ld	a, #0x0c
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;apps/mini_os.c:312: text_clear_row(13u);
	ld	a, #0x0d
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;apps/mini_os.c:313: text_clear_row(14u);
	ld	a, #0x0e
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;apps/mini_os.c:315: text_write(12u, 0u, "SAVED STATE");
	ld	hl, #___str_4
	push	hl
	xor	a, a
	ld	d,a
	ld	e,#0x0c
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/mini_os.c:316: if (selected == PROGRAM_COUNTER) {
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	or	a, a
	jr	NZ, 00105$
;apps/mini_os.c:317: text_write(13u, 0u, "VALUE ");
	ld	hl, #___str_5
	push	hl
	xor	a, a
	ld	d,a
	ld	e,#0x0d
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:318: text_write_i16(13u, 6u, store_read_i16(STORE_COUNTER_VALUE));
	ld	h,#0x08
	ex	(sp),hl
	inc	sp
	call	_store_read_i16
	inc	sp
	push	hl
	ld	de, #0x060d
	push	de
	call	_text_write_i16
	pop	af
;apps/mini_os.c:319: text_write(14u, 0u, "RUNS ");
	ld	hl, #___str_6
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0e
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:320: text_write_u16(14u, 5u, store_read_u16(STORE_COUNTER_RUNS));
	ld	h,#0x0a
	ex	(sp),hl
	inc	sp
	call	_store_read_u16
	inc	sp
	push	hl
	ld	de, #0x050e
	push	de
	call	_text_write_u16
	pop	af
	pop	af
	ret
00105$:
;apps/mini_os.c:321: } else if (selected == PROGRAM_MATH) {
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	dec	a
	jr	NZ, 00102$
;apps/mini_os.c:322: text_write(13u, 0u, "PROBLEM ");
	ld	hl, #___str_7
	push	hl
	xor	a, a
	ld	d,a
	ld	e,#0x0d
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:323: text_write_u16(13u, 8u, (unsigned int)(store_read(STORE_MATH_INDEX) + 1u));
	ld	h,#0x10
	ex	(sp),hl
	inc	sp
	call	_store_read
	inc	sp
	ld	h, #0x00
	inc	hl
	push	hl
	ld	de, #0x080d
	push	de
	call	_text_write_u16
	pop	af
;apps/mini_os.c:324: text_write(14u, 0u, "SCORE ");
	ld	hl, #___str_8
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0e
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:325: text_write_u16(14u, 6u, store_read(STORE_MATH_CORRECT));
	ld	h,#0x11
	ex	(sp),hl
	inc	sp
	call	_store_read
	inc	sp
	ld	h, #0x00
	push	hl
	ld	de, #0x060e
	push	de
	call	_text_write_u16
	pop	af
	pop	af
	ret
00102$:
;apps/mini_os.c:327: text_write(13u, 0u, "PIXELS ");
	ld	hl, #___str_9
	push	hl
	xor	a, a
	ld	d,a
	ld	e,#0x0d
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/mini_os.c:328: text_write_u16(13u, 7u, pad_count_pixels());
	call	_pad_count_pixels
	ld	h, #0x00
	push	hl
	ld	de, #0x070d
	push	de
	call	_text_write_u16
	pop	af
;apps/mini_os.c:329: text_write(14u, 0u, "CUR ");
	ld	hl, #___str_10
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0e
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:330: text_write_u16(14u, 4u, store_read(STORE_PAD_X));
	ld	h,#0x20
	ex	(sp),hl
	inc	sp
	call	_store_read
	inc	sp
	ld	h, #0x00
	push	hl
	ld	de, #0x040e
	push	de
	call	_text_write_u16
	pop	af
	pop	af
;apps/mini_os.c:331: text_put(14u, 6u, ',');
	ld	de, #0x2c06
	push	de
	ld	a, #0x0e
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
;apps/mini_os.c:332: text_write_u16(14u, 7u, store_read(STORE_PAD_Y));
	ld	a, #0x21
	push	af
	inc	sp
	call	_store_read
	inc	sp
	ld	h, #0x00
	push	hl
	ld	de, #0x070e
	push	de
	call	_text_write_u16
	pop	af
	pop	af
;apps/mini_os.c:334: }
	ret
___str_4:
	.ascii "SAVED STATE"
	.db 0x00
___str_5:
	.ascii "VALUE "
	.db 0x00
___str_6:
	.ascii "RUNS "
	.db 0x00
___str_7:
	.ascii "PROBLEM "
	.db 0x00
___str_8:
	.ascii "SCORE "
	.db 0x00
___str_9:
	.ascii "PIXELS "
	.db 0x00
___str_10:
	.ascii "CUR "
	.db 0x00
;apps/mini_os.c:336: static void draw_menu(unsigned char selected, const char *message) {
;	---------------------------------
; Function draw_menu
; ---------------------------------
_draw_menu:
;apps/mini_os.c:340: clear_screen();
	call	_clear_screen
;apps/mini_os.c:341: draw_title("MENU");
	ld	hl, #___str_11
	push	hl
	call	_draw_title
;apps/mini_os.c:342: text_write(1u, 0u, "C PROGRAM SLOTS");
	ld	hl, #___str_12
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x01
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/mini_os.c:343: for (i = 0u; i < PROGRAM_COUNT; ++i) {
	ld	c, #0x00
00104$:
;apps/mini_os.c:344: row = (unsigned char)(3u + (i << 1));
	ld	a, c
	add	a, a
	add	a, #0x03
	ld	b, a
;apps/mini_os.c:345: text_put(row, 0u, (i == selected) ? '>' : ' ');
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	sub	a, c
	jr	NZ, 00108$
	ld	de, #0x003e
	jr	00109$
00108$:
	ld	de, #0x0020
00109$:
	ld	a, e
	push	bc
	push	af
	inc	sp
	xor	a, a
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_text_put
	pop	af
	inc	sp
	pop	bc
;apps/mini_os.c:346: text_write(row, 2u, program_name(i));
	push	bc
	ld	a, c
	push	af
	inc	sp
	call	_program_name
	inc	sp
	pop	bc
	push	bc
	push	hl
	ld	a, #0x02
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_text_write
	pop	af
	pop	af
	pop	bc
;apps/mini_os.c:343: for (i = 0u; i < PROGRAM_COUNT; ++i) {
	inc	c
	ld	a, c
	sub	a, #0x03
	jr	C, 00104$
;apps/mini_os.c:349: text_write(9u, 0u, "CENTER/A RUN");
	ld	hl, #___str_13
	push	hl
	xor	a, a
	ld	d,a
	ld	e,#0x09
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:350: text_write(10u, 0u, "B RESET SLOT");
	ld	hl, #___str_14
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0a
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:351: text_write(11u, 0u, "C HELP");
	ld	hl, #___str_15
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0b
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/mini_os.c:352: draw_state_summary(selected);
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_draw_state_summary
	inc	sp
;apps/mini_os.c:354: if (message != 0) {
	ld	iy, #3
	add	iy, sp
	ld	a, 1 (iy)
	or	a, 0 (iy)
	ret	Z
;apps/mini_os.c:355: text_clear_row(15u);
	ld	a, #0x0f
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;apps/mini_os.c:356: text_write(15u, 0u, message);
	ld	hl, #3
	add	hl, sp
	ld	c, (hl)
	inc	hl
	ld	b, (hl)
	push	bc
	xor	a, a
	ld	d,a
	ld	e,#0x0f
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/mini_os.c:358: }
	ret
___str_11:
	.ascii "MENU"
	.db 0x00
___str_12:
	.ascii "C PROGRAM SLOTS"
	.db 0x00
___str_13:
	.ascii "CENTER/A RUN"
	.db 0x00
___str_14:
	.ascii "B RESET SLOT"
	.db 0x00
___str_15:
	.ascii "C HELP"
	.db 0x00
;apps/mini_os.c:360: static void show_help(void) {
;	---------------------------------
; Function show_help
; ---------------------------------
_show_help:
;apps/mini_os.c:364: clear_screen();
	call	_clear_screen
;apps/mini_os.c:365: draw_title("HELP");
	ld	hl, #___str_16
	push	hl
	call	_draw_title
;apps/mini_os.c:366: text_write(2u, 0u, "APPS ARE C CODE");
	ld	hl, #___str_17
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x02
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:367: text_write(4u, 0u, "STATE AT 0x6000");
	ld	hl, #___str_18
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x04
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:368: text_write(6u, 0u, "C EXITS APP");
	ld	hl, #___str_19
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x06
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:369: text_write(8u, 0u, "EXIT SAVES SLOT");
	ld	hl, #___str_20
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x08
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:370: text_write(10u, 0u, "B RESETS SLOT");
	ld	hl, #___str_21
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0a
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:371: text_write(13u, 0u, "CENTER/C BACK");
	ld	hl, #___str_22
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0d
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/mini_os.c:373: wait_for_release();
	call	_wait_for_release
;apps/mini_os.c:374: last_buttons = GLIC_BUTTONS_NONE;
	ld	h, #0xff
;apps/mini_os.c:375: while (1) {
00105$:
;apps/mini_os.c:376: buttons = glic_read_buttons();
	push	hl
	call	_glic_read_buttons
	pop	af
	ld	h, a
;apps/mini_os.c:377: if ((button_edge(buttons, last_buttons, GLIC_BTN_CENTER) != 0u) ||
	push	hl
	ld	a, #0x01
	push	af
	inc	sp
	push	hl
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	hl
	or	a, a
	jp	NZ,_wait_for_release
;apps/mini_os.c:378: (button_edge(buttons, last_buttons, GLIC_BTN_C) != 0u)) {
	push	hl
	ld	a, #0x20
	push	af
	inc	sp
	push	hl
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	hl
	or	a, a
;apps/mini_os.c:379: wait_for_release();
;apps/mini_os.c:380: return;
	jp	NZ,_wait_for_release
;apps/mini_os.c:382: last_buttons = buttons;
	ld	h, l
;apps/mini_os.c:383: glic_delay(LOOP_DELAY);
	push	hl
	ld	de, #0x044c
	push	de
	call	_glic_delay
	pop	af
	pop	hl
;apps/mini_os.c:385: }
	jr	00105$
___str_16:
	.ascii "HELP"
	.db 0x00
___str_17:
	.ascii "APPS ARE C CODE"
	.db 0x00
___str_18:
	.ascii "STATE AT 0x6000"
	.db 0x00
___str_19:
	.ascii "C EXITS APP"
	.db 0x00
___str_20:
	.ascii "EXIT SAVES SLOT"
	.db 0x00
___str_21:
	.ascii "B RESETS SLOT"
	.db 0x00
___str_22:
	.ascii "CENTER/C BACK"
	.db 0x00
;apps/mini_os.c:387: static void draw_counter(void) {
;	---------------------------------
; Function draw_counter
; ---------------------------------
_draw_counter:
;apps/mini_os.c:388: clear_screen();
	call	_clear_screen
;apps/mini_os.c:389: draw_title("COUNTER");
	ld	hl, #___str_23
	push	hl
	call	_draw_title
;apps/mini_os.c:390: text_write(3u, 0u, "VALUE");
	ld	hl, #___str_24
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x03
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:391: text_write_i16(4u, 0u, store_read_i16(STORE_COUNTER_VALUE));
	ld	h,#0x08
	ex	(sp),hl
	inc	sp
	call	_store_read_i16
	inc	sp
	push	hl
	xor	a, a
	ld	d,a
	ld	e,#0x04
	push	de
	call	_text_write_i16
	pop	af
;apps/mini_os.c:392: text_write(6u, 0u, "RUNS");
	ld	hl, #___str_25
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x06
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:393: text_write_u16(7u, 0u, store_read_u16(STORE_COUNTER_RUNS));
	ld	h,#0x0a
	ex	(sp),hl
	inc	sp
	call	_store_read_u16
	inc	sp
	push	hl
	xor	a, a
	ld	d,a
	ld	e,#0x07
	push	de
	call	_text_write_u16
	pop	af
;apps/mini_os.c:394: text_write(10u, 0u, "UP/A +1");
	ld	hl, #___str_26
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0a
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:395: text_write(11u, 0u, "DOWN/B -1");
	ld	hl, #___str_27
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0b
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:396: text_write(12u, 0u, "CENTER +10");
	ld	hl, #___str_28
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0c
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:397: text_write(14u, 0u, "C SAVE EXIT");
	ld	hl, #___str_29
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0e
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/mini_os.c:398: }
	ret
___str_23:
	.ascii "COUNTER"
	.db 0x00
___str_24:
	.ascii "VALUE"
	.db 0x00
___str_25:
	.ascii "RUNS"
	.db 0x00
___str_26:
	.ascii "UP/A +1"
	.db 0x00
___str_27:
	.ascii "DOWN/B -1"
	.db 0x00
___str_28:
	.ascii "CENTER +10"
	.db 0x00
___str_29:
	.ascii "C SAVE EXIT"
	.db 0x00
;apps/mini_os.c:400: static void run_counter(void) {
;	---------------------------------
; Function run_counter
; ---------------------------------
_run_counter:
;apps/mini_os.c:406: runs = (unsigned int)(store_read_u16(STORE_COUNTER_RUNS) + 1u);
	ld	a, #0x0a
	push	af
	inc	sp
	call	_store_read_u16
	inc	sp
	inc	hl
;apps/mini_os.c:407: store_write_u16(STORE_COUNTER_RUNS, runs);
	push	hl
	ld	a, #0x0a
	push	af
	inc	sp
	call	_store_write_u16
	pop	af
	inc	sp
;apps/mini_os.c:408: draw_counter();
	call	_draw_counter
;apps/mini_os.c:409: wait_for_release();
	call	_wait_for_release
;apps/mini_os.c:410: last_buttons = GLIC_BUTTONS_NONE;
	ld	c, #0xff
;apps/mini_os.c:412: while (1) {
00115$:
;apps/mini_os.c:413: buttons = glic_read_buttons();
	push	bc
	call	_glic_read_buttons
	ld	a, l
	pop	bc
	ld	b, a
;apps/mini_os.c:414: value = store_read_i16(STORE_COUNTER_VALUE);
	push	bc
	ld	a, #0x08
	push	af
	inc	sp
	call	_store_read_i16
	inc	sp
	ex	de, hl
	pop	bc
;apps/mini_os.c:415: if ((button_edge(buttons, last_buttons, GLIC_BTN_UP) != 0u) ||
	push	bc
	push	de
	ld	a, #0x02
	push	af
	inc	sp
	ld	a, c
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	de
	pop	bc
	or	a, a
	jr	NZ, 00110$
;apps/mini_os.c:416: (button_edge(buttons, last_buttons, GLIC_BTN_A) != 0u)) {
	push	bc
	push	de
	ld	a, #0x80
	push	af
	inc	sp
	ld	a, c
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	de
	pop	bc
	or	a, a
	jr	Z, 00111$
00110$:
;apps/mini_os.c:417: ++value;
	inc	de
;apps/mini_os.c:418: store_write_i16(STORE_COUNTER_VALUE, value);
	push	bc
	push	de
	ld	a, #0x08
	push	af
	inc	sp
	call	_store_write_i16
	pop	af
	inc	sp
	call	_draw_counter
	pop	bc
	jp	00112$
00111$:
;apps/mini_os.c:420: } else if ((button_edge(buttons, last_buttons, GLIC_BTN_DOWN) != 0u) ||
	push	bc
	push	de
	ld	a, #0x08
	push	af
	inc	sp
	ld	a, c
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	de
	pop	bc
	or	a, a
	jr	NZ, 00106$
;apps/mini_os.c:421: (button_edge(buttons, last_buttons, GLIC_BTN_B) != 0u)) {
	push	bc
	push	de
	ld	a, #0x40
	push	af
	inc	sp
	ld	a, c
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	de
	pop	bc
	or	a, a
	jr	Z, 00107$
00106$:
;apps/mini_os.c:422: --value;
	dec	de
;apps/mini_os.c:423: store_write_i16(STORE_COUNTER_VALUE, value);
	push	bc
	push	de
	ld	a, #0x08
	push	af
	inc	sp
	call	_store_write_i16
	pop	af
	inc	sp
	call	_draw_counter
	pop	bc
	jr	00112$
00107$:
;apps/mini_os.c:425: } else if (button_edge(buttons, last_buttons, GLIC_BTN_CENTER) != 0u) {
	push	bc
	push	de
	ld	a, #0x01
	push	af
	inc	sp
	ld	a, c
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	de
	pop	bc
	or	a, a
	jr	Z, 00104$
;apps/mini_os.c:426: value = (int)(value + 10);
	ld	hl, #0x000a
	add	hl, de
;apps/mini_os.c:427: store_write_i16(STORE_COUNTER_VALUE, value);
	push	bc
	push	hl
	ld	a, #0x08
	push	af
	inc	sp
	call	_store_write_i16
	pop	af
	inc	sp
	call	_draw_counter
	pop	bc
	jr	00112$
00104$:
;apps/mini_os.c:429: } else if (button_edge(buttons, last_buttons, GLIC_BTN_C) != 0u) {
	push	bc
	push	de
	ld	a, #0x20
	push	af
	inc	sp
	ld	a, c
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	de
	pop	bc
	or	a, a
	jr	Z, 00112$
;apps/mini_os.c:430: store_write_i16(STORE_COUNTER_VALUE, value);
	push	de
	ld	a, #0x08
	push	af
	inc	sp
	call	_store_write_i16
	pop	af
	inc	sp
;apps/mini_os.c:431: wait_for_release();
;apps/mini_os.c:432: return;
	jp	_wait_for_release
00112$:
;apps/mini_os.c:434: last_buttons = buttons;
	ld	c, b
;apps/mini_os.c:435: glic_delay(LOOP_DELAY);
	push	bc
	ld	hl, #0x044c
	push	hl
	call	_glic_delay
	pop	af
	pop	bc
;apps/mini_os.c:437: }
	jp	00115$
;apps/mini_os.c:439: static void draw_math(void) {
;	---------------------------------
; Function draw_math
; ---------------------------------
_draw_math:
;apps/mini_os.c:443: clear_screen();
	call	_clear_screen
;apps/mini_os.c:444: draw_title("MATH");
	ld	hl, #___str_30
	push	hl
	call	_draw_title
;apps/mini_os.c:445: index = store_read(STORE_MATH_INDEX);
	ld	h,#0x10
	ex	(sp),hl
	inc	sp
	call	_store_read
	ld	e, l
	inc	sp
;apps/mini_os.c:446: if (index >= MATH_COUNT) {
	ld	a, e
	sub	a, #0x06
	jr	C, 00102$
;apps/mini_os.c:447: index = 0u;
	ld	e, #0x00
;apps/mini_os.c:448: store_write(STORE_MATH_INDEX, 0u);
	push	de
	xor	a, a
	ld	d,a
	ld	e,#0x10
	push	de
	call	_store_write
	pop	af
	pop	de
00102$:
;apps/mini_os.c:451: text_write(2u, 0u, "PROBLEM ");
	push	de
	ld	hl, #___str_31
	push	hl
	xor	a, a
	ld	d,a
	ld	e,#0x02
	push	de
	call	_text_write
	pop	af
	pop	af
	pop	de
;apps/mini_os.c:452: text_write_u16(2u, 8u, (unsigned int)(index + 1u));
	ld	a, e
	ld	b, #0x00
	ld	c, a
	inc	bc
	push	de
	push	bc
	ld	de, #0x0802
	push	de
	call	_text_write_u16
	pop	af
	pop	af
	ld	de, #0x2f09
	push	de
	ld	a, #0x02
	push	af
	inc	sp
	call	_text_put
	inc	sp
	ld	hl,#0x0006
	ex	(sp),hl
	ld	de, #0x0a02
	push	de
	call	_text_write_u16
	pop	af
	pop	af
	pop	de
;apps/mini_os.c:456: text_write_i16(4u, 0u, (int)math_left[index]);
	ld	hl, #_math_left
	ld	d, #0x00
	add	hl, de
	ld	a, (hl)
	ld	c, a
	rla
	sbc	a, a
	ld	b, a
	push	de
	push	bc
	xor	a, a
	ld	d,a
	ld	e,#0x04
	push	de
	call	_text_write_i16
	pop	af
	pop	af
	pop	de
;apps/mini_os.c:457: text_put(4u, 3u, math_op[index]);
	ld	hl, #_math_op
	ld	d, #0x00
	add	hl, de
	ld	a, (hl)
	push	de
	ld	d,a
	ld	e,#0x03
	push	de
	ld	a, #0x04
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
	pop	de
;apps/mini_os.c:458: text_write_i16(4u, 5u, (int)math_right[index]);
	ld	hl, #_math_right+0
	ld	d, #0x00
	add	hl, de
	ld	a, (hl)
	ld	c, a
	rla
	sbc	a, a
	ld	b, a
	push	bc
	ld	de, #0x0504
	push	de
	call	_text_write_i16
	pop	af
;apps/mini_os.c:459: text_write(4u, 8u, "= ?");
	ld	hl, #___str_32
	ex	(sp),hl
	ld	de, #0x0804
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:461: text_write(6u, 0u, "ANSWER ");
	ld	hl, #___str_33
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x06
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:462: text_write_i16(6u, 7u, store_read_i16(STORE_MATH_ANSWER));
	ld	h,#0x12
	ex	(sp),hl
	inc	sp
	call	_store_read_i16
	inc	sp
	push	hl
	ld	de, #0x0706
	push	de
	call	_text_write_i16
	pop	af
;apps/mini_os.c:463: text_write(8u, 0u, "SCORE ");
	ld	hl, #___str_34
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x08
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:464: text_write_u16(8u, 6u, store_read(STORE_MATH_CORRECT));
	ld	h,#0x11
	ex	(sp),hl
	inc	sp
	call	_store_read
	inc	sp
	ld	h, #0x00
	push	hl
	ld	de, #0x0608
	push	de
	call	_text_write_u16
	pop	af
;apps/mini_os.c:465: text_write(9u, 0u, "TRIES ");
	ld	hl, #___str_35
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x09
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:466: text_write_u16(9u, 6u, store_read(STORE_MATH_ATTEMPTS));
	ld	h,#0x14
	ex	(sp),hl
	inc	sp
	call	_store_read
	inc	sp
	ld	h, #0x00
	push	hl
	ld	de, #0x0609
	push	de
	call	_text_write_u16
	pop	af
;apps/mini_os.c:468: text_write(11u, 0u, "UP/DN +/-1");
	ld	hl, #___str_36
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0b
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:469: text_write(12u, 0u, "A/B +/-10");
	ld	hl, #___str_37
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0c
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:470: text_write(13u, 0u, "CENTER CHECK");
	ld	hl, #___str_38
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0d
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:471: text_write(14u, 0u, "C SAVE EXIT");
	ld	hl, #___str_39
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0e
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:473: last = store_read(STORE_MATH_LAST);
	ld	h,#0x15
	ex	(sp),hl
	inc	sp
	call	_store_read
	inc	sp
	ld	a, l
;apps/mini_os.c:474: if (last == 1u) {
	cp	a, #0x01
	jr	NZ, 00106$
;apps/mini_os.c:475: text_write(15u, 0u, "CORRECT SAVED");
	ld	hl, #___str_40
	push	hl
	xor	a, a
	ld	d,a
	ld	e,#0x0f
	push	de
	call	_text_write
	pop	af
	pop	af
	ret
00106$:
;apps/mini_os.c:476: } else if (last == 2u) {
	sub	a, #0x02
	ret	NZ
;apps/mini_os.c:477: text_write(15u, 0u, "TRY AGAIN");
	ld	hl, #___str_41
	push	hl
	xor	a, a
	ld	d,a
	ld	e,#0x0f
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/mini_os.c:479: }
	ret
___str_30:
	.ascii "MATH"
	.db 0x00
___str_31:
	.ascii "PROBLEM "
	.db 0x00
___str_32:
	.ascii "= ?"
	.db 0x00
___str_33:
	.ascii "ANSWER "
	.db 0x00
___str_34:
	.ascii "SCORE "
	.db 0x00
___str_35:
	.ascii "TRIES "
	.db 0x00
___str_36:
	.ascii "UP/DN +/-1"
	.db 0x00
___str_37:
	.ascii "A/B +/-10"
	.db 0x00
___str_38:
	.ascii "CENTER CHECK"
	.db 0x00
___str_39:
	.ascii "C SAVE EXIT"
	.db 0x00
___str_40:
	.ascii "CORRECT SAVED"
	.db 0x00
___str_41:
	.ascii "TRY AGAIN"
	.db 0x00
;apps/mini_os.c:481: static void math_advance_problem(void) {
;	---------------------------------
; Function math_advance_problem
; ---------------------------------
_math_advance_problem:
;apps/mini_os.c:484: index = (unsigned char)(store_read(STORE_MATH_INDEX) + 1u);
	ld	a, #0x10
	push	af
	inc	sp
	call	_store_read
	ld	a, l
	inc	sp
	inc	a
;apps/mini_os.c:485: if (index >= MATH_COUNT) {
	cp	a, #0x06
	jr	C, 00102$
;apps/mini_os.c:486: index = 0u;
	xor	a, a
00102$:
;apps/mini_os.c:488: store_write(STORE_MATH_INDEX, index);
	ld	d,a
	ld	e,#0x10
	push	de
	call	_store_write
;apps/mini_os.c:489: store_write_i16(STORE_MATH_ANSWER, 0);
	ld	hl, #0x0000
	ex	(sp),hl
	ld	a, #0x12
	push	af
	inc	sp
	call	_store_write_i16
	pop	af
	inc	sp
;apps/mini_os.c:490: }
	ret
;apps/mini_os.c:492: static void run_math(void) {
;	---------------------------------
; Function run_math
; ---------------------------------
_run_math:
	push	ix
	ld	ix,#0
	add	ix,sp
	push	af
;apps/mini_os.c:500: draw_math();
	call	_draw_math
;apps/mini_os.c:501: wait_for_release();
	call	_wait_for_release
;apps/mini_os.c:502: last_buttons = GLIC_BUTTONS_NONE;
	ld	-2 (ix), #0xff
;apps/mini_os.c:504: while (1) {
00122$:
;apps/mini_os.c:505: buttons = glic_read_buttons();
	call	_glic_read_buttons
	ld	-1 (ix), l
;apps/mini_os.c:506: answer = store_read_i16(STORE_MATH_ANSWER);
	ld	a, #0x12
	push	af
	inc	sp
	call	_store_read_i16
	inc	sp
;apps/mini_os.c:507: if (button_edge(buttons, last_buttons, GLIC_BTN_UP) != 0u) {
	push	hl
	ld	h, #0x02
	ld	l, -2 (ix)
	push	hl
	ld	a, -1 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	de
	or	a, a
	jr	Z, 00119$
;apps/mini_os.c:508: ++answer;
	inc	de
;apps/mini_os.c:509: store_write_i16(STORE_MATH_ANSWER, answer);
	push	de
	ld	a, #0x12
	push	af
	inc	sp
	call	_store_write_i16
	pop	af
	inc	sp
;apps/mini_os.c:510: store_write(STORE_MATH_LAST, 0u);
	xor	a, a
	ld	d,a
	ld	e,#0x15
	push	de
	call	_store_write
	pop	af
;apps/mini_os.c:511: draw_math();
	call	_draw_math
	jp	00120$
00119$:
;apps/mini_os.c:512: } else if (button_edge(buttons, last_buttons, GLIC_BTN_DOWN) != 0u) {
	push	de
	ld	h, #0x08
	ld	l, -2 (ix)
	push	hl
	ld	a, -1 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	de
	or	a, a
	jr	Z, 00116$
;apps/mini_os.c:513: --answer;
	dec	de
;apps/mini_os.c:514: store_write_i16(STORE_MATH_ANSWER, answer);
	push	de
	ld	a, #0x12
	push	af
	inc	sp
	call	_store_write_i16
	pop	af
	inc	sp
;apps/mini_os.c:515: store_write(STORE_MATH_LAST, 0u);
	xor	a, a
	ld	d,a
	ld	e,#0x15
	push	de
	call	_store_write
	pop	af
;apps/mini_os.c:516: draw_math();
	call	_draw_math
	jp	00120$
00116$:
;apps/mini_os.c:517: } else if (button_edge(buttons, last_buttons, GLIC_BTN_A) != 0u) {
	push	de
	ld	h, #0x80
	ld	l, -2 (ix)
	push	hl
	ld	a, -1 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	de
	or	a, a
	jr	Z, 00113$
;apps/mini_os.c:518: answer = (int)(answer + 10);
	ld	hl, #0x000a
	add	hl, de
;apps/mini_os.c:519: store_write_i16(STORE_MATH_ANSWER, answer);
	push	hl
	ld	a, #0x12
	push	af
	inc	sp
	call	_store_write_i16
	pop	af
	inc	sp
;apps/mini_os.c:520: store_write(STORE_MATH_LAST, 0u);
	xor	a, a
	ld	d,a
	ld	e,#0x15
	push	de
	call	_store_write
	pop	af
;apps/mini_os.c:521: draw_math();
	call	_draw_math
	jp	00120$
00113$:
;apps/mini_os.c:522: } else if (button_edge(buttons, last_buttons, GLIC_BTN_B) != 0u) {
	push	de
	ld	h, #0x40
	ld	l, -2 (ix)
	push	hl
	ld	a, -1 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	de
	or	a, a
	jr	Z, 00110$
;apps/mini_os.c:523: answer = (int)(answer - 10);
	ld	a, e
	add	a, #0xf6
	ld	c, a
	ld	a, d
	adc	a, #0xff
	ld	b, a
;apps/mini_os.c:524: store_write_i16(STORE_MATH_ANSWER, answer);
	push	bc
	ld	a, #0x12
	push	af
	inc	sp
	call	_store_write_i16
	pop	af
	inc	sp
;apps/mini_os.c:525: store_write(STORE_MATH_LAST, 0u);
	xor	a, a
	ld	d,a
	ld	e,#0x15
	push	de
	call	_store_write
	pop	af
;apps/mini_os.c:526: draw_math();
	call	_draw_math
	jp	00120$
00110$:
;apps/mini_os.c:527: } else if (button_edge(buttons, last_buttons, GLIC_BTN_CENTER) != 0u) {
	push	de
	ld	h, #0x01
	ld	l, -2 (ix)
	push	hl
	ld	a, -1 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	de
	or	a, a
	jr	Z, 00107$
;apps/mini_os.c:528: attempts = (unsigned char)(store_read(STORE_MATH_ATTEMPTS) + 1u);
	push	de
	ld	a, #0x14
	push	af
	inc	sp
	call	_store_read
	ld	a, l
	inc	sp
	pop	de
	inc	a
;apps/mini_os.c:529: store_write(STORE_MATH_ATTEMPTS, attempts);
	push	de
	ld	d,a
	ld	e,#0x14
	push	de
	call	_store_write
	ld	h,#0x10
	ex	(sp),hl
	inc	sp
	call	_store_read
	ld	a, l
	inc	sp
	push	af
	inc	sp
	call	_math_answer_for
	inc	sp
	pop	de
	cp	a, a
	sbc	hl, de
	jr	NZ, 00102$
;apps/mini_os.c:532: correct = (unsigned char)(store_read(STORE_MATH_CORRECT) + 1u);
	ld	a, #0x11
	push	af
	inc	sp
	call	_store_read
	ld	a, l
	inc	sp
	inc	a
;apps/mini_os.c:533: store_write(STORE_MATH_CORRECT, correct);
	ld	d,a
	ld	e,#0x11
	push	de
	call	_store_write
	pop	af
;apps/mini_os.c:534: store_write(STORE_MATH_LAST, 1u);
	ld	de, #0x0115
	push	de
	call	_store_write
	pop	af
;apps/mini_os.c:535: math_advance_problem();
	call	_math_advance_problem
	jr	00103$
00102$:
;apps/mini_os.c:537: store_write(STORE_MATH_LAST, 2u);
	ld	de, #0x0215
	push	de
	call	_store_write
	pop	af
00103$:
;apps/mini_os.c:539: draw_math();
	call	_draw_math
	jr	00120$
00107$:
;apps/mini_os.c:540: } else if (button_edge(buttons, last_buttons, GLIC_BTN_C) != 0u) {
	push	de
	ld	h, #0x20
	ld	l, -2 (ix)
	push	hl
	ld	a, -1 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	de
	or	a, a
	jr	Z, 00120$
;apps/mini_os.c:541: store_write_i16(STORE_MATH_ANSWER, answer);
	push	de
	ld	a, #0x12
	push	af
	inc	sp
	call	_store_write_i16
	pop	af
	inc	sp
;apps/mini_os.c:542: wait_for_release();
	call	_wait_for_release
;apps/mini_os.c:543: return;
	jr	00124$
00120$:
;apps/mini_os.c:545: last_buttons = buttons;
	ld	a, -1 (ix)
	ld	-2 (ix), a
;apps/mini_os.c:546: glic_delay(LOOP_DELAY);
	ld	hl, #0x044c
	push	hl
	call	_glic_delay
	pop	af
	jp	00122$
00124$:
;apps/mini_os.c:548: }
	ld	sp, ix
	pop	ix
	ret
;apps/mini_os.c:550: static void draw_pad(void) {
;	---------------------------------
; Function draw_pad
; ---------------------------------
_draw_pad:
	push	ix
	ld	ix,#0
	add	ix,sp
	ld	hl, #-6
	add	hl, sp
	ld	sp, hl
;apps/mini_os.c:558: clear_screen();
	call	_clear_screen
;apps/mini_os.c:559: draw_title("PAD");
	ld	hl, #___str_42
	push	hl
	call	_draw_title
;apps/mini_os.c:560: cursor_x = store_read(STORE_PAD_X);
	ld	h,#0x20
	ex	(sp),hl
	inc	sp
	call	_store_read
	ld	c, l
	inc	sp
;apps/mini_os.c:561: cursor_y = store_read(STORE_PAD_Y);
	push	bc
	ld	a, #0x21
	push	af
	inc	sp
	call	_store_read
	ld	a, l
	inc	sp
	pop	bc
	ld	e, a
;apps/mini_os.c:562: if (cursor_x >= PAD_WIDTH) {
	ld	a, c
	sub	a, #0x10
	jr	C, 00102$
;apps/mini_os.c:563: cursor_x = 0u;
	ld	c, #0x00
00102$:
;apps/mini_os.c:565: if (cursor_y >= PAD_HEIGHT) {
	ld	a, e
	sub	a, #0x08
	jr	C, 00128$
;apps/mini_os.c:566: cursor_y = 0u;
	ld	e, #0x00
;apps/mini_os.c:569: for (row = 0u; row < PAD_HEIGHT; ++row) {
00128$:
	ld	-2 (ix), #0
;apps/mini_os.c:570: for (col = 0u; col < PAD_WIDTH; ++col) {
00126$:
	ld	a, -2 (ix)
	sub	a, e
	ld	a, #0x01
	jr	Z, 00173$
	xor	a, a
00173$:
	ld	-6 (ix), a
	ld	a, -2 (ix)
	add	a, #0x02
	ld	-5 (ix), a
	ld	-1 (ix), #0
00110$:
;apps/mini_os.c:571: on = pad_get(col, row);
	push	bc
	push	de
	ld	h, -2 (ix)
	ld	l, -1 (ix)
	push	hl
	call	_pad_get
	pop	af
	ld	a, l
	pop	de
	pop	bc
	ld	l, a
;apps/mini_os.c:572: ch = on ? '#' : '.';
	or	a, a
	jr	Z, 00116$
	ld	b, #0x23
	ld	d, #0x00
	jr	00117$
00116$:
	ld	b, #0x2e
	ld	d, #0x00
00117$:
;apps/mini_os.c:573: if ((col == cursor_x) && (row == cursor_y)) {
	ld	a, -1 (ix)
	sub	a, c
	jr	NZ, 00106$
	ld	a, -6 (ix)
	or	a, a
	jr	Z, 00106$
;apps/mini_os.c:574: ch = on ? '@' : 'O';
	ld	a, l
	or	a, a
	jr	Z, 00118$
	ld	-4 (ix), #0x40
	ld	-3 (ix), #0
	jr	00119$
00118$:
	ld	-4 (ix), #0x4f
	ld	-3 (ix), #0
00119$:
	ld	b, -4 (ix)
00106$:
;apps/mini_os.c:576: text_put((unsigned char)(2u + row), col, ch);
	push	bc
	push	de
	push	bc
	inc	sp
	ld	h, -1 (ix)
	ld	l, -5 (ix)
	push	hl
	call	_text_put
	pop	af
	inc	sp
	pop	de
	pop	bc
;apps/mini_os.c:570: for (col = 0u; col < PAD_WIDTH; ++col) {
	inc	-1 (ix)
	ld	a, -1 (ix)
	sub	a, #0x10
	jr	C, 00110$
;apps/mini_os.c:569: for (row = 0u; row < PAD_HEIGHT; ++row) {
	inc	-2 (ix)
	ld	a, -2 (ix)
	sub	a, #0x08
	jp	C, 00126$
;apps/mini_os.c:580: text_write(11u, 0u, "CENTER TOGGLE");
	ld	hl, #___str_43
	push	hl
	xor	a, a
	ld	d,a
	ld	e,#0x0b
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:581: text_write(12u, 0u, "A CLEAR B INVERT");
	ld	hl, #___str_44
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0c
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:582: text_write(13u, 0u, "ARROWS MOVE");
	ld	hl, #___str_45
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0d
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:583: text_write(14u, 0u, "C SAVE EXIT");
	ld	hl, #___str_46
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0e
	push	de
	call	_text_write
	pop	af
;apps/mini_os.c:584: text_write(15u, 0u, "PIXELS ");
	ld	hl, #___str_47
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0f
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/mini_os.c:585: text_write_u16(15u, 7u, pad_count_pixels());
	call	_pad_count_pixels
	ld	h, #0x00
	push	hl
	ld	de, #0x070f
	push	de
	call	_text_write_u16
;apps/mini_os.c:586: }
	ld	sp,ix
	pop	ix
	ret
___str_42:
	.ascii "PAD"
	.db 0x00
___str_43:
	.ascii "CENTER TOGGLE"
	.db 0x00
___str_44:
	.ascii "A CLEAR B INVERT"
	.db 0x00
___str_45:
	.ascii "ARROWS MOVE"
	.db 0x00
___str_46:
	.ascii "C SAVE EXIT"
	.db 0x00
___str_47:
	.ascii "PIXELS "
	.db 0x00
;apps/mini_os.c:588: static void pad_invert(void) {
;	---------------------------------
; Function pad_invert
; ---------------------------------
_pad_invert:
;apps/mini_os.c:592: for (row = 0u; row < PAD_HEIGHT; ++row) {
	ld	b, #0x00
00102$:
;apps/mini_os.c:593: value = (unsigned int)(pad_row(row) ^ 0xffffu);
	push	bc
	push	bc
	inc	sp
	call	_pad_row
	inc	sp
	pop	bc
	ld	a, l
	cpl
	ld	e, a
	ld	a, h
	cpl
	ld	d, a
;apps/mini_os.c:594: pad_write_row(row, value);
	push	bc
	push	de
	push	bc
	inc	sp
	call	_pad_write_row
	pop	af
	inc	sp
	pop	bc
;apps/mini_os.c:592: for (row = 0u; row < PAD_HEIGHT; ++row) {
	inc	b
	ld	a, b
	sub	a, #0x08
	jr	C, 00102$
;apps/mini_os.c:596: }
	ret
;apps/mini_os.c:598: static void run_pad(void) {
;	---------------------------------
; Function run_pad
; ---------------------------------
_run_pad:
	push	af
	push	af
;apps/mini_os.c:604: draw_pad();
	call	_draw_pad
;apps/mini_os.c:605: wait_for_release();
	call	_wait_for_release
;apps/mini_os.c:606: last_buttons = GLIC_BUTTONS_NONE;
	ld	iy, #0
	add	iy, sp
	ld	0 (iy), #0xff
;apps/mini_os.c:608: while (1) {
00129$:
;apps/mini_os.c:609: buttons = glic_read_buttons();
	call	_glic_read_buttons
	ld	a, l
	ld	iy, #1
	add	iy, sp
	ld	0 (iy), a
;apps/mini_os.c:610: x = store_read(STORE_PAD_X);
	ld	a, #0x20
	push	af
	inc	sp
	call	_store_read
	ld	a, l
	inc	sp
	ld	iy, #2
	add	iy, sp
	ld	0 (iy), a
;apps/mini_os.c:611: y = store_read(STORE_PAD_Y);
	ld	a, #0x21
	push	af
	inc	sp
	call	_store_read
	ld	a, l
	inc	sp
	ld	iy, #3
	add	iy, sp
	ld	0 (iy), a
;apps/mini_os.c:613: if ((button_edge(buttons, last_buttons, GLIC_BTN_LEFT) != 0u) &&
	ld	a, #0x10
	push	af
	inc	sp
	ld	a, -3 (iy)
	dec	iy
	dec	iy
	dec	iy
	push	af
	inc	sp
	ld	a, 1 (iy)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00125$
;apps/mini_os.c:614: (x != 0u)) {
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	or	a, a
	jr	Z, 00125$
;apps/mini_os.c:615: --x;
	ld	a, 0 (iy)
	dec	a
;apps/mini_os.c:616: store_write(STORE_PAD_X, x);
	ld	d,a
	ld	e,#0x20
	push	de
	call	_store_write
	pop	af
;apps/mini_os.c:617: draw_pad();
	call	_draw_pad
	jp	00126$
00125$:
;apps/mini_os.c:618: } else if ((button_edge(buttons, last_buttons, GLIC_BTN_RIGHT) != 0u) &&
	ld	a, #0x04
	push	af
	inc	sp
	ld	iy, #1
	add	iy, sp
	ld	h, 0 (iy)
	ld	l, 1 (iy)
	push	hl
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00121$
;apps/mini_os.c:619: (x < (PAD_WIDTH - 1u))) {
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	sub	a, #0x0f
	jr	NC, 00121$
;apps/mini_os.c:620: ++x;
	ld	a, 0 (iy)
	inc	a
;apps/mini_os.c:621: store_write(STORE_PAD_X, x);
	ld	d,a
	ld	e,#0x20
	push	de
	call	_store_write
	pop	af
;apps/mini_os.c:622: draw_pad();
	call	_draw_pad
	jp	00126$
00121$:
;apps/mini_os.c:623: } else if ((button_edge(buttons, last_buttons, GLIC_BTN_UP) != 0u) &&
	ld	a, #0x02
	push	af
	inc	sp
	ld	iy, #1
	add	iy, sp
	ld	h, 0 (iy)
	ld	l, 1 (iy)
	push	hl
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00117$
;apps/mini_os.c:624: (y != 0u)) {
	ld	iy, #3
	add	iy, sp
	ld	a, 0 (iy)
	or	a, a
	jr	Z, 00117$
;apps/mini_os.c:625: --y;
	ld	a, 0 (iy)
	dec	a
;apps/mini_os.c:626: store_write(STORE_PAD_Y, y);
	ld	d,a
	ld	e,#0x21
	push	de
	call	_store_write
	pop	af
;apps/mini_os.c:627: draw_pad();
	call	_draw_pad
	jp	00126$
00117$:
;apps/mini_os.c:628: } else if ((button_edge(buttons, last_buttons, GLIC_BTN_DOWN) != 0u) &&
	ld	a, #0x08
	push	af
	inc	sp
	ld	iy, #1
	add	iy, sp
	ld	h, 0 (iy)
	ld	l, 1 (iy)
	push	hl
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00113$
;apps/mini_os.c:629: (y < (PAD_HEIGHT - 1u))) {
	ld	iy, #3
	add	iy, sp
	ld	a, 0 (iy)
	sub	a, #0x07
	jr	NC, 00113$
;apps/mini_os.c:630: ++y;
	ld	a, 0 (iy)
	inc	a
;apps/mini_os.c:631: store_write(STORE_PAD_Y, y);
	ld	d,a
	ld	e,#0x21
	push	de
	call	_store_write
	pop	af
;apps/mini_os.c:632: draw_pad();
	call	_draw_pad
	jp	00126$
00113$:
;apps/mini_os.c:633: } else if (button_edge(buttons, last_buttons, GLIC_BTN_CENTER) != 0u) {
	ld	a, #0x01
	push	af
	inc	sp
	ld	iy, #1
	add	iy, sp
	ld	h, 0 (iy)
	ld	l, 1 (iy)
	push	hl
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00110$
;apps/mini_os.c:634: pad_set(x, y, (unsigned char)(pad_get(x, y) == 0u));
	ld	iy, #3
	add	iy, sp
	ld	h, 0 (iy)
	ld	l, -1 (iy)
	push	hl
	call	_pad_get
	pop	af
	ld	a, l
	or	a, a
	ld	a, #0x01
	jr	Z, 00199$
	xor	a, a
00199$:
	push	af
	inc	sp
	ld	iy, #4
	add	iy, sp
	ld	h, 0 (iy)
	ld	l, -1 (iy)
	push	hl
	call	_pad_set
	pop	af
	inc	sp
;apps/mini_os.c:635: draw_pad();
	call	_draw_pad
	jr	00126$
00110$:
;apps/mini_os.c:636: } else if (button_edge(buttons, last_buttons, GLIC_BTN_A) != 0u) {
	ld	a, #0x80
	push	af
	inc	sp
	ld	iy, #1
	add	iy, sp
	ld	h, 0 (iy)
	ld	l, 1 (iy)
	push	hl
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00107$
;apps/mini_os.c:637: reset_pad_state();
	call	_reset_pad_state
;apps/mini_os.c:638: draw_pad();
	call	_draw_pad
	jr	00126$
00107$:
;apps/mini_os.c:639: } else if (button_edge(buttons, last_buttons, GLIC_BTN_B) != 0u) {
	ld	a, #0x40
	push	af
	inc	sp
	ld	iy, #1
	add	iy, sp
	ld	h, 0 (iy)
	ld	l, 1 (iy)
	push	hl
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00104$
;apps/mini_os.c:640: pad_invert();
	call	_pad_invert
;apps/mini_os.c:641: draw_pad();
	call	_draw_pad
	jr	00126$
00104$:
;apps/mini_os.c:642: } else if (button_edge(buttons, last_buttons, GLIC_BTN_C) != 0u) {
	ld	a, #0x20
	push	af
	inc	sp
	ld	iy, #1
	add	iy, sp
	ld	h, 0 (iy)
	ld	l, 1 (iy)
	push	hl
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00126$
;apps/mini_os.c:643: store_write(STORE_PAD_X, x);
	ld	hl, #2
	add	hl, sp
	ld	d, (hl)
	ld	e,#0x20
	push	de
	call	_store_write
	pop	af
;apps/mini_os.c:644: store_write(STORE_PAD_Y, y);
	ld	hl, #3
	add	hl, sp
	ld	d, (hl)
	ld	e,#0x21
	push	de
	call	_store_write
	pop	af
;apps/mini_os.c:645: wait_for_release();
	call	_wait_for_release
;apps/mini_os.c:646: return;
	jr	00131$
00126$:
;apps/mini_os.c:649: last_buttons = buttons;
	ld	iy, #1
	add	iy, sp
	ld	a, 0 (iy)
	dec	iy
	ld	0 (iy), a
;apps/mini_os.c:650: glic_delay(LOOP_DELAY);
	ld	hl, #0x044c
	push	hl
	call	_glic_delay
	pop	af
	jp	00129$
00131$:
;apps/mini_os.c:652: }
	pop	af
	pop	af
	ret
;apps/mini_os.c:654: static void run_program(unsigned char program) {
;	---------------------------------
; Function run_program
; ---------------------------------
_run_program:
;apps/mini_os.c:655: if (program == PROGRAM_COUNTER) {
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	or	a, a
;apps/mini_os.c:656: run_counter();
	jp	Z,_run_counter
;apps/mini_os.c:657: } else if (program == PROGRAM_MATH) {
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	dec	a
	jp	Z,_run_math
;apps/mini_os.c:658: run_math();
;apps/mini_os.c:660: run_pad();
;apps/mini_os.c:662: }
	jp	_run_pad
;apps/mini_os.c:664: void main(void) {
;	---------------------------------
; Function main
; ---------------------------------
_main::
;apps/mini_os.c:670: storage_init();
	call	_storage_init
;apps/mini_os.c:671: selected = store_read(STORE_SELECTED);
	ld	a, #0x04
	push	af
	inc	sp
	call	_store_read
	inc	sp
	ld	h, l
;apps/mini_os.c:672: if (selected >= PROGRAM_COUNT) {
	ld	a, h
	sub	a, #0x03
	jr	C, 00102$
;apps/mini_os.c:673: selected = 0u;
	ld	h, #0x00
00102$:
;apps/mini_os.c:677: draw_menu(selected, message);
	push	hl
	ld	de, #0x0000
	push	de
	push	hl
	inc	sp
	call	_draw_menu
	pop	af
	inc	sp
	call	_wait_for_release
	pop	hl
;apps/mini_os.c:679: last_buttons = GLIC_BUTTONS_NONE;
	ld	c, #0xff
;apps/mini_os.c:681: while (1) {
00121$:
;apps/mini_os.c:682: buttons = glic_read_buttons();
	push	hl
	push	bc
	call	_glic_read_buttons
	pop	bc
	pop	af
	ld	h, a
;apps/mini_os.c:683: if ((button_edge(buttons, last_buttons, GLIC_BTN_UP) != 0u) &&
	push	hl
	push	bc
	ld	b, #0x02
	push	bc
	ld	a, l
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	bc
	pop	hl
	or	a, a
	jr	Z, 00117$
;apps/mini_os.c:684: (selected != 0u)) {
	ld	a, h
	or	a, a
	jr	Z, 00117$
;apps/mini_os.c:685: --selected;
	dec	h
;apps/mini_os.c:686: store_write(STORE_SELECTED, selected);
	push	hl
	ld	l, #0x04
	push	hl
	call	_store_write
	pop	af
	pop	hl
;apps/mini_os.c:688: draw_menu(selected, message);
	push	hl
	ld	de, #0x0000
	push	de
	push	hl
	inc	sp
	call	_draw_menu
	pop	af
	inc	sp
	pop	hl
	jp	00118$
00117$:
;apps/mini_os.c:689: } else if ((button_edge(buttons, last_buttons, GLIC_BTN_DOWN) != 0u) &&
	push	hl
	push	bc
	ld	b, #0x08
	push	bc
	ld	a, l
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	bc
	pop	hl
	or	a, a
	jr	Z, 00113$
;apps/mini_os.c:690: (selected < (PROGRAM_COUNT - 1u))) {
	ld	a, h
	sub	a, #0x02
	jr	NC, 00113$
;apps/mini_os.c:691: ++selected;
	inc	h
;apps/mini_os.c:692: store_write(STORE_SELECTED, selected);
	push	hl
	ld	l, #0x04
	push	hl
	call	_store_write
	pop	af
	pop	hl
;apps/mini_os.c:694: draw_menu(selected, message);
	push	hl
	ld	de, #0x0000
	push	de
	push	hl
	inc	sp
	call	_draw_menu
	pop	af
	inc	sp
	pop	hl
	jp	00118$
00113$:
;apps/mini_os.c:695: } else if ((button_edge(buttons, last_buttons, GLIC_BTN_CENTER) != 0u) ||
	push	hl
	push	bc
	ld	b, #0x01
	push	bc
	ld	a, l
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	bc
	pop	hl
	or	a, a
	jr	NZ, 00108$
;apps/mini_os.c:696: (button_edge(buttons, last_buttons, GLIC_BTN_A) != 0u)) {
	push	hl
	push	bc
	ld	b, #0x80
	push	bc
	ld	a, l
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	bc
	pop	hl
	or	a, a
	jr	Z, 00109$
00108$:
;apps/mini_os.c:697: wait_for_release();
	push	hl
	call	_wait_for_release
	pop	hl
;apps/mini_os.c:698: run_program(selected);
	push	hl
	push	hl
	inc	sp
	call	_run_program
	inc	sp
	pop	hl
;apps/mini_os.c:699: message = "STATE SAVED";
	ld	bc, #___str_48+0
;apps/mini_os.c:700: draw_menu(selected, message);
	push	hl
	push	bc
	push	hl
	inc	sp
	call	_draw_menu
	pop	af
	inc	sp
	pop	hl
	jr	00118$
00109$:
;apps/mini_os.c:701: } else if (button_edge(buttons, last_buttons, GLIC_BTN_B) != 0u) {
	push	hl
	push	bc
	ld	b, #0x40
	push	bc
	ld	a, l
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	bc
	pop	hl
	or	a, a
	jr	Z, 00106$
;apps/mini_os.c:702: reset_program_state(selected);
	push	hl
	push	hl
	inc	sp
	call	_reset_program_state
	inc	sp
	pop	hl
;apps/mini_os.c:703: message = "SLOT RESET";
	ld	bc, #___str_49+0
;apps/mini_os.c:704: draw_menu(selected, message);
	push	hl
	push	bc
	push	hl
	inc	sp
	call	_draw_menu
	pop	af
	inc	sp
	pop	hl
	jr	00118$
00106$:
;apps/mini_os.c:705: } else if (button_edge(buttons, last_buttons, GLIC_BTN_C) != 0u) {
	push	hl
	ld	b, #0x20
	push	bc
	ld	a, l
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	hl
	or	a, a
	jr	Z, 00118$
;apps/mini_os.c:706: show_help();
	push	hl
	call	_show_help
	pop	hl
;apps/mini_os.c:708: draw_menu(selected, message);
	push	hl
	ld	de, #0x0000
	push	de
	push	hl
	inc	sp
	call	_draw_menu
	pop	af
	inc	sp
	pop	hl
00118$:
;apps/mini_os.c:711: last_buttons = buttons;
	ld	c, l
;apps/mini_os.c:712: glic_delay(LOOP_DELAY);
	push	hl
	push	bc
	ld	de, #0x044c
	push	de
	call	_glic_delay
	pop	af
	pop	bc
	pop	hl
;apps/mini_os.c:714: }
	jp	00121$
___str_48:
	.ascii "STATE SAVED"
	.db 0x00
___str_49:
	.ascii "SLOT RESET"
	.db 0x00
	.area _CODE
	.area _INITIALIZER
	.area _CABS (ABS)
