; generated by sdcc-z80-bin
    JR __sdcc_z80_bin_start
    DB "text_editor",0
__sdcc_z80_bin_start:
    LD SP,#0x7700
    CALL _main
__sdcc_z80_bin_halt:
    JR __sdcc_z80_bin_halt

;--------------------------------------------------------
; File Created by SDCC : free open source ANSI-C Compiler
; Version 4.1.0 #12072 (Linux)
;--------------------------------------------------------
	.module text_editor
	.optsdcc -mz80
	
;--------------------------------------------------------
; Public variables in this module
;--------------------------------------------------------
	.globl _main
;--------------------------------------------------------
; special function registers
;--------------------------------------------------------
;--------------------------------------------------------
; ram data
;--------------------------------------------------------
	.area _DATA
_selected_file:
	.ds 1
;--------------------------------------------------------
; ram data
;--------------------------------------------------------
	.area _INITIALIZED
;--------------------------------------------------------
; absolute external ram data
;--------------------------------------------------------
	.area _DABS (ABS)
;--------------------------------------------------------
; global & static initialisations
;--------------------------------------------------------
	.area _HOME
	.area _GSINIT
	.area _GSFINAL
	.area _GSINIT
;--------------------------------------------------------
; Home
;--------------------------------------------------------
	.area _HOME
	.area _HOME
;--------------------------------------------------------
; code
;--------------------------------------------------------
	.area _CODE
;apps/../common/glic80.h:29: static unsigned char glic_read_buttons(void) __naked {
;	---------------------------------
; Function glic_read_buttons
; ---------------------------------
_glic_read_buttons:
;apps/../common/glic80.h:34: __endasm;
	in	a,(0)
	ld	l,a
	ret
;apps/../common/glic80.h:35: }
;apps/../common/glic80.h:37: static unsigned char glic_button_pressed(unsigned char buttons,
;	---------------------------------
; Function glic_button_pressed
; ---------------------------------
_glic_button_pressed:
;apps/../common/glic80.h:39: return (buttons & mask) == 0u;
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	inc	iy
	and	a, 0 (iy)
	or	a, a
	ld	a, #0x01
	jr	Z, 00104$
	xor	a, a
00104$:
	ld	l, a
;apps/../common/glic80.h:40: }
	ret
_glic_bit_masks:
	.db #0x01	; 1
	.db #0x02	; 2
	.db #0x04	; 4
	.db #0x08	; 8
	.db #0x10	; 16
	.db #0x20	; 32
	.db #0x40	; 64
	.db #0x80	; 128
;apps/../common/glic80.h:42: static void glic_delay(unsigned int count) {
;	---------------------------------
; Function glic_delay
; ---------------------------------
_glic_delay:
;apps/../common/glic80.h:43: while (count != 0u) {
	pop	de
	pop	bc
	push	bc
	push	de
00101$:
	ld	a, b
	or	a, c
	ret	Z
;apps/../common/glic80.h:44: --count;
	dec	bc
;apps/../common/glic80.h:47: __endasm;
	nop
;apps/../common/glic80.h:49: }
	jr	00101$
;apps/../common/glic80.h:51: static void glic_clear_text(void) {
;	---------------------------------
; Function glic_clear_text
; ---------------------------------
_glic_clear_text:
;apps/../common/glic80.h:54: for (i = 0; i < GLIC_CVRAM_BYTES; ++i) {
	ld	bc, #0x0000
00102$:
;apps/../common/glic80.h:55: GLIC_CVRAM[i] = 0x00u;
	ld	hl, #0x7700
	add	hl, bc
	ld	(hl), #0x00
;apps/../common/glic80.h:54: for (i = 0; i < GLIC_CVRAM_BYTES; ++i) {
	inc	bc
	ld	a, b
	sub	a, #0x01
	jr	C, 00102$
;apps/../common/glic80.h:57: }
	ret
;apps/../common/glic80.h:59: static void glic_fill_graphics(unsigned char value) {
;	---------------------------------
; Function glic_fill_graphics
; ---------------------------------
_glic_fill_graphics:
;apps/../common/glic80.h:62: for (i = 0; i < GLIC_GVRAM_BYTES; ++i) {
	ld	bc, #0x0000
00102$:
;apps/../common/glic80.h:63: GLIC_GVRAM[i] = value;
	ld	hl, #0x7800
	add	hl, bc
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	ld	(hl), a
;apps/../common/glic80.h:62: for (i = 0; i < GLIC_GVRAM_BYTES; ++i) {
	inc	bc
	ld	a, b
	sub	a, #0x08
	jr	C, 00102$
;apps/../common/glic80.h:65: }
	ret
;apps/../common/glic80.h:67: static void glic_plot(unsigned char x, unsigned char y, unsigned char value) {
;	---------------------------------
; Function glic_plot
; ---------------------------------
_glic_plot:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/../common/glic80.h:71: if ((x >= GLIC_SCREEN_WIDTH) || (y >= 128u)) {
	ld	a, 4 (ix)
	sub	a, #0x80
	jr	NC, 00107$
	ld	a, 5 (ix)
	sub	a, #0x80
;apps/../common/glic80.h:72: return;
	jr	NC, 00107$
;apps/../common/glic80.h:75: offset = (((unsigned int)(y >> 3)) << 7) + x;
	ld	a, 5 (ix)
	rrca
	rrca
	rrca
	and	a, #0x1f
	ld	l, a
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	ld	c, 4 (ix)
	ld	b, #0x00
	add	hl, bc
	ex	de, hl
;apps/../common/glic80.h:76: mask = glic_bit_masks[y & 7u];
	ld	bc, #_glic_bit_masks+0
	ld	a, 5 (ix)
	and	a, #0x07
	ld	l, a
	ld	h, #0x00
	add	hl, bc
	ld	b, (hl)
;apps/../common/glic80.h:78: GLIC_GVRAM[offset] |= mask;
	ld	hl, #0x7800
	add	hl, de
	ld	c, (hl)
;apps/../common/glic80.h:77: if (value != 0u) {
	ld	a, 6 (ix)
	or	a, a
	jr	Z, 00105$
;apps/../common/glic80.h:78: GLIC_GVRAM[offset] |= mask;
	ld	a, c
	or	a, b
	ld	(hl), a
	jr	00107$
00105$:
;apps/../common/glic80.h:80: GLIC_GVRAM[offset] &= (unsigned char)~mask;
	ld	a, b
	cpl
	and	a, c
	ld	(hl), a
00107$:
;apps/../common/glic80.h:82: }
	pop	ix
	ret
;apps/../common/glic80.h:84: static void glic_draw_bitmap8(unsigned char x,
;	---------------------------------
; Function glic_draw_bitmap8
; ---------------------------------
_glic_draw_bitmap8:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/../common/glic80.h:92: for (row = 0u; row < 8u; ++row) {
	ld	c, #0x00
00107$:
;apps/../common/glic80.h:93: bits = rows[row];
	ld	l, 6 (ix)
	ld	h, 7 (ix)
	ld	b, #0x00
	add	hl, bc
	ld	l, (hl)
;apps/../common/glic80.h:94: mask = 0x80u;
	ld	e, #0x80
;apps/../common/glic80.h:95: for (col = 0u; col < 8u; ++col) {
	ld	a, 5 (ix)
	add	a, c
	ld	b, a
	ld	d, #0x00
00105$:
;apps/../common/glic80.h:96: if ((bits & mask) != 0u) {
	ld	a, l
	and	a,e
	jr	Z, 00102$
;apps/../common/glic80.h:97: glic_plot((unsigned char)(x + col), (unsigned char)(y + row), 1u);
	ld	a, 4 (ix)
	add	a, d
	push	hl
	push	bc
	push	de
	ld	h, #0x01
	ld	l, b
	push	hl
	push	af
	inc	sp
	call	_glic_plot
	pop	af
	inc	sp
	pop	de
	pop	bc
	pop	hl
00102$:
;apps/../common/glic80.h:99: mask >>= 1;
	srl	e
;apps/../common/glic80.h:95: for (col = 0u; col < 8u; ++col) {
	inc	d
	ld	a, d
	sub	a, #0x08
	jr	C, 00105$
;apps/../common/glic80.h:92: for (row = 0u; row < 8u; ++row) {
	inc	c
	ld	a, c
	sub	a, #0x08
	jr	C, 00107$
;apps/../common/glic80.h:102: }
	pop	ix
	ret
;apps/../common/glic80.h:104: static void glic_draw_tile8(unsigned char cell_x,
;	---------------------------------
; Function glic_draw_tile8
; ---------------------------------
_glic_draw_tile8:
	push	ix
	ld	ix,#0
	add	ix,sp
	push	af
;apps/../common/glic80.h:110: offset = (((unsigned int)cell_y) << 7) + (((unsigned int)cell_x) << 3);
	ld	c, 5 (ix)
	xor	a, a
	rr	a
	ld	b, c
	rr	b
	rra
	ld	c, a
	ld	l, 4 (ix)
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, bc
	ex	de, hl
;apps/../common/glic80.h:111: for (col = 0u; col < 8u; ++col) {
	ld	c, #0x00
00102$:
;apps/../common/glic80.h:112: GLIC_GVRAM[offset + col] = columns[col];
	ld	l, c
	ld	h, #0x00
	add	hl, de
	ld	-2 (ix), l
	ld	a, h
	add	a, #0x78
	ld	-1 (ix), a
	ld	l, 6 (ix)
	ld	h, 7 (ix)
	ld	b, #0x00
	add	hl, bc
	ld	a, (hl)
	pop	hl
	push	hl
	ld	(hl), a
;apps/../common/glic80.h:111: for (col = 0u; col < 8u; ++col) {
	inc	c
	ld	a, c
	sub	a, #0x08
	jr	C, 00102$
;apps/../common/glic80.h:114: }
	ld	sp, ix
	pop	ix
	ret
;apps/../common/glic80.h:116: static void glic_prepare_screen(unsigned char value) {
;	---------------------------------
; Function glic_prepare_screen
; ---------------------------------
_glic_prepare_screen:
;apps/../common/glic80.h:117: glic_clear_text();
	call	_glic_clear_text
;apps/../common/glic80.h:118: glic_fill_graphics(value);
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_glic_fill_graphics
	inc	sp
;apps/../common/glic80.h:119: }
	ret
;apps/../common/glic80.h:121: static void glic_fill_page_run(unsigned char page,
;	---------------------------------
; Function glic_fill_page_run
; ---------------------------------
_glic_fill_page_run:
;apps/../common/glic80.h:127: p = GLIC_GVRAM + (((unsigned int)page) << 7) + x;
	ld	iy, #2
	add	iy, sp
	ld	c, 0 (iy)
	ld	b, #0x00
	xor	a, a
	rr	b
	ld	b, c
	rr	b
	rra
	ld	c, a
	ld	a, b
	add	a, #0x78
	ld	b, a
	ld	a, c
	ld	hl, #3
	add	hl, sp
	add	a, (hl)
	ld	c, a
	jr	NC, 00117$
	inc	b
00117$:
;apps/../common/glic80.h:128: while (width != 0u) {
	ld	e, 2 (iy)
00101$:
	ld	a, e
	or	a, a
	ret	Z
;apps/../common/glic80.h:129: *p++ = value;
	ld	iy, #5
	add	iy, sp
	ld	a, 0 (iy)
	ld	(bc), a
	inc	bc
;apps/../common/glic80.h:130: --width;
	dec	e
;apps/../common/glic80.h:132: }
	jr	00101$
;apps/../common/glic80.h:134: static void glic_fill_pages(unsigned char first_page,
;	---------------------------------
; Function glic_fill_pages
; ---------------------------------
_glic_fill_pages:
;apps/../common/glic80.h:137: while (page_count != 0u) {
	ld	iy, #2
	add	iy, sp
	ld	b, 0 (iy)
	ld	c, 1 (iy)
00101$:
	ld	a, c
	or	a, a
	ret	Z
;apps/../common/glic80.h:138: glic_fill_page_run(first_page, 0u, GLIC_SCREEN_WIDTH, value);
	push	bc
	ld	hl, #6
	add	hl, sp
	ld	d, (hl)
	ld	e,#0x80
	push	de
	xor	a, a
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_fill_page_run
	pop	af
	pop	af
	pop	bc
;apps/../common/glic80.h:139: ++first_page;
	inc	b
;apps/../common/glic80.h:140: --page_count;
	dec	c
;apps/../common/glic80.h:142: }
	jr	00101$
;apps/../common/glic80.h:144: static void glic_fill_columns(unsigned char x,
;	---------------------------------
; Function glic_fill_columns
; ---------------------------------
_glic_fill_columns:
;apps/../common/glic80.h:149: for (page = 0u; page < GLIC_SCREEN_PAGES; ++page) {
	ld	b, #0x00
00102$:
;apps/../common/glic80.h:150: glic_fill_page_run(page, x, width, value);
	push	bc
	ld	iy, #6
	add	iy, sp
	ld	a, 0 (iy)
	push	af
	inc	sp
	ld	a, -1 (iy)
	dec	iy
	push	af
	inc	sp
	ld	a, -1 (iy)
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_fill_page_run
	pop	af
	pop	af
	pop	bc
;apps/../common/glic80.h:149: for (page = 0u; page < GLIC_SCREEN_PAGES; ++page) {
	inc	b
	ld	a, b
	sub	a, #0x10
	jr	C, 00102$
;apps/../common/glic80.h:152: }
	ret
;apps/text_editor.c:35: static volatile unsigned char *text_cell(unsigned char row,
;	---------------------------------
; Function text_cell
; ---------------------------------
_text_cell:
;apps/text_editor.c:40: while (row != 0u) {
	ld	bc, #0x7700
	ld	iy, #2
	add	iy, sp
	ld	l, 0 (iy)
00101$:
	ld	a, l
	or	a, a
	jr	Z, 00103$
;apps/text_editor.c:41: p += 16u;
	ld	a, c
	add	a, #0x10
	ld	c, a
	jr	NC, 00117$
	inc	b
00117$:
;apps/text_editor.c:42: --row;
	dec	l
	jr	00101$
00103$:
;apps/text_editor.c:44: p += col;
	ld	a, c
	ld	hl, #3
	add	hl, sp
	add	a, (hl)
	ld	l, a
	jr	NC, 00118$
	inc	b
00118$:
	ld	h, b
;apps/text_editor.c:45: return p;
;apps/text_editor.c:46: }
	ret
_keyboard_keys:
	.db #0x41	; 65	'A'
	.db #0x42	; 66	'B'
	.db #0x43	; 67	'C'
	.db #0x44	; 68	'D'
	.db #0x45	; 69	'E'
	.db #0x46	; 70	'F'
	.db #0x47	; 71	'G'
	.db #0x48	; 72	'H'
	.db #0x49	; 73	'I'
	.db #0x4a	; 74	'J'
	.db #0x4b	; 75	'K'
	.db #0x4c	; 76	'L'
	.db #0x4d	; 77	'M'
	.db #0x4e	; 78	'N'
	.db #0x4f	; 79	'O'
	.db #0x50	; 80	'P'
	.db #0x51	; 81	'Q'
	.db #0x52	; 82	'R'
	.db #0x53	; 83	'S'
	.db #0x54	; 84	'T'
	.db #0x55	; 85	'U'
	.db #0x56	; 86	'V'
	.db #0x57	; 87	'W'
	.db #0x58	; 88	'X'
	.db #0x59	; 89	'Y'
	.db #0x5a	; 90	'Z'
	.db #0x30	; 48	'0'
	.db #0x31	; 49	'1'
	.db #0x32	; 50	'2'
	.db #0x33	; 51	'3'
	.db #0x34	; 52	'4'
	.db #0x35	; 53	'5'
	.db #0x36	; 54	'6'
	.db #0x37	; 55	'7'
	.db #0x38	; 56	'8'
	.db #0x39	; 57	'9'
	.db #0x5f	; 95
	.db #0x2e	; 46
	.db #0x2c	; 44
	.db #0x21	; 33
;apps/text_editor.c:48: static void text_put(unsigned char row, unsigned char col, unsigned char ch) {
;	---------------------------------
; Function text_put
; ---------------------------------
_text_put:
;apps/text_editor.c:49: if ((row >= 16u) || (col >= 16u)) {
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	sub	a, #0x10
	ret	NC
	ld	a, 1 (iy)
	sub	a, #0x10
;apps/text_editor.c:50: return;
	ret	NC
;apps/text_editor.c:52: *text_cell(row, col) = ch;
	ld	iy, #3
	add	iy, sp
	ld	h, 0 (iy)
	ld	l, -1 (iy)
	push	hl
	call	_text_cell
	pop	af
	ld	iy, #4
	add	iy, sp
	ld	a, 0 (iy)
	ld	(hl), a
;apps/text_editor.c:53: }
	ret
;apps/text_editor.c:55: static void text_clear_row(unsigned char row) {
;	---------------------------------
; Function text_clear_row
; ---------------------------------
_text_clear_row:
;apps/text_editor.c:58: for (col = 0u; col < 16u; ++col) {
	ld	b, #0x00
00102$:
;apps/text_editor.c:59: text_put(row, col, 0u);
	push	bc
	xor	a, a
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	hl, #6
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
	pop	bc
;apps/text_editor.c:58: for (col = 0u; col < 16u; ++col) {
	inc	b
	ld	a, b
	sub	a, #0x10
	jr	C, 00102$
;apps/text_editor.c:61: }
	ret
;apps/text_editor.c:63: static void text_write(unsigned char row, unsigned char col, const char *text) {
;	---------------------------------
; Function text_write
; ---------------------------------
_text_write:
;apps/text_editor.c:64: while ((*text != 0) && (col < 16u)) {
	ld	iy, #4
	add	iy, sp
	ld	l, 0 (iy)
	ld	h, 1 (iy)
	ld	b, -1 (iy)
00102$:
	ld	d, (hl)
	ld	a, d
	or	a, a
	ret	Z
	ld	a, b
	sub	a, #0x10
	ret	NC
;apps/text_editor.c:65: text_put(row, col, (unsigned char)*text);
	push	hl
	push	bc
	ld	e, b
	push	de
	ld	hl, #8
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
	pop	bc
	pop	hl
;apps/text_editor.c:66: ++text;
	inc	hl
;apps/text_editor.c:67: ++col;
	inc	b
;apps/text_editor.c:69: }
	jr	00102$
;apps/text_editor.c:71: static void text_write_u8_3(unsigned char row,
;	---------------------------------
; Function text_write_u8_3
; ---------------------------------
_text_write_u8_3:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/text_editor.c:78: while (value >= 100u) {
	ld	d, 6 (ix)
	ld	c, #0x00
00101$:
;apps/text_editor.c:79: value = (unsigned char)(value - 100u);
	ld	a,d
	cp	a,#0x64
	jr	C, 00113$
	add	a, #0x9c
	ld	d, a
;apps/text_editor.c:80: ++hundreds;
	inc	c
	jr	00101$
00113$:
;apps/text_editor.c:83: while (value >= 10u) {
	ld	e, #0x00
00104$:
;apps/text_editor.c:84: value = (unsigned char)(value - 10u);
	ld	a,d
	cp	a,#0x0a
	jr	C, 00106$
	add	a, #0xf6
	ld	d, a
;apps/text_editor.c:85: ++tens;
	inc	e
	jr	00104$
00106$:
;apps/text_editor.c:87: text_put(row, col, (unsigned char)('0' + hundreds));
	ld	a, c
	add	a, #0x30
	push	de
	push	af
	inc	sp
	ld	h, 5 (ix)
	ld	l, 4 (ix)
	push	hl
	call	_text_put
	pop	af
	inc	sp
	pop	de
;apps/text_editor.c:88: text_put(row, (unsigned char)(col + 1u), (unsigned char)('0' + tens));
	ld	a, e
	add	a, #0x30
	ld	b, 5 (ix)
	inc	b
	push	de
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
	pop	de
;apps/text_editor.c:91: (unsigned char)('0' + value));
	ld	a, d
	add	a, #0x30
;apps/text_editor.c:90: (unsigned char)(col + 2u),
	ld	b, 5 (ix)
	inc	b
	inc	b
;apps/text_editor.c:89: text_put(row,
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
;apps/text_editor.c:92: }
	pop	ix
	ret
;apps/text_editor.c:94: static unsigned char button_edge(unsigned char buttons,
;	---------------------------------
; Function button_edge
; ---------------------------------
_button_edge:
;apps/text_editor.c:97: return (((last_buttons & mask) != 0u) && ((buttons & mask) == 0u));
	ld	iy, #3
	add	iy, sp
	ld	a, 0 (iy)
	inc	iy
	and	a, 0 (iy)
	or	a, a
	jr	Z, 00103$
	ld	a, -2 (iy)
	and	a, 0 (iy)
	or	a, a
	jr	Z, 00104$
00103$:
	ld	l, #0x00
	ret
00104$:
	ld	l, #0x01
;apps/text_editor.c:98: }
	ret
;apps/text_editor.c:100: static void wait_for_release(void) {
;	---------------------------------
; Function wait_for_release
; ---------------------------------
_wait_for_release:
;apps/text_editor.c:101: while (glic_read_buttons() != GLIC_BUTTONS_NONE) {
00101$:
	call	_glic_read_buttons
	inc	l
	ret	Z
;apps/text_editor.c:102: glic_delay(500u);
	ld	hl, #0x01f4
	push	hl
	call	_glic_delay
	pop	af
;apps/text_editor.c:104: }
	jr	00101$
;apps/text_editor.c:106: static volatile unsigned char *file_record(unsigned char file) {
;	---------------------------------
; Function file_record
; ---------------------------------
_file_record:
;apps/text_editor.c:110: while (file != 0u) {
	ld	hl, #0x6004
	ld	iy, #2
	add	iy, sp
	ld	c, 0 (iy)
00101$:
	ld	a, c
	or	a, a
	ret	Z
;apps/text_editor.c:111: p += FILE_RECORD_SIZE;
	ld	de, #0x00c1
	add	hl, de
;apps/text_editor.c:112: --file;
	dec	c
;apps/text_editor.c:114: return p;
;apps/text_editor.c:115: }
	jr	00101$
;apps/text_editor.c:117: static volatile unsigned char *file_data(unsigned char file) {
;	---------------------------------
; Function file_data
; ---------------------------------
_file_data:
;apps/text_editor.c:118: return file_record(file) + 1u;
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_file_record
	inc	sp
	inc	hl
;apps/text_editor.c:119: }
	ret
;apps/text_editor.c:121: static unsigned char file_length(unsigned char file) {
;	---------------------------------
; Function file_length
; ---------------------------------
_file_length:
;apps/text_editor.c:122: return *file_record(file);
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_file_record
	inc	sp
	ld	l, (hl)
;apps/text_editor.c:123: }
	ret
;apps/text_editor.c:125: static void set_file_length(unsigned char file, unsigned char len) {
;	---------------------------------
; Function set_file_length
; ---------------------------------
_set_file_length:
;apps/text_editor.c:126: *file_record(file) = len;
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_file_record
	inc	sp
	ld	iy, #3
	add	iy, sp
	ld	a, 0 (iy)
	ld	(hl), a
;apps/text_editor.c:127: }
	ret
;apps/text_editor.c:129: static void clear_file(unsigned char file) {
;	---------------------------------
; Function clear_file
; ---------------------------------
_clear_file:
;apps/text_editor.c:133: p = file_record(file);
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_file_record
	inc	sp
;apps/text_editor.c:134: *p++ = 0u;
	ld	(hl), #0x00
	inc	hl
;apps/text_editor.c:135: for (i = 0u; i < TEXT_CAPACITY; ++i) {
	xor	a, a
00102$:
;apps/text_editor.c:136: *p++ = 0u;
	ld	(hl), #0x00
	inc	hl
;apps/text_editor.c:135: for (i = 0u; i < TEXT_CAPACITY; ++i) {
	inc	a
	cp	a, #0xc0
	jr	C, 00102$
;apps/text_editor.c:138: }
	ret
;apps/text_editor.c:140: static void storage_init(void) {
;	---------------------------------
; Function storage_init
; ---------------------------------
_storage_init:
;apps/text_editor.c:143: if ((STORAGE_BASE[0] != STORAGE_MAGIC0) ||
	ld	a, (#0x6000)
	sub	a, #0x54
	jr	NZ, 00102$
;apps/text_editor.c:144: (STORAGE_BASE[1] != STORAGE_MAGIC1) ||
	ld	a, (#0x6001)
	sub	a, #0x58
	jr	NZ, 00102$
;apps/text_editor.c:145: (STORAGE_BASE[2] != STORAGE_MAGIC2) ||
	ld	a, (#0x6002)
	sub	a, #0x54
	jr	NZ, 00102$
;apps/text_editor.c:146: (STORAGE_BASE[3] != STORAGE_MAGIC3)) {
	ld	a, (#0x6003)
	sub	a, #0x31
	jr	Z, 00122$
00102$:
;apps/text_editor.c:147: STORAGE_BASE[0] = STORAGE_MAGIC0;
	ld	hl, #0x6000
	ld	(hl), #0x54
;apps/text_editor.c:148: STORAGE_BASE[1] = STORAGE_MAGIC1;
	ld	l, #0x01
	ld	(hl), #0x58
;apps/text_editor.c:149: STORAGE_BASE[2] = STORAGE_MAGIC2;
	ld	l, #0x02
	ld	(hl), #0x54
;apps/text_editor.c:150: STORAGE_BASE[3] = STORAGE_MAGIC3;
	ld	l, #0x03
	ld	(hl), #0x31
;apps/text_editor.c:151: for (file = 0u; file < FILE_COUNT; ++file) {
	ld	b, #0x00
00110$:
;apps/text_editor.c:152: clear_file(file);
	push	bc
	push	bc
	inc	sp
	call	_clear_file
	inc	sp
	pop	bc
;apps/text_editor.c:151: for (file = 0u; file < FILE_COUNT; ++file) {
	inc	b
	ld	a, b
	sub	a, #0x03
	jr	C, 00110$
;apps/text_editor.c:154: return;
	ret
;apps/text_editor.c:157: for (file = 0u; file < FILE_COUNT; ++file) {
00122$:
	ld	b, #0x00
00112$:
;apps/text_editor.c:158: if (file_length(file) > TEXT_CAPACITY) {
	push	bc
	push	bc
	inc	sp
	call	_file_length
	inc	sp
	pop	bc
	ld	a, #0xc0
	sub	a, l
	jr	NC, 00113$
;apps/text_editor.c:159: clear_file(file);
	push	bc
	push	bc
	inc	sp
	call	_clear_file
	inc	sp
	pop	bc
00113$:
;apps/text_editor.c:157: for (file = 0u; file < FILE_COUNT; ++file) {
	inc	b
	ld	a, b
	sub	a, #0x03
	jr	C, 00112$
;apps/text_editor.c:162: }
	ret
;apps/text_editor.c:164: static unsigned char key_at(unsigned char row, unsigned char col) {
;	---------------------------------
; Function key_at
; ---------------------------------
_key_at:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/text_editor.c:165: return keyboard_keys[(row << 3) + col];
	ld	a, 4 (ix)
	add	a, a
	add	a, a
	add	a, a
	ld	c, 5 (ix)
	add	a, c
	ld	c, a
	rla
	sbc	a, a
	ld	b, a
	ld	hl, #_keyboard_keys
	add	hl, bc
	ld	l, (hl)
;apps/text_editor.c:166: }
	pop	ix
	ret
;apps/text_editor.c:168: static unsigned char typed_key(unsigned char row, unsigned char col) {
;	---------------------------------
; Function typed_key
; ---------------------------------
_typed_key:
;apps/text_editor.c:171: ch = key_at(row, col);
	ld	iy, #3
	add	iy, sp
	ld	h, 0 (iy)
	ld	l, -1 (iy)
	push	hl
	call	_key_at
	pop	af
;apps/text_editor.c:172: if (ch == '_') {
	ld	a, l
	sub	a, #0x5f
	ret	NZ
;apps/text_editor.c:173: return ' ';
	ld	l, #0x20
;apps/text_editor.c:175: return ch;
;apps/text_editor.c:176: }
	ret
;apps/text_editor.c:178: static unsigned char display_key(unsigned char row, unsigned char col) {
;	---------------------------------
; Function display_key
; ---------------------------------
_display_key:
;apps/text_editor.c:179: return key_at(row, col);
	ld	iy, #3
	add	iy, sp
	ld	h, 0 (iy)
	ld	l, -1 (iy)
	push	hl
	call	_key_at
	pop	af
;apps/text_editor.c:180: }
	ret
;apps/text_editor.c:182: static unsigned char edit_window_start(unsigned char len) {
;	---------------------------------
; Function edit_window_start
; ---------------------------------
_edit_window_start:
;apps/text_editor.c:186: while ((start <= (TEXT_CAPACITY - EDIT_VISIBLE_CHARS)) &&
	ld	c, #0x00
00102$:
	ld	a, #0x50
	sub	a, c
	jr	C, 00104$
;apps/text_editor.c:187: ((unsigned char)(start + EDIT_VISIBLE_CHARS) <= len)) {
	ld	a, c
	add	a, #0x70
	ld	b, a
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	sub	a, b
	jr	C, 00104$
;apps/text_editor.c:188: start = (unsigned char)(start + 16u);
	ld	a, c
	add	a, #0x10
	ld	c, a
	jr	00102$
00104$:
;apps/text_editor.c:190: return start;
	ld	l, c
;apps/text_editor.c:191: }
	ret
;apps/text_editor.c:193: static void draw_text_rows(unsigned char file,
;	---------------------------------
; Function draw_text_rows
; ---------------------------------
_draw_text_rows:
	push	ix
	ld	ix,#0
	add	ix,sp
	push	af
	dec	sp
;apps/text_editor.c:204: data = file_data(file);
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_file_data
	inc	sp
;apps/text_editor.c:205: len = file_length(file);
	push	hl
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_file_length
	ld	-3 (ix), l
	inc	sp
	pop	de
;apps/text_editor.c:206: pos = start;
	ld	c, 7 (ix)
;apps/text_editor.c:208: for (row = 0u; row < rows; ++row) {
	ld	-1 (ix), #0
00111$:
	ld	a, -1 (ix)
	sub	a, 6 (ix)
	jr	NC, 00113$
;apps/text_editor.c:209: text_clear_row((unsigned char)(first_row + row));
	ld	a, 5 (ix)
	add	a, -1 (ix)
	ld	b, a
	push	bc
	push	de
	push	bc
	inc	sp
	call	_text_clear_row
	inc	sp
	pop	de
	pop	bc
;apps/text_editor.c:210: for (col = 0u; col < 16u; ++col) {
	ld	-2 (ix), b
	ld	b, #0x00
00108$:
;apps/text_editor.c:211: if (pos < len) {
	ld	a, c
	sub	a, -3 (ix)
	jr	NC, 00104$
;apps/text_editor.c:212: ch = data[pos];
	ld	l, c
	ld	h, #0x00
	add	hl, de
	ld	a, (hl)
	ld	h, a
;apps/text_editor.c:213: if (ch == 0u) {
	or	a, a
	jr	NZ, 00105$
;apps/text_editor.c:214: ch = ' ';
	ld	h, #0x20
	jr	00105$
00104$:
;apps/text_editor.c:217: ch = ' ';
	ld	h, #0x20
00105$:
;apps/text_editor.c:219: text_put((unsigned char)(first_row + row), col, ch);
	push	bc
	push	de
	ld	l, b
	push	hl
	ld	a, -2 (ix)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
	pop	de
	pop	bc
;apps/text_editor.c:220: ++pos;
	inc	c
;apps/text_editor.c:210: for (col = 0u; col < 16u; ++col) {
	inc	b
	ld	a, b
	sub	a, #0x10
	jr	C, 00108$
;apps/text_editor.c:208: for (row = 0u; row < rows; ++row) {
	inc	-1 (ix)
	jr	00111$
00113$:
;apps/text_editor.c:223: }
	ld	sp, ix
	pop	ix
	ret
;apps/text_editor.c:225: static void draw_menu_files(void) {
;	---------------------------------
; Function draw_menu_files
; ---------------------------------
_draw_menu_files:
	push	ix
	ld	ix,#0
	add	ix,sp
	push	af
	push	af
	dec	sp
;apps/text_editor.c:230: for (file = 0u; file < FILE_COUNT; ++file) {
	ld	-1 (ix), #0
00105$:
;apps/text_editor.c:231: row = (unsigned char)(3u + (file << 1));
	ld	a, -1 (ix)
	ld	-5 (ix), a
	add	a, a
	add	a, #0x03
;apps/text_editor.c:232: text_clear_row(row);
	ld	-4 (ix), a
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;apps/text_editor.c:233: text_put(row, 0u, (file == selected_file) ? '>' : ' ');
	ld	a,(#_selected_file + 0)
	sub	a, -1 (ix)
	jr	NZ, 00109$
	ld	-3 (ix), #0x3e
	ld	-2 (ix), #0
	jr	00110$
00109$:
	ld	-3 (ix), #0x20
	ld	-2 (ix), #0
00110$:
	ld	a, -3 (ix)
	push	af
	inc	sp
	xor	a, a
	push	af
	inc	sp
	ld	a, -4 (ix)
	push	af
	inc	sp
	call	_text_put
;apps/text_editor.c:234: text_write(row, 2u, "FILE ");
	inc	sp
	ld	hl,#___str_0
	ex	(sp),hl
	ld	h, #0x02
	ld	l, -4 (ix)
	push	hl
	call	_text_write
	pop	af
	pop	af
;apps/text_editor.c:235: text_put(row, 7u, (unsigned char)('1' + file));
	ld	a, -5 (ix)
	add	a, #0x31
	ld	d,a
	ld	e,#0x07
	push	de
	ld	a, -4 (ix)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
;apps/text_editor.c:236: len = file_length(file);
	ld	a, -1 (ix)
	push	af
	inc	sp
	call	_file_length
	ld	a, l
	inc	sp
	ld	b, a
;apps/text_editor.c:237: if (len == 0u) {
	or	a, a
	jr	NZ, 00102$
;apps/text_editor.c:238: text_write(row, 9u, "EMPTY");
	ld	hl, #___str_1
	push	hl
	ld	h, #0x09
	ld	l, -4 (ix)
	push	hl
	call	_text_write
	pop	af
	pop	af
	jr	00106$
00102$:
;apps/text_editor.c:240: text_write(row, 9u, "LEN");
	push	bc
	ld	hl, #___str_2
	push	hl
	ld	h, #0x09
	ld	l, -4 (ix)
	push	hl
	call	_text_write
	pop	af
	pop	af
	pop	bc
;apps/text_editor.c:241: text_write_u8_3(row, 13u, len);
	ld	c, #0x0d
	push	bc
	ld	a, -4 (ix)
	push	af
	inc	sp
	call	_text_write_u8_3
	pop	af
	inc	sp
00106$:
;apps/text_editor.c:230: for (file = 0u; file < FILE_COUNT; ++file) {
	inc	-1 (ix)
	ld	a, -1 (ix)
	sub	a, #0x03
	jp	C, 00105$
;apps/text_editor.c:244: }
	ld	sp, ix
	pop	ix
	ret
___str_0:
	.ascii "FILE "
	.db 0x00
___str_1:
	.ascii "EMPTY"
	.db 0x00
___str_2:
	.ascii "LEN"
	.db 0x00
;apps/text_editor.c:246: static void draw_menu(void) {
;	---------------------------------
; Function draw_menu
; ---------------------------------
_draw_menu:
;apps/text_editor.c:247: glic_prepare_screen(GLIC_BLACK);
	xor	a, a
	push	af
	inc	sp
	call	_glic_prepare_screen
	inc	sp
;apps/text_editor.c:248: text_write(0u, 2u, "TEXT EDITOR");
	ld	hl, #___str_3
	push	hl
	ld	a, #0x02
	push	af
	inc	sp
	xor	a, a
	push	af
	inc	sp
	call	_text_write
	pop	af
;apps/text_editor.c:249: text_write(1u, 3u, "RAM FILES");
	ld	hl, #___str_4
	ex	(sp),hl
	ld	de, #0x0301
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/text_editor.c:250: draw_menu_files();
	call	_draw_menu_files
;apps/text_editor.c:251: text_write(10u, 0u, "UP/DN PICK");
	ld	hl, #___str_5
	push	hl
	xor	a, a
	ld	d,a
	ld	e,#0x0a
	push	de
	call	_text_write
	pop	af
;apps/text_editor.c:252: text_write(11u, 0u, "CENTER EDIT");
	ld	hl, #___str_6
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0b
	push	de
	call	_text_write
	pop	af
;apps/text_editor.c:253: text_write(12u, 0u, "A VIEW B ERASE");
	ld	hl, #___str_7
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0c
	push	de
	call	_text_write
	pop	af
;apps/text_editor.c:254: text_write(13u, 0u, "C HELP");
	ld	hl, #___str_8
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0d
	push	de
	call	_text_write
	pop	af
;apps/text_editor.c:255: text_write(15u, 0u, "RUNNING RAM SAVE");
	ld	hl, #___str_9
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0f
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/text_editor.c:256: }
	ret
___str_3:
	.ascii "TEXT EDITOR"
	.db 0x00
___str_4:
	.ascii "RAM FILES"
	.db 0x00
___str_5:
	.ascii "UP/DN PICK"
	.db 0x00
___str_6:
	.ascii "CENTER EDIT"
	.db 0x00
___str_7:
	.ascii "A VIEW B ERASE"
	.db 0x00
___str_8:
	.ascii "C HELP"
	.db 0x00
___str_9:
	.ascii "RUNNING RAM SAVE"
	.db 0x00
;apps/text_editor.c:258: static void draw_confirm_clear(void) {
;	---------------------------------
; Function draw_confirm_clear
; ---------------------------------
_draw_confirm_clear:
;apps/text_editor.c:259: glic_prepare_screen(GLIC_BLACK);
	xor	a, a
	push	af
	inc	sp
	call	_glic_prepare_screen
	inc	sp
;apps/text_editor.c:260: text_write(3u, 2u, "CLEAR FILE ");
	ld	hl, #___str_10
	push	hl
	ld	de, #0x0203
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/text_editor.c:261: text_put(3u, 13u, (unsigned char)('1' + selected_file));
	ld	a,(#_selected_file + 0)
	add	a, #0x31
	ld	d,a
	ld	e,#0x0d
	push	de
	ld	a, #0x03
	push	af
	inc	sp
	call	_text_put
;apps/text_editor.c:262: text_write(6u, 2u, "A YES");
	inc	sp
	ld	hl,#___str_11
	ex	(sp),hl
	ld	de, #0x0206
	push	de
	call	_text_write
	pop	af
;apps/text_editor.c:263: text_write(8u, 2u, "B/C NO");
	ld	hl, #___str_12
	ex	(sp),hl
	ld	de, #0x0208
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/text_editor.c:264: }
	ret
___str_10:
	.ascii "CLEAR FILE "
	.db 0x00
___str_11:
	.ascii "A YES"
	.db 0x00
___str_12:
	.ascii "B/C NO"
	.db 0x00
;apps/text_editor.c:266: static void confirm_clear(void) {
;	---------------------------------
; Function confirm_clear
; ---------------------------------
_confirm_clear:
;apps/text_editor.c:270: draw_confirm_clear();
	call	_draw_confirm_clear
;apps/text_editor.c:271: last_buttons = GLIC_BUTTONS_NONE;
	ld	h, #0xff
;apps/text_editor.c:272: while (1) {
00108$:
;apps/text_editor.c:273: buttons = glic_read_buttons();
	push	hl
	call	_glic_read_buttons
	pop	af
	ld	h, a
;apps/text_editor.c:274: if (button_edge(buttons, last_buttons, GLIC_BTN_A) != 0u) {
	push	hl
	ld	a, #0x80
	push	af
	inc	sp
	push	hl
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	hl
	or	a, a
	jr	Z, 00102$
;apps/text_editor.c:275: clear_file(selected_file);
	ld	a,(#_selected_file + 0)
	push	af
	inc	sp
	call	_clear_file
	inc	sp
;apps/text_editor.c:276: wait_for_release();
;apps/text_editor.c:277: return;
	jp	_wait_for_release
00102$:
;apps/text_editor.c:279: if ((button_edge(buttons, last_buttons, GLIC_BTN_B) != 0u) ||
	push	hl
	ld	a, #0x40
	push	af
	inc	sp
	push	hl
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	hl
	or	a, a
	jp	NZ,_wait_for_release
;apps/text_editor.c:280: (button_edge(buttons, last_buttons, GLIC_BTN_C) != 0u) ||
	push	hl
	ld	a, #0x20
	push	af
	inc	sp
	push	hl
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	hl
	or	a, a
	jp	NZ,_wait_for_release
;apps/text_editor.c:281: (button_edge(buttons, last_buttons, GLIC_BTN_CENTER) != 0u)) {
	push	hl
	ld	a, #0x01
	push	af
	inc	sp
	push	hl
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	hl
	or	a, a
;apps/text_editor.c:282: wait_for_release();
;apps/text_editor.c:283: return;
	jp	NZ,_wait_for_release
;apps/text_editor.c:285: last_buttons = buttons;
	ld	h, l
;apps/text_editor.c:286: glic_delay(LOOP_DELAY);
	push	hl
	ld	de, #0x04b0
	push	de
	call	_glic_delay
	pop	af
	pop	hl
;apps/text_editor.c:288: }
	jr	00108$
;apps/text_editor.c:290: static void show_help(void) {
;	---------------------------------
; Function show_help
; ---------------------------------
_show_help:
;apps/text_editor.c:294: glic_prepare_screen(GLIC_BLACK);
	xor	a, a
	push	af
	inc	sp
	call	_glic_prepare_screen
	inc	sp
;apps/text_editor.c:295: text_write(0u, 2u, "TEXT EDITOR");
	ld	hl, #___str_13
	push	hl
	ld	a, #0x02
	push	af
	inc	sp
	xor	a, a
	push	af
	inc	sp
	call	_text_write
	pop	af
;apps/text_editor.c:296: text_write(2u, 0u, "MENU UP/DN PICK");
	ld	hl, #___str_14
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x02
	push	de
	call	_text_write
	pop	af
;apps/text_editor.c:297: text_write(3u, 0u, "CENTER EDIT");
	ld	hl, #___str_15
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x03
	push	de
	call	_text_write
	pop	af
;apps/text_editor.c:298: text_write(4u, 0u, "A VIEW B ERASE");
	ld	hl, #___str_16
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x04
	push	de
	call	_text_write
	pop	af
;apps/text_editor.c:299: text_write(6u, 0u, "EDIT ARROWS KEY");
	ld	hl, #___str_17
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x06
	push	de
	call	_text_write
	pop	af
;apps/text_editor.c:300: text_write(7u, 0u, "CENTER TYPE");
	ld	hl, #___str_18
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x07
	push	de
	call	_text_write
	pop	af
;apps/text_editor.c:301: text_write(8u, 0u, "A SAVE B DEL");
	ld	hl, #___str_19
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x08
	push	de
	call	_text_write
	pop	af
;apps/text_editor.c:302: text_write(9u, 0u, "C MENU");
	ld	hl, #___str_20
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x09
	push	de
	call	_text_write
	pop	af
;apps/text_editor.c:303: text_write(11u, 0u, "VIEW < > FILE");
	ld	hl, #___str_21
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0b
	push	de
	call	_text_write
	pop	af
;apps/text_editor.c:304: text_write(12u, 0u, "CENTER EDIT");
	ld	hl, #___str_15
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0c
	push	de
	call	_text_write
	pop	af
;apps/text_editor.c:305: text_write(13u, 0u, "C BACK");
	ld	hl, #___str_22
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0d
	push	de
	call	_text_write
	pop	af
;apps/text_editor.c:306: text_write(15u, 4u, "PRESS C");
	ld	hl, #___str_23
	ex	(sp),hl
	ld	de, #0x040f
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/text_editor.c:308: last_buttons = GLIC_BUTTONS_NONE;
	ld	h, #0xff
;apps/text_editor.c:309: while (1) {
00105$:
;apps/text_editor.c:310: buttons = glic_read_buttons();
	push	hl
	call	_glic_read_buttons
	pop	af
	ld	h, a
;apps/text_editor.c:311: if ((button_edge(buttons, last_buttons, GLIC_BTN_C) != 0u) ||
	push	hl
	ld	a, #0x20
	push	af
	inc	sp
	push	hl
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	hl
	or	a, a
	jp	NZ,_wait_for_release
;apps/text_editor.c:312: (button_edge(buttons, last_buttons, GLIC_BTN_CENTER) != 0u)) {
	push	hl
	ld	a, #0x01
	push	af
	inc	sp
	push	hl
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	hl
	or	a, a
;apps/text_editor.c:313: wait_for_release();
;apps/text_editor.c:314: return;
	jp	NZ,_wait_for_release
;apps/text_editor.c:316: last_buttons = buttons;
	ld	h, l
;apps/text_editor.c:317: glic_delay(LOOP_DELAY);
	push	hl
	ld	de, #0x04b0
	push	de
	call	_glic_delay
	pop	af
	pop	hl
;apps/text_editor.c:319: }
	jr	00105$
___str_13:
	.ascii "TEXT EDITOR"
	.db 0x00
___str_14:
	.ascii "MENU UP/DN PICK"
	.db 0x00
___str_15:
	.ascii "CENTER EDIT"
	.db 0x00
___str_16:
	.ascii "A VIEW B ERASE"
	.db 0x00
___str_17:
	.ascii "EDIT ARROWS KEY"
	.db 0x00
___str_18:
	.ascii "CENTER TYPE"
	.db 0x00
___str_19:
	.ascii "A SAVE B DEL"
	.db 0x00
___str_20:
	.ascii "C MENU"
	.db 0x00
___str_21:
	.ascii "VIEW < > FILE"
	.db 0x00
___str_22:
	.ascii "C BACK"
	.db 0x00
___str_23:
	.ascii "PRESS C"
	.db 0x00
;apps/text_editor.c:321: static unsigned char run_menu(void) {
;	---------------------------------
; Function run_menu
; ---------------------------------
_run_menu:
	dec	sp
;apps/text_editor.c:325: draw_menu();
	call	_draw_menu
;apps/text_editor.c:326: last_buttons = GLIC_BUTTONS_NONE;
	ld	b, #0xff
;apps/text_editor.c:328: while (1) {
00124$:
;apps/text_editor.c:329: buttons = glic_read_buttons();
	push	bc
	call	_glic_read_buttons
	pop	bc
	ld	a, l
	ld	iy, #0
	add	iy, sp
	ld	0 (iy), a
;apps/text_editor.c:330: if (button_edge(buttons, last_buttons, GLIC_BTN_UP) != 0u) {
	push	bc
	ld	a, #0x02
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	a, 0 (iy)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	bc
	or	a, a
	jr	Z, 00121$
;apps/text_editor.c:331: if (selected_file == 0u) {
	ld	iy, #_selected_file
	ld	a, 0 (iy)
	or	a, a
	jr	NZ, 00102$
;apps/text_editor.c:332: selected_file = (unsigned char)(FILE_COUNT - 1u);
	ld	0 (iy), #0x02
	jr	00103$
00102$:
;apps/text_editor.c:334: --selected_file;
	ld	hl, #_selected_file
	dec	(hl)
00103$:
;apps/text_editor.c:336: draw_menu_files();
	call	_draw_menu_files
	jp	00122$
00121$:
;apps/text_editor.c:337: } else if (button_edge(buttons, last_buttons, GLIC_BTN_DOWN) != 0u) {
	push	bc
	ld	a, #0x08
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	hl, #4
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	bc
	or	a, a
	jr	Z, 00118$
;apps/text_editor.c:338: ++selected_file;
	ld	iy, #_selected_file
	inc	0 (iy)
;apps/text_editor.c:339: if (selected_file >= FILE_COUNT) {
	ld	a, 0 (iy)
	sub	a, #0x03
	jr	C, 00105$
;apps/text_editor.c:340: selected_file = 0u;
	ld	0 (iy), #0x00
00105$:
;apps/text_editor.c:342: draw_menu_files();
	call	_draw_menu_files
	jp	00122$
00118$:
;apps/text_editor.c:343: } else if (button_edge(buttons, last_buttons, GLIC_BTN_CENTER) != 0u) {
	push	bc
	ld	a, #0x01
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	hl, #4
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	bc
	or	a, a
	jr	Z, 00115$
;apps/text_editor.c:344: wait_for_release();
	call	_wait_for_release
;apps/text_editor.c:345: return ACTION_EDIT;
	ld	l, #0x01
	jr	00126$
00115$:
;apps/text_editor.c:346: } else if (button_edge(buttons, last_buttons, GLIC_BTN_A) != 0u) {
	push	bc
	ld	a, #0x80
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	hl, #4
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	bc
	or	a, a
	jr	Z, 00112$
;apps/text_editor.c:347: wait_for_release();
	call	_wait_for_release
;apps/text_editor.c:348: return ACTION_VIEW;
	ld	l, #0x02
	jr	00126$
00112$:
;apps/text_editor.c:349: } else if (button_edge(buttons, last_buttons, GLIC_BTN_B) != 0u) {
	push	bc
	ld	a, #0x40
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	hl, #4
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	bc
	or	a, a
	jr	Z, 00109$
;apps/text_editor.c:350: wait_for_release();
	call	_wait_for_release
;apps/text_editor.c:351: confirm_clear();
	call	_confirm_clear
;apps/text_editor.c:352: draw_menu();
	call	_draw_menu
;apps/text_editor.c:353: last_buttons = GLIC_BUTTONS_NONE;
	jr	00122$
00109$:
;apps/text_editor.c:354: } else if (button_edge(buttons, last_buttons, GLIC_BTN_C) != 0u) {
	ld	a, #0x20
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00122$
;apps/text_editor.c:355: wait_for_release();
	call	_wait_for_release
;apps/text_editor.c:356: show_help();
	call	_show_help
;apps/text_editor.c:357: draw_menu();
	call	_draw_menu
;apps/text_editor.c:358: last_buttons = GLIC_BUTTONS_NONE;
00122$:
;apps/text_editor.c:361: last_buttons = buttons;
	ld	hl, #0
	add	hl, sp
	ld	b, (hl)
;apps/text_editor.c:362: glic_delay(LOOP_DELAY);
	push	bc
	ld	hl, #0x04b0
	push	hl
	call	_glic_delay
	pop	af
	pop	bc
	jp	00124$
00126$:
;apps/text_editor.c:364: }
	inc	sp
	ret
;apps/text_editor.c:366: static void draw_keyboard(unsigned char key_row, unsigned char key_col) {
;	---------------------------------
; Function draw_keyboard
; ---------------------------------
_draw_keyboard:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/text_editor.c:371: for (row = 0u; row < KEY_ROWS; ++row) {
	ld	c, #0x00
00108$:
;apps/text_editor.c:372: text_clear_row((unsigned char)(KEY_TOP + row));
	ld	a, c
	add	a, #0x09
	ld	b, a
	push	bc
	push	bc
	inc	sp
	call	_text_clear_row
	inc	sp
	pop	bc
;apps/text_editor.c:373: for (col = 0u; col < KEY_COLS; ++col) {
	ld	a, 4 (ix)
	sub	a, c
	ld	a, #0x01
	jr	Z, 00140$
	xor	a, a
00140$:
	ld	l, a
	ld	e, #0x00
00106$:
;apps/text_editor.c:374: screen_col = (unsigned char)(col << 1);
	ld	a, e
	add	a, a
	ld	d, a
;apps/text_editor.c:377: key_at(row, col));
	push	hl
	push	bc
	push	de
	ld	b, e
	push	bc
	call	_key_at
	pop	af
	ld	a, l
	pop	de
	pop	bc
	push	bc
	push	de
	push	af
	inc	sp
	ld	e, b
	push	de
	call	_text_put
	pop	af
	inc	sp
	pop	de
	pop	bc
	pop	hl
;apps/text_editor.c:378: if ((row == key_row) && (col == key_col)) {
	ld	a, l
	or	a, a
	jr	Z, 00107$
	ld	a, 5 (ix)
	sub	a, e
	jr	NZ, 00107$
;apps/text_editor.c:380: (unsigned char)(screen_col + 1u),
	inc	d
;apps/text_editor.c:379: text_put((unsigned char)(KEY_TOP + row),
	push	hl
	push	bc
	push	de
	ld	a, #0x3c
	push	af
	inc	sp
	ld	e, b
	push	de
	call	_text_put
	pop	af
	inc	sp
	pop	de
	pop	bc
	pop	hl
00107$:
;apps/text_editor.c:373: for (col = 0u; col < KEY_COLS; ++col) {
	inc	e
	ld	a, e
	sub	a, #0x08
	jr	C, 00106$
;apps/text_editor.c:371: for (row = 0u; row < KEY_ROWS; ++row) {
	inc	c
	ld	a, c
	sub	a, #0x05
	jr	C, 00108$
;apps/text_editor.c:385: }
	pop	ix
	ret
;apps/text_editor.c:387: static void draw_editor_header(unsigned char file,
;	---------------------------------
; Function draw_editor_header
; ---------------------------------
_draw_editor_header:
;apps/text_editor.c:393: text_clear_row(0u);
	xor	a, a
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;apps/text_editor.c:394: text_write(0u, 0u, "EDIT FILE ");
	ld	hl, #___str_24
	push	hl
	xor	a, a
	push	af
	inc	sp
	xor	a, a
	push	af
	inc	sp
	call	_text_write
	pop	af
	pop	af
;apps/text_editor.c:395: text_put(0u, 10u, (unsigned char)('1' + file));
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	add	a, #0x31
	ld	d,a
	ld	e,#0x0a
	push	de
	xor	a, a
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
;apps/text_editor.c:396: text_write(0u, 12u, status);
	ld	hl, #5
	add	hl, sp
	ld	c, (hl)
	inc	hl
	ld	b, (hl)
	push	bc
	ld	a, #0x0c
	push	af
	inc	sp
	xor	a, a
	push	af
	inc	sp
	call	_text_write
	pop	af
	pop	af
;apps/text_editor.c:398: len = file_length(file);
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_file_length
	inc	sp
;apps/text_editor.c:399: text_clear_row(8u);
	push	hl
	ld	a, #0x08
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
	pop	hl
;apps/text_editor.c:400: text_write_u8_3(8u, 0u, len);
	ld	a, l
	push	af
	inc	sp
	xor	a, a
	ld	d,a
	ld	e,#0x08
	push	de
	call	_text_write_u8_3
;apps/text_editor.c:401: text_write(8u, 3u, "/192 KEY ");
	inc	sp
	ld	hl,#___str_25
	ex	(sp),hl
	ld	de, #0x0308
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/text_editor.c:402: text_put(8u, 12u, display_key(key_row, key_col));
	ld	iy, #4
	add	iy, sp
	ld	h, 0 (iy)
	ld	l, -1 (iy)
	push	hl
	call	_display_key
	pop	af
	ld	d, l
	ld	e,#0x0c
	push	de
	ld	a, #0x08
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
;apps/text_editor.c:403: }
	ret
___str_24:
	.ascii "EDIT FILE "
	.db 0x00
___str_25:
	.ascii "/192 KEY "
	.db 0x00
;apps/text_editor.c:405: static void draw_editor_text(unsigned char file) {
;	---------------------------------
; Function draw_editor_text
; ---------------------------------
_draw_editor_text:
;apps/text_editor.c:409: edit_window_start(file_length(file)));
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_file_length
	ld	a, l
	inc	sp
	push	af
	inc	sp
	call	_edit_window_start
	ld	a, l
	inc	sp
;apps/text_editor.c:406: draw_text_rows(file,
	ld	d,a
	ld	e,#0x07
	push	de
	ld	a, #0x01
	push	af
	inc	sp
	ld	hl, #5
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_draw_text_rows
	pop	af
	pop	af
;apps/text_editor.c:410: }
	ret
;apps/text_editor.c:412: static void draw_editor(unsigned char file,
;	---------------------------------
; Function draw_editor
; ---------------------------------
_draw_editor:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/text_editor.c:416: glic_prepare_screen(GLIC_BLACK);
	xor	a, a
	push	af
	inc	sp
	call	_glic_prepare_screen
	inc	sp
;apps/text_editor.c:417: draw_editor_header(file, key_row, key_col, status);
	ld	l, 7 (ix)
	ld	h, 8 (ix)
	push	hl
	ld	h, 6 (ix)
	ld	l, 5 (ix)
	push	hl
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_draw_editor_header
	pop	af
	pop	af
	inc	sp
;apps/text_editor.c:418: draw_editor_text(file);
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_draw_editor_text
	inc	sp
;apps/text_editor.c:419: draw_keyboard(key_row, key_col);
	ld	h, 6 (ix)
	ld	l, 5 (ix)
	push	hl
	call	_draw_keyboard
;apps/text_editor.c:420: text_write(14u, 0u, "A SAVE B DEL");
	ld	hl, #___str_26
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0e
	push	de
	call	_text_write
	pop	af
;apps/text_editor.c:421: text_write(15u, 0u, "C MENU CTR TYPE");
	ld	hl, #___str_27
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0f
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/text_editor.c:422: }
	pop	ix
	ret
___str_26:
	.ascii "A SAVE B DEL"
	.db 0x00
___str_27:
	.ascii "C MENU CTR TYPE"
	.db 0x00
;apps/text_editor.c:424: static void insert_char(unsigned char file,
;	---------------------------------
; Function insert_char
; ---------------------------------
_insert_char:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/text_editor.c:430: len = file_length(file);
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_file_length
	inc	sp
	ld	b, l
;apps/text_editor.c:431: if (len >= TEXT_CAPACITY) {
	ld	a, b
	sub	a, #0xc0
;apps/text_editor.c:432: return;
	jr	NC, 00105$
;apps/text_editor.c:435: data = file_data(file);
	push	bc
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_file_data
	inc	sp
	ex	de, hl
	pop	bc
;apps/text_editor.c:436: data[len] = typed_key(key_row, key_col);
	ld	l, b
	ld	h, #0x00
	add	hl, de
	push	hl
	push	bc
	push	de
	ld	h, 6 (ix)
	ld	l, 5 (ix)
	push	hl
	call	_typed_key
	pop	af
	ld	a, l
	pop	de
	pop	bc
	pop	hl
	ld	(hl), a
;apps/text_editor.c:437: ++len;
	inc	b
;apps/text_editor.c:438: set_file_length(file, len);
	push	bc
	push	de
	push	bc
	inc	sp
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_set_file_length
	pop	af
	pop	de
	pop	bc
;apps/text_editor.c:439: if (len < TEXT_CAPACITY) {
	ld	a, b
	sub	a, #0xc0
	jr	NC, 00105$
;apps/text_editor.c:440: data[len] = 0u;
	ld	l, b
	ld	h, #0x00
	add	hl, de
	ld	(hl), #0x00
00105$:
;apps/text_editor.c:442: }
	pop	ix
	ret
;apps/text_editor.c:444: static void delete_char(unsigned char file) {
;	---------------------------------
; Function delete_char
; ---------------------------------
_delete_char:
;apps/text_editor.c:448: len = file_length(file);
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_file_length
	inc	sp
	ld	a, l
;apps/text_editor.c:449: if (len == 0u) {
	or	a, a
;apps/text_editor.c:450: return;
	ret	Z
;apps/text_editor.c:452: --len;
	ld	e, a
	dec	e
;apps/text_editor.c:453: set_file_length(file, len);
	push	de
	ld	a, e
	push	af
	inc	sp
	ld	hl, #5
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_set_file_length
	pop	af
	ld	hl, #4
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_file_data
	inc	sp
	pop	de
;apps/text_editor.c:455: data[len] = 0u;
	ld	d, #0x00
	add	hl, de
	ld	(hl), #0x00
;apps/text_editor.c:456: }
	ret
;apps/text_editor.c:458: static void run_editor(unsigned char file) {
;	---------------------------------
; Function run_editor
; ---------------------------------
_run_editor:
	push	ix
	ld	ix,#0
	add	ix,sp
	push	af
	push	af
	dec	sp
;apps/text_editor.c:465: key_row = 0u;
	ld	-2 (ix), #0
;apps/text_editor.c:466: key_col = 0u;
	ld	-1 (ix), #0
;apps/text_editor.c:467: status = "";
;apps/text_editor.c:468: draw_editor(file, key_row, key_col, status);
	ld	hl, #___str_28
	push	hl
	xor	a, a
	push	af
	inc	sp
	xor	a, a
	push	af
	inc	sp
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_draw_editor
	pop	af
	pop	af
;apps/text_editor.c:469: last_buttons = GLIC_BUTTONS_NONE;
	ld	-5 (ix), #0xff
	inc	sp
;apps/text_editor.c:471: while (1) {
00138$:
;apps/text_editor.c:472: buttons = glic_read_buttons();
	call	_glic_read_buttons
	ld	-4 (ix), l
;apps/text_editor.c:473: if (button_edge(buttons, last_buttons, GLIC_BTN_UP) != 0u) {
	ld	h, #0x02
	ld	l, -5 (ix)
	push	hl
	ld	a, -4 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	-3 (ix), l
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00135$
;apps/text_editor.c:474: if (key_row == 0u) {
	ld	a, -2 (ix)
	or	a, a
	jr	NZ, 00102$
;apps/text_editor.c:475: key_row = (unsigned char)(KEY_ROWS - 1u);
	ld	-2 (ix), #0x04
	jr	00103$
00102$:
;apps/text_editor.c:477: --key_row;
	dec	-2 (ix)
00103$:
;apps/text_editor.c:479: status = "";
;apps/text_editor.c:480: draw_editor(file, key_row, key_col, status);
	ld	hl, #___str_28
	push	hl
	ld	h, -1 (ix)
	ld	l, -2 (ix)
	push	hl
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_draw_editor
	pop	af
	pop	af
	inc	sp
	jp	00136$
00135$:
;apps/text_editor.c:481: } else if (button_edge(buttons, last_buttons, GLIC_BTN_DOWN) != 0u) {
	ld	h, #0x08
	ld	l, -5 (ix)
	push	hl
	ld	a, -4 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00132$
;apps/text_editor.c:482: ++key_row;
	inc	-2 (ix)
;apps/text_editor.c:483: if (key_row >= KEY_ROWS) {
	ld	a, -2 (ix)
	sub	a, #0x05
	jr	C, 00105$
;apps/text_editor.c:484: key_row = 0u;
	ld	-2 (ix), #0
00105$:
;apps/text_editor.c:486: status = "";
;apps/text_editor.c:487: draw_editor(file, key_row, key_col, status);
	ld	hl, #___str_28
	push	hl
	ld	h, -1 (ix)
	ld	l, -2 (ix)
	push	hl
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_draw_editor
	pop	af
	pop	af
	inc	sp
	jp	00136$
00132$:
;apps/text_editor.c:488: } else if (button_edge(buttons, last_buttons, GLIC_BTN_LEFT) != 0u) {
	ld	h, #0x10
	ld	l, -5 (ix)
	push	hl
	ld	a, -4 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00129$
;apps/text_editor.c:489: if (key_col == 0u) {
	ld	a, -1 (ix)
	or	a, a
	jr	NZ, 00107$
;apps/text_editor.c:490: key_col = (unsigned char)(KEY_COLS - 1u);
	ld	-1 (ix), #0x07
	jr	00108$
00107$:
;apps/text_editor.c:492: --key_col;
	dec	-1 (ix)
00108$:
;apps/text_editor.c:494: status = "";
;apps/text_editor.c:495: draw_editor(file, key_row, key_col, status);
	ld	hl, #___str_28
	push	hl
	ld	h, -1 (ix)
	ld	l, -2 (ix)
	push	hl
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_draw_editor
	pop	af
	pop	af
	inc	sp
	jp	00136$
00129$:
;apps/text_editor.c:496: } else if (button_edge(buttons, last_buttons, GLIC_BTN_RIGHT) != 0u) {
	ld	h, #0x04
	ld	l, -5 (ix)
	push	hl
	ld	a, -4 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00126$
;apps/text_editor.c:497: ++key_col;
	inc	-1 (ix)
;apps/text_editor.c:498: if (key_col >= KEY_COLS) {
	ld	a, -1 (ix)
	sub	a, #0x08
	jr	C, 00110$
;apps/text_editor.c:499: key_col = 0u;
	ld	-1 (ix), #0
00110$:
;apps/text_editor.c:501: status = "";
;apps/text_editor.c:502: draw_editor(file, key_row, key_col, status);
	ld	hl, #___str_28
	push	hl
	ld	h, -1 (ix)
	ld	l, -2 (ix)
	push	hl
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_draw_editor
	pop	af
	pop	af
	inc	sp
	jp	00136$
00126$:
;apps/text_editor.c:503: } else if (button_edge(buttons, last_buttons, GLIC_BTN_CENTER) != 0u) {
	ld	h, #0x01
	ld	l, -5 (ix)
	push	hl
	ld	a, -4 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00123$
;apps/text_editor.c:504: if (file_length(file) < TEXT_CAPACITY) {
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_file_length
	ld	a, l
	inc	sp
	sub	a, #0xc0
	jr	NC, 00112$
;apps/text_editor.c:505: insert_char(file, key_row, key_col);
	ld	h, -1 (ix)
	ld	l, -2 (ix)
	push	hl
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_insert_char
	pop	af
	inc	sp
;apps/text_editor.c:506: status = "";
	ld	bc, #___str_28
	jr	00113$
00112$:
;apps/text_editor.c:508: status = "FULL";
	ld	bc, #___str_29
00113$:
;apps/text_editor.c:510: draw_editor(file, key_row, key_col, status);
	push	bc
	ld	h, -1 (ix)
	ld	l, -2 (ix)
	push	hl
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_draw_editor
	pop	af
	pop	af
	inc	sp
	jp	00136$
00123$:
;apps/text_editor.c:511: } else if (button_edge(buttons, last_buttons, GLIC_BTN_B) != 0u) {
	ld	h, #0x40
	ld	l, -5 (ix)
	push	hl
	ld	a, -4 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00120$
;apps/text_editor.c:512: delete_char(file);
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_delete_char
	inc	sp
;apps/text_editor.c:513: status = "";
;apps/text_editor.c:514: draw_editor(file, key_row, key_col, status);
	ld	hl, #___str_28
	push	hl
	ld	h, -1 (ix)
	ld	l, -2 (ix)
	push	hl
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_draw_editor
	pop	af
	pop	af
	inc	sp
	jr	00136$
00120$:
;apps/text_editor.c:515: } else if (button_edge(buttons, last_buttons, GLIC_BTN_A) != 0u) {
	ld	h, #0x80
	ld	l, -5 (ix)
	push	hl
	ld	a, -4 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00117$
;apps/text_editor.c:516: STORAGE_BASE[0] = STORAGE_MAGIC0;
	ld	hl, #0x6000
	ld	(hl), #0x54
;apps/text_editor.c:517: STORAGE_BASE[1] = STORAGE_MAGIC1;
	ld	l, #0x01
	ld	(hl), #0x58
;apps/text_editor.c:518: STORAGE_BASE[2] = STORAGE_MAGIC2;
	ld	l, #0x02
	ld	(hl), #0x54
;apps/text_editor.c:519: STORAGE_BASE[3] = STORAGE_MAGIC3;
	ld	l, #0x03
	ld	(hl), #0x31
;apps/text_editor.c:520: status = "SAV";
;apps/text_editor.c:521: draw_editor(file, key_row, key_col, status);
	ld	hl, #___str_30
	push	hl
	ld	h, -1 (ix)
	ld	l, -2 (ix)
	push	hl
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_draw_editor
	pop	af
	pop	af
	inc	sp
	jr	00136$
00117$:
;apps/text_editor.c:522: } else if (button_edge(buttons, last_buttons, GLIC_BTN_C) != 0u) {
	ld	h, #0x20
	ld	l, -5 (ix)
	push	hl
	ld	a, -4 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00136$
;apps/text_editor.c:523: wait_for_release();
	call	_wait_for_release
;apps/text_editor.c:524: return;
	jr	00140$
00136$:
;apps/text_editor.c:527: last_buttons = buttons;
	ld	a, -4 (ix)
	ld	-5 (ix), a
;apps/text_editor.c:528: glic_delay(LOOP_DELAY);
	ld	hl, #0x04b0
	push	hl
	call	_glic_delay
	pop	af
	jp	00138$
00140$:
;apps/text_editor.c:530: }
	ld	sp, ix
	pop	ix
	ret
___str_28:
	.db 0x00
___str_29:
	.ascii "FULL"
	.db 0x00
___str_30:
	.ascii "SAV"
	.db 0x00
;apps/text_editor.c:532: static void draw_viewer(unsigned char file) {
;	---------------------------------
; Function draw_viewer
; ---------------------------------
_draw_viewer:
	dec	sp
;apps/text_editor.c:535: glic_prepare_screen(GLIC_BLACK);
	xor	a, a
	push	af
	inc	sp
	call	_glic_prepare_screen
	inc	sp
;apps/text_editor.c:536: text_write(0u, 0u, "VIEW FILE ");
	ld	hl, #___str_31
	push	hl
	xor	a, a
	push	af
	inc	sp
	xor	a, a
	push	af
	inc	sp
	call	_text_write
	pop	af
	pop	af
;apps/text_editor.c:537: text_put(0u, 10u, (unsigned char)('1' + file));
	ld	hl, #3
	add	hl, sp
	ld	a, (hl)
	add	a, #0x31
	ld	d,a
	ld	e,#0x0a
	push	de
	xor	a, a
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
;apps/text_editor.c:538: len = file_length(file);
	ld	hl, #3
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_file_length
	ld	c, l
	inc	sp
	ld	iy, #0
	add	iy, sp
	ld	0 (iy), c
;apps/text_editor.c:539: if (len == 0u) {
	ld	a, c
	or	a, a
	jr	NZ, 00102$
;apps/text_editor.c:540: text_write(5u, 5u, "EMPTY");
	ld	hl, #___str_32
	push	hl
	ld	de, #0x0505
	push	de
	call	_text_write
	pop	af
	pop	af
	jr	00103$
00102$:
;apps/text_editor.c:542: draw_text_rows(file, 1u, 12u, 0u);
	xor	a, a
	ld	d,a
	ld	e,#0x0c
	push	de
	ld	a, #0x01
	push	af
	inc	sp
	ld	hl, #6
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_draw_text_rows
	pop	af
	pop	af
00103$:
;apps/text_editor.c:544: text_write(13u, 0u, "LEN ");
	ld	hl, #___str_33
	push	hl
	xor	a, a
	ld	d,a
	ld	e,#0x0d
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/text_editor.c:545: text_write_u8_3(13u, 4u, len);
	ld	hl, #0
	add	hl, sp
	ld	d, (hl)
	ld	e,#0x04
	push	de
	ld	a, #0x0d
	push	af
	inc	sp
	call	_text_write_u8_3
;apps/text_editor.c:546: text_write(14u, 0u, "CENTER EDIT");
	inc	sp
	ld	hl,#___str_34
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0e
	push	de
	call	_text_write
	pop	af
;apps/text_editor.c:547: text_write(15u, 0u, "C MENU  < > FILE");
	ld	hl, #___str_35
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0f
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/text_editor.c:548: }
	inc	sp
	ret
___str_31:
	.ascii "VIEW FILE "
	.db 0x00
___str_32:
	.ascii "EMPTY"
	.db 0x00
___str_33:
	.ascii "LEN "
	.db 0x00
___str_34:
	.ascii "CENTER EDIT"
	.db 0x00
___str_35:
	.ascii "C MENU  < > FILE"
	.db 0x00
;apps/text_editor.c:550: static void run_viewer(void) {
;	---------------------------------
; Function run_viewer
; ---------------------------------
_run_viewer:
;apps/text_editor.c:554: draw_viewer(selected_file);
	ld	a,(#_selected_file + 0)
	push	af
	inc	sp
	call	_draw_viewer
	inc	sp
;apps/text_editor.c:555: last_buttons = GLIC_BUTTONS_NONE;
	ld	c, #0xff
;apps/text_editor.c:557: while (1) {
00119$:
;apps/text_editor.c:558: buttons = glic_read_buttons();
	push	bc
	call	_glic_read_buttons
	ld	a, l
	pop	bc
	ld	b, a
;apps/text_editor.c:559: if (button_edge(buttons, last_buttons, GLIC_BTN_LEFT) != 0u) {
	push	bc
	ld	a, #0x10
	push	af
	inc	sp
	ld	a, c
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	bc
	or	a, a
	jr	Z, 00116$
;apps/text_editor.c:560: if (selected_file == 0u) {
	ld	iy, #_selected_file
	ld	a, 0 (iy)
	or	a, a
	jr	NZ, 00102$
;apps/text_editor.c:561: selected_file = (unsigned char)(FILE_COUNT - 1u);
	ld	0 (iy), #0x02
	jr	00103$
00102$:
;apps/text_editor.c:563: --selected_file;
	ld	hl, #_selected_file
	dec	(hl)
00103$:
;apps/text_editor.c:565: draw_viewer(selected_file);
	push	bc
	ld	a,(#_selected_file + 0)
	push	af
	inc	sp
	call	_draw_viewer
	inc	sp
	pop	bc
	jp	00117$
00116$:
;apps/text_editor.c:566: } else if (button_edge(buttons, last_buttons, GLIC_BTN_RIGHT) != 0u) {
	push	bc
	ld	a, #0x04
	push	af
	inc	sp
	ld	a, c
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	bc
	or	a, a
	jr	Z, 00113$
;apps/text_editor.c:567: ++selected_file;
	ld	iy, #_selected_file
	inc	0 (iy)
;apps/text_editor.c:568: if (selected_file >= FILE_COUNT) {
	ld	a, 0 (iy)
	sub	a, #0x03
	jr	C, 00105$
;apps/text_editor.c:569: selected_file = 0u;
	ld	0 (iy), #0x00
00105$:
;apps/text_editor.c:571: draw_viewer(selected_file);
	push	bc
	ld	a,(#_selected_file + 0)
	push	af
	inc	sp
	call	_draw_viewer
	inc	sp
	pop	bc
	jr	00117$
00113$:
;apps/text_editor.c:572: } else if (button_edge(buttons, last_buttons, GLIC_BTN_CENTER) != 0u) {
	push	bc
	ld	a, #0x01
	push	af
	inc	sp
	ld	a, c
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	bc
	or	a, a
	jr	Z, 00110$
;apps/text_editor.c:573: wait_for_release();
	push	bc
	call	_wait_for_release
	ld	a,(#_selected_file + 0)
	push	af
	inc	sp
	call	_run_editor
	inc	sp
	ld	a,(#_selected_file + 0)
	push	af
	inc	sp
	call	_draw_viewer
	inc	sp
	pop	bc
;apps/text_editor.c:576: last_buttons = GLIC_BUTTONS_NONE;
	jr	00117$
00110$:
;apps/text_editor.c:577: } else if ((button_edge(buttons, last_buttons, GLIC_BTN_C) != 0u) ||
	push	bc
	ld	a, #0x20
	push	af
	inc	sp
	ld	a, c
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_button_edge
	pop	af
	inc	sp
	ld	a, l
	pop	bc
	or	a, a
	jp	NZ,_wait_for_release
;apps/text_editor.c:578: (button_edge(buttons, last_buttons, GLIC_BTN_B) != 0u)) {
	push	bc
	ld	a, #0x40
	push	af
	inc	sp
	ld	a, c
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_button_edge
	pop	af
	inc	sp
	ld	a, l
	pop	bc
	or	a, a
;apps/text_editor.c:579: wait_for_release();
;apps/text_editor.c:580: return;
	jp	NZ,_wait_for_release
00117$:
;apps/text_editor.c:583: last_buttons = buttons;
	ld	c, b
;apps/text_editor.c:584: glic_delay(LOOP_DELAY);
	push	bc
	ld	hl, #0x04b0
	push	hl
	call	_glic_delay
	pop	af
	pop	bc
;apps/text_editor.c:586: }
	jp	00119$
;apps/text_editor.c:588: void main(void) {
;	---------------------------------
; Function main
; ---------------------------------
_main::
;apps/text_editor.c:591: selected_file = 0u;
	ld	hl, #_selected_file
	ld	(hl), #0x00
;apps/text_editor.c:592: storage_init();
	call	_storage_init
;apps/text_editor.c:594: while (1) {
00107$:
;apps/text_editor.c:595: action = run_menu();
	call	_run_menu
	ld	a, l
;apps/text_editor.c:596: if (action == ACTION_EDIT) {
	cp	a, #0x01
	jr	NZ, 00104$
;apps/text_editor.c:597: run_editor(selected_file);
	ld	a,(#_selected_file + 0)
	push	af
	inc	sp
	call	_run_editor
	inc	sp
	jr	00107$
00104$:
;apps/text_editor.c:598: } else if (action == ACTION_VIEW) {
	sub	a, #0x02
	jr	NZ, 00107$
;apps/text_editor.c:599: run_viewer();
	call	_run_viewer
;apps/text_editor.c:602: }
	jr	00107$
	.area _CODE
	.area _INITIALIZER
	.area _CABS (ABS)
