; generated by sdcc-z80-bin
    JR __sdcc_z80_bin_start
    DB "z80_emulator",0
__sdcc_z80_bin_start:
    LD SP,#0x7700
    CALL _main
__sdcc_z80_bin_halt:
    JR __sdcc_z80_bin_halt

;--------------------------------------------------------
; File Created by SDCC : free open source ANSI-C Compiler
; Version 4.1.0 #12072 (Linux)
;--------------------------------------------------------
	.module z80_emulator
	.optsdcc -mz80
	
;--------------------------------------------------------
; Public variables in this module
;--------------------------------------------------------
	.globl _main
;--------------------------------------------------------
; special function registers
;--------------------------------------------------------
;--------------------------------------------------------
; ram data
;--------------------------------------------------------
	.area _DATA
_cpu:
	.ds 19
_emu_ram:
	.ds 1792
;--------------------------------------------------------
; ram data
;--------------------------------------------------------
	.area _INITIALIZED
;--------------------------------------------------------
; absolute external ram data
;--------------------------------------------------------
	.area _DABS (ABS)
;--------------------------------------------------------
; global & static initialisations
;--------------------------------------------------------
	.area _HOME
	.area _GSINIT
	.area _GSFINAL
	.area _GSINIT
;--------------------------------------------------------
; Home
;--------------------------------------------------------
	.area _HOME
	.area _HOME
;--------------------------------------------------------
; code
;--------------------------------------------------------
	.area _CODE
;apps/../common/glic80.h:29: static unsigned char glic_read_buttons(void) __naked {
;	---------------------------------
; Function glic_read_buttons
; ---------------------------------
_glic_read_buttons:
;apps/../common/glic80.h:34: __endasm;
	in	a,(0)
	ld	l,a
	ret
;apps/../common/glic80.h:35: }
;apps/../common/glic80.h:37: static unsigned char glic_button_pressed(unsigned char buttons,
;	---------------------------------
; Function glic_button_pressed
; ---------------------------------
_glic_button_pressed:
;apps/../common/glic80.h:39: return (buttons & mask) == 0u;
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	inc	iy
	and	a, 0 (iy)
	or	a, a
	ld	a, #0x01
	jr	Z, 00104$
	xor	a, a
00104$:
	ld	l, a
;apps/../common/glic80.h:40: }
	ret
_glic_bit_masks:
	.db #0x01	; 1
	.db #0x02	; 2
	.db #0x04	; 4
	.db #0x08	; 8
	.db #0x10	; 16
	.db #0x20	; 32
	.db #0x40	; 64
	.db #0x80	; 128
;apps/../common/glic80.h:42: static void glic_delay(unsigned int count) {
;	---------------------------------
; Function glic_delay
; ---------------------------------
_glic_delay:
;apps/../common/glic80.h:43: while (count != 0u) {
	pop	de
	pop	bc
	push	bc
	push	de
00101$:
	ld	a, b
	or	a, c
	ret	Z
;apps/../common/glic80.h:44: --count;
	dec	bc
;apps/../common/glic80.h:47: __endasm;
	nop
;apps/../common/glic80.h:49: }
	jr	00101$
;apps/../common/glic80.h:51: static void glic_clear_text(void) {
;	---------------------------------
; Function glic_clear_text
; ---------------------------------
_glic_clear_text:
;apps/../common/glic80.h:54: for (i = 0; i < GLIC_CVRAM_BYTES; ++i) {
	ld	bc, #0x0000
00102$:
;apps/../common/glic80.h:55: GLIC_CVRAM[i] = 0x00u;
	ld	hl, #0x7700
	add	hl, bc
	ld	(hl), #0x00
;apps/../common/glic80.h:54: for (i = 0; i < GLIC_CVRAM_BYTES; ++i) {
	inc	bc
	ld	a, b
	sub	a, #0x01
	jr	C, 00102$
;apps/../common/glic80.h:57: }
	ret
;apps/../common/glic80.h:59: static void glic_fill_graphics(unsigned char value) {
;	---------------------------------
; Function glic_fill_graphics
; ---------------------------------
_glic_fill_graphics:
;apps/../common/glic80.h:62: for (i = 0; i < GLIC_GVRAM_BYTES; ++i) {
	ld	bc, #0x0000
00102$:
;apps/../common/glic80.h:63: GLIC_GVRAM[i] = value;
	ld	hl, #0x7800
	add	hl, bc
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	ld	(hl), a
;apps/../common/glic80.h:62: for (i = 0; i < GLIC_GVRAM_BYTES; ++i) {
	inc	bc
	ld	a, b
	sub	a, #0x08
	jr	C, 00102$
;apps/../common/glic80.h:65: }
	ret
;apps/../common/glic80.h:67: static void glic_plot(unsigned char x, unsigned char y, unsigned char value) {
;	---------------------------------
; Function glic_plot
; ---------------------------------
_glic_plot:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/../common/glic80.h:71: if ((x >= GLIC_SCREEN_WIDTH) || (y >= 128u)) {
	ld	a, 4 (ix)
	sub	a, #0x80
	jr	NC, 00107$
	ld	a, 5 (ix)
	sub	a, #0x80
;apps/../common/glic80.h:72: return;
	jr	NC, 00107$
;apps/../common/glic80.h:75: offset = (((unsigned int)(y >> 3)) << 7) + x;
	ld	a, 5 (ix)
	rrca
	rrca
	rrca
	and	a, #0x1f
	ld	l, a
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	ld	c, 4 (ix)
	ld	b, #0x00
	add	hl, bc
	ex	de, hl
;apps/../common/glic80.h:76: mask = glic_bit_masks[y & 7u];
	ld	bc, #_glic_bit_masks+0
	ld	a, 5 (ix)
	and	a, #0x07
	ld	l, a
	ld	h, #0x00
	add	hl, bc
	ld	b, (hl)
;apps/../common/glic80.h:78: GLIC_GVRAM[offset] |= mask;
	ld	hl, #0x7800
	add	hl, de
	ld	c, (hl)
;apps/../common/glic80.h:77: if (value != 0u) {
	ld	a, 6 (ix)
	or	a, a
	jr	Z, 00105$
;apps/../common/glic80.h:78: GLIC_GVRAM[offset] |= mask;
	ld	a, c
	or	a, b
	ld	(hl), a
	jr	00107$
00105$:
;apps/../common/glic80.h:80: GLIC_GVRAM[offset] &= (unsigned char)~mask;
	ld	a, b
	cpl
	and	a, c
	ld	(hl), a
00107$:
;apps/../common/glic80.h:82: }
	pop	ix
	ret
;apps/../common/glic80.h:84: static void glic_draw_bitmap8(unsigned char x,
;	---------------------------------
; Function glic_draw_bitmap8
; ---------------------------------
_glic_draw_bitmap8:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/../common/glic80.h:92: for (row = 0u; row < 8u; ++row) {
	ld	c, #0x00
00107$:
;apps/../common/glic80.h:93: bits = rows[row];
	ld	l, 6 (ix)
	ld	h, 7 (ix)
	ld	b, #0x00
	add	hl, bc
	ld	l, (hl)
;apps/../common/glic80.h:94: mask = 0x80u;
	ld	e, #0x80
;apps/../common/glic80.h:95: for (col = 0u; col < 8u; ++col) {
	ld	a, 5 (ix)
	add	a, c
	ld	b, a
	ld	d, #0x00
00105$:
;apps/../common/glic80.h:96: if ((bits & mask) != 0u) {
	ld	a, l
	and	a,e
	jr	Z, 00102$
;apps/../common/glic80.h:97: glic_plot((unsigned char)(x + col), (unsigned char)(y + row), 1u);
	ld	a, 4 (ix)
	add	a, d
	push	hl
	push	bc
	push	de
	ld	h, #0x01
	ld	l, b
	push	hl
	push	af
	inc	sp
	call	_glic_plot
	pop	af
	inc	sp
	pop	de
	pop	bc
	pop	hl
00102$:
;apps/../common/glic80.h:99: mask >>= 1;
	srl	e
;apps/../common/glic80.h:95: for (col = 0u; col < 8u; ++col) {
	inc	d
	ld	a, d
	sub	a, #0x08
	jr	C, 00105$
;apps/../common/glic80.h:92: for (row = 0u; row < 8u; ++row) {
	inc	c
	ld	a, c
	sub	a, #0x08
	jr	C, 00107$
;apps/../common/glic80.h:102: }
	pop	ix
	ret
;apps/../common/glic80.h:104: static void glic_draw_tile8(unsigned char cell_x,
;	---------------------------------
; Function glic_draw_tile8
; ---------------------------------
_glic_draw_tile8:
	push	ix
	ld	ix,#0
	add	ix,sp
	push	af
;apps/../common/glic80.h:110: offset = (((unsigned int)cell_y) << 7) + (((unsigned int)cell_x) << 3);
	ld	c, 5 (ix)
	xor	a, a
	rr	a
	ld	b, c
	rr	b
	rra
	ld	c, a
	ld	l, 4 (ix)
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, bc
	ex	de, hl
;apps/../common/glic80.h:111: for (col = 0u; col < 8u; ++col) {
	ld	c, #0x00
00102$:
;apps/../common/glic80.h:112: GLIC_GVRAM[offset + col] = columns[col];
	ld	l, c
	ld	h, #0x00
	add	hl, de
	ld	-2 (ix), l
	ld	a, h
	add	a, #0x78
	ld	-1 (ix), a
	ld	l, 6 (ix)
	ld	h, 7 (ix)
	ld	b, #0x00
	add	hl, bc
	ld	a, (hl)
	pop	hl
	push	hl
	ld	(hl), a
;apps/../common/glic80.h:111: for (col = 0u; col < 8u; ++col) {
	inc	c
	ld	a, c
	sub	a, #0x08
	jr	C, 00102$
;apps/../common/glic80.h:114: }
	ld	sp, ix
	pop	ix
	ret
;apps/../common/glic80.h:116: static void glic_prepare_screen(unsigned char value) {
;	---------------------------------
; Function glic_prepare_screen
; ---------------------------------
_glic_prepare_screen:
;apps/../common/glic80.h:117: glic_clear_text();
	call	_glic_clear_text
;apps/../common/glic80.h:118: glic_fill_graphics(value);
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_glic_fill_graphics
	inc	sp
;apps/../common/glic80.h:119: }
	ret
;apps/../common/glic80.h:121: static void glic_fill_page_run(unsigned char page,
;	---------------------------------
; Function glic_fill_page_run
; ---------------------------------
_glic_fill_page_run:
;apps/../common/glic80.h:127: p = GLIC_GVRAM + (((unsigned int)page) << 7) + x;
	ld	iy, #2
	add	iy, sp
	ld	c, 0 (iy)
	ld	b, #0x00
	xor	a, a
	rr	b
	ld	b, c
	rr	b
	rra
	ld	c, a
	ld	a, b
	add	a, #0x78
	ld	b, a
	ld	a, c
	ld	hl, #3
	add	hl, sp
	add	a, (hl)
	ld	c, a
	jr	NC, 00117$
	inc	b
00117$:
;apps/../common/glic80.h:128: while (width != 0u) {
	ld	e, 2 (iy)
00101$:
	ld	a, e
	or	a, a
	ret	Z
;apps/../common/glic80.h:129: *p++ = value;
	ld	iy, #5
	add	iy, sp
	ld	a, 0 (iy)
	ld	(bc), a
	inc	bc
;apps/../common/glic80.h:130: --width;
	dec	e
;apps/../common/glic80.h:132: }
	jr	00101$
;apps/../common/glic80.h:134: static void glic_fill_pages(unsigned char first_page,
;	---------------------------------
; Function glic_fill_pages
; ---------------------------------
_glic_fill_pages:
;apps/../common/glic80.h:137: while (page_count != 0u) {
	ld	iy, #2
	add	iy, sp
	ld	b, 0 (iy)
	ld	c, 1 (iy)
00101$:
	ld	a, c
	or	a, a
	ret	Z
;apps/../common/glic80.h:138: glic_fill_page_run(first_page, 0u, GLIC_SCREEN_WIDTH, value);
	push	bc
	ld	hl, #6
	add	hl, sp
	ld	d, (hl)
	ld	e,#0x80
	push	de
	xor	a, a
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_fill_page_run
	pop	af
	pop	af
	pop	bc
;apps/../common/glic80.h:139: ++first_page;
	inc	b
;apps/../common/glic80.h:140: --page_count;
	dec	c
;apps/../common/glic80.h:142: }
	jr	00101$
;apps/../common/glic80.h:144: static void glic_fill_columns(unsigned char x,
;	---------------------------------
; Function glic_fill_columns
; ---------------------------------
_glic_fill_columns:
;apps/../common/glic80.h:149: for (page = 0u; page < GLIC_SCREEN_PAGES; ++page) {
	ld	b, #0x00
00102$:
;apps/../common/glic80.h:150: glic_fill_page_run(page, x, width, value);
	push	bc
	ld	iy, #6
	add	iy, sp
	ld	a, 0 (iy)
	push	af
	inc	sp
	ld	a, -1 (iy)
	dec	iy
	push	af
	inc	sp
	ld	a, -1 (iy)
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_fill_page_run
	pop	af
	pop	af
	pop	bc
;apps/../common/glic80.h:149: for (page = 0u; page < GLIC_SCREEN_PAGES; ++page) {
	inc	b
	ld	a, b
	sub	a, #0x10
	jr	C, 00102$
;apps/../common/glic80.h:152: }
	ret
;apps/z80_emulator.c:53: static volatile unsigned char *text_cell(unsigned char row,
;	---------------------------------
; Function text_cell
; ---------------------------------
_text_cell:
;apps/z80_emulator.c:58: while (row != 0u) {
	ld	bc, #0x7700
	ld	iy, #2
	add	iy, sp
	ld	l, 0 (iy)
00101$:
	ld	a, l
	or	a, a
	jr	Z, 00103$
;apps/z80_emulator.c:59: p += 16u;
	ld	a, c
	add	a, #0x10
	ld	c, a
	jr	NC, 00117$
	inc	b
00117$:
;apps/z80_emulator.c:60: --row;
	dec	l
	jr	00101$
00103$:
;apps/z80_emulator.c:62: p += col;
	ld	a, c
	ld	hl, #3
	add	hl, sp
	add	a, (hl)
	ld	l, a
	jr	NC, 00118$
	inc	b
00118$:
	ld	h, b
;apps/z80_emulator.c:63: return p;
;apps/z80_emulator.c:64: }
	ret
_guest_japan_program:
	.db #0x31	; 49	'1'
	.db #0x00	; 0
	.db #0x77	; 119	'w'
	.db #0x21	; 33
	.db #0x00	; 0
	.db #0x77	; 119	'w'
	.db #0x01	; 1
	.db #0x00	; 0
	.db #0x01	; 1
	.db #0xaf	; 175
	.db #0x77	; 119	'w'
	.db #0x23	; 35
	.db #0x0b	; 11
	.db #0x78	; 120	'x'
	.db #0xb1	; 177
	.db #0x20	; 32
	.db #0xf9	; 249
	.db #0x21	; 33
	.db #0x00	; 0
	.db #0x78	; 120	'x'
	.db #0x01	; 1
	.db #0x00	; 0
	.db #0x08	; 8
	.db #0x3e	; 62
	.db #0xff	; 255
	.db #0x77	; 119	'w'
	.db #0x23	; 35
	.db #0x0b	; 11
	.db #0x78	; 120	'x'
	.db #0xb1	; 177
	.db #0x20	; 32
	.db #0xf9	; 249
	.db #0xaf	; 175
	.db #0x21	; 33
	.db #0x38	; 56	'8'
	.db #0x7a	; 122	'z'
	.db #0x06	; 6
	.db #0x10	; 16
	.db #0x77	; 119	'w'
	.db #0x23	; 35
	.db #0x10	; 16
	.db #0xfc	; 252
	.db #0x21	; 33
	.db #0xb0	; 176
	.db #0x7a	; 122	'z'
	.db #0x06	; 6
	.db #0x20	; 32
	.db #0x77	; 119	'w'
	.db #0x23	; 35
	.db #0x10	; 16
	.db #0xfc	; 252
	.db #0x21	; 33
	.db #0x2a	; 42
	.db #0x7b	; 123
	.db #0x06	; 6
	.db #0x2c	; 44
	.db #0x77	; 119	'w'
	.db #0x23	; 35
	.db #0x10	; 16
	.db #0xfc	; 252
	.db #0x21	; 33
	.db #0x9e	; 158
	.db #0x7b	; 123
	.db #0x06	; 6
	.db #0x34	; 52	'4'
	.db #0x77	; 119	'w'
	.db #0x23	; 35
	.db #0x10	; 16
	.db #0xfc	; 252
	.db #0x21	; 33
	.db #0x26	; 38
	.db #0x7c	; 124
	.db #0x06	; 6
	.db #0x34	; 52	'4'
	.db #0x77	; 119	'w'
	.db #0x23	; 35
	.db #0x10	; 16
	.db #0xfc	; 252
	.db #0x21	; 33
	.db #0xaa	; 170
	.db #0x7c	; 124
	.db #0x06	; 6
	.db #0x2c	; 44
	.db #0x77	; 119	'w'
	.db #0x23	; 35
	.db #0x10	; 16
	.db #0xfc	; 252
	.db #0x21	; 33
	.db #0x30	; 48	'0'
	.db #0x7d	; 125
	.db #0x06	; 6
	.db #0x20	; 32
	.db #0x77	; 119	'w'
	.db #0x23	; 35
	.db #0x10	; 16
	.db #0xfc	; 252
	.db #0x21	; 33
	.db #0xb8	; 184
	.db #0x7d	; 125
	.db #0x06	; 6
	.db #0x10	; 16
	.db #0x77	; 119	'w'
	.db #0x23	; 35
	.db #0x10	; 16
	.db #0xfc	; 252
	.db #0x76	; 118	'v'
;apps/z80_emulator.c:66: static void text_put(unsigned char row, unsigned char col, unsigned char ch) {
;	---------------------------------
; Function text_put
; ---------------------------------
_text_put:
;apps/z80_emulator.c:67: if ((row >= 16u) || (col >= 16u)) {
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	sub	a, #0x10
	ret	NC
	ld	a, 1 (iy)
	sub	a, #0x10
;apps/z80_emulator.c:68: return;
	ret	NC
;apps/z80_emulator.c:70: *text_cell(row, col) = ch;
	ld	iy, #3
	add	iy, sp
	ld	h, 0 (iy)
	ld	l, -1 (iy)
	push	hl
	call	_text_cell
	pop	af
	ld	iy, #4
	add	iy, sp
	ld	a, 0 (iy)
	ld	(hl), a
;apps/z80_emulator.c:71: }
	ret
;apps/z80_emulator.c:73: static void text_clear_row(unsigned char row) {
;	---------------------------------
; Function text_clear_row
; ---------------------------------
_text_clear_row:
;apps/z80_emulator.c:76: for (col = 0u; col < 16u; ++col) {
	ld	b, #0x00
00102$:
;apps/z80_emulator.c:77: text_put(row, col, 0u);
	push	bc
	xor	a, a
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	hl, #6
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
	pop	bc
;apps/z80_emulator.c:76: for (col = 0u; col < 16u; ++col) {
	inc	b
	ld	a, b
	sub	a, #0x10
	jr	C, 00102$
;apps/z80_emulator.c:79: }
	ret
;apps/z80_emulator.c:81: static void text_write(unsigned char row, unsigned char col, const char *text) {
;	---------------------------------
; Function text_write
; ---------------------------------
_text_write:
;apps/z80_emulator.c:82: while ((*text != 0) && (col < 16u)) {
	ld	iy, #4
	add	iy, sp
	ld	l, 0 (iy)
	ld	h, 1 (iy)
	ld	b, -1 (iy)
00102$:
	ld	d, (hl)
	ld	a, d
	or	a, a
	ret	Z
	ld	a, b
	sub	a, #0x10
	ret	NC
;apps/z80_emulator.c:83: text_put(row, col, (unsigned char)*text);
	push	hl
	push	bc
	ld	e, b
	push	de
	ld	hl, #8
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
	pop	bc
	pop	hl
;apps/z80_emulator.c:84: ++text;
	inc	hl
;apps/z80_emulator.c:85: ++col;
	inc	b
;apps/z80_emulator.c:87: }
	jr	00102$
;apps/z80_emulator.c:89: static unsigned char hex_digit(unsigned char value) {
;	---------------------------------
; Function hex_digit
; ---------------------------------
_hex_digit:
;apps/z80_emulator.c:90: value &= 0x0fu;
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	and	a, #0x0f
;apps/z80_emulator.c:92: return (unsigned char)('0' + value);
	ld	0 (iy), a
	ld	c, a
;apps/z80_emulator.c:91: if (value < 10u) {
	ld	a, 0 (iy)
	sub	a, #0x0a
	jr	NC, 00102$
;apps/z80_emulator.c:92: return (unsigned char)('0' + value);
	ld	a, c
	add	a, #0x30
	ld	l, a
	ret
00102$:
;apps/z80_emulator.c:94: return (unsigned char)('A' + (value - 10u));
	ld	a, c
	add	a, #0x37
	ld	l, a
;apps/z80_emulator.c:95: }
	ret
;apps/z80_emulator.c:97: static void text_write_hex8(unsigned char row,
;	---------------------------------
; Function text_write_hex8
; ---------------------------------
_text_write_hex8:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/z80_emulator.c:100: text_put(row, col, hex_digit((unsigned char)(value >> 4)));
	ld	a, 6 (ix)
	rlca
	rlca
	rlca
	rlca
	and	a, #0x0f
	push	af
	inc	sp
	call	_hex_digit
	inc	sp
	ld	h, l
	ld	l, 5 (ix)
	push	hl
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
;apps/z80_emulator.c:101: text_put(row, (unsigned char)(col + 1u), hex_digit(value));
	ld	a, 6 (ix)
	push	af
	inc	sp
	call	_hex_digit
	ld	a, l
	inc	sp
	ld	b, 5 (ix)
	inc	b
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
;apps/z80_emulator.c:102: }
	pop	ix
	ret
;apps/z80_emulator.c:104: static void text_write_hex16(unsigned char row,
;	---------------------------------
; Function text_write_hex16
; ---------------------------------
_text_write_hex16:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/z80_emulator.c:107: text_write_hex8(row, col, (unsigned char)(value >> 8));
	ld	b, 7 (ix)
	push	bc
	inc	sp
	ld	h, 5 (ix)
	ld	l, 4 (ix)
	push	hl
	call	_text_write_hex8
	pop	af
	inc	sp
;apps/z80_emulator.c:108: text_write_hex8(row, (unsigned char)(col + 2u), (unsigned char)value);
	ld	a, 6 (ix)
	ld	b, 5 (ix)
	inc	b
	inc	b
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_text_write_hex8
	pop	af
	inc	sp
;apps/z80_emulator.c:109: }
	pop	ix
	ret
;apps/z80_emulator.c:111: static unsigned char button_edge(unsigned char buttons,
;	---------------------------------
; Function button_edge
; ---------------------------------
_button_edge:
;apps/z80_emulator.c:114: return (((last_buttons & mask) != 0u) && ((buttons & mask) == 0u));
	ld	iy, #3
	add	iy, sp
	ld	a, 0 (iy)
	inc	iy
	and	a, 0 (iy)
	or	a, a
	jr	Z, 00103$
	ld	a, -2 (iy)
	and	a, 0 (iy)
	or	a, a
	jr	Z, 00104$
00103$:
	ld	l, #0x00
	ret
00104$:
	ld	l, #0x01
;apps/z80_emulator.c:115: }
	ret
;apps/z80_emulator.c:117: static void wait_for_release(void) {
;	---------------------------------
; Function wait_for_release
; ---------------------------------
_wait_for_release:
;apps/z80_emulator.c:118: while (glic_read_buttons() != GLIC_BUTTONS_NONE) {
00101$:
	call	_glic_read_buttons
	inc	l
	ret	Z
;apps/z80_emulator.c:119: glic_delay(500u);
	ld	hl, #0x01f4
	push	hl
	call	_glic_delay
	pop	af
;apps/z80_emulator.c:121: }
	jr	00101$
;apps/z80_emulator.c:123: static unsigned int make16(unsigned char lo, unsigned char hi) {
;	---------------------------------
; Function make16
; ---------------------------------
_make16:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/z80_emulator.c:124: return (unsigned int)(lo | (((unsigned int)hi) << 8));
	ld	c, 5 (ix)
	ld	a, #0x00
	ld	e, 4 (ix)
	ld	d, #0x00
	or	a, e
	ld	l, a
	ld	a, c
	or	a, d
	ld	h, a
;apps/z80_emulator.c:125: }
	pop	ix
	ret
;apps/z80_emulator.c:127: static unsigned char hi8(unsigned int value) {
;	---------------------------------
; Function hi8
; ---------------------------------
_hi8:
;apps/z80_emulator.c:128: return (unsigned char)(value >> 8);
	ld	iy, #2
	add	iy, sp
	ld	l, 1 (iy)
;apps/z80_emulator.c:129: }
	ret
;apps/z80_emulator.c:131: static unsigned char lo8(unsigned int value) {
;	---------------------------------
; Function lo8
; ---------------------------------
_lo8:
;apps/z80_emulator.c:132: return (unsigned char)value;
	ld	iy, #2
	add	iy, sp
	ld	l, 0 (iy)
;apps/z80_emulator.c:133: }
	ret
;apps/z80_emulator.c:135: static unsigned int get_bc(void) {
;	---------------------------------
; Function get_bc
; ---------------------------------
_get_bc:
;apps/z80_emulator.c:136: return make16(cpu.c, cpu.b);
	ld	hl, #_cpu + 1
	ld	b, (hl)
	ld	a, (#_cpu + 2)
	push	bc
	inc	sp
	push	af
	inc	sp
	call	_make16
	pop	af
;apps/z80_emulator.c:137: }
	ret
;apps/z80_emulator.c:139: static unsigned int get_de(void) {
;	---------------------------------
; Function get_de
; ---------------------------------
_get_de:
;apps/z80_emulator.c:140: return make16(cpu.e, cpu.d);
	ld	hl, #_cpu + 3
	ld	b, (hl)
	ld	a, (#_cpu + 4)
	push	bc
	inc	sp
	push	af
	inc	sp
	call	_make16
	pop	af
;apps/z80_emulator.c:141: }
	ret
;apps/z80_emulator.c:143: static unsigned int get_hl(void) {
;	---------------------------------
; Function get_hl
; ---------------------------------
_get_hl:
;apps/z80_emulator.c:144: return make16(cpu.l, cpu.h);
	ld	hl, #_cpu + 5
	ld	b, (hl)
	ld	a, (#_cpu + 6)
	push	bc
	inc	sp
	push	af
	inc	sp
	call	_make16
	pop	af
;apps/z80_emulator.c:145: }
	ret
;apps/z80_emulator.c:147: static unsigned int get_af(void) {
;	---------------------------------
; Function get_af
; ---------------------------------
_get_af:
;apps/z80_emulator.c:148: return make16(cpu.f, cpu.a);
	ld	hl, #_cpu+0
	ld	b, (hl)
	ld	a, (#(_cpu + 0x0007) + 0)
	push	bc
	inc	sp
	push	af
	inc	sp
	call	_make16
	pop	af
;apps/z80_emulator.c:149: }
	ret
;apps/z80_emulator.c:151: static void set_bc(unsigned int value) {
;	---------------------------------
; Function set_bc
; ---------------------------------
_set_bc:
;apps/z80_emulator.c:152: cpu.b = hi8(value);
	pop	bc
	pop	hl
	push	hl
	push	bc
	push	hl
	call	_hi8
	pop	af
	ld	a, l
	ld	(#(_cpu + 0x0001)),a
;apps/z80_emulator.c:153: cpu.c = lo8(value);
	pop	bc
	pop	hl
	push	hl
	push	bc
	push	hl
	call	_lo8
	pop	af
	ld	a, l
	ld	hl, #(_cpu + 0x0002)
	ld	(hl), a
;apps/z80_emulator.c:154: }
	ret
;apps/z80_emulator.c:156: static void set_de(unsigned int value) {
;	---------------------------------
; Function set_de
; ---------------------------------
_set_de:
;apps/z80_emulator.c:157: cpu.d = hi8(value);
	pop	bc
	pop	hl
	push	hl
	push	bc
	push	hl
	call	_hi8
	pop	af
	ld	a, l
	ld	(#(_cpu + 0x0003)),a
;apps/z80_emulator.c:158: cpu.e = lo8(value);
	pop	bc
	pop	hl
	push	hl
	push	bc
	push	hl
	call	_lo8
	pop	af
	ld	a, l
	ld	hl, #(_cpu + 0x0004)
	ld	(hl), a
;apps/z80_emulator.c:159: }
	ret
;apps/z80_emulator.c:161: static void set_hl(unsigned int value) {
;	---------------------------------
; Function set_hl
; ---------------------------------
_set_hl:
;apps/z80_emulator.c:162: cpu.h = hi8(value);
	pop	bc
	pop	hl
	push	hl
	push	bc
	push	hl
	call	_hi8
	pop	af
	ld	a, l
	ld	(#(_cpu + 0x0005)),a
;apps/z80_emulator.c:163: cpu.l = lo8(value);
	pop	bc
	pop	hl
	push	hl
	push	bc
	push	hl
	call	_lo8
	pop	af
	ld	a, l
	ld	hl, #(_cpu + 0x0006)
	ld	(hl), a
;apps/z80_emulator.c:164: }
	ret
;apps/z80_emulator.c:166: static void set_af(unsigned int value) {
;	---------------------------------
; Function set_af
; ---------------------------------
_set_af:
;apps/z80_emulator.c:167: cpu.a = hi8(value);
	pop	bc
	pop	hl
	push	hl
	push	bc
	push	hl
	call	_hi8
	pop	af
	ld	a, l
	ld	(#_cpu),a
;apps/z80_emulator.c:168: cpu.f = lo8(value);
	pop	bc
	pop	hl
	push	hl
	push	bc
	push	hl
	call	_lo8
	pop	af
	ld	a, l
	ld	hl, #(_cpu + 0x0007)
	ld	(hl), a
;apps/z80_emulator.c:169: }
	ret
;apps/z80_emulator.c:171: static unsigned char memory_read(unsigned int address) {
;	---------------------------------
; Function memory_read
; ---------------------------------
_memory_read:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/z80_emulator.c:172: if (address < (unsigned int)sizeof(guest_japan_program)) {
	ld	a, 4 (ix)
	sub	a, #0x6a
	ld	a, 5 (ix)
	sbc	a, #0x00
	jr	NC, 00102$
;apps/z80_emulator.c:173: return guest_japan_program[address];
	ld	bc, #_guest_japan_program+0
	ld	l, 4 (ix)
	ld	h, 5 (ix)
	add	hl, bc
	ld	l, (hl)
	jr	00112$
00102$:
;apps/z80_emulator.c:176: (address < (unsigned int)(EMU_RAM_BASE + EMU_RAM_SIZE))) {
	ld	a, 5 (ix)
	sub	a, #0x77
	ld	a, #0x00
	rla
	ld	c, a
;apps/z80_emulator.c:175: if ((address >= EMU_RAM_BASE) &&
	ld	a, 5 (ix)
	sub	a, #0x70
	jr	C, 00104$
;apps/z80_emulator.c:176: (address < (unsigned int)(EMU_RAM_BASE + EMU_RAM_SIZE))) {
	ld	a, c
	or	a, a
	jr	Z, 00104$
;apps/z80_emulator.c:177: return emu_ram[address - EMU_RAM_BASE];
	ld	bc, #_emu_ram+0
	ld	a, 4 (ix)
	add	a, #0x00
	ld	l, a
	ld	a, 5 (ix)
	adc	a, #0x90
	ld	h, a
	add	hl, bc
	ld	l, (hl)
	jr	00112$
00104$:
;apps/z80_emulator.c:179: if ((address >= 0x7700u) && (address < 0x7800u)) {
	ld	a, 5 (ix)
	sub	a, #0x78
	ld	a, #0x00
	rla
	bit	0, c
	jr	NZ, 00107$
	or	a, a
	jr	Z, 00107$
;apps/z80_emulator.c:180: return GLIC_CVRAM[address - 0x7700u];
	ld	a, 4 (ix)
	add	a, #0x00
	ld	c, a
	ld	a, 5 (ix)
	adc	a, #0x89
	ld	b, a
	ld	hl, #0x7700
	add	hl, bc
	ld	l, (hl)
	jr	00112$
00107$:
;apps/z80_emulator.c:182: if ((address >= 0x7800u) && (address < 0x8000u)) {
	bit	0,a
	jr	NZ, 00110$
	ld	a, 5 (ix)
	sub	a, #0x80
	jr	NC, 00110$
;apps/z80_emulator.c:183: return GLIC_GVRAM[address - 0x7800u];
	ld	a, 4 (ix)
	add	a, #0x00
	ld	c, a
	ld	a, 5 (ix)
	adc	a, #0x88
	ld	b, a
	ld	hl, #0x7800
	add	hl, bc
	ld	l, (hl)
	jr	00112$
00110$:
;apps/z80_emulator.c:185: return 0u;
	ld	l, #0x00
00112$:
;apps/z80_emulator.c:186: }
	pop	ix
	ret
;apps/z80_emulator.c:188: static void memory_write(unsigned int address, unsigned char value) {
;	---------------------------------
; Function memory_write
; ---------------------------------
_memory_write:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/z80_emulator.c:190: (address < (unsigned int)(EMU_RAM_BASE + EMU_RAM_SIZE))) {
	ld	a, 5 (ix)
	sub	a, #0x77
	ld	a, #0x00
	rla
	ld	c, a
;apps/z80_emulator.c:189: if ((address >= EMU_RAM_BASE) &&
	ld	a, 5 (ix)
	sub	a, #0x70
	jr	C, 00109$
;apps/z80_emulator.c:190: (address < (unsigned int)(EMU_RAM_BASE + EMU_RAM_SIZE))) {
	ld	a, c
	or	a, a
	jr	Z, 00109$
;apps/z80_emulator.c:191: emu_ram[address - EMU_RAM_BASE] = value;
	ld	bc, #_emu_ram+0
	ld	a, 4 (ix)
	add	a, #0x00
	ld	l, a
	ld	a, 5 (ix)
	adc	a, #0x90
	ld	h, a
	add	hl, bc
	ld	a, 6 (ix)
	ld	(hl), a
	jr	00112$
00109$:
;apps/z80_emulator.c:192: } else if ((address >= 0x7700u) && (address < 0x7800u)) {
	ld	a, 5 (ix)
	sub	a, #0x78
	ld	a, #0x00
	rla
	bit	0, c
	jr	NZ, 00105$
	or	a, a
	jr	Z, 00105$
;apps/z80_emulator.c:193: GLIC_CVRAM[address - 0x7700u] = value;
	ld	a, 4 (ix)
	add	a, #0x00
	ld	l, a
	ld	a, 5 (ix)
	adc	a, #0x89
	add	a, #0x77
	ld	h, a
	ld	a, 6 (ix)
	ld	(hl), a
	jr	00112$
00105$:
;apps/z80_emulator.c:194: } else if ((address >= 0x7800u) && (address < 0x8000u)) {
	bit	0,a
	jr	NZ, 00112$
	ld	a, 5 (ix)
	sub	a, #0x80
	jr	NC, 00112$
;apps/z80_emulator.c:195: GLIC_GVRAM[address - 0x7800u] = value;
	ld	a, 4 (ix)
	add	a, #0x00
	ld	l, a
	ld	a, 5 (ix)
	adc	a, #0x88
	add	a, #0x78
	ld	h, a
	ld	a, 6 (ix)
	ld	(hl), a
00112$:
;apps/z80_emulator.c:197: }
	pop	ix
	ret
;apps/z80_emulator.c:199: static unsigned char fetch8(void) {
;	---------------------------------
; Function fetch8
; ---------------------------------
_fetch8:
;apps/z80_emulator.c:202: value = memory_read(cpu.pc);
	ld	hl, (#(_cpu + 0x0008) + 0)
	push	hl
	call	_memory_read
	pop	af
	ld	c, l
;apps/z80_emulator.c:203: cpu.pc = (unsigned int)(cpu.pc + 1u);
	ld	de, (#(_cpu + 0x0008) + 0)
	inc	de
	ld	((_cpu + 0x0008)), de
;apps/z80_emulator.c:204: return value;
	ld	l, c
;apps/z80_emulator.c:205: }
	ret
;apps/z80_emulator.c:207: static unsigned int fetch16(void) {
;	---------------------------------
; Function fetch16
; ---------------------------------
_fetch16:
;apps/z80_emulator.c:211: lo = fetch8();
	call	_fetch8
;apps/z80_emulator.c:212: hi = fetch8();
	push	hl
	call	_fetch8
	ld	a, l
	pop	hl
;apps/z80_emulator.c:213: return make16(lo, hi);
	push	af
	ld	a, l
	inc	sp
	push	af
	inc	sp
	call	_make16
	pop	af
;apps/z80_emulator.c:214: }
	ret
;apps/z80_emulator.c:216: static unsigned int add_signed8(unsigned int value, unsigned char offset) {
;	---------------------------------
; Function add_signed8
; ---------------------------------
_add_signed8:
;apps/z80_emulator.c:218: return (unsigned int)(value + offset);
	ld	iy, #4
	add	iy, sp
	ld	c, 0 (iy)
	ld	b, #0x00
;apps/z80_emulator.c:217: if (offset < 0x80u) {
	ld	a, 0 (iy)
	sub	a, #0x80
	jr	NC, 00102$
;apps/z80_emulator.c:218: return (unsigned int)(value + offset);
	ld	l, -2 (iy)
	ld	h, -1 (iy)
	add	hl, bc
	ret
00102$:
;apps/z80_emulator.c:220: return (unsigned int)(value - (unsigned int)(0x100u - offset));
	xor	a, a
	sub	a, c
	ld	c, a
	ld	a, #0x01
	sbc	a, b
	ld	b, a
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	sub	a, c
	ld	e, a
	ld	a, 1 (iy)
	sbc	a, b
	ld	d, a
	ex	de, hl
;apps/z80_emulator.c:221: }
	ret
;apps/z80_emulator.c:223: static void push16(unsigned int value) {
;	---------------------------------
; Function push16
; ---------------------------------
_push16:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/z80_emulator.c:224: cpu.sp = (unsigned int)(cpu.sp - 1u);
	ld	bc, (#(_cpu + 0x000a) + 0)
	dec	bc
	ld	((_cpu + 0x000a)), bc
;apps/z80_emulator.c:225: memory_write(cpu.sp, hi8(value));
	ld	l, 4 (ix)
	ld	h, 5 (ix)
	push	hl
	call	_hi8
	pop	af
	ld	b, l
	ld	hl, (#(_cpu + 0x000a) + 0)
	push	bc
	inc	sp
	push	hl
	call	_memory_write
	pop	af
	inc	sp
;apps/z80_emulator.c:226: cpu.sp = (unsigned int)(cpu.sp - 1u);
	ld	bc, (#(_cpu + 0x000a) + 0)
	dec	bc
	ld	((_cpu + 0x000a)), bc
;apps/z80_emulator.c:227: memory_write(cpu.sp, lo8(value));
	ld	l, 4 (ix)
	ld	h, 5 (ix)
	push	hl
	call	_lo8
	pop	af
	ld	b, l
	ld	hl, (#(_cpu + 0x000a) + 0)
	push	bc
	inc	sp
	push	hl
	call	_memory_write
	pop	af
	inc	sp
;apps/z80_emulator.c:228: }
	pop	ix
	ret
;apps/z80_emulator.c:230: static unsigned int pop16(void) {
;	---------------------------------
; Function pop16
; ---------------------------------
_pop16:
	push	ix
	ld	ix,#0
	add	ix,sp
	dec	sp
;apps/z80_emulator.c:234: lo = memory_read(cpu.sp);
	ld	hl, (#(_cpu + 0x000a) + 0)
	push	hl
	call	_memory_read
	pop	af
	ld	-1 (ix), l
;apps/z80_emulator.c:235: cpu.sp = (unsigned int)(cpu.sp + 1u);
	ld	bc, (#(_cpu + 0x000a) + 0)
	inc	bc
	ld	((_cpu + 0x000a)), bc
;apps/z80_emulator.c:236: hi = memory_read(cpu.sp);
	push	bc
	call	_memory_read
	pop	af
	ld	a, l
	ld	b, a
;apps/z80_emulator.c:237: cpu.sp = (unsigned int)(cpu.sp + 1u);
	ld	de, (#(_cpu + 0x000a) + 0)
	inc	de
	ld	((_cpu + 0x000a)), de
;apps/z80_emulator.c:238: return make16(lo, hi);
	push	bc
	inc	sp
	ld	a, -1 (ix)
	push	af
	inc	sp
	call	_make16
	pop	af
;apps/z80_emulator.c:239: }
	inc	sp
	pop	ix
	ret
;apps/z80_emulator.c:241: static void set_sz_flags(unsigned char value, unsigned char carry) {
;	---------------------------------
; Function set_sz_flags
; ---------------------------------
_set_sz_flags:
;apps/z80_emulator.c:242: cpu.f = carry;
	ld	bc, #_cpu+7
	ld	iy, #3
	add	iy, sp
	ld	a, 0 (iy)
	ld	(bc), a
;apps/z80_emulator.c:243: if (value == 0u) {
	ld	a, -1 (iy)
	or	a, a
	jr	NZ, 00102$
;apps/z80_emulator.c:244: cpu.f |= FLAG_Z;
	ld	a, (bc)
	set	6, a
	ld	(bc), a
00102$:
;apps/z80_emulator.c:246: if ((value & 0x80u) != 0u) {
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	rlca
	ret	NC
;apps/z80_emulator.c:247: cpu.f |= FLAG_S;
	ld	a, (bc)
	set	7, a
	ld	(bc), a
;apps/z80_emulator.c:249: }
	ret
;apps/z80_emulator.c:251: static unsigned char register_read(unsigned char code) {
;	---------------------------------
; Function register_read
; ---------------------------------
_register_read:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/z80_emulator.c:252: if (code == 0u) {
	ld	a, 4 (ix)
	or	a, a
	jr	NZ, 00102$
;apps/z80_emulator.c:253: return cpu.b;
	ld	hl, #_cpu+1
	ld	l, (hl)
	jr	00115$
00102$:
;apps/z80_emulator.c:255: if (code == 1u) {
	ld	a, 4 (ix)
	dec	a
	jr	NZ, 00104$
;apps/z80_emulator.c:256: return cpu.c;
	ld	a, (#(_cpu + 0x0002) + 0)
	ld	l, a
	jr	00115$
00104$:
;apps/z80_emulator.c:258: if (code == 2u) {
	ld	a, 4 (ix)
	sub	a, #0x02
	jr	NZ, 00106$
;apps/z80_emulator.c:259: return cpu.d;
	ld	a, (#(_cpu + 0x0003) + 0)
	ld	l, a
	jr	00115$
00106$:
;apps/z80_emulator.c:261: if (code == 3u) {
	ld	a, 4 (ix)
	sub	a, #0x03
	jr	NZ, 00108$
;apps/z80_emulator.c:262: return cpu.e;
	ld	a, (#(_cpu + 0x0004) + 0)
	ld	l, a
	jr	00115$
00108$:
;apps/z80_emulator.c:264: if (code == 4u) {
	ld	a, 4 (ix)
	sub	a, #0x04
	jr	NZ, 00110$
;apps/z80_emulator.c:265: return cpu.h;
	ld	a, (#(_cpu + 0x0005) + 0)
	ld	l, a
	jr	00115$
00110$:
;apps/z80_emulator.c:267: if (code == 5u) {
	ld	a, 4 (ix)
	sub	a, #0x05
	jr	NZ, 00112$
;apps/z80_emulator.c:268: return cpu.l;
	ld	a, (#(_cpu + 0x0006) + 0)
	ld	l, a
	jr	00115$
00112$:
;apps/z80_emulator.c:270: if (code == 6u) {
	ld	a, 4 (ix)
	sub	a, #0x06
	jr	NZ, 00114$
;apps/z80_emulator.c:271: return memory_read(get_hl());
	call	_get_hl
	push	hl
	call	_memory_read
	pop	af
	jr	00115$
00114$:
;apps/z80_emulator.c:273: return cpu.a;
	ld	a, (#_cpu + 0)
	ld	l, a
00115$:
;apps/z80_emulator.c:274: }
	pop	ix
	ret
;apps/z80_emulator.c:276: static void register_write(unsigned char code, unsigned char value) {
;	---------------------------------
; Function register_write
; ---------------------------------
_register_write:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/z80_emulator.c:277: if (code == 0u) {
	ld	a, 4 (ix)
	or	a, a
	jr	NZ, 00120$
;apps/z80_emulator.c:278: cpu.b = value;
	ld	hl, #(_cpu + 0x0001)
	ld	a, 5 (ix)
	ld	(hl), a
	jr	00122$
00120$:
;apps/z80_emulator.c:279: } else if (code == 1u) {
	ld	a, 4 (ix)
	dec	a
	jr	NZ, 00117$
;apps/z80_emulator.c:280: cpu.c = value;
	ld	hl, #(_cpu + 0x0002)
	ld	a, 5 (ix)
	ld	(hl), a
	jr	00122$
00117$:
;apps/z80_emulator.c:281: } else if (code == 2u) {
	ld	a, 4 (ix)
	sub	a, #0x02
	jr	NZ, 00114$
;apps/z80_emulator.c:282: cpu.d = value;
	ld	hl, #(_cpu + 0x0003)
	ld	a, 5 (ix)
	ld	(hl), a
	jr	00122$
00114$:
;apps/z80_emulator.c:283: } else if (code == 3u) {
	ld	a, 4 (ix)
	sub	a, #0x03
	jr	NZ, 00111$
;apps/z80_emulator.c:284: cpu.e = value;
	ld	hl, #(_cpu + 0x0004)
	ld	a, 5 (ix)
	ld	(hl), a
	jr	00122$
00111$:
;apps/z80_emulator.c:285: } else if (code == 4u) {
	ld	a, 4 (ix)
	sub	a, #0x04
	jr	NZ, 00108$
;apps/z80_emulator.c:286: cpu.h = value;
	ld	hl, #(_cpu + 0x0005)
	ld	a, 5 (ix)
	ld	(hl), a
	jr	00122$
00108$:
;apps/z80_emulator.c:287: } else if (code == 5u) {
	ld	a, 4 (ix)
	sub	a, #0x05
	jr	NZ, 00105$
;apps/z80_emulator.c:288: cpu.l = value;
	ld	hl, #(_cpu + 0x0006)
	ld	a, 5 (ix)
	ld	(hl), a
	jr	00122$
00105$:
;apps/z80_emulator.c:289: } else if (code == 6u) {
	ld	a, 4 (ix)
	sub	a, #0x06
	jr	NZ, 00102$
;apps/z80_emulator.c:290: memory_write(get_hl(), value);
	call	_get_hl
	ld	a, 5 (ix)
	push	af
	inc	sp
	push	hl
	call	_memory_write
	pop	af
	inc	sp
	jr	00122$
00102$:
;apps/z80_emulator.c:292: cpu.a = value;
	ld	hl, #_cpu
	ld	a, 5 (ix)
	ld	(hl), a
00122$:
;apps/z80_emulator.c:294: }
	pop	ix
	ret
;apps/z80_emulator.c:296: static unsigned int pair_read(unsigned char code) {
;	---------------------------------
; Function pair_read
; ---------------------------------
_pair_read:
;apps/z80_emulator.c:297: if (code == 0u) {
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	or	a, a
;apps/z80_emulator.c:298: return get_bc();
	jp	Z,_get_bc
;apps/z80_emulator.c:300: if (code == 1u) {
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	dec	a
	jp	Z,_get_de
;apps/z80_emulator.c:301: return get_de();
	jr	00104$
00104$:
;apps/z80_emulator.c:303: if (code == 2u) {
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	sub	a, #0x02
	jp	Z,_get_hl
;apps/z80_emulator.c:304: return get_hl();
	jr	00106$
00106$:
;apps/z80_emulator.c:306: return cpu.sp;
	ld	hl, (#(_cpu + 0x000a) + 0)
;apps/z80_emulator.c:307: }
	ret
;apps/z80_emulator.c:309: static void pair_write(unsigned char code, unsigned int value) {
;	---------------------------------
; Function pair_write
; ---------------------------------
_pair_write:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/z80_emulator.c:310: if (code == 0u) {
	ld	a, 4 (ix)
	or	a, a
	jr	NZ, 00108$
;apps/z80_emulator.c:311: set_bc(value);
	ld	l, 5 (ix)
	ld	h, 6 (ix)
	push	hl
	call	_set_bc
	pop	af
	jr	00110$
00108$:
;apps/z80_emulator.c:312: } else if (code == 1u) {
	ld	a, 4 (ix)
	dec	a
	jr	NZ, 00105$
;apps/z80_emulator.c:313: set_de(value);
	ld	l, 5 (ix)
	ld	h, 6 (ix)
	push	hl
	call	_set_de
	pop	af
	jr	00110$
00105$:
;apps/z80_emulator.c:314: } else if (code == 2u) {
	ld	a, 4 (ix)
	sub	a, #0x02
	jr	NZ, 00102$
;apps/z80_emulator.c:315: set_hl(value);
	ld	l, 5 (ix)
	ld	h, 6 (ix)
	push	hl
	call	_set_hl
	pop	af
	jr	00110$
00102$:
;apps/z80_emulator.c:317: cpu.sp = value;
	ld	hl, #(_cpu + 0x000a)
	ld	a, 5 (ix)
	ld	(hl), a
	inc	hl
	ld	a, 6 (ix)
	ld	(hl), a
00110$:
;apps/z80_emulator.c:319: }
	pop	ix
	ret
;apps/z80_emulator.c:321: static unsigned int stack_pair_read(unsigned char code) {
;	---------------------------------
; Function stack_pair_read
; ---------------------------------
_stack_pair_read:
;apps/z80_emulator.c:322: if (code == 0u) {
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	or	a, a
;apps/z80_emulator.c:323: return get_bc();
	jp	Z,_get_bc
;apps/z80_emulator.c:325: if (code == 1u) {
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	dec	a
	jp	Z,_get_de
;apps/z80_emulator.c:326: return get_de();
	jr	00104$
00104$:
;apps/z80_emulator.c:328: if (code == 2u) {
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	sub	a, #0x02
	jp	Z,_get_hl
;apps/z80_emulator.c:329: return get_hl();
;apps/z80_emulator.c:331: return get_af();
;apps/z80_emulator.c:332: }
	jp	_get_af
;apps/z80_emulator.c:334: static void stack_pair_write(unsigned char code, unsigned int value) {
;	---------------------------------
; Function stack_pair_write
; ---------------------------------
_stack_pair_write:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/z80_emulator.c:335: if (code == 0u) {
	ld	a, 4 (ix)
	or	a, a
	jr	NZ, 00108$
;apps/z80_emulator.c:336: set_bc(value);
	ld	l, 5 (ix)
	ld	h, 6 (ix)
	push	hl
	call	_set_bc
	pop	af
	jr	00110$
00108$:
;apps/z80_emulator.c:337: } else if (code == 1u) {
	ld	a, 4 (ix)
	dec	a
	jr	NZ, 00105$
;apps/z80_emulator.c:338: set_de(value);
	ld	l, 5 (ix)
	ld	h, 6 (ix)
	push	hl
	call	_set_de
	pop	af
	jr	00110$
00105$:
;apps/z80_emulator.c:339: } else if (code == 2u) {
	ld	a, 4 (ix)
	sub	a, #0x02
	jr	NZ, 00102$
;apps/z80_emulator.c:340: set_hl(value);
	ld	l, 5 (ix)
	ld	h, 6 (ix)
	push	hl
	call	_set_hl
	pop	af
	jr	00110$
00102$:
;apps/z80_emulator.c:342: set_af(value);
	ld	l, 5 (ix)
	ld	h, 6 (ix)
	push	hl
	call	_set_af
	pop	af
00110$:
;apps/z80_emulator.c:344: }
	pop	ix
	ret
;apps/z80_emulator.c:346: static unsigned char condition_true(unsigned char condition) {
;	---------------------------------
; Function condition_true
; ---------------------------------
_condition_true:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/z80_emulator.c:347: if (condition == 0u) {
	ld	a, 4 (ix)
	or	a, a
	jr	NZ, 00102$
;apps/z80_emulator.c:348: return (cpu.f & FLAG_Z) == 0u;
	ld	a, (#(_cpu + 0x0007) + 0)
	and	a, #0x40
	ld	e, #0x00
	or	a, a
	or	a, e
	ld	a, #0x01
	jr	Z, 00153$
	xor	a, a
00153$:
	ld	l, a
	jp	00115$
00102$:
;apps/z80_emulator.c:350: if (condition == 1u) {
	ld	a, 4 (ix)
	dec	a
	jr	NZ, 00104$
;apps/z80_emulator.c:351: return (cpu.f & FLAG_Z) != 0u;
	ld	a, (#(_cpu + 0x0007) + 0)
	and	a, #0x40
	or	a,#0x00
	sub	a,#0x01
	ld	a, #0x00
	rla
	xor	a, #0x01
	ld	l, a
	jp	00115$
00104$:
;apps/z80_emulator.c:353: if (condition == 2u) {
	ld	a, 4 (ix)
	sub	a, #0x02
	jr	NZ, 00106$
;apps/z80_emulator.c:354: return (cpu.f & FLAG_C) == 0u;
	ld	a, (#(_cpu + 0x0007) + 0)
	and	a, #0x01
	ld	e, #0x00
	or	a, a
	or	a, e
	ld	a, #0x01
	jr	Z, 00159$
	xor	a, a
00159$:
	ld	l, a
	jr	00115$
00106$:
;apps/z80_emulator.c:356: if (condition == 3u) {
	ld	a, 4 (ix)
	sub	a, #0x03
	jr	NZ, 00108$
;apps/z80_emulator.c:357: return (cpu.f & FLAG_C) != 0u;
	ld	a, (#(_cpu + 0x0007) + 0)
	and	a, #0x01
	or	a,#0x00
	sub	a,#0x01
	ld	a, #0x00
	rla
	xor	a, #0x01
	ld	l, a
	jr	00115$
00108$:
;apps/z80_emulator.c:359: if (condition == 4u) {
	ld	a, 4 (ix)
	sub	a, #0x04
	jr	NZ, 00110$
;apps/z80_emulator.c:360: return (cpu.f & FLAG_PV) == 0u;
	ld	a, (#(_cpu + 0x0007) + 0)
	and	a, #0x04
	ld	e, #0x00
	or	a, a
	or	a, e
	ld	a, #0x01
	jr	Z, 00165$
	xor	a, a
00165$:
	ld	l, a
	jr	00115$
00110$:
;apps/z80_emulator.c:362: if (condition == 5u) {
	ld	a, 4 (ix)
	sub	a, #0x05
	jr	NZ, 00112$
;apps/z80_emulator.c:363: return (cpu.f & FLAG_PV) != 0u;
	ld	a, (#(_cpu + 0x0007) + 0)
	and	a, #0x04
	or	a,#0x00
	sub	a,#0x01
	ld	a, #0x00
	rla
	xor	a, #0x01
	ld	l, a
	jr	00115$
00112$:
;apps/z80_emulator.c:365: if (condition == 6u) {
	ld	a, 4 (ix)
	sub	a, #0x06
	jr	NZ, 00114$
;apps/z80_emulator.c:366: return (cpu.f & FLAG_S) == 0u;
	ld	a, (#(_cpu + 0x0007) + 0)
	and	a, #0x80
	ld	e, #0x00
	or	a, a
	or	a, e
	ld	a, #0x01
	jr	Z, 00171$
	xor	a, a
00171$:
	ld	l, a
	jr	00115$
00114$:
;apps/z80_emulator.c:368: return (cpu.f & FLAG_S) != 0u;
	ld	a, (#(_cpu + 0x0007) + 0)
	and	a, #0x80
	or	a,#0x00
	sub	a,#0x01
	ld	a, #0x00
	rla
	xor	a, #0x01
	ld	l, a
00115$:
;apps/z80_emulator.c:369: }
	pop	ix
	ret
;apps/z80_emulator.c:371: static void trap(unsigned char opcode, unsigned int pc) {
;	---------------------------------
; Function trap
; ---------------------------------
_trap:
;apps/z80_emulator.c:372: cpu.halted = 1u;
	ld	hl, #(_cpu + 0x0010)
	ld	(hl), #0x01
;apps/z80_emulator.c:373: cpu.trap_opcode = opcode;
	ld	hl, #(_cpu + 0x0011)
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	ld	(hl), a
;apps/z80_emulator.c:374: cpu.trap_pc = pc;
	ld	hl, #(_cpu + 0x000e)
	ld	a, 1 (iy)
	inc	iy
	ld	(hl), a
	inc	hl
	ld	a, 1 (iy)
	ld	(hl), a
;apps/z80_emulator.c:375: }
	ret
;apps/z80_emulator.c:377: static void alu_add(unsigned char value) {
;	---------------------------------
; Function alu_add
; ---------------------------------
_alu_add:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/z80_emulator.c:380: result = (unsigned int)(cpu.a + value);
	ld	bc, #_cpu+0
	ld	a, (bc)
	ld	e, a
	ld	d, #0x00
	ld	l, 4 (ix)
	ld	h, #0x00
	add	hl, de
	ex	de, hl
;apps/z80_emulator.c:381: cpu.a = (unsigned char)result;
	ld	a, e
	ld	(bc), a
;apps/z80_emulator.c:382: set_sz_flags(cpu.a, (result > 0xffu) ? FLAG_C : 0u);
	ld	a, #0xff
	cp	a, e
	ld	a, #0x00
	sbc	a, d
	jr	NC, 00103$
	ld	de, #0x0001
	jr	00104$
00103$:
	ld	de, #0x0000
00104$:
	ld	a, (bc)
	ld	h, e
	push	hl
	inc	sp
	push	af
	inc	sp
	call	_set_sz_flags
	pop	af
;apps/z80_emulator.c:383: }
	pop	ix
	ret
;apps/z80_emulator.c:385: static void alu_sub(unsigned char value) {
;	---------------------------------
; Function alu_sub
; ---------------------------------
_alu_sub:
	push	ix
	ld	ix,#0
	add	ix,sp
;apps/z80_emulator.c:388: carry = (cpu.a < value) ? FLAG_C : 0u;
	ld	hl, #_cpu+0
	ld	c, (hl)
	ld	a, c
	sub	a, 4 (ix)
	jr	NC, 00103$
	ld	de, #0x0001
	jr	00104$
00103$:
	ld	de, #0x0000
00104$:
;apps/z80_emulator.c:389: cpu.a = (unsigned char)(cpu.a - value);
	ld	a, c
	sub	a, 4 (ix)
	ld	(hl), a
;apps/z80_emulator.c:390: set_sz_flags(cpu.a, carry);
	ld	h, e
	push	hl
	inc	sp
	push	af
	inc	sp
	call	_set_sz_flags
	pop	af
;apps/z80_emulator.c:391: }
	pop	ix
	ret
;apps/z80_emulator.c:393: static void alu_and(unsigned char value) {
;	---------------------------------
; Function alu_and
; ---------------------------------
_alu_and:
;apps/z80_emulator.c:394: cpu.a = (unsigned char)(cpu.a & value);
	ld	bc, #_cpu+0
	ld	a, (bc)
	ld	iy, #2
	add	iy, sp
	and	a, 0 (iy)
	ld	(bc), a
;apps/z80_emulator.c:395: set_sz_flags(cpu.a, 0u);
	ld	h, #0x00
	push	hl
	inc	sp
	push	af
	inc	sp
	call	_set_sz_flags
	pop	af
;apps/z80_emulator.c:396: }
	ret
;apps/z80_emulator.c:398: static void alu_xor(unsigned char value) {
;	---------------------------------
; Function alu_xor
; ---------------------------------
_alu_xor:
;apps/z80_emulator.c:399: cpu.a = (unsigned char)(cpu.a ^ value);
	ld	bc, #_cpu+0
	ld	a, (bc)
	ld	iy, #2
	add	iy, sp
	xor	a, 0 (iy)
	ld	(bc), a
;apps/z80_emulator.c:400: set_sz_flags(cpu.a, 0u);
	ld	h, #0x00
	push	hl
	inc	sp
	push	af
	inc	sp
	call	_set_sz_flags
	pop	af
;apps/z80_emulator.c:401: }
	ret
;apps/z80_emulator.c:403: static void alu_or(unsigned char value) {
;	---------------------------------
; Function alu_or
; ---------------------------------
_alu_or:
;apps/z80_emulator.c:404: cpu.a = (unsigned char)(cpu.a | value);
	ld	bc, #_cpu+0
	ld	a, (bc)
	ld	iy, #2
	add	iy, sp
	or	a, 0 (iy)
	ld	(bc), a
;apps/z80_emulator.c:405: set_sz_flags(cpu.a, 0u);
	ld	h, #0x00
	push	hl
	inc	sp
	push	af
	inc	sp
	call	_set_sz_flags
	pop	af
;apps/z80_emulator.c:406: }
	ret
;apps/z80_emulator.c:408: static void alu_cp(unsigned char value) {
;	---------------------------------
; Function alu_cp
; ---------------------------------
_alu_cp:
;apps/z80_emulator.c:412: result = (unsigned char)(cpu.a - value);
	ld	hl, #_cpu+0
	ld	c, (hl)
	ld	hl, #2
	add	hl, sp
	ld	a, c
	sub	a, (hl)
	ld	b, a
;apps/z80_emulator.c:413: carry = (cpu.a < value) ? FLAG_C : 0u;
	ld	hl, #2
	add	hl, sp
	ld	a, c
	sub	a, (hl)
	jr	NC, 00103$
	ld	de, #0x0001
	jr	00104$
00103$:
	ld	de, #0x0000
00104$:
	ld	a, e
;apps/z80_emulator.c:414: set_sz_flags(result, carry);
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_set_sz_flags
	pop	af
;apps/z80_emulator.c:415: }
	ret
;apps/z80_emulator.c:417: static void inc_register(unsigned char code) {
;	---------------------------------
; Function inc_register
; ---------------------------------
_inc_register:
;apps/z80_emulator.c:421: value = (unsigned char)(register_read(code) + 1u);
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_register_read
	ld	b, l
	inc	sp
	inc	b
;apps/z80_emulator.c:422: register_write(code, value);
	push	bc
	push	bc
	inc	sp
	ld	hl, #5
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_register_write
	pop	af
	pop	bc
;apps/z80_emulator.c:423: carry = (unsigned char)(cpu.f & FLAG_C);
	ld	a, (#(_cpu + 0x0007) + 0)
	and	a, #0x01
;apps/z80_emulator.c:424: set_sz_flags(value, carry);
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_set_sz_flags
	pop	af
;apps/z80_emulator.c:425: }
	ret
;apps/z80_emulator.c:427: static void dec_register(unsigned char code) {
;	---------------------------------
; Function dec_register
; ---------------------------------
_dec_register:
;apps/z80_emulator.c:431: value = (unsigned char)(register_read(code) - 1u);
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_register_read
	ld	b, l
	inc	sp
	dec	b
;apps/z80_emulator.c:432: register_write(code, value);
	push	bc
	push	bc
	inc	sp
	ld	hl, #5
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_register_write
	pop	af
	pop	bc
;apps/z80_emulator.c:433: carry = (unsigned char)(cpu.f & FLAG_C);
	ld	a, (#(_cpu + 0x0007) + 0)
	and	a, #0x01
;apps/z80_emulator.c:434: set_sz_flags(value, carry);
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_set_sz_flags
	pop	af
;apps/z80_emulator.c:435: }
	ret
;apps/z80_emulator.c:437: static void emulator_step(void) {
;	---------------------------------
; Function emulator_step
; ---------------------------------
_emulator_step:
	push	ix
	ld	ix,#0
	add	ix,sp
	push	af
	push	af
	dec	sp
;apps/z80_emulator.c:445: if (cpu.halted != 0u) {
	ld	hl, #(_cpu + 0x0010)
	ld	a, (hl)
	or	a, a
;apps/z80_emulator.c:446: return;
	jp	NZ,00193$
;apps/z80_emulator.c:449: pc_before = cpu.pc;
	ld	hl, #(_cpu + 0x0008)
	ld	a, (hl)
	ld	-5 (ix), a
	inc	hl
	ld	a, (hl)
	ld	-4 (ix), a
;apps/z80_emulator.c:450: opcode = fetch8();
	call	_fetch8
	ld	-3 (ix), l
;apps/z80_emulator.c:451: cpu.steps = (unsigned int)(cpu.steps + 1u);
	ld	bc, (#(_cpu + 0x000c) + 0)
	inc	bc
	ld	((_cpu + 0x000c)), bc
;apps/z80_emulator.c:453: if (opcode == 0x76u) {
	ld	a, -3 (ix)
	sub	a, #0x76
	jr	NZ, 00104$
;apps/z80_emulator.c:454: cpu.halted = 1u;
	ld	hl, #(_cpu + 0x0010)
	ld	(hl), #0x01
;apps/z80_emulator.c:455: return;
	jp	00193$
00104$:
;apps/z80_emulator.c:458: if ((opcode >= 0x40u) && (opcode <= 0x7fu)) {
	ld	a, -3 (ix)
	sub	a, #0x40
	jr	C, 00106$
	ld	a, #0x7f
	sub	a, -3 (ix)
	jr	C, 00106$
;apps/z80_emulator.c:459: code = (unsigned char)(opcode & 0x07u);
	ld	a, -3 (ix)
	and	a, #0x07
;apps/z80_emulator.c:460: value = register_read(code);
	push	af
	inc	sp
	call	_register_read
	ld	b, l
	inc	sp
;apps/z80_emulator.c:461: register_write((unsigned char)((opcode >> 3) & 0x07u), value);
	ld	a, -3 (ix)
	rrca
	rrca
	rrca
	and	a, #0x1f
	and	a, #0x07
	push	bc
	inc	sp
	push	af
	inc	sp
	call	_register_write
	pop	af
;apps/z80_emulator.c:462: return;
	jp	00193$
00106$:
;apps/z80_emulator.c:465: if ((opcode >= 0x80u) && (opcode <= 0xbfu)) {
	ld	a, -3 (ix)
	sub	a, #0x80
	jp	C, 00127$
	ld	a, #0xbf
	sub	a, -3 (ix)
	jp	C, 00127$
;apps/z80_emulator.c:466: value = register_read((unsigned char)(opcode & 0x07u));
	ld	a, -3 (ix)
	and	a, #0x07
	push	af
	inc	sp
	call	_register_read
	ld	-2 (ix), l
	inc	sp
;apps/z80_emulator.c:467: code = (unsigned char)((opcode >> 3) & 0x07u);
	ld	a, -3 (ix)
	rrca
	rrca
	rrca
	and	a, #0x1f
	and	a, #0x07
;apps/z80_emulator.c:468: if (code == 0u) {
	ld	-1 (ix), a
	or	a, a
	jr	NZ, 00124$
;apps/z80_emulator.c:469: alu_add(value);
	ld	a, -2 (ix)
	push	af
	inc	sp
	call	_alu_add
	jp	00193$
00124$:
;apps/z80_emulator.c:470: } else if (code == 2u) {
	ld	a, -1 (ix)
	sub	a, #0x02
	jr	NZ, 00121$
;apps/z80_emulator.c:471: alu_sub(value);
	ld	a, -2 (ix)
	push	af
	inc	sp
	call	_alu_sub
	jp	00193$
00121$:
;apps/z80_emulator.c:472: } else if (code == 4u) {
	ld	a, -1 (ix)
	sub	a, #0x04
	jr	NZ, 00118$
;apps/z80_emulator.c:473: alu_and(value);
	ld	a, -2 (ix)
	push	af
	inc	sp
	call	_alu_and
	jp	00193$
00118$:
;apps/z80_emulator.c:474: } else if (code == 5u) {
	ld	a, -1 (ix)
	sub	a, #0x05
	jr	NZ, 00115$
;apps/z80_emulator.c:475: alu_xor(value);
	ld	a, -2 (ix)
	push	af
	inc	sp
	call	_alu_xor
	jp	00193$
00115$:
;apps/z80_emulator.c:476: } else if (code == 6u) {
	ld	a, -1 (ix)
	sub	a, #0x06
	jr	NZ, 00112$
;apps/z80_emulator.c:477: alu_or(value);
	ld	a, -2 (ix)
	push	af
	inc	sp
	call	_alu_or
	jp	00193$
00112$:
;apps/z80_emulator.c:478: } else if (code == 7u) {
	ld	a, -1 (ix)
	sub	a, #0x07
	jr	NZ, 00109$
;apps/z80_emulator.c:479: alu_cp(value);
	ld	a, -2 (ix)
	push	af
	inc	sp
	call	_alu_cp
	jp	00193$
00109$:
;apps/z80_emulator.c:481: trap(opcode, pc_before);
	pop	hl
	push	hl
	push	hl
	ld	a, -3 (ix)
	push	af
	inc	sp
	call	_trap
	pop	af
;apps/z80_emulator.c:483: return;
	jp	00193$
00127$:
;apps/z80_emulator.c:486: if ((opcode & 0xc7u) == 0x04u) {
	ld	e, -3 (ix)
	ld	a, e
	and	a, #0xc7
	ld	c, a
	ld	b, #0x00
	ld	a, c
	sub	a, #0x04
	or	a, b
	jr	NZ, 00130$
;apps/z80_emulator.c:487: inc_register((unsigned char)((opcode >> 3) & 0x07u));
	ld	a, -3 (ix)
	rrca
	rrca
	rrca
	and	a, #0x1f
	and	a, #0x07
	push	af
	inc	sp
	call	_inc_register
;apps/z80_emulator.c:488: return;
	jp	00193$
00130$:
;apps/z80_emulator.c:490: if ((opcode & 0xc7u) == 0x05u) {
	ld	a, c
	sub	a, #0x05
	or	a, b
	jr	NZ, 00132$
;apps/z80_emulator.c:491: dec_register((unsigned char)((opcode >> 3) & 0x07u));
	ld	a, -3 (ix)
	rrca
	rrca
	rrca
	and	a, #0x1f
	and	a, #0x07
	push	af
	inc	sp
	call	_dec_register
;apps/z80_emulator.c:492: return;
	jp	00193$
00132$:
;apps/z80_emulator.c:494: if ((opcode & 0xc7u) == 0x06u) {
	ld	a, c
	sub	a, #0x06
	or	a, b
	jr	NZ, 00134$
;apps/z80_emulator.c:495: register_write((unsigned char)((opcode >> 3) & 0x07u), fetch8());
	call	_fetch8
	ld	b, l
	ld	a, -3 (ix)
	rrca
	rrca
	rrca
	and	a, #0x1f
	and	a, #0x07
	push	bc
	inc	sp
	push	af
	inc	sp
	call	_register_write
	pop	af
;apps/z80_emulator.c:496: return;
	jp	00193$
00134$:
;apps/z80_emulator.c:498: if ((opcode & 0xcfu) == 0x01u) {
	ld	a, e
	and	a, #0xcf
	ld	e, a
	ld	d, #0x00
	ld	a, e
	dec	a
	or	a, d
	jr	NZ, 00136$
;apps/z80_emulator.c:499: pair_write((unsigned char)((opcode >> 4) & 0x03u), fetch16());
	call	_fetch16
	ld	a, -3 (ix)
	rlca
	rlca
	rlca
	rlca
	and	a, #0x0f
	and	a, #0x03
	push	hl
	push	af
	inc	sp
	call	_pair_write
	pop	af
;apps/z80_emulator.c:500: return;
	jp	00193$
00136$:
;apps/z80_emulator.c:502: if ((opcode & 0xcfu) == 0x03u) {
	ld	a, e
	sub	a, #0x03
	or	a, d
	jr	NZ, 00138$
;apps/z80_emulator.c:503: code = (unsigned char)((opcode >> 4) & 0x03u);
	ld	a, -3 (ix)
	rlca
	rlca
	rlca
	rlca
	and	a, #0x0f
	and	a, #0x03
	ld	c, a
;apps/z80_emulator.c:504: pair_write(code, (unsigned int)(pair_read(code) + 1u));
	push	bc
	ld	a, c
	push	af
	inc	sp
	call	_pair_read
	inc	sp
	pop	bc
	inc	hl
	push	hl
	ld	a, c
	push	af
	inc	sp
	call	_pair_write
	pop	af
;apps/z80_emulator.c:505: return;
	jp	00193$
00138$:
;apps/z80_emulator.c:507: if ((opcode & 0xcfu) == 0x0bu) {
	ld	a, e
	sub	a, #0x0b
	or	a, d
	jr	NZ, 00140$
;apps/z80_emulator.c:508: code = (unsigned char)((opcode >> 4) & 0x03u);
	ld	a, -3 (ix)
	rlca
	rlca
	rlca
	rlca
	and	a, #0x0f
	and	a, #0x03
	ld	c, a
;apps/z80_emulator.c:509: pair_write(code, (unsigned int)(pair_read(code) - 1u));
	push	bc
	ld	a, c
	push	af
	inc	sp
	call	_pair_read
	inc	sp
	pop	bc
	dec	hl
	push	hl
	ld	a, c
	push	af
	inc	sp
	call	_pair_write
	pop	af
;apps/z80_emulator.c:510: return;
	jp	00193$
00140$:
;apps/z80_emulator.c:512: if ((opcode & 0xcfu) == 0x09u) {
	ld	a, e
	sub	a, #0x09
	or	a, d
	jr	NZ, 00142$
;apps/z80_emulator.c:513: result = (unsigned int)(get_hl() +
	call	_get_hl
	ex	de, hl
;apps/z80_emulator.c:514: pair_read((unsigned char)((opcode >> 4) & 0x03u)));
	ld	a, -3 (ix)
	rlca
	rlca
	rlca
	rlca
	and	a, #0x0f
	and	a, #0x03
	push	de
	push	af
	inc	sp
	call	_pair_read
	inc	sp
	pop	de
	add	hl, de
;apps/z80_emulator.c:515: set_hl(result);
	push	hl
	call	_set_hl
	pop	af
;apps/z80_emulator.c:516: return;
	jp	00193$
00142$:
;apps/z80_emulator.c:518: if ((opcode & 0xc7u) == 0xc0u) {
	ld	a, c
	sub	a, #0xc0
	or	a, b
	jr	NZ, 00146$
;apps/z80_emulator.c:519: if (condition_true((unsigned char)((opcode >> 3) & 0x07u)) != 0u) {
	ld	a, -3 (ix)
	rrca
	rrca
	rrca
	and	a, #0x1f
	and	a, #0x07
	push	af
	inc	sp
	call	_condition_true
	inc	sp
	ld	a, l
	or	a, a
	jp	Z,00193$
;apps/z80_emulator.c:520: cpu.pc = pop16();
	call	_pop16
	ex	de, hl
	ld	((_cpu + 0x0008)), de
;apps/z80_emulator.c:522: return;
	jp	00193$
00146$:
;apps/z80_emulator.c:524: if ((opcode & 0xc7u) == 0xc2u) {
	ld	a, c
	sub	a, #0xc2
	or	a, b
	jr	NZ, 00150$
;apps/z80_emulator.c:525: address = fetch16();
	call	_fetch16
	ex	de, hl
;apps/z80_emulator.c:526: if (condition_true((unsigned char)((opcode >> 3) & 0x07u)) != 0u) {
	ld	a, -3 (ix)
	rrca
	rrca
	rrca
	and	a, #0x1f
	and	a, #0x07
	push	de
	push	af
	inc	sp
	call	_condition_true
	inc	sp
	ld	a, l
	pop	de
	or	a, a
	jp	Z,00193$
;apps/z80_emulator.c:527: cpu.pc = address;
	ld	((_cpu + 0x0008)), de
;apps/z80_emulator.c:529: return;
	jp	00193$
00150$:
;apps/z80_emulator.c:531: if ((opcode & 0xc7u) == 0xc4u) {
	ld	a, c
	sub	a, #0xc4
	or	a, b
	jr	NZ, 00154$
;apps/z80_emulator.c:532: address = fetch16();
	call	_fetch16
	ex	de, hl
;apps/z80_emulator.c:533: if (condition_true((unsigned char)((opcode >> 3) & 0x07u)) != 0u) {
	ld	a, -3 (ix)
	rrca
	rrca
	rrca
	and	a, #0x1f
	and	a, #0x07
	push	de
	push	af
	inc	sp
	call	_condition_true
	inc	sp
	ld	a, l
	pop	de
	or	a, a
	jp	Z,00193$
;apps/z80_emulator.c:534: push16(cpu.pc);
	ld	hl, (#(_cpu + 0x0008) + 0)
	push	de
	push	hl
	call	_push16
	pop	af
	pop	de
;apps/z80_emulator.c:535: cpu.pc = address;
	ld	((_cpu + 0x0008)), de
;apps/z80_emulator.c:537: return;
	jp	00193$
00154$:
;apps/z80_emulator.c:539: if ((opcode & 0xcfu) == 0xc1u) {
	ld	a, e
	sub	a, #0xc1
	or	a, d
	jr	NZ, 00156$
;apps/z80_emulator.c:540: stack_pair_write((unsigned char)((opcode >> 4) & 0x03u), pop16());
	call	_pop16
	ld	a, -3 (ix)
	rlca
	rlca
	rlca
	rlca
	and	a, #0x0f
	and	a, #0x03
	push	hl
	push	af
	inc	sp
	call	_stack_pair_write
	pop	af
;apps/z80_emulator.c:541: return;
	jp	00193$
00156$:
;apps/z80_emulator.c:543: if ((opcode & 0xcfu) == 0xc5u) {
	ld	a, e
	sub	a, #0xc5
	or	a, d
	jr	NZ, 00158$
;apps/z80_emulator.c:544: push16(stack_pair_read((unsigned char)((opcode >> 4) & 0x03u)));
	ld	a, -3 (ix)
	rlca
	rlca
	rlca
	rlca
	and	a, #0x0f
	and	a, #0x03
	push	af
	inc	sp
	call	_stack_pair_read
	inc	sp
	push	hl
	call	_push16
	pop	af
;apps/z80_emulator.c:545: return;
	jp	00193$
00158$:
;apps/z80_emulator.c:548: switch (opcode) {
	ld	a, -3 (ix)
	or	a, a
	jp	Z,00193$
	ld	a, -3 (ix)
	sub	a, #0x02
	jp	Z,00160$
	ld	a, -3 (ix)
	sub	a, #0x0a
	jp	Z,00161$
	ld	a, -3 (ix)
	sub	a, #0x10
	jp	Z,00162$
	ld	a, -3 (ix)
	sub	a, #0x12
	jp	Z,00165$
	ld	a, -3 (ix)
	sub	a, #0x18
	jp	Z,00166$
	ld	a, -3 (ix)
	sub	a, #0x1a
	jp	Z,00167$
	ld	a, -3 (ix)
	sub	a, #0x20
	jp	Z,00171$
	ld	a, -3 (ix)
	sub	a, #0x22
	jp	Z,00174$
	ld	a, -3 (ix)
	sub	a, #0x28
	jp	Z,00171$
	ld	a, -3 (ix)
	sub	a, #0x2a
	jp	Z,00175$
	ld	a, -3 (ix)
	sub	a, #0x2f
	jp	Z,00176$
	ld	a, -3 (ix)
	sub	a, #0x30
	jp	Z,00171$
	ld	a, -3 (ix)
	sub	a, #0x32
	jp	Z,00177$
	ld	a, -3 (ix)
	sub	a, #0x37
	jp	Z,00178$
	ld	a, -3 (ix)
	sub	a, #0x38
	jp	Z,00171$
	ld	a, -3 (ix)
	sub	a, #0x3a
	jp	Z,00179$
	ld	a, -3 (ix)
	sub	a, #0x3f
	jp	Z,00180$
	ld	a, -3 (ix)
	sub	a, #0xc3
	jp	Z,00181$
	ld	a, -3 (ix)
	sub	a, #0xc9
	jp	Z,00182$
	ld	a, -3 (ix)
	sub	a, #0xcd
	jp	Z,00183$
	ld	a, -3 (ix)
	sub	a, #0xd3
	jp	Z,00184$
	ld	a, -3 (ix)
	sub	a, #0xdb
	jp	Z,00185$
	ld	a, -3 (ix)
	sub	a, #0xe9
	jp	Z,00186$
	ld	a, -3 (ix)
	sub	a, #0xeb
	jp	Z,00187$
	ld	a, -3 (ix)
	sub	a, #0xf3
	jp	Z,00193$
	ld	a, -3 (ix)
	sub	a, #0xf9
	jp	Z,00190$
	ld	a, -3 (ix)
	sub	a, #0xfb
	jp	Z,00193$
;apps/z80_emulator.c:549: case 0x00u:
;apps/z80_emulator.c:550: return;
	jp	00191$
;apps/z80_emulator.c:551: case 0x02u:
00160$:
;apps/z80_emulator.c:552: memory_write(get_bc(), cpu.a);
	ld	hl, #_cpu
	ld	b, (hl)
	push	bc
	call	_get_bc
	inc	sp
	push	hl
	call	_memory_write
	pop	af
;apps/z80_emulator.c:553: return;
	jp	00193$
;apps/z80_emulator.c:554: case 0x0au:
00161$:
;apps/z80_emulator.c:555: cpu.a = memory_read(get_bc());
	call	_get_bc
	push	hl
	call	_memory_read
	pop	af
	ld	a, l
	ld	hl, #_cpu
	ld	(hl), a
;apps/z80_emulator.c:556: return;
	jp	00193$
;apps/z80_emulator.c:557: case 0x10u:
00162$:
;apps/z80_emulator.c:558: value = fetch8();
	call	_fetch8
	ld	e, l
;apps/z80_emulator.c:559: cpu.b = (unsigned char)(cpu.b - 1u);
	ld	hl, #_cpu + 1
	ld	c, (hl)
	dec	c
;apps/z80_emulator.c:560: if (cpu.b != 0u) {
	ld	a,c
	ld	(hl),a
	or	a, a
	jp	Z,00193$
;apps/z80_emulator.c:561: cpu.pc = add_signed8(cpu.pc, value);
	ld	hl, (#(_cpu + 0x0008) + 0)
	ld	a, e
	push	af
	inc	sp
	push	hl
	call	_add_signed8
	pop	af
	inc	sp
	ex	de, hl
	ld	((_cpu + 0x0008)), de
;apps/z80_emulator.c:563: return;
	jp	00193$
;apps/z80_emulator.c:564: case 0x12u:
00165$:
;apps/z80_emulator.c:565: memory_write(get_de(), cpu.a);
	ld	hl, #_cpu
	ld	b, (hl)
	push	bc
	call	_get_de
	inc	sp
	push	hl
	call	_memory_write
	pop	af
;apps/z80_emulator.c:566: return;
	jp	00193$
;apps/z80_emulator.c:567: case 0x18u:
00166$:
;apps/z80_emulator.c:568: cpu.pc = add_signed8(cpu.pc, fetch8());
	call	_fetch8
	ld	b, l
	ld	hl, (#(_cpu + 0x0008) + 0)
	push	bc
	inc	sp
	push	hl
	call	_add_signed8
	pop	af
	inc	sp
	ex	de, hl
	ld	((_cpu + 0x0008)), de
;apps/z80_emulator.c:569: return;
	jp	00193$
;apps/z80_emulator.c:570: case 0x1au:
00167$:
;apps/z80_emulator.c:571: cpu.a = memory_read(get_de());
	call	_get_de
	push	hl
	call	_memory_read
	pop	af
	ld	a, l
	ld	hl, #_cpu
	ld	(hl), a
;apps/z80_emulator.c:572: return;
	jp	00193$
;apps/z80_emulator.c:576: case 0x38u:
00171$:
;apps/z80_emulator.c:577: value = fetch8();
	call	_fetch8
	ld	-1 (ix), l
;apps/z80_emulator.c:578: if (condition_true((unsigned char)((opcode >> 3) & 0x03u)) != 0u) {
	ld	a, -3 (ix)
	rrca
	rrca
	rrca
	and	a, #0x1f
	and	a, #0x03
	push	af
	inc	sp
	call	_condition_true
	inc	sp
	ld	a, l
	or	a, a
	jp	Z,00193$
;apps/z80_emulator.c:579: cpu.pc = add_signed8(cpu.pc, value);
	ld	hl, (#(_cpu + 0x0008) + 0)
	ld	a, -1 (ix)
	push	af
	inc	sp
	push	hl
	call	_add_signed8
	pop	af
	inc	sp
	ex	de, hl
	ld	((_cpu + 0x0008)), de
;apps/z80_emulator.c:581: return;
	jp	00193$
;apps/z80_emulator.c:582: case 0x22u:
00174$:
;apps/z80_emulator.c:583: address = fetch16();
	call	_fetch16
	ex	de, hl
;apps/z80_emulator.c:584: memory_write(address, cpu.l);
	ld	a, (#_cpu + 6)
	push	de
	push	af
	inc	sp
	push	de
	call	_memory_write
	pop	af
	inc	sp
	pop	de
;apps/z80_emulator.c:585: memory_write((unsigned int)(address + 1u), cpu.h);
	ld	a, (#_cpu + 5)
	inc	de
	push	af
	inc	sp
	push	de
	call	_memory_write
	pop	af
;apps/z80_emulator.c:586: return;
	jp	00193$
;apps/z80_emulator.c:587: case 0x2au:
00175$:
;apps/z80_emulator.c:588: address = fetch16();
	call	_fetch16
	ex	de, hl
;apps/z80_emulator.c:589: cpu.l = memory_read(address);
	push	de
	push	de
	call	_memory_read
	pop	af
	ld	a, l
	pop	de
	ld	(#(_cpu + 0x0006)),a
;apps/z80_emulator.c:590: cpu.h = memory_read((unsigned int)(address + 1u));
	inc	de
	push	de
	call	_memory_read
	pop	af
	ld	a, l
	ld	hl, #(_cpu + 0x0005)
	ld	(hl), a
;apps/z80_emulator.c:591: return;
	jp	00193$
;apps/z80_emulator.c:592: case 0x2fu:
00176$:
;apps/z80_emulator.c:593: cpu.a = (unsigned char)~cpu.a;
	ld	a, (#_cpu + 0)
	cpl
	ld	hl, #_cpu
	ld	(hl), a
;apps/z80_emulator.c:594: return;
	jp	00193$
;apps/z80_emulator.c:595: case 0x32u:
00177$:
;apps/z80_emulator.c:596: memory_write(fetch16(), cpu.a);
	ld	hl, #_cpu
	ld	b, (hl)
	push	bc
	call	_fetch16
	inc	sp
	push	hl
	call	_memory_write
	pop	af
;apps/z80_emulator.c:597: return;
	jp	00193$
;apps/z80_emulator.c:598: case 0x37u:
00178$:
;apps/z80_emulator.c:599: cpu.f |= FLAG_C;
	ld	bc, #_cpu + 7
	ld	a, (bc)
	set	0, a
	ld	(bc), a
;apps/z80_emulator.c:600: return;
	jp	00193$
;apps/z80_emulator.c:601: case 0x3au:
00179$:
;apps/z80_emulator.c:602: cpu.a = memory_read(fetch16());
	call	_fetch16
	push	hl
	call	_memory_read
	pop	af
	ld	a, l
	ld	hl, #_cpu
	ld	(hl), a
;apps/z80_emulator.c:603: return;
	jp	00193$
;apps/z80_emulator.c:604: case 0x3fu:
00180$:
;apps/z80_emulator.c:605: cpu.f ^= FLAG_C;
	ld	bc, #_cpu + 7
	ld	a, (bc)
	xor	a, #0x01
	ld	(bc), a
;apps/z80_emulator.c:606: return;
	jr	00193$
;apps/z80_emulator.c:607: case 0xc3u:
00181$:
;apps/z80_emulator.c:608: cpu.pc = fetch16();
	call	_fetch16
	ex	de, hl
	ld	((_cpu + 0x0008)), de
;apps/z80_emulator.c:609: return;
	jr	00193$
;apps/z80_emulator.c:610: case 0xc9u:
00182$:
;apps/z80_emulator.c:611: cpu.pc = pop16();
	call	_pop16
	ex	de, hl
	ld	((_cpu + 0x0008)), de
;apps/z80_emulator.c:612: return;
	jr	00193$
;apps/z80_emulator.c:613: case 0xcdu:
00183$:
;apps/z80_emulator.c:614: address = fetch16();
	call	_fetch16
	ex	de, hl
;apps/z80_emulator.c:615: push16(cpu.pc);
	ld	hl, (#(_cpu + 0x0008) + 0)
	push	de
	push	hl
	call	_push16
	pop	af
	pop	de
;apps/z80_emulator.c:616: cpu.pc = address;
	ld	((_cpu + 0x0008)), de
;apps/z80_emulator.c:617: return;
	jr	00193$
;apps/z80_emulator.c:618: case 0xd3u:
00184$:
;apps/z80_emulator.c:619: fetch8();
	call	_fetch8
;apps/z80_emulator.c:620: cpu.last_out = cpu.a;
	ld	a, (#_cpu + 0)
	ld	hl, #(_cpu + 0x0012)
	ld	(hl), a
;apps/z80_emulator.c:621: return;
	jr	00193$
;apps/z80_emulator.c:622: case 0xdbu:
00185$:
;apps/z80_emulator.c:623: value = fetch8();
	call	_fetch8
;apps/z80_emulator.c:624: cpu.a = (value == 0u) ? glic_read_buttons() : 0xffu;
	ld	a, l
	or	a, a
	jr	NZ, 00195$
	call	_glic_read_buttons
	ld	c, l
	jr	00196$
00195$:
	ld	bc, #0x00ff
00196$:
	ld	hl, #_cpu
	ld	(hl), c
;apps/z80_emulator.c:625: return;
	jr	00193$
;apps/z80_emulator.c:626: case 0xe9u:
00186$:
;apps/z80_emulator.c:627: cpu.pc = get_hl();
	call	_get_hl
	ex	de, hl
	ld	((_cpu + 0x0008)), de
;apps/z80_emulator.c:628: return;
	jr	00193$
;apps/z80_emulator.c:629: case 0xebu:
00187$:
;apps/z80_emulator.c:630: result = get_de();
	call	_get_de
;apps/z80_emulator.c:631: set_de(get_hl());
	push	hl
	call	_get_hl
	push	hl
	call	_set_de
	pop	af
	call	_set_hl
	pop	af
;apps/z80_emulator.c:633: return;
;apps/z80_emulator.c:635: case 0xfbu:
;apps/z80_emulator.c:636: return;
	jr	00193$
;apps/z80_emulator.c:637: case 0xf9u:
00190$:
;apps/z80_emulator.c:638: cpu.sp = get_hl();
	call	_get_hl
	ex	de, hl
	ld	((_cpu + 0x000a)), de
;apps/z80_emulator.c:639: return;
	jr	00193$
;apps/z80_emulator.c:640: default:
00191$:
;apps/z80_emulator.c:641: trap(opcode, pc_before);
	pop	hl
	push	hl
	push	hl
	ld	a, -3 (ix)
	push	af
	inc	sp
	call	_trap
	pop	af
;apps/z80_emulator.c:642: return;
;apps/z80_emulator.c:643: }
00193$:
;apps/z80_emulator.c:644: }
	ld	sp, ix
	pop	ix
	ret
;apps/z80_emulator.c:646: static void emulator_reset(void) {
;	---------------------------------
; Function emulator_reset
; ---------------------------------
_emulator_reset:
;apps/z80_emulator.c:649: cpu.a = 0u;
	ld	hl, #_cpu
	ld	(hl), #0x00
;apps/z80_emulator.c:650: cpu.b = 0u;
	ld	hl, #(_cpu + 0x0001)
	ld	(hl), #0x00
;apps/z80_emulator.c:651: cpu.c = 0u;
	ld	hl, #(_cpu + 0x0002)
	ld	(hl), #0x00
;apps/z80_emulator.c:652: cpu.d = 0u;
	ld	hl, #(_cpu + 0x0003)
	ld	(hl), #0x00
;apps/z80_emulator.c:653: cpu.e = 0u;
	ld	hl, #(_cpu + 0x0004)
	ld	(hl), #0x00
;apps/z80_emulator.c:654: cpu.h = 0u;
	ld	hl, #(_cpu + 0x0005)
	ld	(hl), #0x00
;apps/z80_emulator.c:655: cpu.l = 0u;
	ld	hl, #(_cpu + 0x0006)
	ld	(hl), #0x00
;apps/z80_emulator.c:656: cpu.f = 0u;
	ld	hl, #(_cpu + 0x0007)
	ld	(hl), #0x00
;apps/z80_emulator.c:657: cpu.pc = 0u;
	ld	hl, #0x0000
	ld	((_cpu + 0x0008)), hl
;apps/z80_emulator.c:658: cpu.sp = 0x7700u;
	ld	h, #0x77
	ld	((_cpu + 0x000a)), hl
;apps/z80_emulator.c:659: cpu.steps = 0u;
	ld	h, l
	ld	((_cpu + 0x000c)), hl
;apps/z80_emulator.c:660: cpu.trap_pc = 0u;
	ld	l, h
	ld	((_cpu + 0x000e)), hl
;apps/z80_emulator.c:661: cpu.halted = 0u;
	ld	hl, #(_cpu + 0x0010)
	ld	(hl), #0x00
;apps/z80_emulator.c:662: cpu.trap_opcode = 0u;
	ld	hl, #(_cpu + 0x0011)
	ld	(hl), #0x00
;apps/z80_emulator.c:663: cpu.last_out = 0u;
	ld	hl, #(_cpu + 0x0012)
	ld	(hl), #0x00
;apps/z80_emulator.c:665: for (i = 0u; i < EMU_RAM_SIZE; ++i) {
	ld	bc, #0x0000
00102$:
;apps/z80_emulator.c:666: emu_ram[i] = 0u;
	ld	hl, #_emu_ram
	add	hl, bc
	ld	(hl), #0x00
;apps/z80_emulator.c:665: for (i = 0u; i < EMU_RAM_SIZE; ++i) {
	inc	bc
	ld	a, b
	sub	a, #0x07
	jr	C, 00102$
;apps/z80_emulator.c:668: }
	ret
;apps/z80_emulator.c:670: static void draw_home_flag_icon(void) {
;	---------------------------------
; Function draw_home_flag_icon
; ---------------------------------
_draw_home_flag_icon:
;apps/z80_emulator.c:673: for (page = 5u; page < 11u; ++page) {
	ld	b, #0x05
00102$:
;apps/z80_emulator.c:674: glic_fill_page_run(page, 32u, 64u, GLIC_WHITE);
	push	bc
	ld	de, #0xff40
	push	de
	ld	a, #0x20
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_fill_page_run
	pop	af
	pop	af
	pop	bc
;apps/z80_emulator.c:673: for (page = 5u; page < 11u; ++page) {
	inc	b
	ld	a, b
	sub	a, #0x0b
	jr	C, 00102$
;apps/z80_emulator.c:676: glic_fill_page_run(6u, 58u, 12u, GLIC_BLACK);
	xor	a, a
	ld	d,a
	ld	e,#0x0c
	push	de
	ld	de, #0x3a06
	push	de
	call	_glic_fill_page_run
	pop	af
	pop	af
;apps/z80_emulator.c:677: glic_fill_page_run(7u, 52u, 24u, GLIC_BLACK);
	xor	a, a
	ld	d,a
	ld	e,#0x18
	push	de
	ld	de, #0x3407
	push	de
	call	_glic_fill_page_run
	pop	af
	pop	af
;apps/z80_emulator.c:678: glic_fill_page_run(8u, 52u, 24u, GLIC_BLACK);
	xor	a, a
	ld	d,a
	ld	e,#0x18
	push	de
	ld	de, #0x3408
	push	de
	call	_glic_fill_page_run
	pop	af
	pop	af
;apps/z80_emulator.c:679: glic_fill_page_run(9u, 58u, 12u, GLIC_BLACK);
	xor	a, a
	ld	d,a
	ld	e,#0x0c
	push	de
	ld	de, #0x3a09
	push	de
	call	_glic_fill_page_run
	pop	af
	pop	af
;apps/z80_emulator.c:680: }
	ret
;apps/z80_emulator.c:682: static void draw_home(void) {
;	---------------------------------
; Function draw_home
; ---------------------------------
_draw_home:
;apps/z80_emulator.c:683: glic_prepare_screen(GLIC_BLACK);
	xor	a, a
	push	af
	inc	sp
	call	_glic_prepare_screen
	inc	sp
;apps/z80_emulator.c:684: draw_home_flag_icon();
	call	_draw_home_flag_icon
;apps/z80_emulator.c:685: text_write(0u, 0u, "Z80 EMULATOR");
	ld	hl, #___str_0
	push	hl
	xor	a, a
	push	af
	inc	sp
	xor	a, a
	push	af
	inc	sp
	call	_text_write
	pop	af
;apps/z80_emulator.c:686: text_write(1u, 0u, "JAPAN ASM DEMO");
	ld	hl, #___str_1
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x01
	push	de
	call	_text_write
	pop	af
;apps/z80_emulator.c:687: text_write(3u, 0u, "A RUN");
	ld	hl, #___str_2
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x03
	push	de
	call	_text_write
	pop	af
;apps/z80_emulator.c:688: text_write(4u, 0u, "DOUBLE A HOME");
	ld	hl, #___str_3
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x04
	push	de
	call	_text_write
	pop	af
;apps/z80_emulator.c:689: text_write(12u, 0u, "GUEST PC 0000");
	ld	hl, #___str_4
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0c
	push	de
	call	_text_write
	pop	af
;apps/z80_emulator.c:690: text_write(13u, 0u, "VRAM 7700 7800");
	ld	hl, #___str_5
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0d
	push	de
	call	_text_write
	pop	af
;apps/z80_emulator.c:691: text_write(15u, 0u, "READY");
	ld	hl, #___str_6
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0f
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/z80_emulator.c:692: }
	ret
___str_0:
	.ascii "Z80 EMULATOR"
	.db 0x00
___str_1:
	.ascii "JAPAN ASM DEMO"
	.db 0x00
___str_2:
	.ascii "A RUN"
	.db 0x00
___str_3:
	.ascii "DOUBLE A HOME"
	.db 0x00
___str_4:
	.ascii "GUEST PC 0000"
	.db 0x00
___str_5:
	.ascii "VRAM 7700 7800"
	.db 0x00
___str_6:
	.ascii "READY"
	.db 0x00
;apps/z80_emulator.c:694: static void draw_emulator_status(void) {
;	---------------------------------
; Function draw_emulator_status
; ---------------------------------
_draw_emulator_status:
	push	ix
	ld	ix,#0
	add	ix,sp
	dec	sp
;apps/z80_emulator.c:695: text_clear_row(13u);
	ld	a, #0x0d
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;apps/z80_emulator.c:696: text_clear_row(14u);
	ld	a, #0x0e
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;apps/z80_emulator.c:697: text_clear_row(15u);
	ld	a, #0x0f
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;apps/z80_emulator.c:699: if (cpu.trap_opcode != 0u) {
	ld	a, (#(_cpu + 0x0011) + 0)
	ld	-1 (ix), a
	or	a, a
	jr	Z, 00104$
;apps/z80_emulator.c:700: text_write(13u, 0u, "UNSUPPORTED OP");
	ld	hl, #___str_7
	push	hl
	xor	a, a
	ld	d,a
	ld	e,#0x0d
	push	de
	call	_text_write
	pop	af
;apps/z80_emulator.c:701: text_write(14u, 0u, "PC ");
	ld	hl, #___str_8
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0e
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/z80_emulator.c:702: text_write_hex16(14u, 3u, cpu.trap_pc);
	ld	hl, (#_cpu + 14)
	push	hl
	ld	de, #0x030e
	push	de
	call	_text_write_hex16
	pop	af
;apps/z80_emulator.c:703: text_write(14u, 8u, "OP ");
	ld	hl, #___str_9
	ex	(sp),hl
	ld	de, #0x080e
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/z80_emulator.c:704: text_write_hex8(14u, 11u, cpu.trap_opcode);
	ld	a, (#(_cpu + 0x0011) + 0)
	ld	d,a
	ld	e,#0x0b
	push	de
	ld	a, #0x0e
	push	af
	inc	sp
	call	_text_write_hex8
;apps/z80_emulator.c:705: text_write(15u, 0u, "DOUBLE A HOME");
	inc	sp
	ld	hl,#___str_10
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0f
	push	de
	call	_text_write
	pop	af
	pop	af
	jr	00106$
00104$:
;apps/z80_emulator.c:706: } else if (cpu.halted != 0u) {
	ld	hl, #_cpu + 16
	ld	a, (hl)
	ld	-1 (ix), a
	or	a, a
	jr	Z, 00106$
;apps/z80_emulator.c:707: text_write(13u, 0u, "GUEST HALTED");
	ld	hl, #___str_11
	push	hl
	xor	a, a
	ld	d,a
	ld	e,#0x0d
	push	de
	call	_text_write
	pop	af
;apps/z80_emulator.c:708: text_write(14u, 0u, "PC ");
	ld	hl, #___str_8
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0e
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/z80_emulator.c:709: text_write_hex16(14u, 3u, cpu.pc);
	ld	hl, (#_cpu + 8)
	push	hl
	ld	de, #0x030e
	push	de
	call	_text_write_hex16
	pop	af
;apps/z80_emulator.c:710: text_write(15u, 0u, "DOUBLE A HOME");
	ld	hl, #___str_10
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0f
	push	de
	call	_text_write
	pop	af
	pop	af
00106$:
;apps/z80_emulator.c:712: }
	inc	sp
	pop	ix
	ret
___str_7:
	.ascii "UNSUPPORTED OP"
	.db 0x00
___str_8:
	.ascii "PC "
	.db 0x00
___str_9:
	.ascii "OP "
	.db 0x00
___str_10:
	.ascii "DOUBLE A HOME"
	.db 0x00
___str_11:
	.ascii "GUEST HALTED"
	.db 0x00
;apps/z80_emulator.c:714: static void draw_double_a_prompt(void) {
;	---------------------------------
; Function draw_double_a_prompt
; ---------------------------------
_draw_double_a_prompt:
;apps/z80_emulator.c:715: text_clear_row(15u);
	ld	a, #0x0f
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;apps/z80_emulator.c:716: text_write(15u, 0u, "A AGAIN HOME");
	ld	hl, #___str_12
	push	hl
	xor	a, a
	ld	d,a
	ld	e,#0x0f
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/z80_emulator.c:717: }
	ret
___str_12:
	.ascii "A AGAIN HOME"
	.db 0x00
;apps/z80_emulator.c:719: static void run_emulator(void) {
;	---------------------------------
; Function run_emulator
; ---------------------------------
_run_emulator:
	push	ix
	ld	ix,#0
	add	ix,sp
	dec	sp
;apps/z80_emulator.c:725: glic_prepare_screen(GLIC_BLACK);
	xor	a, a
	push	af
	inc	sp
	call	_glic_prepare_screen
	inc	sp
;apps/z80_emulator.c:726: text_write(7u, 0u, "RUNNING GUEST");
	ld	hl, #___str_13
	push	hl
	xor	a, a
	ld	d,a
	ld	e,#0x07
	push	de
	call	_text_write
	pop	af
	pop	af
;apps/z80_emulator.c:727: emulator_reset();
	call	_emulator_reset
;apps/z80_emulator.c:728: wait_for_release();
	call	_wait_for_release
;apps/z80_emulator.c:730: last_buttons = GLIC_BUTTONS_NONE;
;apps/z80_emulator.c:731: double_a_timer = 0u;
	ld	bc, #0xff00
;apps/z80_emulator.c:733: while (1) {
00116$:
;apps/z80_emulator.c:734: if (cpu.halted == 0u) {
	ld	a, (#(_cpu + 0x0010) + 0)
	or	a, a
	jr	NZ, 00105$
;apps/z80_emulator.c:735: for (i = 0u; i < EMU_STEPS_PER_FRAME; ++i) {
	ld	de, #0x0000
00118$:
;apps/z80_emulator.c:736: emulator_step();
	push	bc
	push	de
	call	_emulator_step
	pop	de
	pop	bc
;apps/z80_emulator.c:737: if (cpu.halted != 0u) {
	ld	a, (#(_cpu + 0x0010) + 0)
	or	a, a
	jr	Z, 00119$
;apps/z80_emulator.c:738: draw_emulator_status();
	push	bc
	call	_draw_emulator_status
	pop	bc
;apps/z80_emulator.c:739: break;
	jr	00105$
00119$:
;apps/z80_emulator.c:735: for (i = 0u; i < EMU_STEPS_PER_FRAME; ++i) {
	inc	de
	ld	a, e
	sub	a, #0xb4
	ld	a, d
	sbc	a, #0x00
	jr	C, 00118$
00105$:
;apps/z80_emulator.c:744: buttons = glic_read_buttons();
	push	bc
	call	_glic_read_buttons
	pop	bc
	ld	-1 (ix), l
;apps/z80_emulator.c:745: if (button_edge(buttons, last_buttons, GLIC_BTN_A) != 0u) {
	push	bc
	ld	a, #0x80
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	a, -1 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	bc
	or	a, a
	jr	Z, 00113$
;apps/z80_emulator.c:746: if (double_a_timer != 0u) {
	ld	a, c
	or	a, a
	jr	Z, 00107$
;apps/z80_emulator.c:747: wait_for_release();
	call	_wait_for_release
;apps/z80_emulator.c:748: return;
	jr	00120$
00107$:
;apps/z80_emulator.c:750: double_a_timer = DOUBLE_A_WINDOW;
	ld	c, #0x18
;apps/z80_emulator.c:751: draw_double_a_prompt();
	push	bc
	call	_draw_double_a_prompt
	pop	bc
	jr	00114$
00113$:
;apps/z80_emulator.c:752: } else if (double_a_timer != 0u) {
	ld	a, c
	or	a, a
	jr	Z, 00114$
;apps/z80_emulator.c:753: --double_a_timer;
;apps/z80_emulator.c:754: if (double_a_timer == 0u) {
	dec	c
	jr	NZ, 00114$
;apps/z80_emulator.c:755: draw_emulator_status();
	push	bc
	call	_draw_emulator_status
	pop	bc
00114$:
;apps/z80_emulator.c:759: last_buttons = buttons;
	ld	b, -1 (ix)
;apps/z80_emulator.c:760: glic_delay(LOOP_DELAY);
	push	bc
	ld	hl, #0x02bc
	push	hl
	call	_glic_delay
	pop	af
	pop	bc
	jr	00116$
00120$:
;apps/z80_emulator.c:762: }
	inc	sp
	pop	ix
	ret
___str_13:
	.ascii "RUNNING GUEST"
	.db 0x00
;apps/z80_emulator.c:764: void main(void) {
;	---------------------------------
; Function main
; ---------------------------------
_main::
;apps/z80_emulator.c:768: draw_home();
	call	_draw_home
;apps/z80_emulator.c:769: wait_for_release();
	call	_wait_for_release
;apps/z80_emulator.c:770: last_buttons = GLIC_BUTTONS_NONE;
	ld	b, #0xff
;apps/z80_emulator.c:772: while (1) {
00105$:
;apps/z80_emulator.c:773: buttons = glic_read_buttons();
	push	bc
	call	_glic_read_buttons
	pop	bc
;apps/z80_emulator.c:774: if (button_edge(buttons, last_buttons, GLIC_BTN_A) != 0u) {
	push	hl
	ld	a, #0x80
	push	af
	ld	c, l
	inc	sp
	push	bc
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	hl
	or	a, a
	jr	Z, 00102$
;apps/z80_emulator.c:775: run_emulator();
	call	_run_emulator
;apps/z80_emulator.c:776: draw_home();
	call	_draw_home
;apps/z80_emulator.c:777: last_buttons = GLIC_BUTTONS_NONE;
	ld	b, #0xff
;apps/z80_emulator.c:778: wait_for_release();
	push	bc
	call	_wait_for_release
	pop	bc
	jr	00105$
00102$:
;apps/z80_emulator.c:780: last_buttons = buttons;
	ld	b, l
;apps/z80_emulator.c:781: glic_delay(LOOP_DELAY);
	push	bc
	ld	hl, #0x02bc
	push	hl
	call	_glic_delay
	pop	af
	pop	bc
;apps/z80_emulator.c:784: }
	jr	00105$
	.area _CODE
	.area _INITIALIZER
	.area _CABS (ABS)
