; generated by sdcc-z80-bin
    JR __sdcc_z80_bin_start
    DB "flappy_bird",0
__sdcc_z80_bin_start:
    LD SP,#0x7700
    CALL _main
__sdcc_z80_bin_halt:
    JR __sdcc_z80_bin_halt

;--------------------------------------------------------
; File Created by SDCC : free open source ANSI-C Compiler
; Version 4.1.0 #12072 (Linux)
;--------------------------------------------------------
	.module flappy_bird
	.optsdcc -mz80
	
;--------------------------------------------------------
; Public variables in this module
;--------------------------------------------------------
	.globl _main
;--------------------------------------------------------
; special function registers
;--------------------------------------------------------
;--------------------------------------------------------
; ram data
;--------------------------------------------------------
	.area _DATA
_rng_state:
	.ds 1
_score:
	.ds 1
;--------------------------------------------------------
; ram data
;--------------------------------------------------------
	.area _INITIALIZED
;--------------------------------------------------------
; absolute external ram data
;--------------------------------------------------------
	.area _DABS (ABS)
;--------------------------------------------------------
; global & static initialisations
;--------------------------------------------------------
	.area _HOME
	.area _GSINIT
	.area _GSFINAL
	.area _GSINIT
;--------------------------------------------------------
; Home
;--------------------------------------------------------
	.area _HOME
	.area _HOME
;--------------------------------------------------------
; code
;--------------------------------------------------------
	.area _CODE
;games/../common/glic80.h:29: static unsigned char glic_read_buttons(void) __naked {
;	---------------------------------
; Function glic_read_buttons
; ---------------------------------
_glic_read_buttons:
;games/../common/glic80.h:34: __endasm;
	in	a,(0)
	ld	l,a
	ret
;games/../common/glic80.h:35: }
;games/../common/glic80.h:37: static unsigned char glic_button_pressed(unsigned char buttons,
;	---------------------------------
; Function glic_button_pressed
; ---------------------------------
_glic_button_pressed:
;games/../common/glic80.h:39: return (buttons & mask) == 0u;
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	inc	iy
	and	a, 0 (iy)
	or	a, a
	ld	a, #0x01
	jr	Z, 00104$
	xor	a, a
00104$:
	ld	l, a
;games/../common/glic80.h:40: }
	ret
_glic_bit_masks:
	.db #0x01	; 1
	.db #0x02	; 2
	.db #0x04	; 4
	.db #0x08	; 8
	.db #0x10	; 16
	.db #0x20	; 32
	.db #0x40	; 64
	.db #0x80	; 128
;games/../common/glic80.h:42: static void glic_delay(unsigned int count) {
;	---------------------------------
; Function glic_delay
; ---------------------------------
_glic_delay:
;games/../common/glic80.h:43: while (count != 0u) {
	pop	de
	pop	bc
	push	bc
	push	de
00101$:
	ld	a, b
	or	a, c
	ret	Z
;games/../common/glic80.h:44: --count;
	dec	bc
;games/../common/glic80.h:47: __endasm;
	nop
;games/../common/glic80.h:49: }
	jr	00101$
;games/../common/glic80.h:51: static void glic_clear_text(void) {
;	---------------------------------
; Function glic_clear_text
; ---------------------------------
_glic_clear_text:
;games/../common/glic80.h:54: for (i = 0; i < GLIC_CVRAM_BYTES; ++i) {
	ld	bc, #0x0000
00102$:
;games/../common/glic80.h:55: GLIC_CVRAM[i] = 0x00u;
	ld	hl, #0x7700
	add	hl, bc
	ld	(hl), #0x00
;games/../common/glic80.h:54: for (i = 0; i < GLIC_CVRAM_BYTES; ++i) {
	inc	bc
	ld	a, b
	sub	a, #0x01
	jr	C, 00102$
;games/../common/glic80.h:57: }
	ret
;games/../common/glic80.h:59: static void glic_fill_graphics(unsigned char value) {
;	---------------------------------
; Function glic_fill_graphics
; ---------------------------------
_glic_fill_graphics:
;games/../common/glic80.h:62: for (i = 0; i < GLIC_GVRAM_BYTES; ++i) {
	ld	bc, #0x0000
00102$:
;games/../common/glic80.h:63: GLIC_GVRAM[i] = value;
	ld	hl, #0x7800
	add	hl, bc
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	ld	(hl), a
;games/../common/glic80.h:62: for (i = 0; i < GLIC_GVRAM_BYTES; ++i) {
	inc	bc
	ld	a, b
	sub	a, #0x08
	jr	C, 00102$
;games/../common/glic80.h:65: }
	ret
;games/../common/glic80.h:67: static void glic_plot(unsigned char x, unsigned char y, unsigned char value) {
;	---------------------------------
; Function glic_plot
; ---------------------------------
_glic_plot:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/../common/glic80.h:71: if ((x >= GLIC_SCREEN_WIDTH) || (y >= 128u)) {
	ld	a, 4 (ix)
	sub	a, #0x80
	jr	NC, 00107$
	ld	a, 5 (ix)
	sub	a, #0x80
;games/../common/glic80.h:72: return;
	jr	NC, 00107$
;games/../common/glic80.h:75: offset = (((unsigned int)(y >> 3)) << 7) + x;
	ld	a, 5 (ix)
	rrca
	rrca
	rrca
	and	a, #0x1f
	ld	l, a
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	ld	c, 4 (ix)
	ld	b, #0x00
	add	hl, bc
	ex	de, hl
;games/../common/glic80.h:76: mask = glic_bit_masks[y & 7u];
	ld	bc, #_glic_bit_masks+0
	ld	a, 5 (ix)
	and	a, #0x07
	ld	l, a
	ld	h, #0x00
	add	hl, bc
	ld	b, (hl)
;games/../common/glic80.h:78: GLIC_GVRAM[offset] |= mask;
	ld	hl, #0x7800
	add	hl, de
	ld	c, (hl)
;games/../common/glic80.h:77: if (value != 0u) {
	ld	a, 6 (ix)
	or	a, a
	jr	Z, 00105$
;games/../common/glic80.h:78: GLIC_GVRAM[offset] |= mask;
	ld	a, c
	or	a, b
	ld	(hl), a
	jr	00107$
00105$:
;games/../common/glic80.h:80: GLIC_GVRAM[offset] &= (unsigned char)~mask;
	ld	a, b
	cpl
	and	a, c
	ld	(hl), a
00107$:
;games/../common/glic80.h:82: }
	pop	ix
	ret
;games/../common/glic80.h:84: static void glic_draw_bitmap8(unsigned char x,
;	---------------------------------
; Function glic_draw_bitmap8
; ---------------------------------
_glic_draw_bitmap8:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/../common/glic80.h:92: for (row = 0u; row < 8u; ++row) {
	ld	c, #0x00
00107$:
;games/../common/glic80.h:93: bits = rows[row];
	ld	l, 6 (ix)
	ld	h, 7 (ix)
	ld	b, #0x00
	add	hl, bc
	ld	l, (hl)
;games/../common/glic80.h:94: mask = 0x80u;
	ld	e, #0x80
;games/../common/glic80.h:95: for (col = 0u; col < 8u; ++col) {
	ld	a, 5 (ix)
	add	a, c
	ld	b, a
	ld	d, #0x00
00105$:
;games/../common/glic80.h:96: if ((bits & mask) != 0u) {
	ld	a, l
	and	a,e
	jr	Z, 00102$
;games/../common/glic80.h:97: glic_plot((unsigned char)(x + col), (unsigned char)(y + row), 1u);
	ld	a, 4 (ix)
	add	a, d
	push	hl
	push	bc
	push	de
	ld	h, #0x01
	ld	l, b
	push	hl
	push	af
	inc	sp
	call	_glic_plot
	pop	af
	inc	sp
	pop	de
	pop	bc
	pop	hl
00102$:
;games/../common/glic80.h:99: mask >>= 1;
	srl	e
;games/../common/glic80.h:95: for (col = 0u; col < 8u; ++col) {
	inc	d
	ld	a, d
	sub	a, #0x08
	jr	C, 00105$
;games/../common/glic80.h:92: for (row = 0u; row < 8u; ++row) {
	inc	c
	ld	a, c
	sub	a, #0x08
	jr	C, 00107$
;games/../common/glic80.h:102: }
	pop	ix
	ret
;games/../common/glic80.h:104: static void glic_draw_tile8(unsigned char cell_x,
;	---------------------------------
; Function glic_draw_tile8
; ---------------------------------
_glic_draw_tile8:
	push	ix
	ld	ix,#0
	add	ix,sp
	push	af
;games/../common/glic80.h:110: offset = (((unsigned int)cell_y) << 7) + (((unsigned int)cell_x) << 3);
	ld	c, 5 (ix)
	xor	a, a
	rr	a
	ld	b, c
	rr	b
	rra
	ld	c, a
	ld	l, 4 (ix)
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, bc
	ex	de, hl
;games/../common/glic80.h:111: for (col = 0u; col < 8u; ++col) {
	ld	c, #0x00
00102$:
;games/../common/glic80.h:112: GLIC_GVRAM[offset + col] = columns[col];
	ld	l, c
	ld	h, #0x00
	add	hl, de
	ld	-2 (ix), l
	ld	a, h
	add	a, #0x78
	ld	-1 (ix), a
	ld	l, 6 (ix)
	ld	h, 7 (ix)
	ld	b, #0x00
	add	hl, bc
	ld	a, (hl)
	pop	hl
	push	hl
	ld	(hl), a
;games/../common/glic80.h:111: for (col = 0u; col < 8u; ++col) {
	inc	c
	ld	a, c
	sub	a, #0x08
	jr	C, 00102$
;games/../common/glic80.h:114: }
	ld	sp, ix
	pop	ix
	ret
;games/../common/glic80.h:116: static void glic_prepare_screen(unsigned char value) {
;	---------------------------------
; Function glic_prepare_screen
; ---------------------------------
_glic_prepare_screen:
;games/../common/glic80.h:117: glic_clear_text();
	call	_glic_clear_text
;games/../common/glic80.h:118: glic_fill_graphics(value);
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_glic_fill_graphics
	inc	sp
;games/../common/glic80.h:119: }
	ret
;games/../common/glic80.h:121: static void glic_fill_page_run(unsigned char page,
;	---------------------------------
; Function glic_fill_page_run
; ---------------------------------
_glic_fill_page_run:
;games/../common/glic80.h:127: p = GLIC_GVRAM + (((unsigned int)page) << 7) + x;
	ld	iy, #2
	add	iy, sp
	ld	c, 0 (iy)
	ld	b, #0x00
	xor	a, a
	rr	b
	ld	b, c
	rr	b
	rra
	ld	c, a
	ld	a, b
	add	a, #0x78
	ld	b, a
	ld	a, c
	ld	hl, #3
	add	hl, sp
	add	a, (hl)
	ld	c, a
	jr	NC, 00117$
	inc	b
00117$:
;games/../common/glic80.h:128: while (width != 0u) {
	ld	e, 2 (iy)
00101$:
	ld	a, e
	or	a, a
	ret	Z
;games/../common/glic80.h:129: *p++ = value;
	ld	iy, #5
	add	iy, sp
	ld	a, 0 (iy)
	ld	(bc), a
	inc	bc
;games/../common/glic80.h:130: --width;
	dec	e
;games/../common/glic80.h:132: }
	jr	00101$
;games/../common/glic80.h:134: static void glic_fill_pages(unsigned char first_page,
;	---------------------------------
; Function glic_fill_pages
; ---------------------------------
_glic_fill_pages:
;games/../common/glic80.h:137: while (page_count != 0u) {
	ld	iy, #2
	add	iy, sp
	ld	b, 0 (iy)
	ld	c, 1 (iy)
00101$:
	ld	a, c
	or	a, a
	ret	Z
;games/../common/glic80.h:138: glic_fill_page_run(first_page, 0u, GLIC_SCREEN_WIDTH, value);
	push	bc
	ld	hl, #6
	add	hl, sp
	ld	d, (hl)
	ld	e,#0x80
	push	de
	xor	a, a
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_fill_page_run
	pop	af
	pop	af
	pop	bc
;games/../common/glic80.h:139: ++first_page;
	inc	b
;games/../common/glic80.h:140: --page_count;
	dec	c
;games/../common/glic80.h:142: }
	jr	00101$
;games/../common/glic80.h:144: static void glic_fill_columns(unsigned char x,
;	---------------------------------
; Function glic_fill_columns
; ---------------------------------
_glic_fill_columns:
;games/../common/glic80.h:149: for (page = 0u; page < GLIC_SCREEN_PAGES; ++page) {
	ld	b, #0x00
00102$:
;games/../common/glic80.h:150: glic_fill_page_run(page, x, width, value);
	push	bc
	ld	iy, #6
	add	iy, sp
	ld	a, 0 (iy)
	push	af
	inc	sp
	ld	a, -1 (iy)
	dec	iy
	push	af
	inc	sp
	ld	a, -1 (iy)
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_fill_page_run
	pop	af
	pop	af
	pop	bc
;games/../common/glic80.h:149: for (page = 0u; page < GLIC_SCREEN_PAGES; ++page) {
	inc	b
	ld	a, b
	sub	a, #0x10
	jr	C, 00102$
;games/../common/glic80.h:152: }
	ret
;games/flappy_bird.c:40: static unsigned char random8(void) {
;	---------------------------------
; Function random8
; ---------------------------------
_random8:
;games/flappy_bird.c:43: bit = (unsigned char)(((rng_state >> 7) ^
	ld	iy, #_rng_state
	ld	a, 0 (iy)
	rlca
	and	a, #0x01
	ld	c, a
;games/flappy_bird.c:44: (rng_state >> 5) ^
	ld	a, 0 (iy)
	rlca
	rlca
	rlca
	and	a, #0x07
	xor	a, c
	ld	c, a
;games/flappy_bird.c:45: (rng_state >> 4) ^
	ld	a, 0 (iy)
	rlca
	rlca
	rlca
	rlca
	and	a, #0x0f
	xor	a, c
;games/flappy_bird.c:46: (rng_state >> 3)) & 1u);
	ld	c, 0 (iy)
	srl	c
	srl	c
	srl	c
	xor	a, c
	and	a, #0x01
;games/flappy_bird.c:47: rng_state = (unsigned char)((rng_state << 1) | bit);
	ld	c, 0 (iy)
	sla	c
	or	a, c
	ld	(_rng_state+0), a
;games/flappy_bird.c:48: return rng_state;
	ld	l, 0 (iy)
;games/flappy_bird.c:49: }
	ret
_bird_wing_up:
	.db #0x18	; 24
	.db #0x3c	; 60
	.db #0x7e	; 126
	.db #0xef	; 239
	.db #0xfe	; 254
	.db #0x5c	; 92
	.db #0x38	; 56	'8'
	.db #0x10	; 16
_bird_wing_down:
	.db #0x18	; 24
	.db #0x3c	; 60
	.db #0x7e	; 126
	.db #0xef	; 239
	.db #0xfe	; 254
	.db #0x38	; 56	'8'
	.db #0x5c	; 92
	.db #0x10	; 16
_bird_crash:
	.db #0x81	; 129
	.db #0x42	; 66	'B'
	.db #0x24	; 36
	.db #0x18	; 24
	.db #0x18	; 24
	.db #0x24	; 36
	.db #0x42	; 66	'B'
	.db #0x81	; 129
_pipe_texture:
	.db #0xff	; 255
	.db #0xdb	; 219
	.db #0xe7	; 231
	.db #0xbd	; 189
_cloud_top:
	.db #0x00	; 0
	.db #0x18	; 24
	.db #0x3c	; 60
	.db #0x7e	; 126
	.db #0x7e	; 126
	.db #0xff	; 255
	.db #0xff	; 255
	.db #0x7e	; 126
	.db #0x3c	; 60
	.db #0x18	; 24
	.db #0x00	; 0
	.db #0x38	; 56	'8'
	.db #0x7c	; 124
	.db #0xfe	; 254
	.db #0xfe	; 254
	.db #0x7c	; 124
	.db #0x38	; 56	'8'
	.db #0x00	; 0
	.db #0x18	; 24
	.db #0x3c	; 60
	.db #0x7e	; 126
	.db #0x3c	; 60
	.db #0x18	; 24
	.db #0x00	; 0
_cloud_bottom:
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x18	; 24
	.db #0x3c	; 60
	.db #0x7e	; 126
	.db #0xff	; 255
	.db #0xff	; 255
	.db #0xff	; 255
	.db #0xff	; 255
	.db #0x7e	; 126
	.db #0x3c	; 60
	.db #0x7c	; 124
	.db #0xfe	; 254
	.db #0xff	; 255
	.db #0xff	; 255
	.db #0xfe	; 254
	.db #0x7c	; 124
	.db #0x3c	; 60
	.db #0x7e	; 126
	.db #0xff	; 255
	.db #0x7e	; 126
	.db #0x3c	; 60
	.db #0x00	; 0
	.db #0x00	; 0
;games/flappy_bird.c:51: static unsigned char flap_pressed(unsigned char buttons) {
;	---------------------------------
; Function flap_pressed
; ---------------------------------
_flap_pressed:
;games/flappy_bird.c:52: return (buttons & FLAP_MASK) != FLAP_MASK;
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	and	a, #0x83
	ld	b, a
	ld	c, #0x00
	ld	a, b
	sub	a, #0x83
	or	a, c
	ld	a, #0x01
	jr	Z, 00104$
	xor	a, a
00104$:
	xor	a, #0x01
	ld	l, a
;games/flappy_bird.c:53: }
	ret
;games/flappy_bird.c:55: static void wait_for_flap_press(void) {
;	---------------------------------
; Function wait_for_flap_press
; ---------------------------------
_wait_for_flap_press:
;games/flappy_bird.c:56: while (flap_pressed(glic_read_buttons()) != 0u) {
00101$:
	call	_glic_read_buttons
	ld	a, l
	push	af
	inc	sp
	call	_flap_pressed
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00104$
;games/flappy_bird.c:57: random8();
	call	_random8
	jr	00101$
;games/flappy_bird.c:59: while (flap_pressed(glic_read_buttons()) == 0u) {
00104$:
	call	_glic_read_buttons
	ld	a, l
	push	af
	inc	sp
	call	_flap_pressed
	ld	a, l
	inc	sp
	or	a, a
	jr	NZ, 00107$
;games/flappy_bird.c:60: random8();
	call	_random8
	jr	00104$
;games/flappy_bird.c:62: while (flap_pressed(glic_read_buttons()) != 0u) {
00107$:
	call	_glic_read_buttons
	ld	a, l
	push	af
	inc	sp
	call	_flap_pressed
	inc	sp
	ld	a, l
	or	a, a
	ret	Z
;games/flappy_bird.c:63: random8();
	call	_random8
;games/flappy_bird.c:65: }
	jr	00107$
;games/flappy_bird.c:67: static volatile unsigned char *text_cell(unsigned char row,
;	---------------------------------
; Function text_cell
; ---------------------------------
_text_cell:
;games/flappy_bird.c:72: while (row != 0u) {
	ld	bc, #0x7700
	ld	iy, #2
	add	iy, sp
	ld	l, 0 (iy)
00101$:
	ld	a, l
	or	a, a
	jr	Z, 00103$
;games/flappy_bird.c:73: p += 16u;
	ld	a, c
	add	a, #0x10
	ld	c, a
	jr	NC, 00117$
	inc	b
00117$:
;games/flappy_bird.c:74: --row;
	dec	l
	jr	00101$
00103$:
;games/flappy_bird.c:76: p += col;
	ld	a, c
	ld	hl, #3
	add	hl, sp
	add	a, (hl)
	ld	l, a
	jr	NC, 00118$
	inc	b
00118$:
	ld	h, b
;games/flappy_bird.c:77: return p;
;games/flappy_bird.c:78: }
	ret
;games/flappy_bird.c:80: static void text_put(unsigned char row, unsigned char col, unsigned char ch) {
;	---------------------------------
; Function text_put
; ---------------------------------
_text_put:
;games/flappy_bird.c:81: if ((row >= 16u) || (col >= 16u)) {
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	sub	a, #0x10
	ret	NC
	ld	a, 1 (iy)
	sub	a, #0x10
;games/flappy_bird.c:82: return;
	ret	NC
;games/flappy_bird.c:84: *text_cell(row, col) = ch;
	ld	iy, #3
	add	iy, sp
	ld	h, 0 (iy)
	ld	l, -1 (iy)
	push	hl
	call	_text_cell
	pop	af
	ld	iy, #4
	add	iy, sp
	ld	a, 0 (iy)
	ld	(hl), a
;games/flappy_bird.c:85: }
	ret
;games/flappy_bird.c:87: static void text_clear_row(unsigned char row) {
;	---------------------------------
; Function text_clear_row
; ---------------------------------
_text_clear_row:
;games/flappy_bird.c:90: for (col = 0u; col < 16u; ++col) {
	ld	b, #0x00
00102$:
;games/flappy_bird.c:91: text_put(row, col, 0u);
	push	bc
	xor	a, a
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	hl, #6
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
	pop	bc
;games/flappy_bird.c:90: for (col = 0u; col < 16u; ++col) {
	inc	b
	ld	a, b
	sub	a, #0x10
	jr	C, 00102$
;games/flappy_bird.c:93: }
	ret
;games/flappy_bird.c:95: static void text_write(unsigned char row, unsigned char col, const char *text) {
;	---------------------------------
; Function text_write
; ---------------------------------
_text_write:
;games/flappy_bird.c:96: while ((*text != 0) && (col < 16u)) {
	ld	iy, #4
	add	iy, sp
	ld	l, 0 (iy)
	ld	h, 1 (iy)
	ld	b, -1 (iy)
00102$:
	ld	d, (hl)
	ld	a, d
	or	a, a
	ret	Z
	ld	a, b
	sub	a, #0x10
	ret	NC
;games/flappy_bird.c:97: text_put(row, col, (unsigned char)*text);
	push	hl
	push	bc
	ld	e, b
	push	de
	ld	hl, #8
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
	pop	bc
	pop	hl
;games/flappy_bird.c:98: ++text;
	inc	hl
;games/flappy_bird.c:99: ++col;
	inc	b
;games/flappy_bird.c:101: }
	jr	00102$
;games/flappy_bird.c:103: static void text_write_u8_3(unsigned char row,
;	---------------------------------
; Function text_write_u8_3
; ---------------------------------
_text_write_u8_3:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/flappy_bird.c:110: while (value >= 100u) {
	ld	d, 6 (ix)
	ld	c, #0x00
00101$:
;games/flappy_bird.c:111: value = (unsigned char)(value - 100u);
	ld	a,d
	cp	a,#0x64
	jr	C, 00113$
	add	a, #0x9c
	ld	d, a
;games/flappy_bird.c:112: ++hundreds;
	inc	c
	jr	00101$
00113$:
;games/flappy_bird.c:115: while (value >= 10u) {
	ld	e, #0x00
00104$:
;games/flappy_bird.c:116: value = (unsigned char)(value - 10u);
	ld	a,d
	cp	a,#0x0a
	jr	C, 00106$
	add	a, #0xf6
	ld	d, a
;games/flappy_bird.c:117: ++tens;
	inc	e
	jr	00104$
00106$:
;games/flappy_bird.c:119: text_put(row, col, (unsigned char)('0' + hundreds));
	ld	a, c
	add	a, #0x30
	push	de
	push	af
	inc	sp
	ld	h, 5 (ix)
	ld	l, 4 (ix)
	push	hl
	call	_text_put
	pop	af
	inc	sp
	pop	de
;games/flappy_bird.c:120: text_put(row, (unsigned char)(col + 1u), (unsigned char)('0' + tens));
	ld	a, e
	add	a, #0x30
	ld	b, 5 (ix)
	inc	b
	push	de
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
	pop	de
;games/flappy_bird.c:123: (unsigned char)('0' + value));
	ld	a, d
	add	a, #0x30
;games/flappy_bird.c:122: (unsigned char)(col + 2u),
	ld	b, 5 (ix)
	inc	b
	inc	b
;games/flappy_bird.c:121: text_put(row,
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
;games/flappy_bird.c:124: }
	pop	ix
	ret
;games/flappy_bird.c:126: static void draw_score(void) {
;	---------------------------------
; Function draw_score
; ---------------------------------
_draw_score:
;games/flappy_bird.c:127: text_clear_row(0u);
	xor	a, a
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;games/flappy_bird.c:128: text_write(0u, 0u, "SCORE");
	ld	hl, #___str_0
	push	hl
	xor	a, a
	push	af
	inc	sp
	xor	a, a
	push	af
	inc	sp
	call	_text_write
	pop	af
	pop	af
;games/flappy_bird.c:129: text_write_u8_3(0u, 6u, score);
	ld	a,(#_score + 0)
	ld	d,a
	ld	e,#0x06
	push	de
	xor	a, a
	push	af
	inc	sp
	call	_text_write_u8_3
	pop	af
	inc	sp
;games/flappy_bird.c:130: }
	ret
___str_0:
	.ascii "SCORE"
	.db 0x00
;games/flappy_bird.c:132: static unsigned char cloud_byte(unsigned char x,
;	---------------------------------
; Function cloud_byte
; ---------------------------------
_cloud_byte:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/flappy_bird.c:138: if ((x < cloud_x) || (x >= (unsigned char)(cloud_x + 24u))) {
	ld	a, 4 (ix)
	sub	a, 6 (ix)
	jr	C, 00101$
	ld	a, 6 (ix)
	add	a, #0x18
	ld	c, a
	ld	a, 4 (ix)
	sub	a, c
	jr	C, 00102$
00101$:
;games/flappy_bird.c:139: return GLIC_BLACK;
	ld	l, #0x00
	jr	00108$
00102$:
;games/flappy_bird.c:141: local_x = (unsigned char)(x - cloud_x);
	ld	a, 4 (ix)
	sub	a, 6 (ix)
	ld	e, a
;games/flappy_bird.c:142: if (page == top_page) {
	ld	a, 5 (ix)
	sub	a, 7 (ix)
	jr	NZ, 00105$
;games/flappy_bird.c:143: return cloud_top[local_x];
	ld	hl, #_cloud_top+0
	ld	d, #0x00
	add	hl, de
	ld	l, (hl)
	jr	00108$
00105$:
;games/flappy_bird.c:145: if (page == (unsigned char)(top_page + 1u)) {
	ld	c, 7 (ix)
	inc	c
	ld	a, 5 (ix)
	sub	a, c
	jr	NZ, 00107$
;games/flappy_bird.c:146: return cloud_bottom[local_x];
	ld	hl, #_cloud_bottom+0
	ld	d, #0x00
	add	hl, de
	ld	l, (hl)
	jr	00108$
00107$:
;games/flappy_bird.c:148: return GLIC_BLACK;
	ld	l, #0x00
00108$:
;games/flappy_bird.c:149: }
	pop	ix
	ret
;games/flappy_bird.c:151: static unsigned char background_byte(unsigned char x, unsigned char page) {
;	---------------------------------
; Function background_byte
; ---------------------------------
_background_byte:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/flappy_bird.c:154: bits = cloud_byte(x, page, 7u, 2u);
	ld	de, #0x0207
	push	de
	ld	h, 5 (ix)
	ld	l, 4 (ix)
	push	hl
	call	_cloud_byte
	pop	af
	pop	af
;games/flappy_bird.c:155: if (bits != GLIC_BLACK) {
	ld	a, l
	or	a, a
;games/flappy_bird.c:156: return bits;
	jr	NZ, 00120$
;games/flappy_bird.c:158: bits = cloud_byte(x, page, 62u, 4u);
	ld	de, #0x043e
	push	de
	ld	h, 5 (ix)
	ld	l, 4 (ix)
	push	hl
	call	_cloud_byte
	pop	af
	pop	af
;games/flappy_bird.c:159: if (bits != GLIC_BLACK) {
	ld	a, l
	or	a, a
;games/flappy_bird.c:160: return bits;
	jr	NZ, 00120$
;games/flappy_bird.c:164: if (((x & 31u) == 4u) || ((x & 63u) == 45u)) {
	ld	e, 4 (ix)
	ld	a, e
	and	a, #0x3f
	ld	c, a
	ld	b, #0x00
;games/flappy_bird.c:163: if (page == 1u) {
	ld	a, 5 (ix)
	dec	a
	jr	NZ, 00118$
;games/flappy_bird.c:164: if (((x & 31u) == 4u) || ((x & 63u) == 45u)) {
	ld	a, e
	and	a, #0x1f
	ld	e, a
	ld	d, #0x00
	ld	a, e
	sub	a, #0x04
	or	a, d
	jr	Z, 00105$
	ld	a, c
	sub	a, #0x2d
	or	a, b
	jr	NZ, 00119$
00105$:
;games/flappy_bird.c:165: return 0x08u;
	ld	l, #0x08
	jr	00120$
00118$:
;games/flappy_bird.c:167: } else if (page == 8u) {
	ld	a, 5 (ix)
	sub	a, #0x08
	jr	NZ, 00115$
;games/flappy_bird.c:168: if ((x & 63u) == 22u) {
	ld	a, c
	sub	a, #0x16
	or	a, b
	jr	NZ, 00119$
;games/flappy_bird.c:169: return 0x20u;
	ld	l, #0x20
	jr	00120$
00115$:
;games/flappy_bird.c:171: } else if (page == 15u) {
	ld	a, 5 (ix)
	sub	a, #0x0f
	jr	NZ, 00119$
;games/flappy_bird.c:172: if ((x & 2u) == 0u) {
	bit	1, 4 (ix)
	jr	NZ, 00111$
;games/flappy_bird.c:173: return 0xc0u;
	ld	l, #0xc0
	jr	00120$
00111$:
;games/flappy_bird.c:175: return 0xa0u;
	ld	l, #0xa0
	jr	00120$
00119$:
;games/flappy_bird.c:178: return GLIC_BLACK;
	ld	l, #0x00
00120$:
;games/flappy_bird.c:179: }
	pop	ix
	ret
;games/flappy_bird.c:181: static void clear_scene(void) {
;	---------------------------------
; Function clear_scene
; ---------------------------------
_clear_scene:
;games/flappy_bird.c:185: for (page = 0u; page < GLIC_SCREEN_PAGES; ++page) {
	ld	c, #0x00
;games/flappy_bird.c:186: for (x = 0u; x < GLIC_SCREEN_WIDTH; ++x) {
00109$:
	ld	b, #0x00
00103$:
;games/flappy_bird.c:187: GLIC_GVRAM[(((unsigned int)page) << 7) + x] =
	ld	l, c
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	ld	a, b
	ld	d, #0x00
	ld	e, a
	add	hl, de
	ld	de, #0x7800
	add	hl, de
;games/flappy_bird.c:188: background_byte(x, page);
	push	hl
	push	bc
	ld	a, c
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_background_byte
	pop	af
	ld	a, l
	pop	bc
	pop	hl
	ld	(hl), a
;games/flappy_bird.c:186: for (x = 0u; x < GLIC_SCREEN_WIDTH; ++x) {
	inc	b
	ld	a, b
	sub	a, #0x80
	jr	C, 00103$
;games/flappy_bird.c:185: for (page = 0u; page < GLIC_SCREEN_PAGES; ++page) {
	inc	c
	ld	a, c
	sub	a, #0x10
	jr	C, 00109$
;games/flappy_bird.c:191: }
	ret
;games/flappy_bird.c:193: static unsigned char pipe_byte(unsigned char pipe_x,
;	---------------------------------
; Function pipe_byte
; ---------------------------------
_pipe_byte:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/flappy_bird.c:200: if ((page >= 15u) || (x < pipe_x)) {
	ld	a, 7 (ix)
	sub	a, #0x0f
	jr	NC, 00101$
	ld	a, 6 (ix)
	sub	a, 4 (ix)
	jr	NC, 00102$
00101$:
;games/flappy_bird.c:201: return background_byte(x, page);
	ld	h, 7 (ix)
	ld	l, 6 (ix)
	push	hl
	call	_background_byte
	pop	af
	jr	00114$
00102$:
;games/flappy_bird.c:204: local_x = (unsigned char)(x - pipe_x);
	ld	a, 6 (ix)
	sub	a, 4 (ix)
;games/flappy_bird.c:205: if (local_x >= PIPE_WIDTH) {
	ld	c, a
	sub	a, #0x0e
	jr	C, 00105$
;games/flappy_bird.c:206: return background_byte(x, page);
	ld	h, 7 (ix)
	ld	l, 6 (ix)
	push	hl
	call	_background_byte
	pop	af
	jr	00114$
00105$:
;games/flappy_bird.c:209: gap_end = (unsigned char)(gap_page + PIPE_GAP_PAGES);
	ld	a, 5 (ix)
	add	a, #0x06
	ld	b, a
;games/flappy_bird.c:210: if ((page >= gap_page) && (page < gap_end)) {
	ld	a, 7 (ix)
	sub	a, 5 (ix)
	jr	C, 00107$
	ld	a, 7 (ix)
	sub	a, b
	jr	NC, 00107$
;games/flappy_bird.c:211: return background_byte(x, page);
	ld	h, 7 (ix)
	ld	l, 6 (ix)
	push	hl
	call	_background_byte
	pop	af
	jr	00114$
00107$:
;games/flappy_bird.c:214: if ((local_x == 0u) || (local_x == (unsigned char)(PIPE_WIDTH - 1u)) ||
	ld	a, c
	or	a, a
	jr	Z, 00109$
	ld	a, c
	sub	a, #0x0d
	jr	Z, 00109$
;games/flappy_bird.c:215: (page == (unsigned char)(gap_page - 1u)) || (page == gap_end)) {
	ld	e, 5 (ix)
	dec	e
	ld	a, 7 (ix)
	sub	a, e
	jr	Z, 00109$
	ld	a, 7 (ix)
	sub	a, b
	jr	NZ, 00110$
00109$:
;games/flappy_bird.c:216: return GLIC_WHITE;
	ld	l, #0xff
	jr	00114$
00110$:
;games/flappy_bird.c:219: return pipe_texture[(local_x + page) & 3u];
	ld	a, c
	add	a, 7 (ix)
	and	a, #0x03
	ld	c, a
	ld	b, #0x00
	ld	hl, #_pipe_texture
	add	hl, bc
	ld	l, (hl)
00114$:
;games/flappy_bird.c:220: }
	pop	ix
	ret
;games/flappy_bird.c:222: static void restore_scene_region(unsigned char x,
;	---------------------------------
; Function restore_scene_region
; ---------------------------------
_restore_scene_region:
	push	ix
	ld	ix,#0
	add	ix,sp
	push	af
;games/flappy_bird.c:231: while (width != 0u) {
	ld	a, 6 (ix)
	add	a, 7 (ix)
	ld	-2 (ix), a
	ld	c, 4 (ix)
	ld	e, 5 (ix)
00106$:
	ld	a, e
	or	a, a
	jr	Z, 00109$
;games/flappy_bird.c:232: if (x < GLIC_SCREEN_WIDTH) {
	ld	a, c
	sub	a, #0x80
	jr	NC, 00105$
;games/flappy_bird.c:233: p = page;
	ld	a, 6 (ix)
	ld	-1 (ix), a
;games/flappy_bird.c:234: while (p < (unsigned char)(page + page_count)) {
00101$:
	ld	a, -1 (ix)
	sub	a, -2 (ix)
	jr	NC, 00105$
;games/flappy_bird.c:235: offset = (((unsigned int)p) << 7) + x;
	ld	l, -1 (ix)
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	ld	a, c
	ld	b, #0x00
	add	a, l
	ld	l, a
	ld	a, b
	adc	a, h
;games/flappy_bird.c:236: GLIC_GVRAM[offset] = pipe_byte(pipe_x, gap_page, x, p);
	add	a, #0x78
	ld	h, a
	push	hl
	push	bc
	push	de
	ld	b, -1 (ix)
	push	bc
	ld	h, 9 (ix)
	ld	l, 8 (ix)
	push	hl
	call	_pipe_byte
	pop	af
	pop	af
	ld	a, l
	pop	de
	pop	bc
	pop	hl
	ld	(hl), a
;games/flappy_bird.c:237: ++p;
	inc	-1 (ix)
	jr	00101$
00105$:
;games/flappy_bird.c:240: ++x;
	inc	c
;games/flappy_bird.c:241: --width;
	dec	e
	jr	00106$
00109$:
;games/flappy_bird.c:243: }
	ld	sp, ix
	pop	ix
	ret
;games/flappy_bird.c:245: static void erase_pipe(unsigned char pipe_x) {
;	---------------------------------
; Function erase_pipe
; ---------------------------------
_erase_pipe:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/flappy_bird.c:250: for (i = 0u; i < PIPE_WIDTH; ++i) {
	ld	c, #0x00
00108$:
;games/flappy_bird.c:251: col = (unsigned char)(pipe_x + i);
	ld	a, 4 (ix)
	add	a, c
;games/flappy_bird.c:252: if (col >= GLIC_SCREEN_WIDTH) {
	ld	b, a
	sub	a, #0x80
	jr	NC, 00104$
;games/flappy_bird.c:255: for (page = 0u; page < 15u; ++page) {
	ld	e, #0x00
00106$:
;games/flappy_bird.c:256: GLIC_GVRAM[(((unsigned int)page) << 7) + col] =
	ld	l, e
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	ld	a, b
	ld	d, #0x00
	add	a, l
	ld	l, a
	ld	a, d
	adc	a, h
	add	a, #0x78
	ld	h, a
;games/flappy_bird.c:257: background_byte(col, page);
	push	hl
	push	bc
	push	de
	ld	a, e
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_background_byte
	pop	af
	ld	a, l
	pop	de
	pop	bc
	pop	hl
	ld	(hl), a
;games/flappy_bird.c:255: for (page = 0u; page < 15u; ++page) {
	inc	e
	ld	a, e
	sub	a, #0x0f
	jr	C, 00106$
00104$:
;games/flappy_bird.c:250: for (i = 0u; i < PIPE_WIDTH; ++i) {
	inc	c
	ld	a, c
	sub	a, #0x0e
	jr	C, 00108$
;games/flappy_bird.c:260: }
	pop	ix
	ret
;games/flappy_bird.c:262: static void erase_pipe_column(unsigned char x) {
;	---------------------------------
; Function erase_pipe_column
; ---------------------------------
_erase_pipe_column:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/flappy_bird.c:265: if (x >= GLIC_SCREEN_WIDTH) {
	ld	a, 4 (ix)
	sub	a, #0x80
;games/flappy_bird.c:266: return;
;games/flappy_bird.c:268: for (page = 0u; page < 15u; ++page) {
	jr	NC, 00106$
	ld	b, #0x00
00104$:
;games/flappy_bird.c:269: GLIC_GVRAM[(((unsigned int)page) << 7) + x] =
	ld	l, b
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	ld	e, 4 (ix)
	ld	d, #0x00
	add	hl, de
	ld	de, #0x7800
	add	hl, de
;games/flappy_bird.c:270: background_byte(x, page);
	push	hl
	push	bc
	push	bc
	inc	sp
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_background_byte
	pop	af
	ld	a, l
	pop	bc
	pop	hl
	ld	(hl), a
;games/flappy_bird.c:268: for (page = 0u; page < 15u; ++page) {
	inc	b
	ld	a, b
	sub	a, #0x0f
	jr	C, 00104$
00106$:
;games/flappy_bird.c:272: }
	pop	ix
	ret
;games/flappy_bird.c:274: static void draw_pipe_column(unsigned char pipe_x,
;	---------------------------------
; Function draw_pipe_column
; ---------------------------------
_draw_pipe_column:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/flappy_bird.c:279: if (x >= GLIC_SCREEN_WIDTH) {
	ld	a, 6 (ix)
	sub	a, #0x80
;games/flappy_bird.c:280: return;
;games/flappy_bird.c:282: for (page = 0u; page < 15u; ++page) {
	jr	NC, 00106$
	ld	b, #0x00
00104$:
;games/flappy_bird.c:283: GLIC_GVRAM[(((unsigned int)page) << 7) + x] =
	ld	l, b
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	ld	e, 6 (ix)
	ld	d, #0x00
	add	hl, de
	ld	de, #0x7800
	add	hl, de
;games/flappy_bird.c:284: pipe_byte(pipe_x, gap_page, x, page);
	push	hl
	push	bc
	push	bc
	inc	sp
	ld	h, 6 (ix)
	ld	l, 5 (ix)
	push	hl
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_pipe_byte
	pop	af
	pop	af
	ld	a, l
	pop	bc
	pop	hl
	ld	(hl), a
;games/flappy_bird.c:282: for (page = 0u; page < 15u; ++page) {
	inc	b
	ld	a, b
	sub	a, #0x0f
	jr	C, 00104$
00106$:
;games/flappy_bird.c:286: }
	pop	ix
	ret
;games/flappy_bird.c:288: static void draw_pipe(unsigned char pipe_x, unsigned char gap_page) {
;	---------------------------------
; Function draw_pipe
; ---------------------------------
_draw_pipe:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/flappy_bird.c:293: for (i = 0u; i < PIPE_WIDTH; ++i) {
	ld	c, #0x00
00108$:
;games/flappy_bird.c:294: col = (unsigned char)(pipe_x + i);
	ld	a, 4 (ix)
	add	a, c
;games/flappy_bird.c:295: if (col >= GLIC_SCREEN_WIDTH) {
	ld	b, a
	sub	a, #0x80
	jr	NC, 00104$
;games/flappy_bird.c:298: for (page = 0u; page < 15u; ++page) {
	ld	e, #0x00
00106$:
;games/flappy_bird.c:299: GLIC_GVRAM[(((unsigned int)page) << 7) + col] =
	ld	l, e
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	ld	a, b
	ld	d, #0x00
	add	a, l
	ld	l, a
	ld	a, d
	adc	a, h
	add	a, #0x78
	ld	h, a
;games/flappy_bird.c:300: pipe_byte(pipe_x, gap_page, col, page);
	push	hl
	push	bc
	push	de
	ld	a, e
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	h, 5 (ix)
	ld	l, 4 (ix)
	push	hl
	call	_pipe_byte
	pop	af
	pop	af
	ld	a, l
	pop	de
	pop	bc
	pop	hl
	ld	(hl), a
;games/flappy_bird.c:298: for (page = 0u; page < 15u; ++page) {
	inc	e
	ld	a, e
	sub	a, #0x0f
	jr	C, 00106$
00104$:
;games/flappy_bird.c:293: for (i = 0u; i < PIPE_WIDTH; ++i) {
	inc	c
	ld	a, c
	sub	a, #0x0e
	jr	C, 00108$
;games/flappy_bird.c:303: }
	pop	ix
	ret
;games/flappy_bird.c:305: static void move_pipe_left(unsigned char old_pipe_x,
;	---------------------------------
; Function move_pipe_left
; ---------------------------------
_move_pipe_left:
;games/flappy_bird.c:310: old_right = (unsigned char)(old_pipe_x + PIPE_WIDTH - 1u);
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	add	a, #0x0d
;games/flappy_bird.c:311: if (old_right < GLIC_SCREEN_WIDTH) {
	cp	a, #0x80
	jr	NC, 00102$
;games/flappy_bird.c:312: erase_pipe_column(old_right);
	push	af
	inc	sp
	call	_erase_pipe_column
	inc	sp
00102$:
;games/flappy_bird.c:314: draw_pipe_column(pipe_x, gap_page, pipe_x);
	ld	iy, #3
	add	iy, sp
	ld	a, 0 (iy)
	push	af
	inc	sp
	ld	a, 1 (iy)
	inc	iy
	push	af
	inc	sp
	ld	a, -1 (iy)
	push	af
	inc	sp
	call	_draw_pipe_column
	pop	af
	inc	sp
;games/flappy_bird.c:315: }
	ret
;games/flappy_bird.c:317: static void erase_bird(unsigned char bird_y,
;	---------------------------------
; Function erase_bird
; ---------------------------------
_erase_bird:
;games/flappy_bird.c:323: page = bird_y >> 3;
	ld	iy, #2
	add	iy, sp
	ld	b, 0 (iy)
	srl	b
	srl	b
	srl	b
;games/flappy_bird.c:324: last_page = (unsigned char)((bird_y + 7u) >> 3);
	ld	e, 0 (iy)
	ld	d, #0x00
	ld	hl, #0x0007
	add	hl, de
	srl	h
	rr	l
	srl	h
	rr	l
	srl	h
	rr	l
	ld	a, l
;games/flappy_bird.c:328: (unsigned char)(last_page - page + 1u),
	sub	a, b
	inc	a
;games/flappy_bird.c:325: restore_scene_region(BIRD_X,
	ld	h, 2 (iy)
	inc	iy
	inc	iy
	push	hl
	inc	sp
	ld	h, -1 (iy)
	push	hl
	inc	sp
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	de, #0x0818
	push	de
	call	_restore_scene_region
	ld	hl, #6
	add	hl, sp
	ld	sp, hl
;games/flappy_bird.c:331: }
	ret
;games/flappy_bird.c:333: static void draw_bird(unsigned char bird_y, unsigned char frame) {
;	---------------------------------
; Function draw_bird
; ---------------------------------
_draw_bird:
;games/flappy_bird.c:334: if ((frame & 4u) == 0u) {
	ld	hl, #3
	add	hl, sp
	bit	2, (hl)
	jr	NZ, 00102$
;games/flappy_bird.c:335: glic_draw_bitmap8(BIRD_X, bird_y, bird_wing_up);
	ld	hl, #_bird_wing_up
	push	hl
	ld	hl, #4
	add	hl, sp
	ld	d, (hl)
	ld	e,#0x18
	push	de
	call	_glic_draw_bitmap8
	pop	af
	pop	af
	ret
00102$:
;games/flappy_bird.c:337: glic_draw_bitmap8(BIRD_X, bird_y, bird_wing_down);
	ld	hl, #_bird_wing_down
	push	hl
	ld	hl, #4
	add	hl, sp
	ld	d, (hl)
	ld	e,#0x18
	push	de
	call	_glic_draw_bitmap8
	pop	af
	pop	af
;games/flappy_bird.c:339: }
	ret
;games/flappy_bird.c:341: static unsigned char bird_hits_pipe(unsigned char pipe_x,
;	---------------------------------
; Function bird_hits_pipe
; ---------------------------------
_bird_hits_pipe:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/flappy_bird.c:348: pipe_right = (unsigned char)(pipe_x + PIPE_WIDTH - 1u);
	ld	a, 4 (ix)
	add	a, #0x0d
	ld	c, a
;games/flappy_bird.c:349: if (((unsigned char)(BIRD_X + 7u) < pipe_x) || (BIRD_X > pipe_right)) {
	ld	a, #0x1f
	sub	a, 4 (ix)
	jr	C, 00101$
	ld	a, c
	sub	a, #0x18
	jr	NC, 00102$
00101$:
;games/flappy_bird.c:350: return 0u;
	ld	l, #0x00
	jr	00107$
00102$:
;games/flappy_bird.c:353: bird_top_page = bird_y >> 3;
	ld	c, 6 (ix)
	srl	c
	srl	c
	srl	c
;games/flappy_bird.c:354: bird_bottom_page = (unsigned char)((bird_y + 7u) >> 3);
	ld	e, 6 (ix)
	ld	d, #0x00
	ld	hl, #0x0007
	add	hl, de
	srl	h
	rr	l
	srl	h
	rr	l
	srl	h
	rr	l
;games/flappy_bird.c:355: if ((bird_top_page < gap_page) ||
	ld	a, c
	sub	a, 5 (ix)
	jr	C, 00104$
;games/flappy_bird.c:356: (bird_bottom_page >= (unsigned char)(gap_page + PIPE_GAP_PAGES))) {
	ld	a, 5 (ix)
	add	a, #0x06
	ld	c, a
	ld	a, l
	sub	a, c
	jr	C, 00105$
00104$:
;games/flappy_bird.c:357: return 1u;
	ld	l, #0x01
	jr	00107$
00105$:
;games/flappy_bird.c:360: return 0u;
	ld	l, #0x00
00107$:
;games/flappy_bird.c:361: }
	pop	ix
	ret
;games/flappy_bird.c:363: static void draw_crash(unsigned char bird_y) {
;	---------------------------------
; Function draw_crash
; ---------------------------------
_draw_crash:
;games/flappy_bird.c:366: glic_draw_bitmap8(BIRD_X, bird_y, bird_crash);
	ld	hl, #_bird_crash
	push	hl
	ld	hl, #4
	add	hl, sp
	ld	d, (hl)
	ld	e,#0x18
	push	de
	call	_glic_draw_bitmap8
	pop	af
	pop	af
;games/flappy_bird.c:367: for (i = 0u; i < GLIC_SCREEN_WIDTH; ++i) {
	ld	b, #0x00
00102$:
;games/flappy_bird.c:368: glic_plot(i, i, 1u);
	push	bc
	ld	a, #0x01
	push	af
	inc	sp
	ld	c, b
	push	bc
	call	_glic_plot
	pop	af
	inc	sp
	pop	bc
;games/flappy_bird.c:369: glic_plot((unsigned char)(127u - i), i, 1u);
	ld	a, #0x7f
	sub	a, b
	push	bc
	ld	h, #0x01
	ld	l, b
	push	hl
	push	af
	inc	sp
	call	_glic_plot
	pop	af
	inc	sp
	pop	bc
;games/flappy_bird.c:367: for (i = 0u; i < GLIC_SCREEN_WIDTH; ++i) {
	inc	b
	ld	a, b
	sub	a, #0x80
	jr	C, 00102$
;games/flappy_bird.c:371: }
	ret
;games/flappy_bird.c:373: static void draw_title_screen(void) {
;	---------------------------------
; Function draw_title_screen
; ---------------------------------
_draw_title_screen:
;games/flappy_bird.c:374: glic_clear_text();
	call	_glic_clear_text
;games/flappy_bird.c:375: clear_scene();
	call	_clear_scene
;games/flappy_bird.c:376: draw_pipe(96u, 5u);
	ld	de, #0x0560
	push	de
	call	_draw_pipe
	pop	af
;games/flappy_bird.c:377: draw_bird(56u, 0u);
	xor	a, a
	ld	d,a
	ld	e,#0x38
	push	de
	call	_draw_bird
;games/flappy_bird.c:378: text_write(2u, 2u, "FLAPPY BIRD");
	ld	hl, #___str_1
	ex	(sp),hl
	ld	de, #0x0202
	push	de
	call	_text_write
	pop	af
;games/flappy_bird.c:379: text_write(5u, 1u, "FLAP TO START");
	ld	hl, #___str_2
	ex	(sp),hl
	ld	de, #0x0105
	push	de
	call	_text_write
	pop	af
;games/flappy_bird.c:380: text_write(7u, 2u, "UP/A FLAP");
	ld	hl, #___str_3
	ex	(sp),hl
	ld	de, #0x0207
	push	de
	call	_text_write
	pop	af
;games/flappy_bird.c:381: text_write(11u, 2u, "DODGE PIPES");
	ld	hl, #___str_4
	ex	(sp),hl
	ld	de, #0x020b
	push	de
	call	_text_write
	pop	af
	pop	af
;games/flappy_bird.c:382: }
	ret
___str_1:
	.ascii "FLAPPY BIRD"
	.db 0x00
___str_2:
	.ascii "FLAP TO START"
	.db 0x00
___str_3:
	.ascii "UP/A FLAP"
	.db 0x00
___str_4:
	.ascii "DODGE PIPES"
	.db 0x00
;games/flappy_bird.c:384: static void draw_game_over_text(void) {
;	---------------------------------
; Function draw_game_over_text
; ---------------------------------
_draw_game_over_text:
;games/flappy_bird.c:385: text_clear_row(0u);
	xor	a, a
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;games/flappy_bird.c:386: text_clear_row(5u);
	ld	a, #0x05
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;games/flappy_bird.c:387: text_clear_row(6u);
	ld	a, #0x06
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;games/flappy_bird.c:388: text_clear_row(7u);
	ld	a, #0x07
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;games/flappy_bird.c:389: text_clear_row(8u);
	ld	a, #0x08
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;games/flappy_bird.c:390: text_clear_row(10u);
	ld	a, #0x0a
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;games/flappy_bird.c:391: text_write(5u, 3u, "GAME OVER");
	ld	hl, #___str_5
	push	hl
	ld	de, #0x0305
	push	de
	call	_text_write
	pop	af
;games/flappy_bird.c:392: text_write(7u, 4u, "SCORE");
	ld	hl, #___str_6
	ex	(sp),hl
	ld	de, #0x0407
	push	de
	call	_text_write
	pop	af
	pop	af
;games/flappy_bird.c:393: text_write_u8_3(7u, 10u, score);
	ld	a,(#_score + 0)
	ld	d,a
	ld	e,#0x0a
	push	de
	ld	a, #0x07
	push	af
	inc	sp
	call	_text_write_u8_3
;games/flappy_bird.c:394: text_write(10u, 3u, "FLAP MENU");
	inc	sp
	ld	hl,#___str_7
	ex	(sp),hl
	ld	de, #0x030a
	push	de
	call	_text_write
	pop	af
	pop	af
;games/flappy_bird.c:395: }
	ret
___str_5:
	.ascii "GAME OVER"
	.db 0x00
___str_6:
	.ascii "SCORE"
	.db 0x00
___str_7:
	.ascii "FLAP MENU"
	.db 0x00
;games/flappy_bird.c:397: void main(void) {
;	---------------------------------
; Function main
; ---------------------------------
_main::
	push	ix
	ld	ix,#0
	add	ix,sp
	ld	hl, #-12
	add	hl, sp
	ld	sp, hl
;games/flappy_bird.c:413: glic_clear_text();
	call	_glic_clear_text
;games/flappy_bird.c:414: rng_state = 0x5au;
	ld	hl, #_rng_state
	ld	(hl), #0x5a
;games/flappy_bird.c:416: while (1) {
00134$:
;games/flappy_bird.c:417: draw_title_screen();
	call	_draw_title_screen
;games/flappy_bird.c:418: wait_for_flap_press();
	call	_wait_for_flap_press
;games/flappy_bird.c:419: clear_scene();
	call	_clear_scene
;games/flappy_bird.c:420: glic_clear_text();
	call	_glic_clear_text
;games/flappy_bird.c:421: bird_y = 56u;
	ld	-4 (ix), #0x38
;games/flappy_bird.c:422: velocity = 0;
	ld	-3 (ix), #0
;games/flappy_bird.c:423: pipe_x = 112u;
	ld	-2 (ix), #0x70
;games/flappy_bird.c:424: gap_page = 5u;
	ld	-12 (ix), #0x05
;games/flappy_bird.c:425: pipe_scored = 0u;
	ld	-11 (ix), #0
;games/flappy_bird.c:426: score = 0u;
	ld	hl, #_score
	ld	(hl), #0x00
;games/flappy_bird.c:428: last_buttons = GLIC_BUTTONS_NONE;
	ld	-10 (ix), #0xff
;games/flappy_bird.c:429: game_over = 0u;
	ld	-9 (ix), #0
;games/flappy_bird.c:430: draw_pipe(pipe_x, gap_page);
	ld	de, #0x0570
	push	de
	call	_draw_pipe
	pop	af
;games/flappy_bird.c:431: draw_bird(bird_y, frame);
	xor	a, a
	ld	d,a
	ld	e,#0x38
	push	de
	call	_draw_bird
	pop	af
;games/flappy_bird.c:432: draw_score();
	call	_draw_score
;games/flappy_bird.c:434: while (game_over == 0u) {
	ld	-1 (ix), #0
00130$:
	ld	a, -9 (ix)
	or	a, a
	jp	NZ, 00132$
;games/flappy_bird.c:435: old_bird_y = bird_y;
	ld	a, -4 (ix)
	ld	-8 (ix), a
;games/flappy_bird.c:436: old_pipe_x = pipe_x;
	ld	a, -2 (ix)
	ld	-7 (ix), a
;games/flappy_bird.c:437: old_gap_page = gap_page;
	ld	a, -12 (ix)
	ld	-6 (ix), a
;games/flappy_bird.c:438: buttons = glic_read_buttons();
	call	_glic_read_buttons
;games/flappy_bird.c:439: if ((flap_pressed(last_buttons) == 0u) &&
	push	hl
	ld	a, -10 (ix)
	push	af
	inc	sp
	call	_flap_pressed
	ld	a, l
	inc	sp
	pop	hl
	or	a, a
	jr	NZ, 00104$
;games/flappy_bird.c:440: (flap_pressed(buttons) != 0u)) {
	push	hl
	ld	a, l
	push	af
	inc	sp
	call	_flap_pressed
	ld	a, l
	inc	sp
	pop	hl
	or	a, a
	jr	Z, 00104$
;games/flappy_bird.c:441: velocity = -5;
	ld	-3 (ix), #0xfb
	jr	00105$
00104$:
;games/flappy_bird.c:442: } else if (velocity < 4) {
	ld	a, -3 (ix)
	xor	a, #0x80
	sub	a, #0x84
	jr	NC, 00105$
;games/flappy_bird.c:443: ++velocity;
	inc	-3 (ix)
00105$:
;games/flappy_bird.c:445: last_buttons = buttons;
	ld	-10 (ix), l
;games/flappy_bird.c:447: next_y = (signed int)bird_y + (signed int)velocity;
	ld	c, -4 (ix)
	ld	b, #0x00
	ld	a, -3 (ix)
	ld	l, a
	rla
	sbc	a, a
	ld	h, a
	add	hl, bc
	ld	-5 (ix), l
	ld	-4 (ix), h
;games/flappy_bird.c:448: if (next_y < 0) {
	bit	7, -4 (ix)
	jr	Z, 00111$
;games/flappy_bird.c:449: bird_y = 0u;
	ld	-4 (ix), #0
;games/flappy_bird.c:450: game_over = 1u;
	ld	-9 (ix), #0x01
	jr	00112$
00111$:
;games/flappy_bird.c:451: } else if (next_y > 119) {
	ld	a, #0x77
	cp	a, -5 (ix)
	ld	a, #0x00
	sbc	a, -4 (ix)
	jp	PO, 00219$
	xor	a, #0x80
00219$:
	jp	P, 00108$
;games/flappy_bird.c:452: bird_y = 119u;
	ld	-4 (ix), #0x77
;games/flappy_bird.c:453: game_over = 1u;
	ld	-9 (ix), #0x01
	jr	00112$
00108$:
;games/flappy_bird.c:455: bird_y = (unsigned char)next_y;
	ld	a, -5 (ix)
	ld	-4 (ix), a
00112$:
;games/flappy_bird.c:458: if (pipe_x == 0u) {
	ld	a, -2 (ix)
	or	a, a
	jr	NZ, 00116$
;games/flappy_bird.c:459: pipe_x = 127u;
	ld	-2 (ix), #0x7f
;games/flappy_bird.c:460: gap_page = (unsigned char)(2u + (random8() & 7u));
	call	_random8
	ld	-5 (ix), l
	ld	a, l
	and	a, #0x07
	add	a, #0x02
	ld	-12 (ix), a
;games/flappy_bird.c:461: if (gap_page > 8u) {
	ld	a, #0x08
	sub	a, -12 (ix)
	jr	NC, 00114$
;games/flappy_bird.c:462: gap_page = 8u;
	ld	-12 (ix), #0x08
00114$:
;games/flappy_bird.c:464: pipe_scored = 0u;
	ld	-11 (ix), #0
	jr	00117$
00116$:
;games/flappy_bird.c:466: --pipe_x;
	dec	-2 (ix)
00117$:
;games/flappy_bird.c:469: pipe_right = (unsigned char)(pipe_x + PIPE_WIDTH - 1u);
	ld	a, -2 (ix)
	add	a, #0x0d
	ld	c, a
;games/flappy_bird.c:470: if ((pipe_scored == 0u) && (pipe_right < BIRD_X)) {
	ld	a, -11 (ix)
	or	a, a
	jr	NZ, 00121$
	ld	a, c
	sub	a, #0x18
	jr	NC, 00121$
;games/flappy_bird.c:471: if (score < 255u) {
	ld	iy, #_score
	ld	a, 0 (iy)
	sub	a, #0xff
	jr	NC, 00119$
;games/flappy_bird.c:472: ++score;
	inc	0 (iy)
00119$:
;games/flappy_bird.c:474: draw_score();
	call	_draw_score
;games/flappy_bird.c:475: pipe_scored = 1u;
	ld	-11 (ix), #0x01
00121$:
;games/flappy_bird.c:478: if (bird_hits_pipe(pipe_x, gap_page, bird_y) != 0u) {
	ld	h, -4 (ix)
	ld	l, -12 (ix)
	push	hl
	ld	a, -2 (ix)
	push	af
	inc	sp
	call	_bird_hits_pipe
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00124$
;games/flappy_bird.c:479: game_over = 1u;
	ld	-9 (ix), #0x01
00124$:
;games/flappy_bird.c:482: erase_bird(old_bird_y, old_pipe_x, old_gap_page);
	ld	h, -6 (ix)
	ld	l, -7 (ix)
	push	hl
	ld	a, -8 (ix)
	push	af
	inc	sp
	call	_erase_bird
	pop	af
	inc	sp
;games/flappy_bird.c:483: if (pipe_x > old_pipe_x) {
	ld	a, -7 (ix)
	sub	a, -2 (ix)
	jr	NC, 00126$
;games/flappy_bird.c:484: erase_pipe(old_pipe_x);
	ld	a, -7 (ix)
	push	af
	inc	sp
	call	_erase_pipe
	inc	sp
;games/flappy_bird.c:485: draw_pipe(pipe_x, gap_page);
	ld	h, -12 (ix)
	ld	l, -2 (ix)
	push	hl
	call	_draw_pipe
	pop	af
	jr	00127$
00126$:
;games/flappy_bird.c:487: move_pipe_left(old_pipe_x, pipe_x, gap_page);
	ld	h, -12 (ix)
	ld	l, -2 (ix)
	push	hl
	ld	a, -7 (ix)
	push	af
	inc	sp
	call	_move_pipe_left
	pop	af
	inc	sp
00127$:
;games/flappy_bird.c:489: draw_bird(bird_y, frame);
	ld	h, -1 (ix)
	ld	l, -4 (ix)
	push	hl
	call	_draw_bird
	pop	af
;games/flappy_bird.c:490: if (game_over != 0u) {
	ld	a, -9 (ix)
	or	a, a
	jr	Z, 00129$
;games/flappy_bird.c:491: draw_crash(bird_y);
	ld	a, -4 (ix)
	push	af
	inc	sp
	call	_draw_crash
	inc	sp
;games/flappy_bird.c:492: draw_game_over_text();
	call	_draw_game_over_text
00129$:
;games/flappy_bird.c:494: ++frame;
	inc	-1 (ix)
;games/flappy_bird.c:495: glic_delay(FLAPPY_DELAY);
	ld	hl, #0x1068
	push	hl
	call	_glic_delay
	pop	af
	jp	00130$
00132$:
;games/flappy_bird.c:498: wait_for_flap_press();
	call	_wait_for_flap_press
;games/flappy_bird.c:500: }
	jp	00134$
	.area _CODE
	.area _INITIALIZER
	.area _CABS (ABS)
