; generated by sdcc-z80-bin
    LD SP,#0x7700
    CALL _main
__sdcc_z80_bin_halt:
    JR __sdcc_z80_bin_halt

;--------------------------------------------------------
; File Created by SDCC : free open source ANSI-C Compiler
; Version 4.1.0 #12072 (Linux)
;--------------------------------------------------------
	.module flappy_bird
	.optsdcc -mz80
	
;--------------------------------------------------------
; Public variables in this module
;--------------------------------------------------------
	.globl _main
;--------------------------------------------------------
; special function registers
;--------------------------------------------------------
;--------------------------------------------------------
; ram data
;--------------------------------------------------------
	.area _DATA
_rng_state:
	.ds 1
;--------------------------------------------------------
; ram data
;--------------------------------------------------------
	.area _INITIALIZED
;--------------------------------------------------------
; absolute external ram data
;--------------------------------------------------------
	.area _DABS (ABS)
;--------------------------------------------------------
; global & static initialisations
;--------------------------------------------------------
	.area _HOME
	.area _GSINIT
	.area _GSFINAL
	.area _GSINIT
;--------------------------------------------------------
; Home
;--------------------------------------------------------
	.area _HOME
	.area _HOME
;--------------------------------------------------------
; code
;--------------------------------------------------------
	.area _CODE
;games/../common/glic80.h:29: static unsigned char glic_read_buttons(void) __naked {
;	---------------------------------
; Function glic_read_buttons
; ---------------------------------
_glic_read_buttons:
;games/../common/glic80.h:34: __endasm;
	in	a,(0)
	ld	l,a
	ret
;games/../common/glic80.h:35: }
;games/../common/glic80.h:37: static unsigned char glic_button_pressed(unsigned char buttons,
;	---------------------------------
; Function glic_button_pressed
; ---------------------------------
_glic_button_pressed:
;games/../common/glic80.h:39: return (buttons & mask) == 0u;
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	inc	iy
	and	a, 0 (iy)
	or	a, a
	ld	a, #0x01
	jr	Z, 00104$
	xor	a, a
00104$:
	ld	l, a
;games/../common/glic80.h:40: }
	ret
_glic_bit_masks:
	.db #0x01	; 1
	.db #0x02	; 2
	.db #0x04	; 4
	.db #0x08	; 8
	.db #0x10	; 16
	.db #0x20	; 32
	.db #0x40	; 64
	.db #0x80	; 128
;games/../common/glic80.h:42: static void glic_delay(unsigned int count) {
;	---------------------------------
; Function glic_delay
; ---------------------------------
_glic_delay:
;games/../common/glic80.h:43: while (count != 0u) {
	pop	de
	pop	bc
	push	bc
	push	de
00101$:
	ld	a, b
	or	a, c
	ret	Z
;games/../common/glic80.h:44: --count;
	dec	bc
;games/../common/glic80.h:47: __endasm;
	nop
;games/../common/glic80.h:49: }
	jr	00101$
;games/../common/glic80.h:51: static void glic_clear_text(void) {
;	---------------------------------
; Function glic_clear_text
; ---------------------------------
_glic_clear_text:
;games/../common/glic80.h:54: for (i = 0; i < GLIC_CVRAM_BYTES; ++i) {
	ld	bc, #0x0000
00102$:
;games/../common/glic80.h:55: GLIC_CVRAM[i] = 0x00u;
	ld	hl, #0x7700
	add	hl, bc
	ld	(hl), #0x00
;games/../common/glic80.h:54: for (i = 0; i < GLIC_CVRAM_BYTES; ++i) {
	inc	bc
	ld	a, b
	sub	a, #0x01
	jr	C, 00102$
;games/../common/glic80.h:57: }
	ret
;games/../common/glic80.h:59: static void glic_fill_graphics(unsigned char value) {
;	---------------------------------
; Function glic_fill_graphics
; ---------------------------------
_glic_fill_graphics:
;games/../common/glic80.h:62: for (i = 0; i < GLIC_GVRAM_BYTES; ++i) {
	ld	bc, #0x0000
00102$:
;games/../common/glic80.h:63: GLIC_GVRAM[i] = value;
	ld	hl, #0x7800
	add	hl, bc
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	ld	(hl), a
;games/../common/glic80.h:62: for (i = 0; i < GLIC_GVRAM_BYTES; ++i) {
	inc	bc
	ld	a, b
	sub	a, #0x08
	jr	C, 00102$
;games/../common/glic80.h:65: }
	ret
;games/../common/glic80.h:67: static void glic_plot(unsigned char x, unsigned char y, unsigned char value) {
;	---------------------------------
; Function glic_plot
; ---------------------------------
_glic_plot:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/../common/glic80.h:71: if ((x >= GLIC_SCREEN_WIDTH) || (y >= 128u)) {
	ld	a, 4 (ix)
	sub	a, #0x80
	jr	NC, 00107$
	ld	a, 5 (ix)
	sub	a, #0x80
;games/../common/glic80.h:72: return;
	jr	NC, 00107$
;games/../common/glic80.h:75: offset = (((unsigned int)(y >> 3)) << 7) + x;
	ld	a, 5 (ix)
	rrca
	rrca
	rrca
	and	a, #0x1f
	ld	l, a
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	ld	c, 4 (ix)
	ld	b, #0x00
	add	hl, bc
	ex	de, hl
;games/../common/glic80.h:76: mask = glic_bit_masks[y & 7u];
	ld	bc, #_glic_bit_masks+0
	ld	a, 5 (ix)
	and	a, #0x07
	ld	l, a
	ld	h, #0x00
	add	hl, bc
	ld	b, (hl)
;games/../common/glic80.h:78: GLIC_GVRAM[offset] |= mask;
	ld	hl, #0x7800
	add	hl, de
	ld	c, (hl)
;games/../common/glic80.h:77: if (value != 0u) {
	ld	a, 6 (ix)
	or	a, a
	jr	Z, 00105$
;games/../common/glic80.h:78: GLIC_GVRAM[offset] |= mask;
	ld	a, c
	or	a, b
	ld	(hl), a
	jr	00107$
00105$:
;games/../common/glic80.h:80: GLIC_GVRAM[offset] &= (unsigned char)~mask;
	ld	a, b
	cpl
	and	a, c
	ld	(hl), a
00107$:
;games/../common/glic80.h:82: }
	pop	ix
	ret
;games/../common/glic80.h:84: static void glic_draw_bitmap8(unsigned char x,
;	---------------------------------
; Function glic_draw_bitmap8
; ---------------------------------
_glic_draw_bitmap8:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/../common/glic80.h:92: for (row = 0u; row < 8u; ++row) {
	ld	c, #0x00
00107$:
;games/../common/glic80.h:93: bits = rows[row];
	ld	l, 6 (ix)
	ld	h, 7 (ix)
	ld	b, #0x00
	add	hl, bc
	ld	l, (hl)
;games/../common/glic80.h:94: mask = 0x80u;
	ld	e, #0x80
;games/../common/glic80.h:95: for (col = 0u; col < 8u; ++col) {
	ld	a, 5 (ix)
	add	a, c
	ld	b, a
	ld	d, #0x00
00105$:
;games/../common/glic80.h:96: if ((bits & mask) != 0u) {
	ld	a, l
	and	a,e
	jr	Z, 00102$
;games/../common/glic80.h:97: glic_plot((unsigned char)(x + col), (unsigned char)(y + row), 1u);
	ld	a, 4 (ix)
	add	a, d
	push	hl
	push	bc
	push	de
	ld	h, #0x01
	ld	l, b
	push	hl
	push	af
	inc	sp
	call	_glic_plot
	pop	af
	inc	sp
	pop	de
	pop	bc
	pop	hl
00102$:
;games/../common/glic80.h:99: mask >>= 1;
	srl	e
;games/../common/glic80.h:95: for (col = 0u; col < 8u; ++col) {
	inc	d
	ld	a, d
	sub	a, #0x08
	jr	C, 00105$
;games/../common/glic80.h:92: for (row = 0u; row < 8u; ++row) {
	inc	c
	ld	a, c
	sub	a, #0x08
	jr	C, 00107$
;games/../common/glic80.h:102: }
	pop	ix
	ret
;games/../common/glic80.h:104: static void glic_draw_tile8(unsigned char cell_x,
;	---------------------------------
; Function glic_draw_tile8
; ---------------------------------
_glic_draw_tile8:
	push	ix
	ld	ix,#0
	add	ix,sp
	push	af
;games/../common/glic80.h:110: offset = (((unsigned int)cell_y) << 7) + (((unsigned int)cell_x) << 3);
	ld	c, 5 (ix)
	xor	a, a
	rr	a
	ld	b, c
	rr	b
	rra
	ld	c, a
	ld	l, 4 (ix)
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, bc
	ex	de, hl
;games/../common/glic80.h:111: for (col = 0u; col < 8u; ++col) {
	ld	c, #0x00
00102$:
;games/../common/glic80.h:112: GLIC_GVRAM[offset + col] = columns[col];
	ld	l, c
	ld	h, #0x00
	add	hl, de
	ld	-2 (ix), l
	ld	a, h
	add	a, #0x78
	ld	-1 (ix), a
	ld	l, 6 (ix)
	ld	h, 7 (ix)
	ld	b, #0x00
	add	hl, bc
	ld	a, (hl)
	pop	hl
	push	hl
	ld	(hl), a
;games/../common/glic80.h:111: for (col = 0u; col < 8u; ++col) {
	inc	c
	ld	a, c
	sub	a, #0x08
	jr	C, 00102$
;games/../common/glic80.h:114: }
	ld	sp, ix
	pop	ix
	ret
;games/../common/glic80.h:116: static void glic_prepare_screen(unsigned char value) {
;	---------------------------------
; Function glic_prepare_screen
; ---------------------------------
_glic_prepare_screen:
;games/../common/glic80.h:117: glic_clear_text();
	call	_glic_clear_text
;games/../common/glic80.h:118: glic_fill_graphics(value);
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_glic_fill_graphics
	inc	sp
;games/../common/glic80.h:119: }
	ret
;games/../common/glic80.h:121: static void glic_fill_page_run(unsigned char page,
;	---------------------------------
; Function glic_fill_page_run
; ---------------------------------
_glic_fill_page_run:
;games/../common/glic80.h:127: p = GLIC_GVRAM + (((unsigned int)page) << 7) + x;
	ld	iy, #2
	add	iy, sp
	ld	c, 0 (iy)
	ld	b, #0x00
	xor	a, a
	rr	b
	ld	b, c
	rr	b
	rra
	ld	c, a
	ld	a, b
	add	a, #0x78
	ld	b, a
	ld	a, c
	ld	hl, #3
	add	hl, sp
	add	a, (hl)
	ld	c, a
	jr	NC, 00117$
	inc	b
00117$:
;games/../common/glic80.h:128: while (width != 0u) {
	ld	e, 2 (iy)
00101$:
	ld	a, e
	or	a, a
	ret	Z
;games/../common/glic80.h:129: *p++ = value;
	ld	iy, #5
	add	iy, sp
	ld	a, 0 (iy)
	ld	(bc), a
	inc	bc
;games/../common/glic80.h:130: --width;
	dec	e
;games/../common/glic80.h:132: }
	jr	00101$
;games/../common/glic80.h:134: static void glic_fill_pages(unsigned char first_page,
;	---------------------------------
; Function glic_fill_pages
; ---------------------------------
_glic_fill_pages:
;games/../common/glic80.h:137: while (page_count != 0u) {
	ld	iy, #2
	add	iy, sp
	ld	b, 0 (iy)
	ld	c, 1 (iy)
00101$:
	ld	a, c
	or	a, a
	ret	Z
;games/../common/glic80.h:138: glic_fill_page_run(first_page, 0u, GLIC_SCREEN_WIDTH, value);
	push	bc
	ld	hl, #6
	add	hl, sp
	ld	d, (hl)
	ld	e,#0x80
	push	de
	xor	a, a
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_fill_page_run
	pop	af
	pop	af
	pop	bc
;games/../common/glic80.h:139: ++first_page;
	inc	b
;games/../common/glic80.h:140: --page_count;
	dec	c
;games/../common/glic80.h:142: }
	jr	00101$
;games/../common/glic80.h:144: static void glic_fill_columns(unsigned char x,
;	---------------------------------
; Function glic_fill_columns
; ---------------------------------
_glic_fill_columns:
;games/../common/glic80.h:149: for (page = 0u; page < GLIC_SCREEN_PAGES; ++page) {
	ld	b, #0x00
00102$:
;games/../common/glic80.h:150: glic_fill_page_run(page, x, width, value);
	push	bc
	ld	iy, #6
	add	iy, sp
	ld	a, 0 (iy)
	push	af
	inc	sp
	ld	a, -1 (iy)
	dec	iy
	push	af
	inc	sp
	ld	a, -1 (iy)
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_fill_page_run
	pop	af
	pop	af
	pop	bc
;games/../common/glic80.h:149: for (page = 0u; page < GLIC_SCREEN_PAGES; ++page) {
	inc	b
	ld	a, b
	sub	a, #0x10
	jr	C, 00102$
;games/../common/glic80.h:152: }
	ret
;games/flappy_bird.c:27: static unsigned char random8(void) {
;	---------------------------------
; Function random8
; ---------------------------------
_random8:
;games/flappy_bird.c:30: bit = (unsigned char)(((rng_state >> 7) ^
	ld	iy, #_rng_state
	ld	a, 0 (iy)
	rlca
	and	a, #0x01
	ld	c, a
;games/flappy_bird.c:31: (rng_state >> 5) ^
	ld	a, 0 (iy)
	rlca
	rlca
	rlca
	and	a, #0x07
	xor	a, c
	ld	c, a
;games/flappy_bird.c:32: (rng_state >> 4) ^
	ld	a, 0 (iy)
	rlca
	rlca
	rlca
	rlca
	and	a, #0x0f
	xor	a, c
;games/flappy_bird.c:33: (rng_state >> 3)) & 1u);
	ld	c, 0 (iy)
	srl	c
	srl	c
	srl	c
	xor	a, c
	and	a, #0x01
;games/flappy_bird.c:34: rng_state = (unsigned char)((rng_state << 1) | bit);
	ld	c, 0 (iy)
	sla	c
	or	a, c
	ld	(_rng_state+0), a
;games/flappy_bird.c:35: return rng_state;
	ld	l, 0 (iy)
;games/flappy_bird.c:36: }
	ret
_bird_wing_up:
	.db #0x18	; 24
	.db #0x3c	; 60
	.db #0x7e	; 126
	.db #0xdb	; 219
	.db #0xff	; 255
	.db #0x7e	; 126
	.db #0x24	; 36
	.db #0x42	; 66	'B'
_bird_wing_down:
	.db #0x18	; 24
	.db #0x3c	; 60
	.db #0x7e	; 126
	.db #0xdb	; 219
	.db #0xff	; 255
	.db #0x5a	; 90	'Z'
	.db #0x3c	; 60
	.db #0x18	; 24
_bird_crash:
	.db #0x81	; 129
	.db #0x42	; 66	'B'
	.db #0x24	; 36
	.db #0x18	; 24
	.db #0x18	; 24
	.db #0x24	; 36
	.db #0x42	; 66	'B'
	.db #0x81	; 129
_pipe_texture:
	.db #0xff	; 255
	.db #0xbd	; 189
	.db #0xe7	; 231
	.db #0xdb	; 219
;games/flappy_bird.c:38: static void wait_for_button_press(void) {
;	---------------------------------
; Function wait_for_button_press
; ---------------------------------
_wait_for_button_press:
;games/flappy_bird.c:39: while (glic_read_buttons() != GLIC_BUTTONS_NONE) {
00101$:
	call	_glic_read_buttons
	inc	l
	jr	Z, 00104$
;games/flappy_bird.c:40: random8();
	call	_random8
	jr	00101$
;games/flappy_bird.c:42: while (glic_read_buttons() == GLIC_BUTTONS_NONE) {
00104$:
	call	_glic_read_buttons
	inc	l
	jr	NZ, 00107$
;games/flappy_bird.c:43: random8();
	call	_random8
	jr	00104$
;games/flappy_bird.c:45: while (glic_read_buttons() != GLIC_BUTTONS_NONE) {
00107$:
	call	_glic_read_buttons
	inc	l
	ret	Z
;games/flappy_bird.c:46: random8();
	call	_random8
;games/flappy_bird.c:48: }
	jr	00107$
;games/flappy_bird.c:50: static unsigned char sky_byte(unsigned char x, unsigned char page) {
;	---------------------------------
; Function sky_byte
; ---------------------------------
_sky_byte:
	push	ix
	ld	ix,#0
	add	ix,sp
	dec	sp
;games/flappy_bird.c:54: return ((x & 1u) != 0u) ? 0xaau : 0x55u;
	ld	c, 4 (ix)
;games/flappy_bird.c:53: if (page == 15u) {
	ld	a, 5 (ix)
	sub	a, #0x0f
	jr	NZ, 00102$
;games/flappy_bird.c:54: return ((x & 1u) != 0u) ? 0xaau : 0x55u;
	bit	0, c
	jr	Z, 00111$
	ld	hl, #0x00aa
	jr	00109$
00111$:
	ld	hl, #0x0055
	jr	00109$
00102$:
;games/flappy_bird.c:56: if (page == 14u) {
	ld	a, 5 (ix)
	sub	a, #0x0e
	jr	NZ, 00104$
;games/flappy_bird.c:57: return ((x & 2u) != 0u) ? 0x88u : 0x22u;
	bit	1, c
	jr	Z, 00113$
	ld	hl, #0x0088
	jr	00109$
00113$:
	ld	hl, #0x0022
	jr	00109$
00104$:
;games/flappy_bird.c:60: value = 0x00u;
	ld	-1 (ix), #0
;games/flappy_bird.c:61: if (((x + (page << 3)) & 31u) == 0u) {
	ld	c, 4 (ix)
	ld	b, #0x00
	ld	e, 5 (ix)
	ld	d, #0x00
	ld	l, e
	ld	h, d
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, bc
	ld	a, l
	and	a, #0x1f
	jr	NZ, 00106$
;games/flappy_bird.c:62: value |= 0x18u;
	ld	-1 (ix), #0x18
00106$:
;games/flappy_bird.c:64: if (((x + (page << 2)) & 63u) == 8u) {
	ex	de,hl
	add	hl, hl
	add	hl, hl
	add	hl, bc
	ld	a, l
	and	a, #0x3f
	ld	b, #0x00
	sub	a, #0x08
	or	a, b
	jr	NZ, 00108$
;games/flappy_bird.c:65: value |= 0x40u;
	ld	a, -1 (ix)
	or	a, #0x40
	ld	-1 (ix), a
00108$:
;games/flappy_bird.c:67: return value;
	ld	l, -1 (ix)
00109$:
;games/flappy_bird.c:68: }
	inc	sp
	pop	ix
	ret
;games/flappy_bird.c:70: static void draw_sky(void) {
;	---------------------------------
; Function draw_sky
; ---------------------------------
_draw_sky:
;games/flappy_bird.c:75: for (page = 0u; page < GLIC_SCREEN_PAGES; ++page) {
	ld	c, #0x00
00105$:
;games/flappy_bird.c:76: offset = ((unsigned int)page) << 7;
	ld	a, c
	ld	b, #0x00
	rr	b
	ld	d, a
	rr	d
	ld	e, #0x00
	rr	e
;games/flappy_bird.c:77: for (x = 0u; x < GLIC_SCREEN_WIDTH; ++x) {
	ld	b, #0x00
00103$:
;games/flappy_bird.c:78: GLIC_GVRAM[offset + x] = sky_byte(x, page);
	ld	a, b
	ld	h, #0x00
	ld	l, a
	add	hl, de
	ld	a, h
	add	a, #0x78
	ld	h, a
	push	hl
	push	bc
	push	de
	ld	a, c
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_sky_byte
	pop	af
	ld	a, l
	pop	de
	pop	bc
	pop	hl
	ld	(hl), a
;games/flappy_bird.c:77: for (x = 0u; x < GLIC_SCREEN_WIDTH; ++x) {
	inc	b
	ld	a, b
	sub	a, #0x80
	jr	C, 00103$
;games/flappy_bird.c:75: for (page = 0u; page < GLIC_SCREEN_PAGES; ++page) {
	inc	c
	ld	a, c
	sub	a, #0x10
	jr	C, 00105$
;games/flappy_bird.c:81: }
	ret
;games/flappy_bird.c:83: static unsigned char pipe_byte(unsigned char pipe_x,
;	---------------------------------
; Function pipe_byte
; ---------------------------------
_pipe_byte:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/flappy_bird.c:90: if ((page >= 15u) || (x < pipe_x)) {
	ld	a, 7 (ix)
	sub	a, #0x0f
	jr	NC, 00101$
	ld	a, 6 (ix)
	sub	a, 4 (ix)
	jr	NC, 00102$
00101$:
;games/flappy_bird.c:91: return sky_byte(x, page);
	ld	h, 7 (ix)
	ld	l, 6 (ix)
	push	hl
	call	_sky_byte
	pop	af
	jr	00114$
00102$:
;games/flappy_bird.c:94: local_x = (unsigned char)(x - pipe_x);
	ld	a, 6 (ix)
	sub	a, 4 (ix)
;games/flappy_bird.c:95: if (local_x >= PIPE_WIDTH) {
	ld	b, a
	sub	a, #0x0e
	jr	C, 00105$
;games/flappy_bird.c:96: return sky_byte(x, page);
	ld	h, 7 (ix)
	ld	l, 6 (ix)
	push	hl
	call	_sky_byte
	pop	af
	jr	00114$
00105$:
;games/flappy_bird.c:99: gap_end = (unsigned char)(gap_page + PIPE_GAP_PAGES);
	ld	a, 5 (ix)
	add	a, #0x05
	ld	c, a
;games/flappy_bird.c:100: if ((page >= gap_page) && (page < gap_end)) {
	ld	a, 7 (ix)
	sub	a, 5 (ix)
	jr	C, 00107$
	ld	a, 7 (ix)
	sub	a, c
	jr	NC, 00107$
;games/flappy_bird.c:101: return sky_byte(x, page);
	ld	h, 7 (ix)
	ld	l, 6 (ix)
	push	hl
	call	_sky_byte
	pop	af
	jr	00114$
00107$:
;games/flappy_bird.c:104: if ((local_x == 0u) ||
	ld	a, b
	or	a, a
	jr	Z, 00109$
;games/flappy_bird.c:105: (local_x == (PIPE_WIDTH - 1u)) ||
	ld	a, b
	sub	a, #0x0d
	jr	Z, 00109$
;games/flappy_bird.c:106: ((unsigned char)(page + 1u) == gap_page) ||
	ld	b, 7 (ix)
	inc	b
	ld	a, 5 (ix)
	sub	a, b
	jr	Z, 00109$
;games/flappy_bird.c:107: (page == gap_end)) {
	ld	a, 7 (ix)
	sub	a, c
	jr	NZ, 00110$
00109$:
;games/flappy_bird.c:108: return 0xffu;
	ld	l, #0xff
	jr	00114$
00110$:
;games/flappy_bird.c:110: return pipe_texture[(x + page) & 3u];
	ld	bc, #_pipe_texture+0
	ld	a, 6 (ix)
	add	a, 7 (ix)
	and	a, #0x03
	ld	l, a
	ld	h, #0x00
	add	hl, bc
	ld	l, (hl)
00114$:
;games/flappy_bird.c:111: }
	pop	ix
	ret
;games/flappy_bird.c:113: static void restore_scene_region(unsigned char x,
;	---------------------------------
; Function restore_scene_region
; ---------------------------------
_restore_scene_region:
	push	ix
	ld	ix,#0
	add	ix,sp
	push	af
;games/flappy_bird.c:122: while (width != 0u) {
	ld	a, 6 (ix)
	add	a, 7 (ix)
	ld	-2 (ix), a
	ld	c, 4 (ix)
	ld	e, 5 (ix)
00106$:
	ld	a, e
	or	a, a
	jr	Z, 00109$
;games/flappy_bird.c:123: if (x < GLIC_SCREEN_WIDTH) {
	ld	a, c
	sub	a, #0x80
	jr	NC, 00105$
;games/flappy_bird.c:124: p = page;
	ld	a, 6 (ix)
	ld	-1 (ix), a
;games/flappy_bird.c:125: while (p < (unsigned char)(page + page_count)) {
00101$:
	ld	a, -1 (ix)
	sub	a, -2 (ix)
	jr	NC, 00105$
;games/flappy_bird.c:126: offset = (((unsigned int)p) << 7) + x;
	ld	l, -1 (ix)
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	ld	a, c
	ld	b, #0x00
	add	a, l
	ld	l, a
	ld	a, b
	adc	a, h
;games/flappy_bird.c:127: GLIC_GVRAM[offset] = pipe_byte(pipe_x, gap_page, x, p);
	add	a, #0x78
	ld	h, a
	push	hl
	push	bc
	push	de
	ld	b, -1 (ix)
	push	bc
	ld	h, 9 (ix)
	ld	l, 8 (ix)
	push	hl
	call	_pipe_byte
	pop	af
	pop	af
	ld	a, l
	pop	de
	pop	bc
	pop	hl
	ld	(hl), a
;games/flappy_bird.c:128: ++p;
	inc	-1 (ix)
	jr	00101$
00105$:
;games/flappy_bird.c:131: ++x;
	inc	c
;games/flappy_bird.c:132: --width;
	dec	e
	jr	00106$
00109$:
;games/flappy_bird.c:134: }
	ld	sp, ix
	pop	ix
	ret
;games/flappy_bird.c:136: static void erase_pipe(unsigned char pipe_x) {
;	---------------------------------
; Function erase_pipe
; ---------------------------------
_erase_pipe:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/flappy_bird.c:141: for (i = 0u; i < PIPE_WIDTH; ++i) {
	ld	c, #0x00
00108$:
;games/flappy_bird.c:142: col = (unsigned char)(pipe_x + i);
	ld	a, 4 (ix)
	add	a, c
;games/flappy_bird.c:143: if (col >= GLIC_SCREEN_WIDTH) {
	ld	b, a
	sub	a, #0x80
	jr	NC, 00104$
;games/flappy_bird.c:146: for (page = 0u; page < 15u; ++page) {
	ld	e, #0x00
00106$:
;games/flappy_bird.c:147: GLIC_GVRAM[(((unsigned int)page) << 7) + col] = sky_byte(col, page);
	ld	l, e
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	ld	a, b
	ld	d, #0x00
	add	a, l
	ld	l, a
	ld	a, d
	adc	a, h
	add	a, #0x78
	ld	h, a
	push	hl
	push	bc
	push	de
	ld	a, e
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_sky_byte
	pop	af
	ld	a, l
	pop	de
	pop	bc
	pop	hl
	ld	(hl), a
;games/flappy_bird.c:146: for (page = 0u; page < 15u; ++page) {
	inc	e
	ld	a, e
	sub	a, #0x0f
	jr	C, 00106$
00104$:
;games/flappy_bird.c:141: for (i = 0u; i < PIPE_WIDTH; ++i) {
	inc	c
	ld	a, c
	sub	a, #0x0e
	jr	C, 00108$
;games/flappy_bird.c:150: }
	pop	ix
	ret
;games/flappy_bird.c:152: static void draw_pipe(unsigned char pipe_x, unsigned char gap_page) {
;	---------------------------------
; Function draw_pipe
; ---------------------------------
_draw_pipe:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/flappy_bird.c:157: for (i = 0u; i < PIPE_WIDTH; ++i) {
	ld	c, #0x00
00108$:
;games/flappy_bird.c:158: col = (unsigned char)(pipe_x + i);
	ld	a, 4 (ix)
	add	a, c
;games/flappy_bird.c:159: if (col >= GLIC_SCREEN_WIDTH) {
	ld	b, a
	sub	a, #0x80
	jr	NC, 00104$
;games/flappy_bird.c:162: for (page = 0u; page < 15u; ++page) {
	ld	e, #0x00
00106$:
;games/flappy_bird.c:163: GLIC_GVRAM[(((unsigned int)page) << 7) + col] =
	ld	l, e
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	ld	a, b
	ld	d, #0x00
	add	a, l
	ld	l, a
	ld	a, d
	adc	a, h
	add	a, #0x78
	ld	h, a
;games/flappy_bird.c:164: pipe_byte(pipe_x, gap_page, col, page);
	push	hl
	push	bc
	push	de
	ld	a, e
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	h, 5 (ix)
	ld	l, 4 (ix)
	push	hl
	call	_pipe_byte
	pop	af
	pop	af
	ld	a, l
	pop	de
	pop	bc
	pop	hl
	ld	(hl), a
;games/flappy_bird.c:162: for (page = 0u; page < 15u; ++page) {
	inc	e
	ld	a, e
	sub	a, #0x0f
	jr	C, 00106$
00104$:
;games/flappy_bird.c:157: for (i = 0u; i < PIPE_WIDTH; ++i) {
	inc	c
	ld	a, c
	sub	a, #0x0e
	jr	C, 00108$
;games/flappy_bird.c:167: }
	pop	ix
	ret
;games/flappy_bird.c:169: static void erase_bird(unsigned char bird_y,
;	---------------------------------
; Function erase_bird
; ---------------------------------
_erase_bird:
;games/flappy_bird.c:175: page = bird_y >> 3;
	ld	iy, #2
	add	iy, sp
	ld	b, 0 (iy)
	srl	b
	srl	b
	srl	b
;games/flappy_bird.c:176: last_page = (unsigned char)((bird_y + 7u) >> 3);
	ld	e, 0 (iy)
	ld	d, #0x00
	ld	hl, #0x0007
	add	hl, de
	srl	h
	rr	l
	srl	h
	rr	l
	srl	h
	rr	l
	ld	a, l
;games/flappy_bird.c:180: (unsigned char)(last_page - page + 1u),
	sub	a, b
	inc	a
;games/flappy_bird.c:177: restore_scene_region(BIRD_X,
	ld	h, 2 (iy)
	inc	iy
	inc	iy
	push	hl
	inc	sp
	ld	h, -1 (iy)
	push	hl
	inc	sp
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	de, #0x0818
	push	de
	call	_restore_scene_region
	ld	hl, #6
	add	hl, sp
	ld	sp, hl
;games/flappy_bird.c:183: }
	ret
;games/flappy_bird.c:185: static void draw_bird(unsigned char bird_y, unsigned char frame) {
;	---------------------------------
; Function draw_bird
; ---------------------------------
_draw_bird:
;games/flappy_bird.c:186: if ((frame & 4u) == 0u) {
	ld	hl, #3
	add	hl, sp
	bit	2, (hl)
	jr	NZ, 00102$
;games/flappy_bird.c:187: glic_draw_bitmap8(BIRD_X, bird_y, bird_wing_up);
	ld	hl, #_bird_wing_up
	push	hl
	ld	hl, #4
	add	hl, sp
	ld	d, (hl)
	ld	e,#0x18
	push	de
	call	_glic_draw_bitmap8
	pop	af
	pop	af
	ret
00102$:
;games/flappy_bird.c:189: glic_draw_bitmap8(BIRD_X, bird_y, bird_wing_down);
	ld	hl, #_bird_wing_down
	push	hl
	ld	hl, #4
	add	hl, sp
	ld	d, (hl)
	ld	e,#0x18
	push	de
	call	_glic_draw_bitmap8
	pop	af
	pop	af
;games/flappy_bird.c:191: }
	ret
;games/flappy_bird.c:193: static unsigned char bird_hits_pipe(unsigned char pipe_x,
;	---------------------------------
; Function bird_hits_pipe
; ---------------------------------
_bird_hits_pipe:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/flappy_bird.c:200: pipe_right = (unsigned char)(pipe_x + PIPE_WIDTH - 1u);
	ld	a, 4 (ix)
	add	a, #0x0d
	ld	c, a
;games/flappy_bird.c:201: if (((unsigned char)(BIRD_X + 7u) < pipe_x) || (BIRD_X > pipe_right)) {
	ld	a, #0x1f
	sub	a, 4 (ix)
	jr	C, 00101$
	ld	a, c
	sub	a, #0x18
	jr	NC, 00102$
00101$:
;games/flappy_bird.c:202: return 0u;
	ld	l, #0x00
	jr	00107$
00102$:
;games/flappy_bird.c:205: bird_top_page = bird_y >> 3;
	ld	c, 6 (ix)
	srl	c
	srl	c
	srl	c
;games/flappy_bird.c:206: bird_bottom_page = (unsigned char)((bird_y + 7u) >> 3);
	ld	e, 6 (ix)
	ld	d, #0x00
	ld	hl, #0x0007
	add	hl, de
	srl	h
	rr	l
	srl	h
	rr	l
	srl	h
	rr	l
;games/flappy_bird.c:207: if ((bird_top_page < gap_page) ||
	ld	a, c
	sub	a, 5 (ix)
	jr	C, 00104$
;games/flappy_bird.c:208: (bird_bottom_page >= (unsigned char)(gap_page + PIPE_GAP_PAGES))) {
	ld	a, 5 (ix)
	add	a, #0x05
	ld	c, a
	ld	a, l
	sub	a, c
	jr	C, 00105$
00104$:
;games/flappy_bird.c:209: return 1u;
	ld	l, #0x01
	jr	00107$
00105$:
;games/flappy_bird.c:212: return 0u;
	ld	l, #0x00
00107$:
;games/flappy_bird.c:213: }
	pop	ix
	ret
;games/flappy_bird.c:215: static void draw_crash(unsigned char bird_y) {
;	---------------------------------
; Function draw_crash
; ---------------------------------
_draw_crash:
;games/flappy_bird.c:218: glic_draw_bitmap8(BIRD_X, bird_y, bird_crash);
	ld	hl, #_bird_crash
	push	hl
	ld	hl, #4
	add	hl, sp
	ld	d, (hl)
	ld	e,#0x18
	push	de
	call	_glic_draw_bitmap8
	pop	af
	pop	af
;games/flappy_bird.c:219: for (i = 0u; i < GLIC_SCREEN_WIDTH; ++i) {
	ld	b, #0x00
00102$:
;games/flappy_bird.c:220: glic_plot(i, i, 1u);
	push	bc
	ld	a, #0x01
	push	af
	inc	sp
	ld	c, b
	push	bc
	call	_glic_plot
	pop	af
	inc	sp
	pop	bc
;games/flappy_bird.c:221: glic_plot((unsigned char)(127u - i), i, 1u);
	ld	a, #0x7f
	sub	a, b
	push	bc
	ld	h, #0x01
	ld	l, b
	push	hl
	push	af
	inc	sp
	call	_glic_plot
	pop	af
	inc	sp
	pop	bc
;games/flappy_bird.c:219: for (i = 0u; i < GLIC_SCREEN_WIDTH; ++i) {
	inc	b
	ld	a, b
	sub	a, #0x80
	jr	C, 00102$
;games/flappy_bird.c:223: }
	ret
;games/flappy_bird.c:225: void main(void) {
;	---------------------------------
; Function main
; ---------------------------------
_main::
	push	ix
	ld	ix,#0
	add	ix,sp
	ld	hl, #-10
	add	hl, sp
	ld	sp, hl
;games/flappy_bird.c:239: glic_clear_text();
	call	_glic_clear_text
;games/flappy_bird.c:240: rng_state = 0x5au;
	ld	hl, #_rng_state
	ld	(hl), #0x5a
;games/flappy_bird.c:241: draw_sky();
	call	_draw_sky
;games/flappy_bird.c:242: wait_for_button_press();
	call	_wait_for_button_press
;games/flappy_bird.c:244: while (1) {
00126$:
;games/flappy_bird.c:245: draw_sky();
	call	_draw_sky
;games/flappy_bird.c:246: bird_y = 56u;
	ld	-10 (ix), #0x38
;games/flappy_bird.c:247: velocity = 0;
	ld	-3 (ix), #0
;games/flappy_bird.c:248: pipe_x = 112u;
	ld	-2 (ix), #0x70
;games/flappy_bird.c:249: gap_page = 5u;
	ld	-4 (ix), #0x05
;games/flappy_bird.c:251: last_buttons = GLIC_BUTTONS_NONE;
	ld	-9 (ix), #0xff
;games/flappy_bird.c:252: game_over = 0u;
	ld	-8 (ix), #0
;games/flappy_bird.c:253: draw_pipe(pipe_x, gap_page);
	ld	de, #0x0570
	push	de
	call	_draw_pipe
	pop	af
;games/flappy_bird.c:254: draw_bird(bird_y, frame);
	xor	a, a
	ld	d,a
	ld	e,#0x38
	push	de
	call	_draw_bird
	pop	af
;games/flappy_bird.c:256: while (game_over == 0u) {
	ld	-1 (ix), #0
00122$:
	ld	a, -8 (ix)
	or	a, a
	jp	NZ, 00124$
;games/flappy_bird.c:257: old_bird_y = bird_y;
	ld	a, -10 (ix)
	ld	-7 (ix), a
;games/flappy_bird.c:258: old_pipe_x = pipe_x;
	ld	a, -2 (ix)
	ld	-6 (ix), a
;games/flappy_bird.c:259: old_gap_page = gap_page;
	ld	a, -4 (ix)
	ld	-5 (ix), a
;games/flappy_bird.c:260: buttons = glic_read_buttons();
	call	_glic_read_buttons
;games/flappy_bird.c:261: if (((last_buttons & FLAP_MASK) == FLAP_MASK) &&
	ld	a, -9 (ix)
	and	a, #0x83
	ld	c, a
	ld	b, #0x00
	ld	a, c
	sub	a, #0x83
	or	a, b
	jr	NZ, 00104$
;games/flappy_bird.c:262: ((buttons & FLAP_MASK) != FLAP_MASK)) {
	ld	a, l
	and	a, #0x83
	ld	b, a
	ld	c, #0x00
	ld	a, b
	sub	a, #0x83
	or	a, c
	jr	Z, 00104$
;games/flappy_bird.c:263: velocity = -5;
	ld	-3 (ix), #0xfb
	jr	00105$
00104$:
;games/flappy_bird.c:264: } else if (velocity < 4) {
	ld	a, -3 (ix)
	xor	a, #0x80
	sub	a, #0x84
	jr	NC, 00105$
;games/flappy_bird.c:265: ++velocity;
	inc	-3 (ix)
00105$:
;games/flappy_bird.c:267: last_buttons = buttons;
	ld	-9 (ix), l
;games/flappy_bird.c:269: next_y = (signed int)bird_y + (signed int)velocity;
	ld	c, -10 (ix)
	ld	b, #0x00
	ld	a, -3 (ix)
	ld	l, a
	rla
	sbc	a, a
	ld	h, a
	add	hl, bc
;games/flappy_bird.c:270: if (next_y < 0) {
	bit	7, h
	jr	Z, 00111$
;games/flappy_bird.c:271: bird_y = 0u;
	ld	-10 (ix), #0
;games/flappy_bird.c:272: game_over = 1u;
	ld	-8 (ix), #0x01
	jr	00112$
00111$:
;games/flappy_bird.c:273: } else if (next_y > 119) {
	ld	a, #0x77
	cp	a, l
	ld	a, #0x00
	sbc	a, h
	jp	PO, 00194$
	xor	a, #0x80
00194$:
	jp	P, 00108$
;games/flappy_bird.c:274: bird_y = 119u;
	ld	-10 (ix), #0x77
;games/flappy_bird.c:275: game_over = 1u;
	ld	-8 (ix), #0x01
	jr	00112$
00108$:
;games/flappy_bird.c:277: bird_y = (unsigned char)next_y;
	ld	-10 (ix), l
00112$:
;games/flappy_bird.c:280: if (pipe_x == 0u) {
	ld	a, -2 (ix)
	or	a, a
	jr	NZ, 00116$
;games/flappy_bird.c:281: pipe_x = 127u;
	ld	-2 (ix), #0x7f
;games/flappy_bird.c:282: gap_page = (unsigned char)(2u + (random8() & 7u));
	call	_random8
	ld	-4 (ix), l
	ld	a, l
	and	a, #0x07
	add	a, #0x02
	ld	-4 (ix), a
;games/flappy_bird.c:283: if (gap_page > 9u) {
	ld	a, #0x09
	sub	a, -4 (ix)
	jr	NC, 00117$
;games/flappy_bird.c:284: gap_page = 9u;
	ld	-4 (ix), #0x09
	jr	00117$
00116$:
;games/flappy_bird.c:287: --pipe_x;
	dec	-2 (ix)
00117$:
;games/flappy_bird.c:290: if (bird_hits_pipe(pipe_x, gap_page, bird_y) != 0u) {
	ld	h, -10 (ix)
	ld	l, -4 (ix)
	push	hl
	ld	a, -2 (ix)
	push	af
	inc	sp
	call	_bird_hits_pipe
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00119$
;games/flappy_bird.c:291: game_over = 1u;
	ld	-8 (ix), #0x01
00119$:
;games/flappy_bird.c:294: erase_bird(old_bird_y, old_pipe_x, old_gap_page);
	ld	h, -5 (ix)
	ld	l, -6 (ix)
	push	hl
	ld	a, -7 (ix)
	push	af
	inc	sp
	call	_erase_bird
	pop	af
	inc	sp
;games/flappy_bird.c:295: erase_pipe(old_pipe_x);
	ld	a, -6 (ix)
	push	af
	inc	sp
	call	_erase_pipe
	inc	sp
;games/flappy_bird.c:296: draw_pipe(pipe_x, gap_page);
	ld	h, -4 (ix)
	ld	l, -2 (ix)
	push	hl
	call	_draw_pipe
	pop	af
;games/flappy_bird.c:297: draw_bird(bird_y, frame);
	ld	h, -1 (ix)
	ld	l, -10 (ix)
	push	hl
	call	_draw_bird
	pop	af
;games/flappy_bird.c:298: if (game_over != 0u) {
	ld	a, -8 (ix)
	or	a, a
	jr	Z, 00121$
;games/flappy_bird.c:299: draw_crash(bird_y);
	ld	a, -10 (ix)
	push	af
	inc	sp
	call	_draw_crash
	inc	sp
00121$:
;games/flappy_bird.c:301: ++frame;
	inc	-1 (ix)
;games/flappy_bird.c:302: glic_delay(FLAPPY_DELAY);
	ld	hl, #0x09c4
	push	hl
	call	_glic_delay
	pop	af
	jp	00122$
00124$:
;games/flappy_bird.c:305: wait_for_button_press();
	call	_wait_for_button_press
;games/flappy_bird.c:307: }
	jp	00126$
	.area _CODE
	.area _INITIALIZER
	.area _CABS (ABS)
