; generated by sdcc-z80-bin
    JR __sdcc_z80_bin_start
    DB "snake",0
__sdcc_z80_bin_start:
    LD SP,#0x7700
    CALL _main
__sdcc_z80_bin_halt:
    JR __sdcc_z80_bin_halt

;--------------------------------------------------------
; File Created by SDCC : free open source ANSI-C Compiler
; Version 4.1.0 #12072 (Linux)
;--------------------------------------------------------
	.module snake
	.optsdcc -mz80
	
;--------------------------------------------------------
; Public variables in this module
;--------------------------------------------------------
	.globl _main
;--------------------------------------------------------
; special function registers
;--------------------------------------------------------
;--------------------------------------------------------
; ram data
;--------------------------------------------------------
	.area _DATA
_rng_state:
	.ds 1
_snake_x:
	.ds 64
_snake_y:
	.ds 64
_snake_len:
	.ds 1
_direction:
	.ds 1
_score:
	.ds 1
_fruit_x:
	.ds 1
_fruit_y:
	.ds 1
_last_tail_x:
	.ds 1
_last_tail_y:
	.ds 1
_last_head_x:
	.ds 1
_last_head_y:
	.ds 1
_last_grew:
	.ds 1
_last_ate_fruit:
	.ds 1
;--------------------------------------------------------
; ram data
;--------------------------------------------------------
	.area _INITIALIZED
;--------------------------------------------------------
; absolute external ram data
;--------------------------------------------------------
	.area _DABS (ABS)
;--------------------------------------------------------
; global & static initialisations
;--------------------------------------------------------
	.area _HOME
	.area _GSINIT
	.area _GSFINAL
	.area _GSINIT
;--------------------------------------------------------
; Home
;--------------------------------------------------------
	.area _HOME
	.area _HOME
;--------------------------------------------------------
; code
;--------------------------------------------------------
	.area _CODE
;games/../common/glic80.h:29: static unsigned char glic_read_buttons(void) __naked {
;	---------------------------------
; Function glic_read_buttons
; ---------------------------------
_glic_read_buttons:
;games/../common/glic80.h:34: __endasm;
	in	a,(0)
	ld	l,a
	ret
;games/../common/glic80.h:35: }
;games/../common/glic80.h:37: static unsigned char glic_button_pressed(unsigned char buttons,
;	---------------------------------
; Function glic_button_pressed
; ---------------------------------
_glic_button_pressed:
;games/../common/glic80.h:39: return (buttons & mask) == 0u;
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	inc	iy
	and	a, 0 (iy)
	or	a, a
	ld	a, #0x01
	jr	Z, 00104$
	xor	a, a
00104$:
	ld	l, a
;games/../common/glic80.h:40: }
	ret
_glic_bit_masks:
	.db #0x01	; 1
	.db #0x02	; 2
	.db #0x04	; 4
	.db #0x08	; 8
	.db #0x10	; 16
	.db #0x20	; 32
	.db #0x40	; 64
	.db #0x80	; 128
;games/../common/glic80.h:42: static void glic_delay(unsigned int count) {
;	---------------------------------
; Function glic_delay
; ---------------------------------
_glic_delay:
;games/../common/glic80.h:43: while (count != 0u) {
	pop	de
	pop	bc
	push	bc
	push	de
00101$:
	ld	a, b
	or	a, c
	ret	Z
;games/../common/glic80.h:44: --count;
	dec	bc
;games/../common/glic80.h:47: __endasm;
	nop
;games/../common/glic80.h:49: }
	jr	00101$
;games/../common/glic80.h:51: static void glic_clear_text(void) {
;	---------------------------------
; Function glic_clear_text
; ---------------------------------
_glic_clear_text:
;games/../common/glic80.h:54: for (i = 0; i < GLIC_CVRAM_BYTES; ++i) {
	ld	bc, #0x0000
00102$:
;games/../common/glic80.h:55: GLIC_CVRAM[i] = 0x00u;
	ld	hl, #0x7700
	add	hl, bc
	ld	(hl), #0x00
;games/../common/glic80.h:54: for (i = 0; i < GLIC_CVRAM_BYTES; ++i) {
	inc	bc
	ld	a, b
	sub	a, #0x01
	jr	C, 00102$
;games/../common/glic80.h:57: }
	ret
;games/../common/glic80.h:59: static void glic_fill_graphics(unsigned char value) {
;	---------------------------------
; Function glic_fill_graphics
; ---------------------------------
_glic_fill_graphics:
;games/../common/glic80.h:62: for (i = 0; i < GLIC_GVRAM_BYTES; ++i) {
	ld	bc, #0x0000
00102$:
;games/../common/glic80.h:63: GLIC_GVRAM[i] = value;
	ld	hl, #0x7800
	add	hl, bc
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	ld	(hl), a
;games/../common/glic80.h:62: for (i = 0; i < GLIC_GVRAM_BYTES; ++i) {
	inc	bc
	ld	a, b
	sub	a, #0x08
	jr	C, 00102$
;games/../common/glic80.h:65: }
	ret
;games/../common/glic80.h:67: static void glic_plot(unsigned char x, unsigned char y, unsigned char value) {
;	---------------------------------
; Function glic_plot
; ---------------------------------
_glic_plot:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/../common/glic80.h:71: if ((x >= GLIC_SCREEN_WIDTH) || (y >= 128u)) {
	ld	a, 4 (ix)
	sub	a, #0x80
	jr	NC, 00107$
	ld	a, 5 (ix)
	sub	a, #0x80
;games/../common/glic80.h:72: return;
	jr	NC, 00107$
;games/../common/glic80.h:75: offset = (((unsigned int)(y >> 3)) << 7) + x;
	ld	a, 5 (ix)
	rrca
	rrca
	rrca
	and	a, #0x1f
	ld	l, a
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	ld	c, 4 (ix)
	ld	b, #0x00
	add	hl, bc
	ex	de, hl
;games/../common/glic80.h:76: mask = glic_bit_masks[y & 7u];
	ld	bc, #_glic_bit_masks+0
	ld	a, 5 (ix)
	and	a, #0x07
	ld	l, a
	ld	h, #0x00
	add	hl, bc
	ld	b, (hl)
;games/../common/glic80.h:78: GLIC_GVRAM[offset] |= mask;
	ld	hl, #0x7800
	add	hl, de
	ld	c, (hl)
;games/../common/glic80.h:77: if (value != 0u) {
	ld	a, 6 (ix)
	or	a, a
	jr	Z, 00105$
;games/../common/glic80.h:78: GLIC_GVRAM[offset] |= mask;
	ld	a, c
	or	a, b
	ld	(hl), a
	jr	00107$
00105$:
;games/../common/glic80.h:80: GLIC_GVRAM[offset] &= (unsigned char)~mask;
	ld	a, b
	cpl
	and	a, c
	ld	(hl), a
00107$:
;games/../common/glic80.h:82: }
	pop	ix
	ret
;games/../common/glic80.h:84: static void glic_draw_bitmap8(unsigned char x,
;	---------------------------------
; Function glic_draw_bitmap8
; ---------------------------------
_glic_draw_bitmap8:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/../common/glic80.h:92: for (row = 0u; row < 8u; ++row) {
	ld	c, #0x00
00107$:
;games/../common/glic80.h:93: bits = rows[row];
	ld	l, 6 (ix)
	ld	h, 7 (ix)
	ld	b, #0x00
	add	hl, bc
	ld	l, (hl)
;games/../common/glic80.h:94: mask = 0x80u;
	ld	e, #0x80
;games/../common/glic80.h:95: for (col = 0u; col < 8u; ++col) {
	ld	a, 5 (ix)
	add	a, c
	ld	b, a
	ld	d, #0x00
00105$:
;games/../common/glic80.h:96: if ((bits & mask) != 0u) {
	ld	a, l
	and	a,e
	jr	Z, 00102$
;games/../common/glic80.h:97: glic_plot((unsigned char)(x + col), (unsigned char)(y + row), 1u);
	ld	a, 4 (ix)
	add	a, d
	push	hl
	push	bc
	push	de
	ld	h, #0x01
	ld	l, b
	push	hl
	push	af
	inc	sp
	call	_glic_plot
	pop	af
	inc	sp
	pop	de
	pop	bc
	pop	hl
00102$:
;games/../common/glic80.h:99: mask >>= 1;
	srl	e
;games/../common/glic80.h:95: for (col = 0u; col < 8u; ++col) {
	inc	d
	ld	a, d
	sub	a, #0x08
	jr	C, 00105$
;games/../common/glic80.h:92: for (row = 0u; row < 8u; ++row) {
	inc	c
	ld	a, c
	sub	a, #0x08
	jr	C, 00107$
;games/../common/glic80.h:102: }
	pop	ix
	ret
;games/../common/glic80.h:104: static void glic_draw_tile8(unsigned char cell_x,
;	---------------------------------
; Function glic_draw_tile8
; ---------------------------------
_glic_draw_tile8:
	push	ix
	ld	ix,#0
	add	ix,sp
	push	af
;games/../common/glic80.h:110: offset = (((unsigned int)cell_y) << 7) + (((unsigned int)cell_x) << 3);
	ld	c, 5 (ix)
	xor	a, a
	rr	a
	ld	b, c
	rr	b
	rra
	ld	c, a
	ld	l, 4 (ix)
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, bc
	ex	de, hl
;games/../common/glic80.h:111: for (col = 0u; col < 8u; ++col) {
	ld	c, #0x00
00102$:
;games/../common/glic80.h:112: GLIC_GVRAM[offset + col] = columns[col];
	ld	l, c
	ld	h, #0x00
	add	hl, de
	ld	-2 (ix), l
	ld	a, h
	add	a, #0x78
	ld	-1 (ix), a
	ld	l, 6 (ix)
	ld	h, 7 (ix)
	ld	b, #0x00
	add	hl, bc
	ld	a, (hl)
	pop	hl
	push	hl
	ld	(hl), a
;games/../common/glic80.h:111: for (col = 0u; col < 8u; ++col) {
	inc	c
	ld	a, c
	sub	a, #0x08
	jr	C, 00102$
;games/../common/glic80.h:114: }
	ld	sp, ix
	pop	ix
	ret
;games/../common/glic80.h:116: static void glic_prepare_screen(unsigned char value) {
;	---------------------------------
; Function glic_prepare_screen
; ---------------------------------
_glic_prepare_screen:
;games/../common/glic80.h:117: glic_clear_text();
	call	_glic_clear_text
;games/../common/glic80.h:118: glic_fill_graphics(value);
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_glic_fill_graphics
	inc	sp
;games/../common/glic80.h:119: }
	ret
;games/../common/glic80.h:121: static void glic_fill_page_run(unsigned char page,
;	---------------------------------
; Function glic_fill_page_run
; ---------------------------------
_glic_fill_page_run:
;games/../common/glic80.h:127: p = GLIC_GVRAM + (((unsigned int)page) << 7) + x;
	ld	iy, #2
	add	iy, sp
	ld	c, 0 (iy)
	ld	b, #0x00
	xor	a, a
	rr	b
	ld	b, c
	rr	b
	rra
	ld	c, a
	ld	a, b
	add	a, #0x78
	ld	b, a
	ld	a, c
	ld	hl, #3
	add	hl, sp
	add	a, (hl)
	ld	c, a
	jr	NC, 00117$
	inc	b
00117$:
;games/../common/glic80.h:128: while (width != 0u) {
	ld	e, 2 (iy)
00101$:
	ld	a, e
	or	a, a
	ret	Z
;games/../common/glic80.h:129: *p++ = value;
	ld	iy, #5
	add	iy, sp
	ld	a, 0 (iy)
	ld	(bc), a
	inc	bc
;games/../common/glic80.h:130: --width;
	dec	e
;games/../common/glic80.h:132: }
	jr	00101$
;games/../common/glic80.h:134: static void glic_fill_pages(unsigned char first_page,
;	---------------------------------
; Function glic_fill_pages
; ---------------------------------
_glic_fill_pages:
;games/../common/glic80.h:137: while (page_count != 0u) {
	ld	iy, #2
	add	iy, sp
	ld	b, 0 (iy)
	ld	c, 1 (iy)
00101$:
	ld	a, c
	or	a, a
	ret	Z
;games/../common/glic80.h:138: glic_fill_page_run(first_page, 0u, GLIC_SCREEN_WIDTH, value);
	push	bc
	ld	hl, #6
	add	hl, sp
	ld	d, (hl)
	ld	e,#0x80
	push	de
	xor	a, a
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_fill_page_run
	pop	af
	pop	af
	pop	bc
;games/../common/glic80.h:139: ++first_page;
	inc	b
;games/../common/glic80.h:140: --page_count;
	dec	c
;games/../common/glic80.h:142: }
	jr	00101$
;games/../common/glic80.h:144: static void glic_fill_columns(unsigned char x,
;	---------------------------------
; Function glic_fill_columns
; ---------------------------------
_glic_fill_columns:
;games/../common/glic80.h:149: for (page = 0u; page < GLIC_SCREEN_PAGES; ++page) {
	ld	b, #0x00
00102$:
;games/../common/glic80.h:150: glic_fill_page_run(page, x, width, value);
	push	bc
	ld	iy, #6
	add	iy, sp
	ld	a, 0 (iy)
	push	af
	inc	sp
	ld	a, -1 (iy)
	dec	iy
	push	af
	inc	sp
	ld	a, -1 (iy)
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_fill_page_run
	pop	af
	pop	af
	pop	bc
;games/../common/glic80.h:149: for (page = 0u; page < GLIC_SCREEN_PAGES; ++page) {
	inc	b
	ld	a, b
	sub	a, #0x10
	jr	C, 00102$
;games/../common/glic80.h:152: }
	ret
;games/snake.c:49: static unsigned char random8(void) {
;	---------------------------------
; Function random8
; ---------------------------------
_random8:
;games/snake.c:52: bit = (unsigned char)(((rng_state >> 7) ^
	ld	iy, #_rng_state
	ld	a, 0 (iy)
	rlca
	and	a, #0x01
	ld	c, a
;games/snake.c:53: (rng_state >> 5) ^
	ld	a, 0 (iy)
	rlca
	rlca
	rlca
	and	a, #0x07
	xor	a, c
	ld	c, a
;games/snake.c:54: (rng_state >> 4) ^
	ld	a, 0 (iy)
	rlca
	rlca
	rlca
	rlca
	and	a, #0x0f
	xor	a, c
;games/snake.c:55: (rng_state >> 3)) & 1u);
	ld	c, 0 (iy)
	srl	c
	srl	c
	srl	c
	xor	a, c
	and	a, #0x01
;games/snake.c:56: rng_state = (unsigned char)((rng_state << 1) | bit);
	ld	c, 0 (iy)
	sla	c
	or	a, c
	ld	(_rng_state+0), a
;games/snake.c:57: return rng_state;
	ld	l, 0 (iy)
;games/snake.c:58: }
	ret
_grass_a:
	.db #0x00	; 0
	.db #0x10	; 16
	.db #0x00	; 0
	.db #0x01	; 1
	.db #0x00	; 0
	.db #0x40	; 64
	.db #0x00	; 0
	.db #0x04	; 4
_grass_b:
	.db #0x04	; 4
	.db #0x00	; 0
	.db #0x40	; 64
	.db #0x00	; 0
	.db #0x01	; 1
	.db #0x00	; 0
	.db #0x10	; 16
	.db #0x00	; 0
_snake_body:
	.db #0x3c	; 60
	.db #0x7e	; 126
	.db #0xdb	; 219
	.db #0xff	; 255
	.db #0xdb	; 219
	.db #0xff	; 255
	.db #0x7e	; 126
	.db #0x3c	; 60
_snake_head:
	.db #0x3c	; 60
	.db #0x7e	; 126
	.db #0xe7	; 231
	.db #0xff	; 255
	.db #0xff	; 255
	.db #0xe7	; 231
	.db #0x7e	; 126
	.db #0x3c	; 60
_fruit_tile:
	.db #0x18	; 24
	.db #0x3c	; 60
	.db #0x7e	; 126
	.db #0xfe	; 254
	.db #0xfe	; 254
	.db #0x7e	; 126
	.db #0x3c	; 60
	.db #0x18	; 24
_border_tile:
	.db #0xff	; 255
	.db #0x81	; 129
	.db #0xbd	; 189
	.db #0xa5	; 165
	.db #0xa5	; 165
	.db #0xbd	; 189
	.db #0x81	; 129
	.db #0xff	; 255
;games/snake.c:60: static unsigned char start_pressed(unsigned char buttons) {
;	---------------------------------
; Function start_pressed
; ---------------------------------
_start_pressed:
;games/snake.c:61: return (buttons & START_MASK) != START_MASK;
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	and	a, #0x81
	ld	b, a
	ld	c, #0x00
	ld	a, b
	sub	a, #0x81
	or	a, c
	ld	a, #0x01
	jr	Z, 00104$
	xor	a, a
00104$:
	xor	a, #0x01
	ld	l, a
;games/snake.c:62: }
	ret
;games/snake.c:64: static void wait_for_start_press(void) {
;	---------------------------------
; Function wait_for_start_press
; ---------------------------------
_wait_for_start_press:
;games/snake.c:65: while (start_pressed(glic_read_buttons()) != 0u) {
00101$:
	call	_glic_read_buttons
	ld	a, l
	push	af
	inc	sp
	call	_start_pressed
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00104$
;games/snake.c:66: random8();
	call	_random8
	jr	00101$
;games/snake.c:68: while (start_pressed(glic_read_buttons()) == 0u) {
00104$:
	call	_glic_read_buttons
	ld	a, l
	push	af
	inc	sp
	call	_start_pressed
	ld	a, l
	inc	sp
	or	a, a
	jr	NZ, 00107$
;games/snake.c:69: random8();
	call	_random8
	jr	00104$
;games/snake.c:71: while (start_pressed(glic_read_buttons()) != 0u) {
00107$:
	call	_glic_read_buttons
	ld	a, l
	push	af
	inc	sp
	call	_start_pressed
	inc	sp
	ld	a, l
	or	a, a
	ret	Z
;games/snake.c:72: random8();
	call	_random8
;games/snake.c:74: }
	jr	00107$
;games/snake.c:76: static volatile unsigned char *text_cell(unsigned char row,
;	---------------------------------
; Function text_cell
; ---------------------------------
_text_cell:
;games/snake.c:81: while (row != 0u) {
	ld	bc, #0x7700
	ld	iy, #2
	add	iy, sp
	ld	l, 0 (iy)
00101$:
	ld	a, l
	or	a, a
	jr	Z, 00103$
;games/snake.c:82: p += 16u;
	ld	a, c
	add	a, #0x10
	ld	c, a
	jr	NC, 00117$
	inc	b
00117$:
;games/snake.c:83: --row;
	dec	l
	jr	00101$
00103$:
;games/snake.c:85: p += col;
	ld	a, c
	ld	hl, #3
	add	hl, sp
	add	a, (hl)
	ld	l, a
	jr	NC, 00118$
	inc	b
00118$:
	ld	h, b
;games/snake.c:86: return p;
;games/snake.c:87: }
	ret
;games/snake.c:89: static void text_put(unsigned char row, unsigned char col, unsigned char ch) {
;	---------------------------------
; Function text_put
; ---------------------------------
_text_put:
;games/snake.c:90: if ((row >= 16u) || (col >= 16u)) {
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	sub	a, #0x10
	ret	NC
	ld	a, 1 (iy)
	sub	a, #0x10
;games/snake.c:91: return;
	ret	NC
;games/snake.c:93: *text_cell(row, col) = ch;
	ld	iy, #3
	add	iy, sp
	ld	h, 0 (iy)
	ld	l, -1 (iy)
	push	hl
	call	_text_cell
	pop	af
	ld	iy, #4
	add	iy, sp
	ld	a, 0 (iy)
	ld	(hl), a
;games/snake.c:94: }
	ret
;games/snake.c:96: static void text_clear_row(unsigned char row) {
;	---------------------------------
; Function text_clear_row
; ---------------------------------
_text_clear_row:
;games/snake.c:99: for (col = 0u; col < 16u; ++col) {
	ld	b, #0x00
00102$:
;games/snake.c:100: text_put(row, col, 0u);
	push	bc
	xor	a, a
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	hl, #6
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
	pop	bc
;games/snake.c:99: for (col = 0u; col < 16u; ++col) {
	inc	b
	ld	a, b
	sub	a, #0x10
	jr	C, 00102$
;games/snake.c:102: }
	ret
;games/snake.c:104: static void text_write(unsigned char row, unsigned char col, const char *text) {
;	---------------------------------
; Function text_write
; ---------------------------------
_text_write:
;games/snake.c:105: while ((*text != 0) && (col < 16u)) {
	ld	iy, #4
	add	iy, sp
	ld	l, 0 (iy)
	ld	h, 1 (iy)
	ld	b, -1 (iy)
00102$:
	ld	d, (hl)
	ld	a, d
	or	a, a
	ret	Z
	ld	a, b
	sub	a, #0x10
	ret	NC
;games/snake.c:106: text_put(row, col, (unsigned char)*text);
	push	hl
	push	bc
	ld	e, b
	push	de
	ld	hl, #8
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
	pop	bc
	pop	hl
;games/snake.c:107: ++text;
	inc	hl
;games/snake.c:108: ++col;
	inc	b
;games/snake.c:110: }
	jr	00102$
;games/snake.c:112: static void text_write_u8_3(unsigned char row,
;	---------------------------------
; Function text_write_u8_3
; ---------------------------------
_text_write_u8_3:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/snake.c:119: while (value >= 100u) {
	ld	d, 6 (ix)
	ld	c, #0x00
00101$:
;games/snake.c:120: value = (unsigned char)(value - 100u);
	ld	a,d
	cp	a,#0x64
	jr	C, 00113$
	add	a, #0x9c
	ld	d, a
;games/snake.c:121: ++hundreds;
	inc	c
	jr	00101$
00113$:
;games/snake.c:124: while (value >= 10u) {
	ld	e, #0x00
00104$:
;games/snake.c:125: value = (unsigned char)(value - 10u);
	ld	a,d
	cp	a,#0x0a
	jr	C, 00106$
	add	a, #0xf6
	ld	d, a
;games/snake.c:126: ++tens;
	inc	e
	jr	00104$
00106$:
;games/snake.c:128: text_put(row, col, (unsigned char)('0' + hundreds));
	ld	a, c
	add	a, #0x30
	push	de
	push	af
	inc	sp
	ld	h, 5 (ix)
	ld	l, 4 (ix)
	push	hl
	call	_text_put
	pop	af
	inc	sp
	pop	de
;games/snake.c:129: text_put(row, (unsigned char)(col + 1u), (unsigned char)('0' + tens));
	ld	a, e
	add	a, #0x30
	ld	b, 5 (ix)
	inc	b
	push	de
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
	pop	de
;games/snake.c:132: (unsigned char)('0' + value));
	ld	a, d
	add	a, #0x30
;games/snake.c:131: (unsigned char)(col + 2u),
	ld	b, 5 (ix)
	inc	b
	inc	b
;games/snake.c:130: text_put(row,
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
;games/snake.c:133: }
	pop	ix
	ret
;games/snake.c:135: static void draw_score(void) {
;	---------------------------------
; Function draw_score
; ---------------------------------
_draw_score:
;games/snake.c:136: text_clear_row(0u);
	xor	a, a
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;games/snake.c:137: text_write(0u, 0u, "SCORE");
	ld	hl, #___str_0
	push	hl
	xor	a, a
	push	af
	inc	sp
	xor	a, a
	push	af
	inc	sp
	call	_text_write
	pop	af
	pop	af
;games/snake.c:138: text_write_u8_3(0u, 6u, score);
	ld	a,(#_score + 0)
	ld	d,a
	ld	e,#0x06
	push	de
	xor	a, a
	push	af
	inc	sp
	call	_text_write_u8_3
	pop	af
	inc	sp
;games/snake.c:139: }
	ret
___str_0:
	.ascii "SCORE"
	.db 0x00
;games/snake.c:141: static unsigned char snake_contains(unsigned char x,
;	---------------------------------
; Function snake_contains
; ---------------------------------
_snake_contains:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/snake.c:146: for (i = 0u; i < count; ++i) {
	ld	bc, #_snake_y+0
	ld	e, #0x00
00106$:
	ld	a, e
	sub	a, 6 (ix)
	jr	NC, 00104$
;games/snake.c:147: if ((snake_x[i] == x) && (snake_y[i] == y)) {
	ld	hl, #_snake_x
	ld	d, #0x00
	add	hl, de
	ld	a,4 (ix)
	sub	a,(hl)
	jr	NZ, 00107$
	ld	l, e
	ld	h, #0x00
	add	hl, bc
	ld	a,5 (ix)
	sub	a,(hl)
	jr	NZ, 00107$
;games/snake.c:148: return 1u;
	ld	l, #0x01
	jr	00108$
00107$:
;games/snake.c:146: for (i = 0u; i < count; ++i) {
	inc	e
	jr	00106$
00104$:
;games/snake.c:151: return 0u;
	ld	l, #0x00
00108$:
;games/snake.c:152: }
	pop	ix
	ret
;games/snake.c:154: static void place_fruit(void) {
;	---------------------------------
; Function place_fruit
; ---------------------------------
_place_fruit:
;games/snake.c:158: do {
	ld	c, #0x00
00102$:
;games/snake.c:159: fruit_x = random8() & 15u;
	push	bc
	call	_random8
	ld	a, l
	pop	bc
	and	a, #0x0f
	ld	(_fruit_x+0), a
;games/snake.c:160: fruit_y = (random8() >> 4) & 15u;
	push	bc
	call	_random8
	ld	a, l
	pop	bc
	rlca
	rlca
	rlca
	rlca
	and	a, #0x0f
	and	a, #0x0f
	ld	(_fruit_y+0), a
;games/snake.c:161: ++tries;
	inc	c
;games/snake.c:162: } while ((snake_contains(fruit_x, fruit_y, snake_len) != 0u) &&
	push	bc
	ld	a,(#_snake_len + 0)
	push	af
	inc	sp
	ld	a,(#_fruit_y + 0)
	push	af
	inc	sp
	ld	a,(#_fruit_x + 0)
	push	af
	inc	sp
	call	_snake_contains
	pop	af
	inc	sp
	ld	a, l
	pop	bc
	or	a, a
	ret	Z
;games/snake.c:163: (tries != 0u));
	ld	a, c
	or	a, a
	jr	NZ, 00102$
;games/snake.c:164: }
	ret
;games/snake.c:166: static void reset_game(void) {
;	---------------------------------
; Function reset_game
; ---------------------------------
_reset_game:
;games/snake.c:167: snake_len = 4u;
	ld	hl, #_snake_len
	ld	(hl), #0x04
;games/snake.c:168: score = 0u;
	ld	hl, #_score
	ld	(hl), #0x00
;games/snake.c:169: snake_x[0] = 8u;
	ld	hl, #_snake_x
	ld	(hl), #0x08
;games/snake.c:170: snake_y[0] = 8u;
	ld	hl, #_snake_y
	ld	(hl), #0x08
;games/snake.c:171: snake_x[1] = 7u;
	ld	hl, #(_snake_x + 0x0001)
	ld	(hl), #0x07
;games/snake.c:172: snake_y[1] = 8u;
	ld	hl, #(_snake_y + 0x0001)
	ld	(hl), #0x08
;games/snake.c:173: snake_x[2] = 6u;
	ld	hl, #(_snake_x + 0x0002)
	ld	(hl), #0x06
;games/snake.c:174: snake_y[2] = 8u;
	ld	hl, #(_snake_y + 0x0002)
	ld	(hl), #0x08
;games/snake.c:175: snake_x[3] = 5u;
	ld	hl, #(_snake_x + 0x0003)
	ld	(hl), #0x05
;games/snake.c:176: snake_y[3] = 8u;
	ld	hl, #(_snake_y + 0x0003)
	ld	(hl), #0x08
;games/snake.c:177: direction = DIR_RIGHT;
	ld	iy, #_direction
	ld	0 (iy), #0x01
;games/snake.c:178: place_fruit();
;games/snake.c:179: }
	jp	_place_fruit
;games/snake.c:181: static void update_direction(unsigned char buttons) {
;	---------------------------------
; Function update_direction
; ---------------------------------
_update_direction:
;games/snake.c:182: if ((glic_button_pressed(buttons, GLIC_BTN_UP) != 0u) &&
	ld	a, #0x02
	push	af
	inc	sp
	ld	hl, #3
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_glic_button_pressed
	pop	af
	ld	a, l
	or	a, a
	jr	Z, 00113$
;games/snake.c:183: (direction != DIR_DOWN)) {
	ld	iy, #_direction
	ld	a, 0 (iy)
	sub	a, #0x02
	jr	Z, 00113$
;games/snake.c:184: direction = DIR_UP;
	ld	0 (iy), #0x00
	ret
00113$:
;games/snake.c:185: } else if ((glic_button_pressed(buttons, GLIC_BTN_RIGHT) != 0u) &&
	ld	a, #0x04
	push	af
	inc	sp
	ld	hl, #3
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_glic_button_pressed
	pop	af
	ld	a, l
	or	a, a
	jr	Z, 00109$
;games/snake.c:186: (direction != DIR_LEFT)) {
	ld	iy, #_direction
	ld	a, 0 (iy)
	sub	a, #0x03
	jr	Z, 00109$
;games/snake.c:187: direction = DIR_RIGHT;
	ld	0 (iy), #0x01
	ret
00109$:
;games/snake.c:188: } else if ((glic_button_pressed(buttons, GLIC_BTN_DOWN) != 0u) &&
	ld	a, #0x08
	push	af
	inc	sp
	ld	hl, #3
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_glic_button_pressed
	pop	af
	ld	a, l
	or	a, a
	jr	Z, 00105$
;games/snake.c:189: (direction != DIR_UP)) {
	ld	iy, #_direction
	ld	a, 0 (iy)
	or	a, a
	jr	Z, 00105$
;games/snake.c:190: direction = DIR_DOWN;
	ld	0 (iy), #0x02
	ret
00105$:
;games/snake.c:191: } else if ((glic_button_pressed(buttons, GLIC_BTN_LEFT) != 0u) &&
	ld	a, #0x10
	push	af
	inc	sp
	ld	hl, #3
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_glic_button_pressed
	pop	af
	ld	a, l
	or	a, a
	ret	Z
;games/snake.c:192: (direction != DIR_RIGHT)) {
	ld	iy, #_direction
	ld	a, 0 (iy)
	dec	a
	ret	Z
;games/snake.c:193: direction = DIR_LEFT;
	ld	0 (iy), #0x03
;games/snake.c:195: }
	ret
;games/snake.c:197: static void draw_floor_tile(unsigned char x, unsigned char y) {
;	---------------------------------
; Function draw_floor_tile
; ---------------------------------
_draw_floor_tile:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/snake.c:198: if (((x + y) & 1u) == 0u) {
	ld	c, 4 (ix)
	ld	b, #0x00
	ld	l, 5 (ix)
	ld	h, #0x00
	add	hl, bc
	bit	0, l
	jr	NZ, 00102$
;games/snake.c:199: glic_draw_tile8(x, y, grass_a);
	ld	hl, #_grass_a
	push	hl
	ld	h, 5 (ix)
	ld	l, 4 (ix)
	push	hl
	call	_glic_draw_tile8
	pop	af
	pop	af
	jr	00104$
00102$:
;games/snake.c:201: glic_draw_tile8(x, y, grass_b);
	ld	hl, #_grass_b
	push	hl
	ld	h, 5 (ix)
	ld	l, 4 (ix)
	push	hl
	call	_glic_draw_tile8
	pop	af
	pop	af
00104$:
;games/snake.c:203: }
	pop	ix
	ret
;games/snake.c:205: static void draw_board(void) {
;	---------------------------------
; Function draw_board
; ---------------------------------
_draw_board:
;games/snake.c:209: for (y = 0u; y < 16u; ++y) {
	ld	c, #0x00
;games/snake.c:210: for (x = 0u; x < 16u; ++x) {
00109$:
	ld	b, #0x00
00103$:
;games/snake.c:211: draw_floor_tile(x, y);
	push	bc
	ld	a, c
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_draw_floor_tile
	pop	af
	pop	bc
;games/snake.c:210: for (x = 0u; x < 16u; ++x) {
	inc	b
	ld	a, b
	sub	a, #0x10
	jr	C, 00103$
;games/snake.c:209: for (y = 0u; y < 16u; ++y) {
	inc	c
	ld	a, c
	sub	a, #0x10
	jr	C, 00109$
;games/snake.c:214: }
	ret
;games/snake.c:216: static void draw_snake(void) {
;	---------------------------------
; Function draw_snake
; ---------------------------------
_draw_snake:
;games/snake.c:219: glic_draw_tile8(fruit_x, fruit_y, fruit_tile);
	ld	hl, #_fruit_tile
	push	hl
	ld	a,(#_fruit_y + 0)
	push	af
	inc	sp
	ld	a,(#_fruit_x + 0)
	push	af
	inc	sp
	call	_glic_draw_tile8
	pop	af
	pop	af
;games/snake.c:220: for (i = 1u; i < snake_len; ++i) {
	ld	c, #0x01
00103$:
	ld	hl, #_snake_len
	ld	a, c
	sub	a, (hl)
	jr	NC, 00101$
;games/snake.c:221: glic_draw_tile8(snake_x[i], snake_y[i], snake_body);
	ld	hl, #_snake_y
	ld	b, #0x00
	add	hl, bc
	ld	e, (hl)
	ld	hl, #_snake_x
	ld	b, #0x00
	add	hl, bc
	ld	a, (hl)
	push	bc
	ld	hl, #_snake_body
	push	hl
	ld	h, e
	push	hl
	inc	sp
	push	af
	inc	sp
	call	_glic_draw_tile8
	pop	af
	pop	af
	pop	bc
;games/snake.c:220: for (i = 1u; i < snake_len; ++i) {
	inc	c
	jr	00103$
00101$:
;games/snake.c:223: glic_draw_tile8(snake_x[0], snake_y[0], snake_head);
	ld	a, (#_snake_y + 0)
	ld	hl, #_snake_x
	ld	b, (hl)
	ld	hl, #_snake_head
	push	hl
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_draw_tile8
	pop	af
	pop	af
;games/snake.c:224: }
	ret
;games/snake.c:226: static void draw_game_over_border(void) {
;	---------------------------------
; Function draw_game_over_border
; ---------------------------------
_draw_game_over_border:
;games/snake.c:229: for (i = 0u; i < 16u; ++i) {
	ld	c, #0x00
00102$:
;games/snake.c:230: glic_draw_tile8(i, 0u, border_tile);
	push	bc
	ld	hl, #_border_tile
	push	hl
	xor	a, a
	ld	b, a
	push	bc
	call	_glic_draw_tile8
	pop	af
	pop	af
	pop	bc
;games/snake.c:231: glic_draw_tile8(i, 15u, border_tile);
	push	bc
	ld	hl, #_border_tile
	push	hl
	ld	b, #0x0f
	push	bc
	call	_glic_draw_tile8
	pop	af
	pop	af
	pop	bc
;games/snake.c:232: glic_draw_tile8(0u, i, border_tile);
	push	bc
	ld	hl, #_border_tile
	push	hl
	ld	a, c
	push	af
	inc	sp
	xor	a, a
	push	af
	inc	sp
	call	_glic_draw_tile8
	pop	af
	pop	af
	pop	bc
;games/snake.c:233: glic_draw_tile8(15u, i, border_tile);
	push	bc
	ld	hl, #_border_tile
	push	hl
	ld	d, c
	ld	e,#0x0f
	push	de
	call	_glic_draw_tile8
	pop	af
	pop	af
	pop	bc
;games/snake.c:229: for (i = 0u; i < 16u; ++i) {
	inc	c
	ld	a, c
	sub	a, #0x10
	jr	C, 00102$
;games/snake.c:235: }
	ret
;games/snake.c:237: static void draw_title_screen(void) {
;	---------------------------------
; Function draw_title_screen
; ---------------------------------
_draw_title_screen:
;games/snake.c:238: glic_prepare_screen(GLIC_BLACK);
	xor	a, a
	push	af
	inc	sp
	call	_glic_prepare_screen
	inc	sp
;games/snake.c:239: draw_board();
	call	_draw_board
;games/snake.c:240: glic_draw_tile8(5u, 8u, snake_body);
	ld	hl, #_snake_body
	push	hl
	ld	de, #0x0805
	push	de
	call	_glic_draw_tile8
	pop	af
;games/snake.c:241: glic_draw_tile8(6u, 8u, snake_body);
	ld	hl, #_snake_body
	ex	(sp),hl
	ld	de, #0x0806
	push	de
	call	_glic_draw_tile8
	pop	af
;games/snake.c:242: glic_draw_tile8(7u, 8u, snake_body);
	ld	hl, #_snake_body
	ex	(sp),hl
	ld	de, #0x0807
	push	de
	call	_glic_draw_tile8
	pop	af
;games/snake.c:243: glic_draw_tile8(8u, 8u, snake_head);
	ld	hl, #_snake_head
	ex	(sp),hl
	ld	de, #0x0808
	push	de
	call	_glic_draw_tile8
	pop	af
;games/snake.c:244: glic_draw_tile8(11u, 8u, fruit_tile);
	ld	hl, #_fruit_tile
	ex	(sp),hl
	ld	de, #0x080b
	push	de
	call	_glic_draw_tile8
	pop	af
;games/snake.c:245: text_write(2u, 5u, "SNAKE");
	ld	hl, #___str_1
	ex	(sp),hl
	ld	de, #0x0502
	push	de
	call	_text_write
	pop	af
;games/snake.c:246: text_write(5u, 1u, "CENTER/A START");
	ld	hl, #___str_2
	ex	(sp),hl
	ld	de, #0x0105
	push	de
	call	_text_write
	pop	af
;games/snake.c:247: text_write(7u, 2u, "ARROWS MOVE");
	ld	hl, #___str_3
	ex	(sp),hl
	ld	de, #0x0207
	push	de
	call	_text_write
	pop	af
;games/snake.c:248: text_write(11u, 2u, "EAT FRUIT");
	ld	hl, #___str_4
	ex	(sp),hl
	ld	de, #0x020b
	push	de
	call	_text_write
	pop	af
	pop	af
;games/snake.c:249: }
	ret
___str_1:
	.ascii "SNAKE"
	.db 0x00
___str_2:
	.ascii "CENTER/A START"
	.db 0x00
___str_3:
	.ascii "ARROWS MOVE"
	.db 0x00
___str_4:
	.ascii "EAT FRUIT"
	.db 0x00
;games/snake.c:251: static void draw_game_over_text(void) {
;	---------------------------------
; Function draw_game_over_text
; ---------------------------------
_draw_game_over_text:
;games/snake.c:252: text_clear_row(0u);
	xor	a, a
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;games/snake.c:253: text_clear_row(5u);
	ld	a, #0x05
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;games/snake.c:254: text_clear_row(6u);
	ld	a, #0x06
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;games/snake.c:255: text_clear_row(7u);
	ld	a, #0x07
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;games/snake.c:256: text_clear_row(8u);
	ld	a, #0x08
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;games/snake.c:257: text_clear_row(10u);
	ld	a, #0x0a
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;games/snake.c:258: text_write(5u, 3u, "GAME OVER");
	ld	hl, #___str_5
	push	hl
	ld	de, #0x0305
	push	de
	call	_text_write
	pop	af
;games/snake.c:259: text_write(7u, 4u, "SCORE");
	ld	hl, #___str_6
	ex	(sp),hl
	ld	de, #0x0407
	push	de
	call	_text_write
	pop	af
	pop	af
;games/snake.c:260: text_write_u8_3(7u, 10u, score);
	ld	a,(#_score + 0)
	ld	d,a
	ld	e,#0x0a
	push	de
	ld	a, #0x07
	push	af
	inc	sp
	call	_text_write_u8_3
;games/snake.c:261: text_write(10u, 1u, "CENTER/A MENU");
	inc	sp
	ld	hl,#___str_7
	ex	(sp),hl
	ld	de, #0x010a
	push	de
	call	_text_write
	pop	af
	pop	af
;games/snake.c:262: }
	ret
___str_5:
	.ascii "GAME OVER"
	.db 0x00
___str_6:
	.ascii "SCORE"
	.db 0x00
___str_7:
	.ascii "CENTER/A MENU"
	.db 0x00
;games/snake.c:264: static unsigned char advance_snake(void) {
;	---------------------------------
; Function advance_snake
; ---------------------------------
_advance_snake:
	push	ix
	ld	ix,#0
	add	ix,sp
	ld	hl, #-6
	add	hl, sp
	ld	sp, hl
;games/snake.c:271: last_head_x = snake_x[0];
	ld	bc, #_snake_x+0
	ld	a, (bc)
	ld	(_last_head_x+0), a
;games/snake.c:272: last_head_y = snake_y[0];
	ld	hl, #_snake_y
	ld	a, (hl)
	ld	(_last_head_y+0), a
;games/snake.c:273: last_tail_x = snake_x[snake_len - 1u];
	ld	a, (#_snake_len + 0)
	ld	e, a
	dec	e
	ld	l, e
	ld	h, #0x00
	add	hl, bc
	ld	a, (hl)
	ld	(_last_tail_x+0), a
;games/snake.c:274: last_tail_y = snake_y[snake_len - 1u];
	ld	hl, #_snake_y
	ld	d, #0x00
	add	hl, de
	ld	a, (hl)
	ld	(_last_tail_y+0), a
;games/snake.c:275: last_grew = 0u;
	ld	hl, #_last_grew
	ld	(hl), #0x00
;games/snake.c:276: last_ate_fruit = 0u;
	ld	hl, #_last_ate_fruit
	ld	(hl), #0x00
;games/snake.c:278: new_x = snake_x[0];
	ld	a, (bc)
	ld	e, a
;games/snake.c:279: new_y = snake_y[0];
	ld	hl, #_snake_y
	ld	d, (hl)
;games/snake.c:281: if (direction == DIR_UP) {
	ld	a,(#_direction + 0)
;games/snake.c:282: if (new_y == 0u) {
	or	a,a
	jr	NZ, 00116$
	or	a,d
	jr	NZ, 00102$
;games/snake.c:283: return 1u;
	ld	l, #0x01
	jp	00136$
00102$:
;games/snake.c:285: --new_y;
	dec	d
	jr	00117$
00116$:
;games/snake.c:286: } else if (direction == DIR_RIGHT) {
	ld	a,(#_direction + 0)
	dec	a
	jr	NZ, 00113$
;games/snake.c:287: if (new_x == 15u) {
	ld	a, e
	sub	a, #0x0f
	jr	NZ, 00104$
;games/snake.c:288: return 1u;
	ld	l, #0x01
	jp	00136$
00104$:
;games/snake.c:290: ++new_x;
	inc	e
	jr	00117$
00113$:
;games/snake.c:291: } else if (direction == DIR_DOWN) {
	ld	a,(#_direction + 0)
	sub	a, #0x02
	jr	NZ, 00110$
;games/snake.c:292: if (new_y == 15u) {
	ld	a, d
	sub	a, #0x0f
	jr	NZ, 00106$
;games/snake.c:293: return 1u;
	ld	l, #0x01
	jp	00136$
00106$:
;games/snake.c:295: ++new_y;
	inc	d
	jr	00117$
00110$:
;games/snake.c:297: if (new_x == 0u) {
	ld	a, e
	or	a, a
	jr	NZ, 00108$
;games/snake.c:298: return 1u;
	ld	l, #0x01
	jp	00136$
00108$:
;games/snake.c:300: --new_x;
	dec	e
00117$:
;games/snake.c:303: grow = 0u;
	ld	-4 (ix), #0
;games/snake.c:304: if ((new_x == fruit_x) && (new_y == fruit_y)) {
	ld	a,(#_fruit_x + 0)
	sub	a, e
	jr	NZ, 00119$
	ld	a,(#_fruit_y + 0)
	sub	a, d
	jr	NZ, 00119$
;games/snake.c:305: grow = 1u;
	ld	-4 (ix), #0x01
;games/snake.c:306: last_ate_fruit = 1u;
	ld	hl, #_last_ate_fruit
	ld	(hl), #0x01
00119$:
;games/snake.c:309: collision_count = snake_len;
	ld	a, (#_snake_len + 0)
	ld	h, a
;games/snake.c:310: if ((grow == 0u) && (collision_count != 0u)) {
	ld	a, -4 (ix)
	or	a,a
	jr	NZ, 00122$
	or	a,h
	jr	Z, 00122$
;games/snake.c:311: --collision_count;
	dec	h
00122$:
;games/snake.c:313: if (snake_contains(new_x, new_y, collision_count) != 0u) {
	push	bc
	push	de
	ld	l, d
	push	hl
	ld	a, e
	push	af
	inc	sp
	call	_snake_contains
	pop	af
	inc	sp
	ld	a, l
	pop	de
	pop	bc
	or	a, a
	jr	Z, 00125$
;games/snake.c:314: return 1u;
	ld	l, #0x01
	jp	00136$
00125$:
;games/snake.c:317: if ((grow != 0u) && (snake_len < SNAKE_MAX)) {
	ld	a, -4 (ix)
	or	a, a
	jr	Z, 00129$
	ld	iy, #_snake_len
	ld	a, 0 (iy)
	sub	a, #0x40
	jr	NC, 00129$
;games/snake.c:318: ++snake_len;
	inc	0 (iy)
;games/snake.c:319: last_grew = 1u;
	ld	hl, #_last_grew
	ld	(hl), #0x01
;games/snake.c:320: if (score < 255u) {
	ld	iy, #_score
	ld	a, 0 (iy)
	sub	a, #0xff
	jr	NC, 00129$
;games/snake.c:321: ++score;
	inc	0 (iy)
00129$:
;games/snake.c:325: i = (unsigned char)(snake_len - 1u);
	ld	a,(#_snake_len + 0)
	add	a, #0xff
	ld	-1 (ix), a
;games/snake.c:326: while (i != 0u) {
00131$:
	ld	a, -1 (ix)
	or	a, a
	jr	Z, 00133$
;games/snake.c:327: snake_x[i] = snake_x[i - 1u];
	ld	a, c
	add	a, -1 (ix)
	ld	-6 (ix), a
	ld	a, b
	adc	a, #0x00
	ld	-5 (ix), a
	ld	a, -1 (ix)
	add	a, #0xff
	ld	-3 (ix), a
	ld	l, a
	ld	h, #0x00
	add	hl, bc
	ld	a, (hl)
	pop	hl
	push	hl
	ld	(hl), a
;games/snake.c:328: snake_y[i] = snake_y[i - 1u];
	ld	a, -1 (ix)
	add	a, #<(_snake_y)
	ld	-2 (ix), a
	ld	a, #0x00
	adc	a, #>(_snake_y)
	ld	-1 (ix), a
	ld	a, #<(_snake_y)
	add	a, -3 (ix)
	ld	l, a
	ld	a, #>(_snake_y)
	adc	a, #0x00
	ld	h, a
	ld	a, (hl)
	ld	l, -2 (ix)
	ld	h, -1 (ix)
	ld	(hl), a
;games/snake.c:329: --i;
	ld	a, -3 (ix)
	ld	-1 (ix), a
	jr	00131$
00133$:
;games/snake.c:331: snake_x[0] = new_x;
	ld	a, e
	ld	(bc), a
;games/snake.c:332: snake_y[0] = new_y;
	ld	hl, #_snake_y
	ld	(hl), d
;games/snake.c:334: if (grow != 0u) {
	ld	a, -4 (ix)
	or	a, a
	jr	Z, 00135$
;games/snake.c:335: place_fruit();
	call	_place_fruit
00135$:
;games/snake.c:338: return 0u;
	ld	l, #0x00
00136$:
;games/snake.c:339: }
	ld	sp, ix
	pop	ix
	ret
;games/snake.c:341: static void draw_snake_step(void) {
;	---------------------------------
; Function draw_snake_step
; ---------------------------------
_draw_snake_step:
;games/snake.c:342: if (last_grew == 0u) {
	ld	a,(#_last_grew + 0)
	or	a, a
	jr	NZ, 00102$
;games/snake.c:343: draw_floor_tile(last_tail_x, last_tail_y);
	ld	a,(#_last_tail_y + 0)
	push	af
	inc	sp
	ld	a,(#_last_tail_x + 0)
	push	af
	inc	sp
	call	_draw_floor_tile
	pop	af
00102$:
;games/snake.c:345: glic_draw_tile8(last_head_x, last_head_y, snake_body);
	ld	hl, #_snake_body
	push	hl
	ld	a,(#_last_head_y + 0)
	push	af
	inc	sp
	ld	a,(#_last_head_x + 0)
	push	af
	inc	sp
	call	_glic_draw_tile8
	pop	af
	pop	af
;games/snake.c:346: glic_draw_tile8(snake_x[0], snake_y[0], snake_head);
	ld	de, #_snake_head+0
	ld	hl, #_snake_y+0
	ld	b, (hl)
	ld	a, (#_snake_x + 0)
	push	de
	push	bc
	inc	sp
	push	af
	inc	sp
	call	_glic_draw_tile8
	pop	af
	pop	af
;games/snake.c:347: if (last_ate_fruit != 0u) {
	ld	a,(#_last_ate_fruit + 0)
	or	a, a
	ret	Z
;games/snake.c:348: glic_draw_tile8(fruit_x, fruit_y, fruit_tile);
	ld	hl, #_fruit_tile
	push	hl
	ld	a,(#_fruit_y + 0)
	push	af
	inc	sp
	ld	a,(#_fruit_x + 0)
	push	af
	inc	sp
	call	_glic_draw_tile8
	pop	af
	pop	af
;games/snake.c:349: draw_score();
;games/snake.c:351: }
	jp	_draw_score
;games/snake.c:353: static void read_controls_during_delay(void) {
;	---------------------------------
; Function read_controls_during_delay
; ---------------------------------
_read_controls_during_delay:
;games/snake.c:356: for (i = 0u; i < 8u; ++i) {
	ld	c, #0x00
00102$:
;games/snake.c:357: update_direction(glic_read_buttons());
	push	bc
	call	_glic_read_buttons
	ld	a, l
	push	af
	inc	sp
	call	_update_direction
	inc	sp
	ld	hl, #0x0708
	push	hl
	call	_glic_delay
	pop	af
	pop	bc
;games/snake.c:356: for (i = 0u; i < 8u; ++i) {
	inc	c
	ld	a, c
	sub	a, #0x08
	jr	C, 00102$
;games/snake.c:360: }
	ret
;games/snake.c:362: void main(void) {
;	---------------------------------
; Function main
; ---------------------------------
_main::
;games/snake.c:365: rng_state = 0xa7u;
	ld	hl, #_rng_state
	ld	(hl), #0xa7
;games/snake.c:367: while (1) {
00107$:
;games/snake.c:368: draw_title_screen();
	call	_draw_title_screen
;games/snake.c:369: wait_for_start_press();
	call	_wait_for_start_press
;games/snake.c:370: reset_game();
	call	_reset_game
;games/snake.c:371: glic_clear_text();
	call	_glic_clear_text
;games/snake.c:372: draw_board();
	call	_draw_board
;games/snake.c:373: draw_snake();
	call	_draw_snake
;games/snake.c:374: draw_score();
	call	_draw_score
;games/snake.c:375: dead = 0u;
	ld	c, #0x00
;games/snake.c:377: while (dead == 0u) {
00103$:
	ld	a, c
	or	a, a
	jr	NZ, 00105$
;games/snake.c:378: read_controls_during_delay();
	call	_read_controls_during_delay
;games/snake.c:379: dead = advance_snake();
	call	_advance_snake
	ld	a, l
	ld	c, a
;games/snake.c:380: if (dead == 0u) {
	or	a, a
	jr	NZ, 00103$
;games/snake.c:381: draw_snake_step();
	push	bc
	call	_draw_snake_step
	pop	bc
	jr	00103$
00105$:
;games/snake.c:385: draw_game_over_border();
	call	_draw_game_over_border
;games/snake.c:386: draw_game_over_text();
	call	_draw_game_over_text
;games/snake.c:387: wait_for_start_press();
	call	_wait_for_start_press
;games/snake.c:389: }
	jr	00107$
	.area _CODE
	.area _INITIALIZER
	.area _CABS (ABS)
