; generated by sdcc-z80-bin
    JR __sdcc_z80_bin_start
    DB "sudoku",0
__sdcc_z80_bin_start:
    LD SP,#0x7700
    CALL _main
__sdcc_z80_bin_halt:
    JR __sdcc_z80_bin_halt

;--------------------------------------------------------
; File Created by SDCC : free open source ANSI-C Compiler
; Version 4.1.0 #12072 (Linux)
;--------------------------------------------------------
	.module sudoku
	.optsdcc -mz80
	
;--------------------------------------------------------
; Public variables in this module
;--------------------------------------------------------
	.globl _main
;--------------------------------------------------------
; special function registers
;--------------------------------------------------------
;--------------------------------------------------------
; ram data
;--------------------------------------------------------
	.area _DATA
_board:
	.ds 81
_givens:
	.ds 81
_solution:
	.ds 81
_selected_level:
	.ds 1
;--------------------------------------------------------
; ram data
;--------------------------------------------------------
	.area _INITIALIZED
;--------------------------------------------------------
; absolute external ram data
;--------------------------------------------------------
	.area _DABS (ABS)
;--------------------------------------------------------
; global & static initialisations
;--------------------------------------------------------
	.area _HOME
	.area _GSINIT
	.area _GSFINAL
	.area _GSINIT
;--------------------------------------------------------
; Home
;--------------------------------------------------------
	.area _HOME
	.area _HOME
;--------------------------------------------------------
; code
;--------------------------------------------------------
	.area _CODE
;games/../common/glic80.h:29: static unsigned char glic_read_buttons(void) __naked {
;	---------------------------------
; Function glic_read_buttons
; ---------------------------------
_glic_read_buttons:
;games/../common/glic80.h:34: __endasm;
	in	a,(0)
	ld	l,a
	ret
;games/../common/glic80.h:35: }
;games/../common/glic80.h:37: static unsigned char glic_button_pressed(unsigned char buttons,
;	---------------------------------
; Function glic_button_pressed
; ---------------------------------
_glic_button_pressed:
;games/../common/glic80.h:39: return (buttons & mask) == 0u;
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	inc	iy
	and	a, 0 (iy)
	or	a, a
	ld	a, #0x01
	jr	Z, 00104$
	xor	a, a
00104$:
	ld	l, a
;games/../common/glic80.h:40: }
	ret
_glic_bit_masks:
	.db #0x01	; 1
	.db #0x02	; 2
	.db #0x04	; 4
	.db #0x08	; 8
	.db #0x10	; 16
	.db #0x20	; 32
	.db #0x40	; 64
	.db #0x80	; 128
;games/../common/glic80.h:42: static void glic_delay(unsigned int count) {
;	---------------------------------
; Function glic_delay
; ---------------------------------
_glic_delay:
;games/../common/glic80.h:43: while (count != 0u) {
	pop	de
	pop	bc
	push	bc
	push	de
00101$:
	ld	a, b
	or	a, c
	ret	Z
;games/../common/glic80.h:44: --count;
	dec	bc
;games/../common/glic80.h:47: __endasm;
	nop
;games/../common/glic80.h:49: }
	jr	00101$
;games/../common/glic80.h:51: static void glic_clear_text(void) {
;	---------------------------------
; Function glic_clear_text
; ---------------------------------
_glic_clear_text:
;games/../common/glic80.h:54: for (i = 0; i < GLIC_CVRAM_BYTES; ++i) {
	ld	bc, #0x0000
00102$:
;games/../common/glic80.h:55: GLIC_CVRAM[i] = 0x00u;
	ld	hl, #0x7700
	add	hl, bc
	ld	(hl), #0x00
;games/../common/glic80.h:54: for (i = 0; i < GLIC_CVRAM_BYTES; ++i) {
	inc	bc
	ld	a, b
	sub	a, #0x01
	jr	C, 00102$
;games/../common/glic80.h:57: }
	ret
;games/../common/glic80.h:59: static void glic_fill_graphics(unsigned char value) {
;	---------------------------------
; Function glic_fill_graphics
; ---------------------------------
_glic_fill_graphics:
;games/../common/glic80.h:62: for (i = 0; i < GLIC_GVRAM_BYTES; ++i) {
	ld	bc, #0x0000
00102$:
;games/../common/glic80.h:63: GLIC_GVRAM[i] = value;
	ld	hl, #0x7800
	add	hl, bc
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	ld	(hl), a
;games/../common/glic80.h:62: for (i = 0; i < GLIC_GVRAM_BYTES; ++i) {
	inc	bc
	ld	a, b
	sub	a, #0x08
	jr	C, 00102$
;games/../common/glic80.h:65: }
	ret
;games/../common/glic80.h:67: static void glic_plot(unsigned char x, unsigned char y, unsigned char value) {
;	---------------------------------
; Function glic_plot
; ---------------------------------
_glic_plot:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/../common/glic80.h:71: if ((x >= GLIC_SCREEN_WIDTH) || (y >= 128u)) {
	ld	a, 4 (ix)
	sub	a, #0x80
	jr	NC, 00107$
	ld	a, 5 (ix)
	sub	a, #0x80
;games/../common/glic80.h:72: return;
	jr	NC, 00107$
;games/../common/glic80.h:75: offset = (((unsigned int)(y >> 3)) << 7) + x;
	ld	a, 5 (ix)
	rrca
	rrca
	rrca
	and	a, #0x1f
	ld	l, a
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, hl
	ld	c, 4 (ix)
	ld	b, #0x00
	add	hl, bc
	ex	de, hl
;games/../common/glic80.h:76: mask = glic_bit_masks[y & 7u];
	ld	bc, #_glic_bit_masks+0
	ld	a, 5 (ix)
	and	a, #0x07
	ld	l, a
	ld	h, #0x00
	add	hl, bc
	ld	b, (hl)
;games/../common/glic80.h:78: GLIC_GVRAM[offset] |= mask;
	ld	hl, #0x7800
	add	hl, de
	ld	c, (hl)
;games/../common/glic80.h:77: if (value != 0u) {
	ld	a, 6 (ix)
	or	a, a
	jr	Z, 00105$
;games/../common/glic80.h:78: GLIC_GVRAM[offset] |= mask;
	ld	a, c
	or	a, b
	ld	(hl), a
	jr	00107$
00105$:
;games/../common/glic80.h:80: GLIC_GVRAM[offset] &= (unsigned char)~mask;
	ld	a, b
	cpl
	and	a, c
	ld	(hl), a
00107$:
;games/../common/glic80.h:82: }
	pop	ix
	ret
;games/../common/glic80.h:84: static void glic_draw_bitmap8(unsigned char x,
;	---------------------------------
; Function glic_draw_bitmap8
; ---------------------------------
_glic_draw_bitmap8:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/../common/glic80.h:92: for (row = 0u; row < 8u; ++row) {
	ld	c, #0x00
00107$:
;games/../common/glic80.h:93: bits = rows[row];
	ld	l, 6 (ix)
	ld	h, 7 (ix)
	ld	b, #0x00
	add	hl, bc
	ld	l, (hl)
;games/../common/glic80.h:94: mask = 0x80u;
	ld	e, #0x80
;games/../common/glic80.h:95: for (col = 0u; col < 8u; ++col) {
	ld	a, 5 (ix)
	add	a, c
	ld	b, a
	ld	d, #0x00
00105$:
;games/../common/glic80.h:96: if ((bits & mask) != 0u) {
	ld	a, l
	and	a,e
	jr	Z, 00102$
;games/../common/glic80.h:97: glic_plot((unsigned char)(x + col), (unsigned char)(y + row), 1u);
	ld	a, 4 (ix)
	add	a, d
	push	hl
	push	bc
	push	de
	ld	h, #0x01
	ld	l, b
	push	hl
	push	af
	inc	sp
	call	_glic_plot
	pop	af
	inc	sp
	pop	de
	pop	bc
	pop	hl
00102$:
;games/../common/glic80.h:99: mask >>= 1;
	srl	e
;games/../common/glic80.h:95: for (col = 0u; col < 8u; ++col) {
	inc	d
	ld	a, d
	sub	a, #0x08
	jr	C, 00105$
;games/../common/glic80.h:92: for (row = 0u; row < 8u; ++row) {
	inc	c
	ld	a, c
	sub	a, #0x08
	jr	C, 00107$
;games/../common/glic80.h:102: }
	pop	ix
	ret
;games/../common/glic80.h:104: static void glic_draw_tile8(unsigned char cell_x,
;	---------------------------------
; Function glic_draw_tile8
; ---------------------------------
_glic_draw_tile8:
	push	ix
	ld	ix,#0
	add	ix,sp
	push	af
;games/../common/glic80.h:110: offset = (((unsigned int)cell_y) << 7) + (((unsigned int)cell_x) << 3);
	ld	c, 5 (ix)
	xor	a, a
	rr	a
	ld	b, c
	rr	b
	rra
	ld	c, a
	ld	l, 4 (ix)
	ld	h, #0x00
	add	hl, hl
	add	hl, hl
	add	hl, hl
	add	hl, bc
	ex	de, hl
;games/../common/glic80.h:111: for (col = 0u; col < 8u; ++col) {
	ld	c, #0x00
00102$:
;games/../common/glic80.h:112: GLIC_GVRAM[offset + col] = columns[col];
	ld	l, c
	ld	h, #0x00
	add	hl, de
	ld	-2 (ix), l
	ld	a, h
	add	a, #0x78
	ld	-1 (ix), a
	ld	l, 6 (ix)
	ld	h, 7 (ix)
	ld	b, #0x00
	add	hl, bc
	ld	a, (hl)
	pop	hl
	push	hl
	ld	(hl), a
;games/../common/glic80.h:111: for (col = 0u; col < 8u; ++col) {
	inc	c
	ld	a, c
	sub	a, #0x08
	jr	C, 00102$
;games/../common/glic80.h:114: }
	ld	sp, ix
	pop	ix
	ret
;games/../common/glic80.h:116: static void glic_prepare_screen(unsigned char value) {
;	---------------------------------
; Function glic_prepare_screen
; ---------------------------------
_glic_prepare_screen:
;games/../common/glic80.h:117: glic_clear_text();
	call	_glic_clear_text
;games/../common/glic80.h:118: glic_fill_graphics(value);
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_glic_fill_graphics
	inc	sp
;games/../common/glic80.h:119: }
	ret
;games/../common/glic80.h:121: static void glic_fill_page_run(unsigned char page,
;	---------------------------------
; Function glic_fill_page_run
; ---------------------------------
_glic_fill_page_run:
;games/../common/glic80.h:127: p = GLIC_GVRAM + (((unsigned int)page) << 7) + x;
	ld	iy, #2
	add	iy, sp
	ld	c, 0 (iy)
	ld	b, #0x00
	xor	a, a
	rr	b
	ld	b, c
	rr	b
	rra
	ld	c, a
	ld	a, b
	add	a, #0x78
	ld	b, a
	ld	a, c
	ld	hl, #3
	add	hl, sp
	add	a, (hl)
	ld	c, a
	jr	NC, 00117$
	inc	b
00117$:
;games/../common/glic80.h:128: while (width != 0u) {
	ld	e, 2 (iy)
00101$:
	ld	a, e
	or	a, a
	ret	Z
;games/../common/glic80.h:129: *p++ = value;
	ld	iy, #5
	add	iy, sp
	ld	a, 0 (iy)
	ld	(bc), a
	inc	bc
;games/../common/glic80.h:130: --width;
	dec	e
;games/../common/glic80.h:132: }
	jr	00101$
;games/../common/glic80.h:134: static void glic_fill_pages(unsigned char first_page,
;	---------------------------------
; Function glic_fill_pages
; ---------------------------------
_glic_fill_pages:
;games/../common/glic80.h:137: while (page_count != 0u) {
	ld	iy, #2
	add	iy, sp
	ld	b, 0 (iy)
	ld	c, 1 (iy)
00101$:
	ld	a, c
	or	a, a
	ret	Z
;games/../common/glic80.h:138: glic_fill_page_run(first_page, 0u, GLIC_SCREEN_WIDTH, value);
	push	bc
	ld	hl, #6
	add	hl, sp
	ld	d, (hl)
	ld	e,#0x80
	push	de
	xor	a, a
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_fill_page_run
	pop	af
	pop	af
	pop	bc
;games/../common/glic80.h:139: ++first_page;
	inc	b
;games/../common/glic80.h:140: --page_count;
	dec	c
;games/../common/glic80.h:142: }
	jr	00101$
;games/../common/glic80.h:144: static void glic_fill_columns(unsigned char x,
;	---------------------------------
; Function glic_fill_columns
; ---------------------------------
_glic_fill_columns:
;games/../common/glic80.h:149: for (page = 0u; page < GLIC_SCREEN_PAGES; ++page) {
	ld	b, #0x00
00102$:
;games/../common/glic80.h:150: glic_fill_page_run(page, x, width, value);
	push	bc
	ld	iy, #6
	add	iy, sp
	ld	a, 0 (iy)
	push	af
	inc	sp
	ld	a, -1 (iy)
	dec	iy
	push	af
	inc	sp
	ld	a, -1 (iy)
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_fill_page_run
	pop	af
	pop	af
	pop	bc
;games/../common/glic80.h:149: for (page = 0u; page < GLIC_SCREEN_PAGES; ++page) {
	inc	b
	ld	a, b
	sub	a, #0x10
	jr	C, 00102$
;games/../common/glic80.h:152: }
	ret
;games/sudoku.c:81: static volatile unsigned char *text_cell(unsigned char row,
;	---------------------------------
; Function text_cell
; ---------------------------------
_text_cell:
;games/sudoku.c:86: while (row != 0u) {
	ld	bc, #0x7700
	ld	iy, #2
	add	iy, sp
	ld	l, 0 (iy)
00101$:
	ld	a, l
	or	a, a
	jr	Z, 00103$
;games/sudoku.c:87: p += 16u;
	ld	a, c
	add	a, #0x10
	ld	c, a
	jr	NC, 00117$
	inc	b
00117$:
;games/sudoku.c:88: --row;
	dec	l
	jr	00101$
00103$:
;games/sudoku.c:90: p += col;
	ld	a, c
	ld	hl, #3
	add	hl, sp
	add	a, (hl)
	ld	l, a
	jr	NC, 00118$
	inc	b
00118$:
	ld	h, b
;games/sudoku.c:91: return p;
;games/sudoku.c:92: }
	ret
_base_solution:
	.db #0x05	; 5
	.db #0x03	; 3
	.db #0x04	; 4
	.db #0x06	; 6
	.db #0x07	; 7
	.db #0x08	; 8
	.db #0x09	; 9
	.db #0x01	; 1
	.db #0x02	; 2
	.db #0x06	; 6
	.db #0x07	; 7
	.db #0x02	; 2
	.db #0x01	; 1
	.db #0x09	; 9
	.db #0x05	; 5
	.db #0x03	; 3
	.db #0x04	; 4
	.db #0x08	; 8
	.db #0x01	; 1
	.db #0x09	; 9
	.db #0x08	; 8
	.db #0x03	; 3
	.db #0x04	; 4
	.db #0x02	; 2
	.db #0x05	; 5
	.db #0x06	; 6
	.db #0x07	; 7
	.db #0x08	; 8
	.db #0x05	; 5
	.db #0x09	; 9
	.db #0x07	; 7
	.db #0x06	; 6
	.db #0x01	; 1
	.db #0x04	; 4
	.db #0x02	; 2
	.db #0x03	; 3
	.db #0x04	; 4
	.db #0x02	; 2
	.db #0x06	; 6
	.db #0x08	; 8
	.db #0x05	; 5
	.db #0x03	; 3
	.db #0x07	; 7
	.db #0x09	; 9
	.db #0x01	; 1
	.db #0x07	; 7
	.db #0x01	; 1
	.db #0x03	; 3
	.db #0x09	; 9
	.db #0x02	; 2
	.db #0x04	; 4
	.db #0x08	; 8
	.db #0x05	; 5
	.db #0x06	; 6
	.db #0x09	; 9
	.db #0x06	; 6
	.db #0x01	; 1
	.db #0x05	; 5
	.db #0x03	; 3
	.db #0x07	; 7
	.db #0x02	; 2
	.db #0x08	; 8
	.db #0x04	; 4
	.db #0x02	; 2
	.db #0x08	; 8
	.db #0x07	; 7
	.db #0x04	; 4
	.db #0x01	; 1
	.db #0x09	; 9
	.db #0x06	; 6
	.db #0x03	; 3
	.db #0x05	; 5
	.db #0x03	; 3
	.db #0x04	; 4
	.db #0x05	; 5
	.db #0x02	; 2
	.db #0x08	; 8
	.db #0x06	; 6
	.db #0x01	; 1
	.db #0x07	; 7
	.db #0x09	; 9
_base_puzzle:
	.db #0x05	; 5
	.db #0x03	; 3
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x07	; 7
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x06	; 6
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x01	; 1
	.db #0x09	; 9
	.db #0x05	; 5
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x09	; 9
	.db #0x08	; 8
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x06	; 6
	.db #0x00	; 0
	.db #0x08	; 8
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x06	; 6
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x03	; 3
	.db #0x04	; 4
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x08	; 8
	.db #0x00	; 0
	.db #0x03	; 3
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x01	; 1
	.db #0x07	; 7
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x02	; 2
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x06	; 6
	.db #0x00	; 0
	.db #0x06	; 6
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x02	; 2
	.db #0x08	; 8
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x04	; 4
	.db #0x01	; 1
	.db #0x09	; 9
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x05	; 5
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x08	; 8
	.db #0x00	; 0
	.db #0x00	; 0
	.db #0x07	; 7
	.db #0x09	; 9
_level2_extra:
	.db #0x02	; 2
	.db #0x03	; 3
	.db #0x05	; 5
	.db #0x0a	; 10
	.db #0x0f	; 15
	.db #0x12	; 18
	.db #0x15	; 21
	.db #0x1c	; 28
	.db #0x20	; 32
	.db #0x25	; 37
	.db #0x2e	; 46
	.db #0x36	; 54	'6'
	.db #0x3f	; 63
	.db #0x48	; 72	'H'
	.db #0xff	; 255
_level1_extra:
	.db #0x06	; 6
	.db #0x08	; 8
	.db #0x0b	; 11
	.db #0x10	; 16
	.db #0x16	; 22
	.db #0x18	; 24
	.db #0x1d	; 29
	.db #0x22	; 34
	.db #0x26	; 38
	.db #0x2b	; 43
	.db #0x2f	; 47
	.db #0x34	; 52	'4'
	.db #0x38	; 56	'8'
	.db #0x3c	; 60
	.db #0x41	; 65	'A'
	.db #0x46	; 70	'F'
	.db #0x49	; 73	'I'
	.db #0x4e	; 78	'N'
	.db #0xff	; 255
_digit_1:
	.db #0x04	; 4
	.db #0x0c	; 12
	.db #0x04	; 4
	.db #0x04	; 4
	.db #0x04	; 4
	.db #0x04	; 4
	.db #0x0e	; 14
_digit_2:
	.db #0x0e	; 14
	.db #0x11	; 17
	.db #0x01	; 1
	.db #0x02	; 2
	.db #0x04	; 4
	.db #0x08	; 8
	.db #0x1f	; 31
_digit_3:
	.db #0x1e	; 30
	.db #0x01	; 1
	.db #0x01	; 1
	.db #0x0e	; 14
	.db #0x01	; 1
	.db #0x01	; 1
	.db #0x1e	; 30
_digit_4:
	.db #0x02	; 2
	.db #0x06	; 6
	.db #0x0a	; 10
	.db #0x12	; 18
	.db #0x1f	; 31
	.db #0x02	; 2
	.db #0x02	; 2
_digit_5:
	.db #0x1f	; 31
	.db #0x10	; 16
	.db #0x1e	; 30
	.db #0x01	; 1
	.db #0x01	; 1
	.db #0x11	; 17
	.db #0x0e	; 14
_digit_6:
	.db #0x06	; 6
	.db #0x08	; 8
	.db #0x10	; 16
	.db #0x1e	; 30
	.db #0x11	; 17
	.db #0x11	; 17
	.db #0x0e	; 14
_digit_7:
	.db #0x1f	; 31
	.db #0x01	; 1
	.db #0x02	; 2
	.db #0x04	; 4
	.db #0x08	; 8
	.db #0x08	; 8
	.db #0x08	; 8
_digit_8:
	.db #0x0e	; 14
	.db #0x11	; 17
	.db #0x11	; 17
	.db #0x0e	; 14
	.db #0x11	; 17
	.db #0x11	; 17
	.db #0x0e	; 14
_digit_9:
	.db #0x0e	; 14
	.db #0x11	; 17
	.db #0x11	; 17
	.db #0x0f	; 15
	.db #0x01	; 1
	.db #0x02	; 2
	.db #0x0c	; 12
;games/sudoku.c:94: static void text_put(unsigned char row, unsigned char col, unsigned char ch) {
;	---------------------------------
; Function text_put
; ---------------------------------
_text_put:
;games/sudoku.c:95: if ((row >= 16u) || (col >= 16u)) {
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
	sub	a, #0x10
	ret	NC
	ld	a, 1 (iy)
	sub	a, #0x10
;games/sudoku.c:96: return;
	ret	NC
;games/sudoku.c:98: *text_cell(row, col) = ch;
	ld	iy, #3
	add	iy, sp
	ld	h, 0 (iy)
	ld	l, -1 (iy)
	push	hl
	call	_text_cell
	pop	af
	ld	iy, #4
	add	iy, sp
	ld	a, 0 (iy)
	ld	(hl), a
;games/sudoku.c:99: }
	ret
;games/sudoku.c:101: static void text_clear_row(unsigned char row) {
;	---------------------------------
; Function text_clear_row
; ---------------------------------
_text_clear_row:
;games/sudoku.c:104: for (col = 0u; col < 16u; ++col) {
	ld	b, #0x00
00102$:
;games/sudoku.c:105: text_put(row, col, 0u);
	push	bc
	xor	a, a
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	hl, #6
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
	pop	bc
;games/sudoku.c:104: for (col = 0u; col < 16u; ++col) {
	inc	b
	ld	a, b
	sub	a, #0x10
	jr	C, 00102$
;games/sudoku.c:107: }
	ret
;games/sudoku.c:109: static void text_write(unsigned char row, unsigned char col, const char *text) {
;	---------------------------------
; Function text_write
; ---------------------------------
_text_write:
;games/sudoku.c:110: while ((*text != 0) && (col < 16u)) {
	ld	iy, #4
	add	iy, sp
	ld	l, 0 (iy)
	ld	h, 1 (iy)
	ld	b, -1 (iy)
00102$:
	ld	d, (hl)
	ld	a, d
	or	a, a
	ret	Z
	ld	a, b
	sub	a, #0x10
	ret	NC
;games/sudoku.c:111: text_put(row, col, (unsigned char)*text);
	push	hl
	push	bc
	ld	e, b
	push	de
	ld	hl, #8
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
	pop	bc
	pop	hl
;games/sudoku.c:112: ++text;
	inc	hl
;games/sudoku.c:113: ++col;
	inc	b
;games/sudoku.c:115: }
	jr	00102$
;games/sudoku.c:117: static void draw_hline(unsigned char x,
;	---------------------------------
; Function draw_hline
; ---------------------------------
_draw_hline:
;games/sudoku.c:121: while (width != 0u) {
	ld	iy, #2
	add	iy, sp
	ld	b, 0 (iy)
	ld	c, 2 (iy)
00101$:
	ld	a, c
	or	a, a
	ret	Z
;games/sudoku.c:122: glic_plot(x, y, value);
	push	bc
	ld	iy, #7
	add	iy, sp
	ld	h, 0 (iy)
	ld	l, -2 (iy)
	push	hl
	push	bc
	inc	sp
	call	_glic_plot
	pop	af
	inc	sp
	pop	bc
;games/sudoku.c:123: ++x;
	inc	b
;games/sudoku.c:124: --width;
	dec	c
;games/sudoku.c:126: }
	jr	00101$
;games/sudoku.c:128: static void draw_vline(unsigned char x,
;	---------------------------------
; Function draw_vline
; ---------------------------------
_draw_vline:
;games/sudoku.c:132: while (height != 0u) {
	ld	iy, #3
	add	iy, sp
	ld	b, 0 (iy)
	ld	c, 1 (iy)
00101$:
	ld	a, c
	or	a, a
	ret	Z
;games/sudoku.c:133: glic_plot(x, y, value);
	push	bc
	ld	iy, #7
	add	iy, sp
	ld	a, 0 (iy)
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	a, -3 (iy)
	push	af
	inc	sp
	call	_glic_plot
	pop	af
	inc	sp
	pop	bc
;games/sudoku.c:134: ++y;
	inc	b
;games/sudoku.c:135: --height;
	dec	c
;games/sudoku.c:137: }
	jr	00101$
;games/sudoku.c:139: static void draw_rect(unsigned char x,
;	---------------------------------
; Function draw_rect
; ---------------------------------
_draw_rect:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/sudoku.c:144: draw_hline(x, y, width, value);
	ld	h, 8 (ix)
	ld	l, 6 (ix)
	push	hl
	ld	h, 5 (ix)
	ld	l, 4 (ix)
	push	hl
	call	_draw_hline
	pop	af
	pop	af
;games/sudoku.c:145: draw_hline(x, (unsigned char)(y + height - 1u), width, value);
	ld	a, 5 (ix)
	add	a, 7 (ix)
	dec	a
	ld	h, 8 (ix)
	push	hl
	inc	sp
	ld	h, 6 (ix)
	push	hl
	inc	sp
	push	af
	inc	sp
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_draw_hline
	pop	af
	pop	af
;games/sudoku.c:146: draw_vline(x, y, height, value);
	ld	h, 8 (ix)
	ld	l, 7 (ix)
	push	hl
	ld	h, 5 (ix)
	ld	l, 4 (ix)
	push	hl
	call	_draw_vline
	pop	af
	pop	af
;games/sudoku.c:147: draw_vline((unsigned char)(x + width - 1u), y, height, value);
	ld	a, 4 (ix)
	add	a, 6 (ix)
	dec	a
	ld	h, 8 (ix)
	push	hl
	inc	sp
	ld	h, 7 (ix)
	push	hl
	inc	sp
	ld	h, 5 (ix)
	push	hl
	inc	sp
	push	af
	inc	sp
	call	_draw_vline
	pop	af
	pop	af
;games/sudoku.c:148: }
	pop	ix
	ret
;games/sudoku.c:150: static void fill_rect(unsigned char x,
;	---------------------------------
; Function fill_rect
; ---------------------------------
_fill_rect:
;games/sudoku.c:155: while (height != 0u) {
	ld	iy, #3
	add	iy, sp
	ld	b, 0 (iy)
	ld	c, 2 (iy)
00101$:
	ld	a, c
	or	a, a
	ret	Z
;games/sudoku.c:156: draw_hline(x, y, width, value);
	push	bc
	ld	iy, #8
	add	iy, sp
	ld	a, 0 (iy)
	push	af
	inc	sp
	ld	a, -2 (iy)
	dec	iy
	dec	iy
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	a, -2 (iy)
	push	af
	inc	sp
	call	_draw_hline
	pop	af
	pop	af
	pop	bc
;games/sudoku.c:157: ++y;
	inc	b
;games/sudoku.c:158: --height;
	dec	c
;games/sudoku.c:160: }
	jr	00101$
;games/sudoku.c:162: static unsigned char cell_index(unsigned char row, unsigned char col) {
;	---------------------------------
; Function cell_index
; ---------------------------------
_cell_index:
;games/sudoku.c:165: index = col;
	ld	iy, #3
	add	iy, sp
	ld	l, 0 (iy)
;games/sudoku.c:166: while (row != 0u) {
	ld	c, -1 (iy)
00101$:
	ld	a, c
	or	a, a
	ret	Z
;games/sudoku.c:167: index = (unsigned char)(index + 9u);
	ld	a, l
	add	a, #0x09
	ld	l, a
;games/sudoku.c:168: --row;
	dec	c
;games/sudoku.c:170: return index;
;games/sudoku.c:171: }
	jr	00101$
;games/sudoku.c:173: static unsigned char cell_screen_x(unsigned char col) {
;	---------------------------------
; Function cell_screen_x
; ---------------------------------
_cell_screen_x:
;games/sudoku.c:177: while (col != 0u) {
	ld	l, #0x01
	ld	iy, #2
	add	iy, sp
	ld	c, 0 (iy)
00101$:
	ld	a, c
	or	a, a
	ret	Z
;games/sudoku.c:178: x = (unsigned char)(x + CELL_SIZE);
	ld	a, l
	add	a, #0x0a
	ld	l, a
;games/sudoku.c:179: --col;
	dec	c
;games/sudoku.c:181: return x;
;games/sudoku.c:182: }
	jr	00101$
;games/sudoku.c:184: static unsigned char cell_screen_y(unsigned char row) {
;	---------------------------------
; Function cell_screen_y
; ---------------------------------
_cell_screen_y:
;games/sudoku.c:188: while (row != 0u) {
	ld	l, #0x14
	ld	iy, #2
	add	iy, sp
	ld	c, 0 (iy)
00101$:
	ld	a, c
	or	a, a
	ret	Z
;games/sudoku.c:189: y = (unsigned char)(y + CELL_SIZE);
	ld	a, l
	add	a, #0x0a
	ld	l, a
;games/sudoku.c:190: --row;
	dec	c
;games/sudoku.c:192: return y;
;games/sudoku.c:193: }
	jr	00101$
;games/sudoku.c:195: static unsigned char button_edge(unsigned char buttons,
;	---------------------------------
; Function button_edge
; ---------------------------------
_button_edge:
;games/sudoku.c:198: return (((last_buttons & mask) != 0u) && ((buttons & mask) == 0u));
	ld	iy, #3
	add	iy, sp
	ld	a, 0 (iy)
	inc	iy
	and	a, 0 (iy)
	or	a, a
	jr	Z, 00103$
	ld	a, -2 (iy)
	and	a, 0 (iy)
	or	a, a
	jr	Z, 00104$
00103$:
	ld	l, #0x00
	ret
00104$:
	ld	l, #0x01
;games/sudoku.c:199: }
	ret
;games/sudoku.c:201: static void wait_for_release(void) {
;	---------------------------------
; Function wait_for_release
; ---------------------------------
_wait_for_release:
;games/sudoku.c:202: while (glic_read_buttons() != GLIC_BUTTONS_NONE) {
00101$:
	call	_glic_read_buttons
	inc	l
	ret	Z
;games/sudoku.c:203: glic_delay(500u);
	ld	hl, #0x01f4
	push	hl
	call	_glic_delay
	pop	af
;games/sudoku.c:205: }
	jr	00101$
;games/sudoku.c:207: static unsigned char list_contains(const unsigned char *list,
;	---------------------------------
; Function list_contains
; ---------------------------------
_list_contains:
;games/sudoku.c:209: while (*list != LIST_END) {
	pop	de
	pop	bc
	push	bc
	push	de
00103$:
	ld	a, (bc)
	ld	e, a
	inc	a
	jr	Z, 00105$
;games/sudoku.c:210: if (*list == value) {
	ld	iy, #4
	add	iy, sp
	ld	a, 0 (iy)
	sub	a, e
	jr	NZ, 00102$
;games/sudoku.c:211: return 1u;
	ld	l, #0x01
	ret
00102$:
;games/sudoku.c:213: ++list;
	inc	bc
	jr	00103$
00105$:
;games/sudoku.c:215: return 0u;
	ld	l, #0x00
;games/sudoku.c:216: }
	ret
;games/sudoku.c:218: static unsigned char level_digit(unsigned char digit, unsigned char level) {
;	---------------------------------
; Function level_digit
; ---------------------------------
_level_digit:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/sudoku.c:219: if (digit == 0u) {
	ld	a, 4 (ix)
;games/sudoku.c:220: return 0u;
	or	a,a
	jr	NZ, 00102$
	ld	l,a
	jr	00110$
00102$:
;games/sudoku.c:223: if (level == 4u) {
	ld	a, 5 (ix)
	sub	a, #0x04
	jr	NZ, 00108$
;games/sudoku.c:224: digit = (unsigned char)(digit + 2u);
	inc	4 (ix)
	inc	4 (ix)
;games/sudoku.c:225: if (digit > 9u) {
	ld	a, #0x09
	sub	a, 4 (ix)
	jr	NC, 00109$
;games/sudoku.c:226: digit = (unsigned char)(digit - 9u);
	ld	a, 4 (ix)
	add	a, #0xf7
	ld	4 (ix), a
	jr	00109$
00108$:
;games/sudoku.c:228: } else if (level == 5u) {
	ld	a, 5 (ix)
	sub	a, #0x05
	jr	NZ, 00109$
;games/sudoku.c:229: digit = (unsigned char)(10u - digit);
	ld	a, #0x0a
	sub	a, 4 (ix)
	ld	4 (ix), a
00109$:
;games/sudoku.c:232: return digit;
	ld	l, 4 (ix)
00110$:
;games/sudoku.c:233: }
	pop	ix
	ret
;games/sudoku.c:235: static unsigned char level_source_index(unsigned char row,
;	---------------------------------
; Function level_source_index
; ---------------------------------
_level_source_index:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/sudoku.c:238: if (level == 5u) {
	ld	a, 6 (ix)
	sub	a, #0x05
	jr	NZ, 00106$
;games/sudoku.c:239: row = (unsigned char)(row + 3u);
	inc	4 (ix)
	inc	4 (ix)
	inc	4 (ix)
;games/sudoku.c:240: if (row >= 9u) {
	ld	a, 4 (ix)
	sub	a, #0x09
	jr	C, 00102$
;games/sudoku.c:241: row = (unsigned char)(row - 9u);
	ld	a, 4 (ix)
	add	a, #0xf7
	ld	4 (ix), a
00102$:
;games/sudoku.c:243: col = (unsigned char)(col + 6u);
	ld	a, 5 (ix)
	add	a, #0x06
;games/sudoku.c:244: if (col >= 9u) {
	ld	5 (ix), a
	sub	a, #0x09
	jr	C, 00106$
;games/sudoku.c:245: col = (unsigned char)(col - 9u);
	ld	a, 5 (ix)
	add	a, #0xf7
	ld	5 (ix), a
00106$:
;games/sudoku.c:249: return cell_index(row, col);
	ld	h, 5 (ix)
	ld	l, 4 (ix)
	push	hl
	call	_cell_index
	pop	af
;games/sudoku.c:250: }
	pop	ix
	ret
;games/sudoku.c:252: static void load_level(unsigned char level) {
;	---------------------------------
; Function load_level
; ---------------------------------
_load_level:
	push	ix
	ld	ix,#0
	add	ix,sp
	ld	hl, #-8
	add	hl, sp
	ld	sp, hl
;games/sudoku.c:260: dst = 0u;
	ld	c, #0x00
;games/sudoku.c:261: for (row = 0u; row < 9u; ++row) {
	ld	a, 4 (ix)
	dec	a
	ld	a, #0x01
	jr	Z, 00174$
	xor	a, a
00174$:
	ld	-8 (ix), a
	ld	a, 4 (ix)
	sub	a, #0x02
	ld	a, #0x01
	jr	Z, 00176$
	xor	a, a
00176$:
	ld	-7 (ix), a
	ld	-3 (ix), #0
;games/sudoku.c:262: for (col = 0u; col < 9u; ++col) {
00128$:
	ld	-2 (ix), c
	ld	-1 (ix), #0
00113$:
;games/sudoku.c:263: src = level_source_index(row, col, level);
	ld	h, 4 (ix)
	ld	l, -1 (ix)
	push	hl
	ld	a, -3 (ix)
	push	af
	inc	sp
	call	_level_source_index
	pop	af
	ld	-6 (ix), l
	inc	sp
;games/sudoku.c:264: solution_value = level_digit(base_solution[src], level);
	ld	a, #<(_base_solution)
	add	a, -6 (ix)
	ld	c, a
	ld	a, #>(_base_solution)
	adc	a, #0x00
	ld	b, a
	ld	a, (bc)
	ld	h, 4 (ix)
	push	hl
	inc	sp
	push	af
	inc	sp
	call	_level_digit
	pop	af
	ld	-5 (ix), l
;games/sudoku.c:265: puzzle_value = level_digit(base_puzzle[src], level);
	ld	a, #<(_base_puzzle)
	add	a, -6 (ix)
	ld	c, a
	ld	a, #>(_base_puzzle)
	adc	a, #0x00
	ld	b, a
	ld	a, (bc)
	ld	h, 4 (ix)
	push	hl
	inc	sp
	push	af
	inc	sp
	call	_level_digit
	pop	af
	ld	-4 (ix), l
;games/sudoku.c:267: if ((level == 2u) && (puzzle_value == 0u) &&
	ld	a, -7 (ix)
	or	a, a
	jr	Z, 00107$
	ld	a, -4 (ix)
	or	a, a
	jr	NZ, 00107$
;games/sudoku.c:268: (list_contains(level2_extra, src) != 0u)) {
	ld	a, -6 (ix)
	push	af
	inc	sp
	ld	hl, #_level2_extra
	push	hl
	call	_list_contains
	pop	af
	inc	sp
	ld	a, l
	or	a, a
	jr	Z, 00107$
;games/sudoku.c:269: puzzle_value = solution_value;
	ld	a, -5 (ix)
	ld	-4 (ix), a
	jr	00108$
00107$:
;games/sudoku.c:270: } else if ((level == 1u) && (puzzle_value == 0u) &&
	ld	a, -8 (ix)
	or	a, a
	jr	Z, 00108$
	ld	a, -4 (ix)
	or	a, a
	jr	NZ, 00108$
;games/sudoku.c:271: ((list_contains(level2_extra, src) != 0u) ||
	ld	a, -6 (ix)
	push	af
	inc	sp
	ld	hl, #_level2_extra
	push	hl
	call	_list_contains
	pop	af
	inc	sp
	ld	a, l
	or	a, a
	jr	NZ, 00101$
;games/sudoku.c:272: (list_contains(level1_extra, src) != 0u))) {
	ld	a, -6 (ix)
	push	af
	inc	sp
	ld	hl, #_level1_extra
	push	hl
	call	_list_contains
	pop	af
	inc	sp
	ld	a, l
	or	a, a
	jr	Z, 00108$
00101$:
;games/sudoku.c:273: puzzle_value = solution_value;
	ld	a, -5 (ix)
	ld	-4 (ix), a
00108$:
;games/sudoku.c:276: board[dst] = puzzle_value;
	ld	a, #<(_board)
	add	a, -2 (ix)
	ld	c, a
	ld	a, #>(_board)
	adc	a, #0x00
	ld	b, a
	ld	a, -4 (ix)
	ld	(bc), a
;games/sudoku.c:277: solution[dst] = solution_value;
	ld	a, #<(_solution)
	add	a, -2 (ix)
	ld	c, a
	ld	a, #>(_solution)
	adc	a, #0x00
	ld	b, a
	ld	a, -5 (ix)
	ld	(bc), a
;games/sudoku.c:278: givens[dst] = (puzzle_value == 0u) ? 0u : 1u;
	ld	a, #<(_givens)
	add	a, -2 (ix)
	ld	c, a
	ld	a, #>(_givens)
	adc	a, #0x00
	ld	b, a
	ld	a, -4 (ix)
	or	a, a
	jr	NZ, 00119$
	ld	de, #0x0000
	jr	00120$
00119$:
	ld	de, #0x0001
00120$:
	ld	a, e
	ld	(bc), a
;games/sudoku.c:279: ++dst;
	inc	-2 (ix)
;games/sudoku.c:262: for (col = 0u; col < 9u; ++col) {
	inc	-1 (ix)
	ld	a, -1 (ix)
	sub	a, #0x09
	jp	C, 00113$
;games/sudoku.c:261: for (row = 0u; row < 9u; ++row) {
	ld	c, -2 (ix)
	inc	-3 (ix)
	ld	a, -3 (ix)
	sub	a, #0x09
	jp	C, 00128$
;games/sudoku.c:282: }
	ld	sp, ix
	pop	ix
	ret
;games/sudoku.c:284: static const unsigned char *digit_rows(unsigned char digit) {
;	---------------------------------
; Function digit_rows
; ---------------------------------
_digit_rows:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/sudoku.c:285: if (digit == 1u) {
	ld	a, 4 (ix)
	dec	a
	jr	NZ, 00102$
;games/sudoku.c:286: return digit_1;
	ld	hl, #_digit_1
	jr	00117$
00102$:
;games/sudoku.c:288: if (digit == 2u) {
	ld	a, 4 (ix)
	sub	a, #0x02
	jr	NZ, 00104$
;games/sudoku.c:289: return digit_2;
	ld	hl, #_digit_2
	jr	00117$
00104$:
;games/sudoku.c:291: if (digit == 3u) {
	ld	a, 4 (ix)
	sub	a, #0x03
	jr	NZ, 00106$
;games/sudoku.c:292: return digit_3;
	ld	hl, #_digit_3
	jr	00117$
00106$:
;games/sudoku.c:294: if (digit == 4u) {
	ld	a, 4 (ix)
	sub	a, #0x04
	jr	NZ, 00108$
;games/sudoku.c:295: return digit_4;
	ld	hl, #_digit_4
	jr	00117$
00108$:
;games/sudoku.c:297: if (digit == 5u) {
	ld	a, 4 (ix)
	sub	a, #0x05
	jr	NZ, 00110$
;games/sudoku.c:298: return digit_5;
	ld	hl, #_digit_5
	jr	00117$
00110$:
;games/sudoku.c:300: if (digit == 6u) {
	ld	a, 4 (ix)
	sub	a, #0x06
	jr	NZ, 00112$
;games/sudoku.c:301: return digit_6;
	ld	hl, #_digit_6
	jr	00117$
00112$:
;games/sudoku.c:303: if (digit == 7u) {
	ld	a, 4 (ix)
	sub	a, #0x07
	jr	NZ, 00114$
;games/sudoku.c:304: return digit_7;
	ld	hl, #_digit_7
	jr	00117$
00114$:
;games/sudoku.c:306: if (digit == 8u) {
	ld	a, 4 (ix)
	sub	a, #0x08
	jr	NZ, 00116$
;games/sudoku.c:307: return digit_8;
	ld	hl, #_digit_8
	jr	00117$
00116$:
;games/sudoku.c:309: return digit_9;
	ld	hl, #_digit_9
00117$:
;games/sudoku.c:310: }
	pop	ix
	ret
;games/sudoku.c:312: static void draw_digit(unsigned char x, unsigned char y, unsigned char digit) {
;	---------------------------------
; Function draw_digit
; ---------------------------------
_draw_digit:
	push	ix
	ld	ix,#0
	add	ix,sp
	dec	sp
;games/sudoku.c:319: rows = digit_rows(digit);
	ld	a, 6 (ix)
	push	af
	inc	sp
	call	_digit_rows
	inc	sp
	ex	de, hl
;games/sudoku.c:320: for (row = 0u; row < 7u; ++row) {
	ld	c, #0x00
00107$:
;games/sudoku.c:321: bits = rows[row];
	ld	l, c
	ld	h, #0x00
	add	hl, de
	ld	l, (hl)
;games/sudoku.c:322: mask = 0x10u;
	ld	b, #0x10
;games/sudoku.c:323: for (col = 0u; col < 5u; ++col) {
	ld	a, 5 (ix)
	add	a, c
	ld	-1 (ix), a
	ld	h, #0x00
00105$:
;games/sudoku.c:324: if ((bits & mask) != 0u) {
	ld	a, l
	and	a,b
	jr	Z, 00102$
;games/sudoku.c:325: glic_plot((unsigned char)(x + col),
	ld	a, 4 (ix)
	add	a, h
	push	hl
	push	bc
	push	de
	push	hl
	ld	h, #0x01
	ex	(sp), hl
	inc	sp
	push	hl
	ld	h, -1 (ix)
	ex	(sp), hl
	inc	sp
	push	af
	inc	sp
	call	_glic_plot
	pop	af
	inc	sp
	pop	de
	pop	bc
	pop	hl
00102$:
;games/sudoku.c:329: mask >>= 1;
	srl	b
;games/sudoku.c:323: for (col = 0u; col < 5u; ++col) {
	inc	h
	ld	a, h
	sub	a, #0x05
	jr	C, 00105$
;games/sudoku.c:320: for (row = 0u; row < 7u; ++row) {
	inc	c
	ld	a, c
	sub	a, #0x07
	jr	C, 00107$
;games/sudoku.c:332: }
	inc	sp
	pop	ix
	ret
;games/sudoku.c:334: static void draw_grid(void) {
;	---------------------------------
; Function draw_grid
; ---------------------------------
_draw_grid:
;games/sudoku.c:341: for (i = 0u; i < 10u; ++i) {
	ld	bc, #0x0100
00107$:
;games/sudoku.c:342: thick = ((i == 0u) || (i == 3u) || (i == 6u) || (i == 9u));
	ld	a, c
	or	a, a
	jr	Z, 00114$
	ld	a,c
	cp	a,#0x03
	jr	Z, 00114$
	cp	a,#0x06
	jr	Z, 00114$
	sub	a, #0x09
	ld	e, #0x00
	jr	NZ, 00115$
00114$:
	ld	e, #0x01
00115$:
;games/sudoku.c:343: draw_vline(x, BOARD_Y, BOARD_PIXELS, 1u);
	push	bc
	push	de
	ld	de, #0x015b
	push	de
	ld	a, #0x14
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_draw_vline
	pop	af
	pop	af
	pop	de
	pop	bc
;games/sudoku.c:344: if (thick != 0u) {
	ld	a, e
	or	a, a
	jr	Z, 00102$
;games/sudoku.c:345: draw_vline((unsigned char)(x + 1u), BOARD_Y, BOARD_PIXELS, 1u);
	ld	a, b
	inc	a
	push	bc
	ld	h, #0x01
	push	hl
	inc	sp
	ld	h, #0x5b
	push	hl
	inc	sp
	ld	h, #0x14
	push	hl
	inc	sp
	push	af
	inc	sp
	call	_draw_vline
	pop	af
	pop	af
	pop	bc
00102$:
;games/sudoku.c:347: x = (unsigned char)(x + CELL_SIZE);
	ld	a, b
	add	a, #0x0a
	ld	b, a
;games/sudoku.c:341: for (i = 0u; i < 10u; ++i) {
	inc	c
	ld	a, c
	sub	a, #0x0a
	jr	C, 00107$
;games/sudoku.c:351: for (i = 0u; i < 10u; ++i) {
	ld	bc, #0x1400
00109$:
;games/sudoku.c:352: thick = ((i == 0u) || (i == 3u) || (i == 6u) || (i == 9u));
	ld	a, c
	or	a, a
	jr	Z, 00123$
	ld	a,c
	cp	a,#0x03
	jr	Z, 00123$
	cp	a,#0x06
	jr	Z, 00123$
	sub	a, #0x09
	ld	e, #0x00
	jr	NZ, 00124$
00123$:
	ld	e, #0x01
00124$:
;games/sudoku.c:353: draw_hline(BOARD_X, y, BOARD_PIXELS, 1u);
	push	bc
	push	de
	ld	de, #0x015b
	push	de
	ld	c, #0x01
	push	bc
	call	_draw_hline
	pop	af
	pop	af
	pop	de
	pop	bc
;games/sudoku.c:354: if (thick != 0u) {
	ld	a, e
	or	a, a
	jr	Z, 00105$
;games/sudoku.c:355: draw_hline(BOARD_X, (unsigned char)(y + 1u), BOARD_PIXELS, 1u);
	ld	a, b
	inc	a
	push	bc
	ld	h, #0x01
	push	hl
	inc	sp
	ld	h, #0x5b
	push	hl
	inc	sp
	ld	d,a
	ld	e,#0x01
	push	de
	call	_draw_hline
	pop	af
	pop	af
	pop	bc
00105$:
;games/sudoku.c:357: y = (unsigned char)(y + CELL_SIZE);
	ld	a, b
	add	a, #0x0a
	ld	b, a
;games/sudoku.c:351: for (i = 0u; i < 10u; ++i) {
	inc	c
	ld	a, c
	sub	a, #0x0a
	jr	C, 00109$
;games/sudoku.c:359: }
	ret
;games/sudoku.c:361: static void clear_cell(unsigned char row, unsigned char col) {
;	---------------------------------
; Function clear_cell
; ---------------------------------
_clear_cell:
;games/sudoku.c:363: (unsigned char)(cell_screen_y(row) + 2u),
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_cell_screen_y
	ld	a, l
	inc	sp
	add	a, #0x02
	ld	b, a
;games/sudoku.c:362: fill_rect((unsigned char)(cell_screen_x(col) + 2u),
	push	bc
	ld	hl, #5
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_cell_screen_x
	inc	sp
	ld	a, l
	pop	bc
	add	a, #0x02
	ld	h, #0x00
	push	hl
	inc	sp
	ld	h, #0x07
	push	hl
	inc	sp
	ld	h, #0x07
	ld	l, b
	push	hl
	push	af
	inc	sp
	call	_fill_rect
	pop	af
	pop	af
	inc	sp
;games/sudoku.c:367: }
	ret
;games/sudoku.c:369: static void draw_cell(unsigned char row, unsigned char col, unsigned char index) {
;	---------------------------------
; Function draw_cell
; ---------------------------------
_draw_cell:
;games/sudoku.c:372: clear_cell(row, col);
	ld	iy, #3
	add	iy, sp
	ld	h, 0 (iy)
	ld	l, -1 (iy)
	push	hl
	call	_clear_cell
	pop	af
;games/sudoku.c:373: value = board[index];
	ld	bc, #_board+0
	ld	a, c
	ld	hl, #4
	add	hl, sp
	add	a, (hl)
	ld	c, a
	jr	NC, 00110$
	inc	b
00110$:
	ld	a, (bc)
	ld	h, a
;games/sudoku.c:374: if (value != 0u) {
	or	a, a
	ret	Z
;games/sudoku.c:376: (unsigned char)(cell_screen_y(row) + 2u),
	push	hl
	ld	hl, #4
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_cell_screen_y
	inc	sp
	pop	af
	ld	h, a
	inc	l
	inc	l
;games/sudoku.c:375: draw_digit((unsigned char)(cell_screen_x(col) + 3u),
	push	hl
	ld	hl, #5
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_cell_screen_x
	ld	a, l
	inc	sp
	pop	hl
	add	a, #0x03
	push	hl
	inc	sp
	ld	h, l
	push	hl
	inc	sp
	push	af
	inc	sp
	call	_draw_digit
	pop	af
	inc	sp
;games/sudoku.c:379: }
	ret
;games/sudoku.c:381: static void draw_cursor(unsigned char row, unsigned char col) {
;	---------------------------------
; Function draw_cursor
; ---------------------------------
_draw_cursor:
;games/sudoku.c:383: (unsigned char)(cell_screen_y(row) + 2u),
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_cell_screen_y
	ld	a, l
	inc	sp
	add	a, #0x02
	ld	b, a
;games/sudoku.c:382: draw_rect((unsigned char)(cell_screen_x(col) + 2u),
	push	bc
	ld	hl, #5
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_cell_screen_x
	inc	sp
	ld	a, l
	pop	bc
	add	a, #0x02
	ld	h, #0x01
	push	hl
	inc	sp
	ld	h, #0x07
	push	hl
	inc	sp
	ld	h, #0x07
	ld	l, b
	push	hl
	push	af
	inc	sp
	call	_draw_rect
	pop	af
	pop	af
	inc	sp
;games/sudoku.c:387: }
	ret
;games/sudoku.c:389: static void draw_board_values(void) {
;	---------------------------------
; Function draw_board_values
; ---------------------------------
_draw_board_values:
;games/sudoku.c:394: index = 0u;
;games/sudoku.c:395: for (row = 0u; row < 9u; ++row) {
	ld	bc, #0x0000
;games/sudoku.c:396: for (col = 0u; col < 9u; ++col) {
00109$:
	ld	d, #0x00
00103$:
;games/sudoku.c:397: draw_cell(row, col, index);
	push	bc
	push	de
	push	bc
	inc	sp
	ld	e, c
	push	de
	call	_draw_cell
	pop	af
	inc	sp
	pop	de
	pop	bc
;games/sudoku.c:398: ++index;
	inc	b
;games/sudoku.c:396: for (col = 0u; col < 9u; ++col) {
	inc	d
	ld	a, d
	sub	a, #0x09
	jr	C, 00103$
;games/sudoku.c:395: for (row = 0u; row < 9u; ++row) {
	inc	c
	ld	a, c
	sub	a, #0x09
	jr	C, 00109$
;games/sudoku.c:401: }
	ret
;games/sudoku.c:403: static unsigned char tens_digit(unsigned char value) {
;	---------------------------------
; Function tens_digit
; ---------------------------------
_tens_digit:
;games/sudoku.c:407: while (value >= 10u) {
	ld	iy, #2
	add	iy, sp
	ld	c, 0 (iy)
	ld	l, #0x00
00101$:
;games/sudoku.c:408: value = (unsigned char)(value - 10u);
	ld	a,c
	cp	a,#0x0a
	ret	C
	add	a, #0xf6
	ld	c, a
;games/sudoku.c:409: ++tens;
	inc	l
;games/sudoku.c:411: return tens;
;games/sudoku.c:412: }
	jr	00101$
;games/sudoku.c:414: static unsigned char ones_digit(unsigned char value) {
;	---------------------------------
; Function ones_digit
; ---------------------------------
_ones_digit:
;games/sudoku.c:415: while (value >= 10u) {
	ld	iy, #2
	add	iy, sp
	ld	a, 0 (iy)
00101$:
	cp	a, #0x0a
	jr	C, 00103$
;games/sudoku.c:416: value = (unsigned char)(value - 10u);
	add	a, #0xf6
	jr	00101$
00103$:
;games/sudoku.c:418: return value;
	ld	l, a
;games/sudoku.c:419: }
	ret
;games/sudoku.c:421: static void write_two_digits(unsigned char row,
;	---------------------------------
; Function write_two_digits
; ---------------------------------
_write_two_digits:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/sudoku.c:424: text_put(row, col, (unsigned char)('0' + tens_digit(value)));
	ld	a, 6 (ix)
	push	af
	inc	sp
	call	_tens_digit
	ld	a, l
	inc	sp
	add	a, #0x30
	push	af
	inc	sp
	ld	h, 5 (ix)
	ld	l, 4 (ix)
	push	hl
	call	_text_put
	pop	af
	inc	sp
;games/sudoku.c:426: (unsigned char)('0' + ones_digit(value)));
	ld	a, 6 (ix)
	push	af
	inc	sp
	call	_ones_digit
	ld	a, l
	inc	sp
	add	a, #0x30
;games/sudoku.c:425: text_put(row, (unsigned char)(col + 1u),
	ld	b, 5 (ix)
	inc	b
	push	af
	inc	sp
	push	bc
	inc	sp
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
;games/sudoku.c:427: }
	pop	ix
	ret
;games/sudoku.c:429: static void draw_game_text(unsigned char level,
;	---------------------------------
; Function draw_game_text
; ---------------------------------
_draw_game_text:
;games/sudoku.c:433: text_clear_row(0u);
	xor	a, a
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;games/sudoku.c:434: text_write(0u, 0u, "L1 T00:00 N1");
	ld	hl, #___str_0
	push	hl
	xor	a, a
	push	af
	inc	sp
	xor	a, a
	push	af
	inc	sp
	call	_text_write
	pop	af
	pop	af
;games/sudoku.c:435: text_put(0u, 1u, (unsigned char)('0' + level));
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	add	a, #0x30
	ld	d,a
	ld	e,#0x01
	push	de
	xor	a, a
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
;games/sudoku.c:436: text_put(0u, 11u, (unsigned char)('0' + selected_digit));
	ld	hl, #3
	add	hl, sp
	ld	a, (hl)
	add	a, #0x30
	ld	d,a
	ld	e,#0x0b
	push	de
	xor	a, a
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
;games/sudoku.c:437: write_two_digits(0u, 4u, minutes);
	ld	hl, #4
	add	hl, sp
	ld	d, (hl)
	ld	e,#0x04
	push	de
	xor	a, a
	push	af
	inc	sp
	call	_write_two_digits
	pop	af
	inc	sp
;games/sudoku.c:438: write_two_digits(0u, 7u, seconds);
	ld	hl, #5
	add	hl, sp
	ld	d, (hl)
	ld	e,#0x07
	push	de
	xor	a, a
	push	af
	inc	sp
	call	_write_two_digits
	pop	af
	inc	sp
;games/sudoku.c:440: text_clear_row(14u);
	ld	a, #0x0e
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;games/sudoku.c:441: text_clear_row(15u);
	ld	a, #0x0f
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;games/sudoku.c:442: text_write(14u, 0u, "MOVE CTR PLACE");
	ld	hl, #___str_1
	push	hl
	xor	a, a
	ld	d,a
	ld	e,#0x0e
	push	de
	call	_text_write
	pop	af
;games/sudoku.c:443: text_write(15u, 0u, "A/B NUM C MENU");
	ld	hl, #___str_2
	ex	(sp),hl
	xor	a, a
	ld	d,a
	ld	e,#0x0f
	push	de
	call	_text_write
	pop	af
	pop	af
;games/sudoku.c:444: }
	ret
___str_0:
	.ascii "L1 T00:00 N1"
	.db 0x00
___str_1:
	.ascii "MOVE CTR PLACE"
	.db 0x00
___str_2:
	.ascii "A/B NUM C MENU"
	.db 0x00
;games/sudoku.c:446: static void update_timer_text(unsigned char minutes, unsigned char seconds) {
;	---------------------------------
; Function update_timer_text
; ---------------------------------
_update_timer_text:
;games/sudoku.c:447: write_two_digits(0u, 4u, minutes);
	ld	hl, #2
	add	hl, sp
	ld	d, (hl)
	ld	e,#0x04
	push	de
	xor	a, a
	push	af
	inc	sp
	call	_write_two_digits
	pop	af
	inc	sp
;games/sudoku.c:448: write_two_digits(0u, 7u, seconds);
	ld	hl, #3
	add	hl, sp
	ld	d, (hl)
	ld	e,#0x07
	push	de
	xor	a, a
	push	af
	inc	sp
	call	_write_two_digits
	pop	af
	inc	sp
;games/sudoku.c:449: }
	ret
;games/sudoku.c:451: static void update_selected_digit_text(unsigned char selected_digit) {
;	---------------------------------
; Function update_selected_digit_text
; ---------------------------------
_update_selected_digit_text:
;games/sudoku.c:452: text_put(0u, 11u, (unsigned char)('0' + selected_digit));
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	add	a, #0x30
	ld	d,a
	ld	e,#0x0b
	push	de
	xor	a, a
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
;games/sudoku.c:453: }
	ret
;games/sudoku.c:455: static void draw_game_screen(unsigned char level,
;	---------------------------------
; Function draw_game_screen
; ---------------------------------
_draw_game_screen:
	push	ix
	ld	ix,#0
	add	ix,sp
;games/sudoku.c:461: glic_prepare_screen(GLIC_BLACK);
	xor	a, a
	push	af
	inc	sp
	call	_glic_prepare_screen
	inc	sp
;games/sudoku.c:462: draw_game_text(level, selected_digit, minutes, seconds);
	ld	h, 7 (ix)
	ld	l, 6 (ix)
	push	hl
	ld	h, 5 (ix)
	ld	l, 4 (ix)
	push	hl
	call	_draw_game_text
	pop	af
	pop	af
;games/sudoku.c:463: draw_grid();
	call	_draw_grid
;games/sudoku.c:464: draw_board_values();
	call	_draw_board_values
;games/sudoku.c:465: draw_cursor(cursor_row, cursor_col);
	ld	h, 9 (ix)
	ld	l, 8 (ix)
	push	hl
	call	_draw_cursor
	pop	af
;games/sudoku.c:466: }
	pop	ix
	ret
;games/sudoku.c:468: static void blink_cell(unsigned char row,
;	---------------------------------
; Function blink_cell
; ---------------------------------
_blink_cell:
	push	ix
	ld	ix,#0
	add	ix,sp
	dec	sp
;games/sudoku.c:473: for (i = 0u; i < 6u; ++i) {
	ld	-1 (ix), #0
00104$:
;games/sudoku.c:478: (i & 1u) ? 0u : 1u);
	ld	a, -1 (ix)
	and	a, #0x01
	ld	c, a
	ld	b, #0x00
	ld	a, b
	or	a, c
	jr	Z, 00108$
	ld	de, #0x0000
	jr	00109$
00108$:
	ld	de, #0x0001
00109$:
;games/sudoku.c:475: (unsigned char)(cell_screen_y(row) + 2u),
	push	bc
	push	de
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_cell_screen_y
	ld	a, l
	inc	sp
	pop	de
	pop	bc
	add	a, #0x02
	ld	d, a
;games/sudoku.c:474: fill_rect((unsigned char)(cell_screen_x(col) + 2u),
	push	bc
	push	de
	ld	a, 5 (ix)
	push	af
	inc	sp
	call	_cell_screen_x
	inc	sp
	pop	de
	pop	bc
	inc	l
	inc	l
	push	bc
	ld	b, e
	ld	c, #0x07
	push	bc
	ld	a, #0x07
	push	af
	ld	e, l
	inc	sp
	push	de
	call	_fill_rect
	pop	af
	pop	af
	inc	sp
	pop	bc
;games/sudoku.c:479: if ((i & 1u) != 0u) {
	ld	a, b
	or	a, c
	jr	Z, 00102$
;games/sudoku.c:480: draw_cell(row, col, index);
	ld	h, 6 (ix)
	ld	l, 5 (ix)
	push	hl
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_draw_cell
;games/sudoku.c:481: draw_cursor(row, col);
	inc	sp
	ld	h, 5 (ix)
	ld	l, 4 (ix)
	ex	(sp),hl
	call	_draw_cursor
	pop	af
00102$:
;games/sudoku.c:483: glic_delay(BLINK_DELAY);
	ld	hl, #0x1194
	push	hl
	call	_glic_delay
	pop	af
;games/sudoku.c:473: for (i = 0u; i < 6u; ++i) {
	inc	-1 (ix)
	ld	a, -1 (ix)
	sub	a, #0x06
	jr	C, 00104$
;games/sudoku.c:485: draw_cell(row, col, index);
	ld	h, 6 (ix)
	ld	l, 5 (ix)
	push	hl
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_draw_cell
;games/sudoku.c:486: draw_cursor(row, col);
	inc	sp
	ld	h, 5 (ix)
	ld	l, 4 (ix)
	ex	(sp),hl
	call	_draw_cursor
	pop	af
;games/sudoku.c:487: }
	inc	sp
	pop	ix
	ret
;games/sudoku.c:489: static unsigned char puzzle_solved(void) {
;	---------------------------------
; Function puzzle_solved
; ---------------------------------
_puzzle_solved:
;games/sudoku.c:492: for (i = 0u; i < 81u; ++i) {
	ld	bc, #_board+0
	ld	e, #0x00
00104$:
;games/sudoku.c:493: if (board[i] != solution[i]) {
	ld	l, e
	ld	h, #0x00
	add	hl, bc
	ld	d, (hl)
	ld	a, #<(_solution)
	add	a, e
	ld	l, a
	ld	a, #>(_solution)
	adc	a, #0x00
	ld	h, a
	ld	a, (hl)
	sub	a, d
	jr	Z, 00105$
;games/sudoku.c:494: return 0u;
	ld	l, #0x00
	ret
00105$:
;games/sudoku.c:492: for (i = 0u; i < 81u; ++i) {
	inc	e
	ld	a, e
	sub	a, #0x51
	jr	C, 00104$
;games/sudoku.c:497: return 1u;
	ld	l, #0x01
;games/sudoku.c:498: }
	ret
;games/sudoku.c:500: static void show_solved_screen(void) {
;	---------------------------------
; Function show_solved_screen
; ---------------------------------
_show_solved_screen:
;games/sudoku.c:503: text_clear_row(14u);
	ld	a, #0x0e
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;games/sudoku.c:504: text_clear_row(15u);
	ld	a, #0x0f
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;games/sudoku.c:505: text_write(14u, 4u, "SOLVED");
	ld	hl, #___str_3
	push	hl
	ld	de, #0x040e
	push	de
	call	_text_write
	pop	af
;games/sudoku.c:506: text_write(15u, 2u, "CENTER MENU");
	ld	hl, #___str_4
	ex	(sp),hl
	ld	de, #0x020f
	push	de
	call	_text_write
	pop	af
	pop	af
;games/sudoku.c:507: wait_for_release();
	call	_wait_for_release
;games/sudoku.c:509: while (1) {
00105$:
;games/sudoku.c:510: buttons = glic_read_buttons();
	call	_glic_read_buttons
	ld	b, l
;games/sudoku.c:511: if ((glic_button_pressed(buttons, GLIC_BTN_CENTER) != 0u) ||
	push	bc
	ld	a, #0x01
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_button_pressed
	pop	af
	ld	a, l
	pop	bc
	or	a, a
	jp	NZ,_wait_for_release
;games/sudoku.c:512: (glic_button_pressed(buttons, GLIC_BTN_C) != 0u)) {
	ld	a, #0x20
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_button_pressed
	pop	af
	ld	a, l
	or	a, a
;games/sudoku.c:513: wait_for_release();
;games/sudoku.c:514: return;
	jp	NZ,_wait_for_release
;games/sudoku.c:516: glic_delay(GAME_LOOP_DELAY);
	ld	hl, #0x04b0
	push	hl
	call	_glic_delay
	pop	af
;games/sudoku.c:518: }
	jr	00105$
___str_3:
	.ascii "SOLVED"
	.db 0x00
___str_4:
	.ascii "CENTER MENU"
	.db 0x00
;games/sudoku.c:520: static void draw_title_level(unsigned char level) {
;	---------------------------------
; Function draw_title_level
; ---------------------------------
_draw_title_level:
;games/sudoku.c:521: text_clear_row(5u);
	ld	a, #0x05
	push	af
	inc	sp
	call	_text_clear_row
	inc	sp
;games/sudoku.c:522: text_write(5u, 4u, "LEVEL 1");
	ld	hl, #___str_5
	push	hl
	ld	de, #0x0405
	push	de
	call	_text_write
	pop	af
	pop	af
;games/sudoku.c:523: text_put(5u, 10u, (unsigned char)('0' + level));
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	add	a, #0x30
	ld	d,a
	ld	e,#0x0a
	push	de
	ld	a, #0x05
	push	af
	inc	sp
	call	_text_put
	pop	af
	inc	sp
;games/sudoku.c:524: }
	ret
___str_5:
	.ascii "LEVEL 1"
	.db 0x00
;games/sudoku.c:526: static void draw_title_screen(unsigned char level) {
;	---------------------------------
; Function draw_title_screen
; ---------------------------------
_draw_title_screen:
;games/sudoku.c:527: glic_prepare_screen(GLIC_BLACK);
	xor	a, a
	push	af
	inc	sp
	call	_glic_prepare_screen
	inc	sp
;games/sudoku.c:528: draw_rect(88u, 8u, 36u, 36u, 1u);
	ld	de, #0x0124
	push	de
	ld	de, #0x2408
	push	de
	ld	a, #0x58
	push	af
	inc	sp
	call	_draw_rect
	pop	af
	pop	af
	inc	sp
;games/sudoku.c:529: draw_vline(100u, 8u, 36u, 1u);
	ld	de, #0x0124
	push	de
	ld	de, #0x0864
	push	de
	call	_draw_vline
	pop	af
	pop	af
;games/sudoku.c:530: draw_vline(112u, 8u, 36u, 1u);
	ld	de, #0x0124
	push	de
	ld	de, #0x0870
	push	de
	call	_draw_vline
	pop	af
	pop	af
;games/sudoku.c:531: draw_hline(88u, 20u, 36u, 1u);
	ld	de, #0x0124
	push	de
	ld	de, #0x1458
	push	de
	call	_draw_hline
	pop	af
	pop	af
;games/sudoku.c:532: draw_hline(88u, 32u, 36u, 1u);
	ld	de, #0x0124
	push	de
	ld	de, #0x2058
	push	de
	call	_draw_hline
	pop	af
;games/sudoku.c:534: text_write(1u, 4u, "SUDOKU");
	ld	hl, #___str_6
	ex	(sp),hl
	ld	de, #0x0401
	push	de
	call	_text_write
	pop	af
	pop	af
;games/sudoku.c:535: draw_title_level(level);
	ld	hl, #2
	add	hl, sp
	ld	a, (hl)
	push	af
	inc	sp
	call	_draw_title_level
	inc	sp
;games/sudoku.c:536: text_write(7u, 2u, "< > CHANGE LVL");
	ld	hl, #___str_7
	push	hl
	ld	de, #0x0207
	push	de
	call	_text_write
	pop	af
;games/sudoku.c:537: text_write(9u, 2u, "CENTER START");
	ld	hl, #___str_8
	ex	(sp),hl
	ld	de, #0x0209
	push	de
	call	_text_write
	pop	af
;games/sudoku.c:538: text_write(11u, 2u, "C CONTROLS");
	ld	hl, #___str_9
	ex	(sp),hl
	ld	de, #0x020b
	push	de
	call	_text_write
	pop	af
	pop	af
;games/sudoku.c:539: }
	ret
___str_6:
	.ascii "SUDOKU"
	.db 0x00
___str_7:
	.ascii "< > CHANGE LVL"
	.db 0x00
___str_8:
	.ascii "CENTER START"
	.db 0x00
___str_9:
	.ascii "C CONTROLS"
	.db 0x00
;games/sudoku.c:541: static void show_controls_screen(void) {
;	---------------------------------
; Function show_controls_screen
; ---------------------------------
_show_controls_screen:
;games/sudoku.c:544: glic_prepare_screen(GLIC_BLACK);
	xor	a, a
	push	af
	inc	sp
	call	_glic_prepare_screen
	inc	sp
;games/sudoku.c:545: text_write(1u, 2u, "SUDOKU KEYS");
	ld	hl, #___str_10
	push	hl
	ld	de, #0x0201
	push	de
	call	_text_write
	pop	af
;games/sudoku.c:546: text_write(3u, 1u, "ARROWS MOVE");
	ld	hl, #___str_11
	ex	(sp),hl
	ld	de, #0x0103
	push	de
	call	_text_write
	pop	af
;games/sudoku.c:547: text_write(4u, 1u, "A/B PICK NUM");
	ld	hl, #___str_12
	ex	(sp),hl
	ld	de, #0x0104
	push	de
	call	_text_write
	pop	af
;games/sudoku.c:548: text_write(5u, 1u, "CENTER PLACE");
	ld	hl, #___str_13
	ex	(sp),hl
	ld	de, #0x0105
	push	de
	call	_text_write
	pop	af
;games/sudoku.c:549: text_write(6u, 1u, "C BACK MENU");
	ld	hl, #___str_14
	ex	(sp),hl
	ld	de, #0x0106
	push	de
	call	_text_write
	pop	af
;games/sudoku.c:550: text_write(8u, 1u, "TITLE SCREEN");
	ld	hl, #___str_15
	ex	(sp),hl
	ld	de, #0x0108
	push	de
	call	_text_write
	pop	af
;games/sudoku.c:551: text_write(9u, 1u, "< > LEVEL");
	ld	hl, #___str_16
	ex	(sp),hl
	ld	de, #0x0109
	push	de
	call	_text_write
	pop	af
;games/sudoku.c:552: text_write(10u, 1u, "CENTER START");
	ld	hl, #___str_17
	ex	(sp),hl
	ld	de, #0x010a
	push	de
	call	_text_write
	pop	af
;games/sudoku.c:553: text_write(12u, 3u, "PRESS C");
	ld	hl, #___str_18
	ex	(sp),hl
	ld	de, #0x030c
	push	de
	call	_text_write
	pop	af
	pop	af
;games/sudoku.c:554: wait_for_release();
	call	_wait_for_release
;games/sudoku.c:556: while (1) {
00105$:
;games/sudoku.c:557: buttons = glic_read_buttons();
	call	_glic_read_buttons
	ld	b, l
;games/sudoku.c:558: if ((glic_button_pressed(buttons, GLIC_BTN_C) != 0u) ||
	push	bc
	ld	a, #0x20
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_button_pressed
	pop	af
	ld	a, l
	pop	bc
	or	a, a
	jp	NZ,_wait_for_release
;games/sudoku.c:559: (glic_button_pressed(buttons, GLIC_BTN_CENTER) != 0u)) {
	ld	a, #0x01
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_glic_button_pressed
	pop	af
	ld	a, l
	or	a, a
;games/sudoku.c:560: wait_for_release();
;games/sudoku.c:561: return;
	jp	NZ,_wait_for_release
;games/sudoku.c:563: glic_delay(GAME_LOOP_DELAY);
	ld	hl, #0x04b0
	push	hl
	call	_glic_delay
	pop	af
;games/sudoku.c:565: }
	jr	00105$
___str_10:
	.ascii "SUDOKU KEYS"
	.db 0x00
___str_11:
	.ascii "ARROWS MOVE"
	.db 0x00
___str_12:
	.ascii "A/B PICK NUM"
	.db 0x00
___str_13:
	.ascii "CENTER PLACE"
	.db 0x00
___str_14:
	.ascii "C BACK MENU"
	.db 0x00
___str_15:
	.ascii "TITLE SCREEN"
	.db 0x00
___str_16:
	.ascii "< > LEVEL"
	.db 0x00
___str_17:
	.ascii "CENTER START"
	.db 0x00
___str_18:
	.ascii "PRESS C"
	.db 0x00
;games/sudoku.c:567: static unsigned char title_menu(void) {
;	---------------------------------
; Function title_menu
; ---------------------------------
_title_menu:
;games/sudoku.c:571: draw_title_screen(selected_level);
	ld	a,(#_selected_level + 0)
	push	af
	inc	sp
	call	_draw_title_screen
	inc	sp
;games/sudoku.c:572: last_buttons = GLIC_BUTTONS_NONE;
	ld	c, #0xff
;games/sudoku.c:574: while (1) {
00119$:
;games/sudoku.c:575: buttons = glic_read_buttons();
	push	bc
	call	_glic_read_buttons
	ld	a, l
	pop	bc
	ld	b, a
;games/sudoku.c:576: if (button_edge(buttons, last_buttons, GLIC_BTN_RIGHT) != 0u) {
	push	bc
	ld	a, #0x04
	push	af
	inc	sp
	ld	a, c
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	bc
	or	a, a
	jr	Z, 00116$
;games/sudoku.c:577: if (selected_level < LEVEL_COUNT) {
	ld	iy, #_selected_level
	ld	a, 0 (iy)
	sub	a, #0x05
	jr	NC, 00102$
;games/sudoku.c:578: ++selected_level;
	inc	0 (iy)
	jr	00103$
00102$:
;games/sudoku.c:580: selected_level = 1u;
	ld	hl, #_selected_level
	ld	(hl), #0x01
00103$:
;games/sudoku.c:582: draw_title_level(selected_level);
	push	bc
	ld	a,(#_selected_level + 0)
	push	af
	inc	sp
	call	_draw_title_level
	inc	sp
	pop	bc
	jr	00117$
00116$:
;games/sudoku.c:583: } else if (button_edge(buttons, last_buttons, GLIC_BTN_LEFT) != 0u) {
	push	bc
	ld	a, #0x10
	push	af
	inc	sp
	ld	a, c
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	bc
	or	a, a
	jr	Z, 00113$
;games/sudoku.c:584: if (selected_level > 1u) {
	ld	a, #0x01
	ld	iy, #_selected_level
	sub	a, 0 (iy)
	jr	NC, 00105$
;games/sudoku.c:585: --selected_level;
	dec	0 (iy)
	jr	00106$
00105$:
;games/sudoku.c:587: selected_level = LEVEL_COUNT;
	ld	hl, #_selected_level
	ld	(hl), #0x05
00106$:
;games/sudoku.c:589: draw_title_level(selected_level);
	push	bc
	ld	a,(#_selected_level + 0)
	push	af
	inc	sp
	call	_draw_title_level
	inc	sp
	pop	bc
	jr	00117$
00113$:
;games/sudoku.c:590: } else if (button_edge(buttons, last_buttons, GLIC_BTN_C) != 0u) {
	push	bc
	ld	a, #0x20
	push	af
	inc	sp
	ld	a, c
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	bc
	or	a, a
	jr	Z, 00110$
;games/sudoku.c:591: show_controls_screen();
	push	bc
	call	_show_controls_screen
	ld	a,(#_selected_level + 0)
	push	af
	inc	sp
	call	_draw_title_screen
	inc	sp
	pop	bc
;games/sudoku.c:593: last_buttons = GLIC_BUTTONS_NONE;
	jr	00117$
00110$:
;games/sudoku.c:594: } else if (button_edge(buttons, last_buttons, GLIC_BTN_CENTER) != 0u) {
	push	bc
	ld	a, #0x01
	push	af
	inc	sp
	ld	a, c
	push	af
	inc	sp
	push	bc
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	pop	bc
	or	a, a
	jr	Z, 00117$
;games/sudoku.c:595: wait_for_release();
	call	_wait_for_release
;games/sudoku.c:596: return selected_level;
	ld	a, (#_selected_level + 0)
	ld	l, a
	ret
00117$:
;games/sudoku.c:599: last_buttons = buttons;
	ld	c, b
;games/sudoku.c:600: glic_delay(GAME_LOOP_DELAY);
	push	bc
	ld	hl, #0x04b0
	push	hl
	call	_glic_delay
	pop	af
	pop	bc
;games/sudoku.c:602: }
	jp	00119$
;games/sudoku.c:604: static void run_game(unsigned char level) {
;	---------------------------------
; Function run_game
; ---------------------------------
_run_game:
	push	ix
	ld	ix,#0
	add	ix,sp
	ld	hl, #-10
	add	hl, sp
	ld	sp, hl
;games/sudoku.c:617: load_level(level);
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_load_level
;games/sudoku.c:618: cursor_row = 0u;
	ld	-6 (ix), #0
;games/sudoku.c:619: cursor_col = 0u;
	ld	-5 (ix), #0
;games/sudoku.c:620: selected_digit = 1u;
	ld	-4 (ix), #0x01
;games/sudoku.c:622: seconds = 0u;
	ld	-3 (ix), #0
;games/sudoku.c:623: ticks = 0u;
	ld	-2 (ix), #0
;games/sudoku.c:624: last_buttons = GLIC_BUTTONS_NONE;
	ld	-7 (ix), #0xff
	inc	sp
;games/sudoku.c:626: draw_game_screen(level, selected_digit, minutes, seconds, cursor_row, cursor_col);
	xor	a, a
	push	af
	inc	sp
	xor	a, a
	push	af
	inc	sp
	xor	a, a
	push	af
	inc	sp
	xor	a, a
	ld	d,a
	ld	e,#0x01
	push	de
	ld	a, 4 (ix)
	push	af
	inc	sp
	call	_draw_game_screen
	ld	hl, #6
	add	hl, sp
	ld	sp, hl
;games/sudoku.c:628: while (1) {
	ld	-1 (ix), #0
00150$:
;games/sudoku.c:629: buttons = glic_read_buttons();
	call	_glic_read_buttons
	ld	-10 (ix), l
;games/sudoku.c:630: old_row = cursor_row;
	ld	a, -6 (ix)
	ld	-9 (ix), a
;games/sudoku.c:631: old_col = cursor_col;
	ld	a, -5 (ix)
	ld	-8 (ix), a
;games/sudoku.c:633: if ((button_edge(buttons, last_buttons, GLIC_BTN_UP) != 0u) &&
	ld	h, #0x02
	ld	l, -7 (ix)
	push	hl
	ld	a, -10 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00137$
;games/sudoku.c:634: (cursor_row > 0u)) {
	ld	a, -6 (ix)
	or	a, a
	jr	Z, 00137$
;games/sudoku.c:635: --cursor_row;
	dec	-6 (ix)
	jp	00138$
00137$:
;games/sudoku.c:636: } else if ((button_edge(buttons, last_buttons, GLIC_BTN_DOWN) != 0u) &&
	ld	h, #0x08
	ld	l, -7 (ix)
	push	hl
	ld	a, -10 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00133$
;games/sudoku.c:637: (cursor_row < 8u)) {
	ld	a, -6 (ix)
	sub	a, #0x08
	jr	NC, 00133$
;games/sudoku.c:638: ++cursor_row;
	inc	-6 (ix)
	jp	00138$
00133$:
;games/sudoku.c:639: } else if ((button_edge(buttons, last_buttons, GLIC_BTN_LEFT) != 0u) &&
	ld	h, #0x10
	ld	l, -7 (ix)
	push	hl
	ld	a, -10 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00129$
;games/sudoku.c:640: (cursor_col > 0u)) {
	ld	a, -5 (ix)
	or	a, a
	jr	Z, 00129$
;games/sudoku.c:641: --cursor_col;
	dec	-5 (ix)
	jp	00138$
00129$:
;games/sudoku.c:642: } else if ((button_edge(buttons, last_buttons, GLIC_BTN_RIGHT) != 0u) &&
	ld	h, #0x04
	ld	l, -7 (ix)
	push	hl
	ld	a, -10 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00125$
;games/sudoku.c:643: (cursor_col < 8u)) {
	ld	a, -5 (ix)
	sub	a, #0x08
	jr	NC, 00125$
;games/sudoku.c:644: ++cursor_col;
	inc	-5 (ix)
	jp	00138$
00125$:
;games/sudoku.c:645: } else if (button_edge(buttons, last_buttons, GLIC_BTN_A) != 0u) {
	ld	h, #0x80
	ld	l, -7 (ix)
	push	hl
	ld	a, -10 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00122$
;games/sudoku.c:646: if (selected_digit < 9u) {
	ld	a, -4 (ix)
	sub	a, #0x09
	jr	NC, 00102$
;games/sudoku.c:647: ++selected_digit;
	inc	-4 (ix)
	jr	00103$
00102$:
;games/sudoku.c:649: selected_digit = 1u;
	ld	-4 (ix), #0x01
00103$:
;games/sudoku.c:651: update_selected_digit_text(selected_digit);
	ld	a, -4 (ix)
	push	af
	inc	sp
	call	_update_selected_digit_text
	inc	sp
	jp	00138$
00122$:
;games/sudoku.c:652: } else if (button_edge(buttons, last_buttons, GLIC_BTN_B) != 0u) {
	ld	h, #0x40
	ld	l, -7 (ix)
	push	hl
	ld	a, -10 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00119$
;games/sudoku.c:653: if (selected_digit > 1u) {
	ld	a, #0x01
	sub	a, -4 (ix)
	jr	NC, 00105$
;games/sudoku.c:654: --selected_digit;
	dec	-4 (ix)
	jr	00106$
00105$:
;games/sudoku.c:656: selected_digit = 9u;
	ld	-4 (ix), #0x09
00106$:
;games/sudoku.c:658: update_selected_digit_text(selected_digit);
	ld	a, -4 (ix)
	push	af
	inc	sp
	call	_update_selected_digit_text
	inc	sp
	jp	00138$
00119$:
;games/sudoku.c:659: } else if (button_edge(buttons, last_buttons, GLIC_BTN_C) != 0u) {
	ld	h, #0x20
	ld	l, -7 (ix)
	push	hl
	ld	a, -10 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00116$
;games/sudoku.c:660: wait_for_release();
	call	_wait_for_release
;games/sudoku.c:661: return;
	jp	00152$
00116$:
;games/sudoku.c:662: } else if (button_edge(buttons, last_buttons, GLIC_BTN_CENTER) != 0u) {
	ld	h, #0x01
	ld	l, -7 (ix)
	push	hl
	ld	a, -10 (ix)
	push	af
	inc	sp
	call	_button_edge
	pop	af
	ld	a, l
	inc	sp
	or	a, a
	jr	Z, 00138$
;games/sudoku.c:663: index = cell_index(cursor_row, cursor_col);
	ld	h, -5 (ix)
	ld	l, -6 (ix)
	push	hl
	call	_cell_index
	pop	af
	ld	c, l
;games/sudoku.c:664: if ((givens[index] != 0u) || (selected_digit != solution[index])) {
	ld	hl, #_givens
	ld	b, #0x00
	add	hl, bc
	ld	a, (hl)
	or	a, a
	jr	NZ, 00109$
	ld	hl, #_solution
	ld	b, #0x00
	add	hl, bc
	ld	a,-4 (ix)
	sub	a,(hl)
	jr	Z, 00110$
00109$:
;games/sudoku.c:665: blink_cell(cursor_row, cursor_col, index);
	ld	h, c
	ld	l, -5 (ix)
	push	hl
	ld	a, -6 (ix)
	push	af
	inc	sp
	call	_blink_cell
	pop	af
	inc	sp
	jr	00138$
00110$:
;games/sudoku.c:667: board[index] = selected_digit;
	ld	hl, #_board
	ld	b, #0x00
	add	hl, bc
	ld	a, -4 (ix)
	ld	(hl), a
;games/sudoku.c:668: draw_cell(cursor_row, cursor_col, index);
	ld	h, c
	ld	l, -5 (ix)
	push	hl
	ld	a, -6 (ix)
	push	af
	inc	sp
	call	_draw_cell
;games/sudoku.c:669: draw_cursor(cursor_row, cursor_col);
	inc	sp
	ld	h, -5 (ix)
	ld	l, -6 (ix)
	ex	(sp),hl
	call	_draw_cursor
	pop	af
;games/sudoku.c:670: if (puzzle_solved() != 0u) {
	call	_puzzle_solved
	ld	a, l
	or	a, a
	jr	Z, 00138$
;games/sudoku.c:671: show_solved_screen();
	call	_show_solved_screen
;games/sudoku.c:672: return;
	jr	00152$
00138$:
;games/sudoku.c:677: if ((old_row != cursor_row) || (old_col != cursor_col)) {
	ld	a, -6 (ix)
	sub	a, -9 (ix)
	jr	NZ, 00140$
	ld	a, -5 (ix)
	sub	a, -8 (ix)
	jr	Z, 00141$
00140$:
;games/sudoku.c:678: index = cell_index(old_row, old_col);
	ld	h, -8 (ix)
	ld	l, -9 (ix)
	push	hl
	call	_cell_index
	pop	af
	ld	-7 (ix), l
;games/sudoku.c:679: draw_cell(old_row, old_col, index);
	ld	h, l
	ld	l, -8 (ix)
	push	hl
	ld	a, -9 (ix)
	push	af
	inc	sp
	call	_draw_cell
;games/sudoku.c:680: draw_cursor(cursor_row, cursor_col);
	inc	sp
	ld	h, -5 (ix)
	ld	l, -6 (ix)
	ex	(sp),hl
	call	_draw_cursor
	pop	af
00141$:
;games/sudoku.c:683: last_buttons = buttons;
	ld	a, -10 (ix)
	ld	-7 (ix), a
;games/sudoku.c:684: ++ticks;
	inc	-2 (ix)
;games/sudoku.c:685: if (ticks >= TIMER_TICKS_PER_SECOND) {
	ld	a, -2 (ix)
	sub	a, #0x14
	jr	C, 00148$
;games/sudoku.c:686: ticks = 0u;
	ld	-2 (ix), #0
;games/sudoku.c:687: ++seconds;
	inc	-3 (ix)
;games/sudoku.c:688: if (seconds >= 60u) {
	ld	a, -3 (ix)
	sub	a, #0x3c
	jr	C, 00146$
;games/sudoku.c:689: seconds = 0u;
	ld	-3 (ix), #0
;games/sudoku.c:690: if (minutes < 99u) {
	ld	a, -1 (ix)
	sub	a, #0x63
	jr	NC, 00146$
;games/sudoku.c:691: ++minutes;
	inc	-1 (ix)
00146$:
;games/sudoku.c:694: update_timer_text(minutes, seconds);
	ld	h, -3 (ix)
	ld	l, -1 (ix)
	push	hl
	call	_update_timer_text
	pop	af
00148$:
;games/sudoku.c:696: glic_delay(GAME_LOOP_DELAY);
	ld	hl, #0x04b0
	push	hl
	call	_glic_delay
	pop	af
	jp	00150$
00152$:
;games/sudoku.c:698: }
	ld	sp, ix
	pop	ix
	ret
;games/sudoku.c:700: void main(void) {
;	---------------------------------
; Function main
; ---------------------------------
_main::
;games/sudoku.c:703: selected_level = 1u;
	ld	hl, #_selected_level
	ld	(hl), #0x01
;games/sudoku.c:704: while (1) {
00102$:
;games/sudoku.c:705: level = title_menu();
	call	_title_menu
	ld	a, l
;games/sudoku.c:706: run_game(level);
	push	af
	inc	sp
	call	_run_game
	inc	sp
;games/sudoku.c:708: }
	jr	00102$
	.area _CODE
	.area _INITIALIZER
	.area _CABS (ABS)
